-- Brote seed data (BUILD_SPEC §14). GENERATED by scripts/gen-seed.mjs — do not edit by hand.
-- Idempotent (on conflict do nothing + targeted deletes). Safe to re-run.

-- domains
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('residuos','Residuos y Reciclaje','Waste & Recycling','#C2703D','residuos','Menos basura, más vueltas: reducí, reusá y reciclá.',1) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('agua','Agua','Water','#2DB4D4','agua','Cada gota cuenta. Cuidá el agua en casa.',2) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('energia','Energía y CO₂','Home Energy & CO₂','#F4A62A','energia','Gastá menos energía y bajá tus emisiones.',3) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('movilidad','Movilidad','Transport','#5B6CF0','movilidad','Moverte limpio: a pie, en bici o en transporte.',4) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('plantas','Plantas y Verde Urbano','Plants & Greening','#3CB371','plantas','Sembrá vida y llená de verde tu entorno.',5) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('animales','Animales y Vida Silvestre','Animals & Wildlife','#E8638C','animales','Dales una mano a los bichos y la fauna.',6) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('alimentacion','Alimentación','Food & Diet','#9CC93B','alimentacion','Comé rico cuidando el planeta.',7) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('consumo','Consumo Responsable','Consumption','#B07CD6','consumo','Comprá mejor, comprá menos, durá más.',8) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('digital','Digital y Tecnología','Tech & Digital','#3DC1C1','digital','Tu huella digital también pesa: livianala.',9) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('comunidad','Comunidad','Community','#FF8A3D','comunidad','Juntos podemos más. Sumate al barrio.',10) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('agua_azul','Océanos y Ríos','Oceans & Rivers','#1E88A8','agua_azul','Protegé el agua azul: ríos, costas y mares.',11) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('aire_suelo','Aire y Suelo','Air & Soil','#A38B6D','aire_suelo','Aire más limpio y suelo más sano.',12) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;
insert into domains (slug,name_es,name_en,color,icon,description_es,sort_order) values ('ciencia','Ciencia Ciudadana','Citizen Science','#6FBF73','ciencia','Observá, registrá y ayudá a la ciencia.',13) on conflict (slug) do update set name_es=excluded.name_es,color=excluded.color,description_es=excluded.description_es;

-- ranks
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('semilla','Semilla','Seed',1,0,5,'#A38B6D','semilla','Tu mundo arranca: tierra desnuda y Pip.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('brote','Brote','Sprout',2,1000,5,'#9CC93B','brote','Aparece el primer pasto y un brote. Primer título.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('plantula','Plántula','Seedling',3,3000,5,'#6FBF73','plantula','Aparecen flores. Podés crear proyectos.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('retono','Retoño','Shoot',4,7000,5,'#3CB371','retono','Tu primer arbolito. Funciones de amigos.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('arbusto','Arbusto','Shrub',5,15000,5,'#1FB57A','arbusto','Arbustos y la primera ave visita tu mundo.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('arbol','Árbol','Tree',6,30000,5,'#0E7A52','arbol','Un árbol completo. Desafíos exclusivos.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('bosque','Bosque','Grove',7,60000,5,'#2DB4D4','bosque','Un bosque, un estanque y más fauna.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('guardian','Guardián','Guardian',8,120000,5,'#1E88A8','guardian','Aura de Guardián para Pip. Proyectos exclusivos.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('ecosistema','Ecosistema','Ecosystem',9,250000,5,'#5B6CF0','ecosistema','Un bioma rico: animales, agua y estructuras.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('planeta','Planeta','Planet',10,500000,5,'#B07CD6','planeta','Tu mundo se vuelve un planeta vivo.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;
insert into ranks (slug,name_es,name_en,tier,xp_threshold,divisions,color,icon,unlock_description_es) values ('gaia','Gaia','Gaia',11,1000000,5,'#FFB23E','gaia','Estatus legendario y un mundo dorado.') on conflict (slug) do update set xp_threshold=excluded.xp_threshold,name_es=excluded.name_es,color=excluded.color,unlock_description_es=excluded.unlock_description_es;

-- activities (168: daily + catalog + reserved)
insert into activities (slug,type,domain_slug,title_es,short_es,effort,impact,verification,base_points,frequency,icon,impact_equivalency_es,active,sort_order) values
('ducha-corta-5-min','daily','agua','Ducha corta (≤5 min)','Cada gota suma.','easy','low','honor',50,'daily','agua','Ahorrás ~20 L de agua',true,1),
('reutiliza-el-agua-para-regar-las-plantas','daily','agua','Reutilizá el agua para regar las plantas','Cada gota suma.','easy','medium','honor',100,'daily','agua','Ahorrás ~50 L de agua',true,2),
('cerra-la-canilla-mientras-te-cepillas-o-enjabona','daily','agua','Cerrá la canilla mientras te cepillás o enjabonás','Cada gota suma.','easy','low','honor',50,'daily','agua','Ahorrás ~20 L de agua',true,3),
('lava-los-platos-con-la-canilla-cerrada','daily','agua','Lavá los platos con la canilla cerrada','Cada gota suma.','easy','low','honor',50,'daily','agua','Ahorrás ~20 L de agua',true,4),
('pone-el-lavarropas-solo-cuando-este-lleno','daily','agua','Poné el lavarropas solo cuando esté lleno','Cada gota suma.','easy','low','honor',50,'daily','agua','Ahorrás ~20 L de agua',true,5),
('camina-un-trayecto-en-vez-de-ir-en-auto','daily','movilidad','Caminá un trayecto en vez de ir en auto','Moverte limpio.','medium','high','honor',150,'daily','movilidad','Evitás muchos kg de CO₂',true,6),
('anda-en-bici-a-algun-lado-hoy','daily','movilidad','Andá en bici a algún lado hoy','Moverte limpio.','medium','high','honor',150,'daily','movilidad','Evitás muchos kg de CO₂',true,7),
('usa-transporte-publico-hoy','daily','movilidad','Usá transporte público hoy','Moverte limpio.','easy','high','honor',100,'daily','movilidad','Evitás muchos kg de CO₂',true,8),
('subi-por-la-escalera-en-vez-del-ascensor','daily','movilidad','Subí por la escalera en vez del ascensor','Moverte limpio.','easy','low','honor',50,'daily','movilidad','Ahorrás un poco de combustible',true,9),
('colga-la-ropa-al-aire-en-vez-de-usar-secadora','daily','energia','Colgá la ropa al aire en vez de usar secadora','Menos consumo, menos CO₂.','easy','medium','honor',100,'daily','energia','Evitás varios kg de CO₂',true,10),
('desenchufa-los-aparatos-que-no-estas-usando','daily','energia','Desenchufá los aparatos que no estás usando','Menos consumo, menos CO₂.','easy','low','honor',50,'daily','energia','Bajás un poco tu consumo',true,11),
('lava-la-ropa-con-agua-fria','daily','energia','Lavá la ropa con agua fría','Menos consumo, menos CO₂.','easy','medium','honor',100,'daily','energia','Evitás varios kg de CO₂',true,12),
('apaga-las-luces-de-los-ambientes-vacios','daily','energia','Apagá las luces de los ambientes vacíos','Menos consumo, menos CO₂.','easy','low','honor',50,'daily','energia','Bajás un poco tu consumo',true,13),
('baja-un-poco-la-calefaccion-o-el-aire','daily','energia','Bajá un poco la calefacción o el aire','Menos consumo, menos CO₂.','easy','medium','honor',100,'daily','energia','Evitás varios kg de CO₂',true,14),
('cocina-con-tapa-y-aprovecha-el-calor','daily','energia','Cociná con tapa y aprovechá el calor','Menos consumo, menos CO₂.','easy','low','honor',50,'daily','energia','Bajás un poco tu consumo',true,15),
('come-una-comida-sin-carne-hoy','daily','alimentacion','Comé una comida sin carne hoy','Comé cuidando el planeta.','easy','high','honor',150,'daily','alimentacion','Evitás una buena dosis de CO₂ y agua',true,16),
('aprovecha-las-sobras-dia-sin-desperdicio','daily','alimentacion','Aprovechá las sobras (día sin desperdicio)','Comé cuidando el planeta.','easy','medium','honor',100,'daily','alimentacion','Ahorrás agua y emisiones',true,17),
('toma-agua-de-la-canilla-en-vez-de-embotellada','daily','alimentacion','Tomá agua de la canilla en vez de embotellada','Comé cuidando el planeta.','easy','low','honor',50,'daily','alimentacion','Reducís tu huella de comida',true,18),
('reduci-los-lacteos-hoy','daily','alimentacion','Reducí los lácteos hoy','Comé cuidando el planeta.','medium','medium','honor',100,'daily','alimentacion','Ahorrás agua y emisiones',true,19),
('separa-bien-tus-residuos-hoy','daily','residuos','Separá bien tus residuos hoy','Menos basura, más vueltas.','easy','low','honor',50,'daily','residuos','Desviás residuos del relleno',true,20),
('lleva-tu-botella-reutilizable','daily','residuos','Llevá tu botella reutilizable','Menos basura, más vueltas.','easy','low','honor',50,'daily','residuos','Desviás residuos del relleno',true,21),
('lleva-tus-bolsas-reutilizables-a-comprar','daily','residuos','Llevá tus bolsas reutilizables a comprar','Menos basura, más vueltas.','easy','low','honor',50,'daily','residuos','Desviás residuos del relleno',true,22),
('evita-un-plastico-de-un-solo-uso-hoy','daily','residuos','Evitá un plástico de un solo uso hoy','Menos basura, más vueltas.','easy','low','honor',50,'daily','residuos','Desviás residuos del relleno',true,23),
('composta-tus-restos-de-comida','daily','residuos','Compostá tus restos de comida','Menos basura, más vueltas.','medium','medium','honor',100,'daily','residuos','Desviás varios kg de residuos',true,24),
('usa-tu-vaso-o-termo-reutilizable','daily','residuos','Usá tu vaso o termo reutilizable','Menos basura, más vueltas.','easy','low','honor',50,'daily','residuos','Desviás residuos del relleno',true,25),
('reutiliza-un-frasco-o-envase','daily','residuos','Reutilizá un frasco o envase','Menos basura, más vueltas.','easy','low','honor',50,'daily','residuos','Desviás residuos del relleno',true,26),
('rega-tus-plantas-al-amanecer-o-atardecer','daily','plantas','Regá tus plantas al amanecer o atardecer','Sembrá vida.','easy','low','honor',50,'daily','plantas','Sumás verde a tu entorno',true,27),
('deja-agua-para-las-aves-o-animales-hoy','daily','animales','Dejá agua para las aves o animales hoy','Una mano a la fauna.','easy','low','honor',50,'daily','animales','Ayudás a la fauna local',true,28),
('recoge-un-poco-de-basura-que-viste-en-la-calle','daily','comunidad','Recogé un poco de basura que viste en la calle','Hacelo con otros.','easy','low','honor',50,'daily','comunidad','Sumás al barrio',true,29),
('borra-mails-y-archivos-viejos-que-no-usas','daily','digital','Borrá mails y archivos viejos que no usás','Aligerá tu huella digital.','easy','low','honor',50,'daily','digital','Aligerás tu huella digital',true,30),
('baja-la-resolucion-del-streaming','daily','digital','Bajá la resolución del streaming','Aligerá tu huella digital.','easy','low','honor',50,'daily','digital','Aligerás tu huella digital',true,31),
('disfruta-afuera-sin-generar-residuos','daily','comunidad','Disfrutá afuera sin generar residuos','Hacelo con otros.','easy','low','honor',50,'daily','comunidad','Sumás al barrio',true,32),
('arma-una-estacion-de-separacion-de-residuos-en-c','catalog','residuos','Armá una estación de separación de residuos en casa','Menos basura, más vueltas.','easy','low','honor',300,'one_time','residuos','Desviás residuos del relleno',true,1),
('empeza-a-compostar-en-casa','catalog','residuos','Empezá a compostar en casa','Menos basura, más vueltas.','medium','medium','photo_ai',750,'one_time','residuos','Desviás varios kg de residuos',true,2),
('arma-una-compostera-con-lombrices-vermicompost','catalog','residuos','Armá una compostera con lombrices (vermicompost)','Menos basura, más vueltas.','medium','medium','photo_ai',750,'one_time','residuos','Desviás varios kg de residuos',true,3),
('pasa-una-semana-de-residuo-cero','catalog','residuos','Pasá una semana de residuo cero','Menos basura, más vueltas.','hard','medium','honor',1500,'weekly','residuos','Desviás varios kg de residuos',true,4),
('hace-una-auditoria-de-tu-basura','catalog','residuos','Hacé una auditoría de tu basura','Menos basura, más vueltas.','medium','low','honor',500,'one_time','residuos','Desviás residuos del relleno',true,5),
('lleva-tus-residuos-electronicos-a-un-punto-certi','catalog','residuos','Llevá tus residuos electrónicos a un punto certificado','Menos basura, más vueltas.','medium','medium','photo_ai',750,'recurring','residuos','Desviás varios kg de residuos',true,6),
('lleva-pilas-y-baterias-a-un-punto-de-recoleccion','catalog','residuos','Llevá pilas y baterías a un punto de recolección','Menos basura, más vueltas.','medium','medium','photo_ai',750,'recurring','residuos','Desviás varios kg de residuos',true,7),
('cambia-a-jabon-o-champu-en-barra','catalog','residuos','Cambiá a jabón o champú en barra','Menos basura, más vueltas.','easy','low','honor',300,'one_time','residuos','Desviás residuos del relleno',true,8),
('pasate-a-facturacion-digital','catalog','residuos','Pasate a facturación digital','Menos basura, más vueltas.','easy','low','honor',300,'one_time','residuos','Desviás residuos del relleno',true,9),
('repara-algo-en-vez-de-tirarlo','catalog','residuos','Repará algo en vez de tirarlo','Menos basura, más vueltas.','medium','medium','photo_ai',750,'recurring','residuos','Desviás varios kg de residuos',true,10),
('organiza-o-participa-de-un-intercambio-de-ropa','catalog','residuos','Organizá o participá de un intercambio de ropa','Menos basura, más vueltas.','medium','medium','photo_ai',750,'recurring','residuos','Desviás varios kg de residuos',true,11),
('dona-cosas-que-ya-no-usas-en-vez-de-tirarlas','catalog','residuos','Doná cosas que ya no usás en vez de tirarlas','Menos basura, más vueltas.','easy','low','honor',300,'recurring','residuos','Desviás residuos del relleno',true,12),
('compra-a-granel-o-en-estaciones-de-recarga','catalog','residuos','Comprá a granel o en estaciones de recarga','Menos basura, más vueltas.','medium','medium','honor',500,'weekly','residuos','Desviás varios kg de residuos',true,13),
('recicla-correctamente-el-aceite-de-cocina-usado','catalog','residuos','Reciclá correctamente el aceite de cocina usado','Menos basura, más vueltas.','medium','medium','honor',500,'recurring','residuos','Desviás varios kg de residuos',true,14),
('compra-productos-con-contenido-reciclado','catalog','residuos','Comprá productos con contenido reciclado','Menos basura, más vueltas.','easy','low','honor',300,'recurring','residuos','Desviás residuos del relleno',true,15),
('evita-la-moda-rapida-toda-una-temporada','catalog','residuos','Evitá la moda rápida toda una temporada','Menos basura, más vueltas.','hard','medium','honor',1500,'recurring','residuos','Desviás varios kg de residuos',true,16),
('instala-un-cabezal-de-ducha-de-bajo-caudal','catalog','agua','Instalá un cabezal de ducha de bajo caudal','Cada gota suma.','medium','medium','photo_ai',750,'one_time','agua','Ahorrás ~50 L de agua',true,17),
('arregla-una-canilla-o-inodoro-que-pierde','catalog','agua','Arreglá una canilla o inodoro que pierde','Cada gota suma.','medium','medium','photo_ai',750,'one_time','agua','Ahorrás ~50 L de agua',true,18),
('instala-un-sistema-de-recoleccion-de-agua-de-llu','catalog','agua','Instalá un sistema de recolección de agua de lluvia','Cada gota suma.','medium','medium','photo_ai',1000,'one_time','agua','Ahorrás ~50 L de agua',true,19),
('reutiliza-aguas-grises-para-el-jardin','catalog','agua','Reutilizá aguas grises para el jardín','Cada gota suma.','medium','medium','honor',750,'recurring','agua','Ahorrás ~50 L de agua',true,20),
('instala-un-inodoro-de-doble-descarga','catalog','agua','Instalá un inodoro de doble descarga','Cada gota suma.','medium','medium','photo_ai',750,'one_time','agua','Ahorrás ~50 L de agua',true,21),
('elegi-plantas-nativas-resistentes-a-la-sequia','catalog','agua','Elegí plantas nativas resistentes a la sequía','Cada gota suma.','medium','medium','photo_ai',750,'one_time','agua','Ahorrás ~50 L de agua',true,22),
('reporta-una-perdida-de-agua-en-la-via-publica','catalog','agua','Reportá una pérdida de agua en la vía pública','Cada gota suma.','easy','medium','honor',500,'one_time','agua','Ahorrás ~50 L de agua',true,23),
('cambiate-a-una-tarifa-de-energia-renovable','catalog','energia','Cambiate a una tarifa de energía renovable','Menos consumo, menos CO₂.','easy','high','photo_ai',1000,'one_time','energia','Evitás cientos de kg de CO₂ al año',true,24),
('cambia-todas-las-lamparas-a-led','catalog','energia','Cambiá todas las lámparas a LED','Menos consumo, menos CO₂.','easy','medium','photo_ai',500,'one_time','energia','Evitás varios kg de CO₂',true,25),
('mejora-la-aislacion-y-burletes-de-tu-casa','catalog','energia','Mejorá la aislación y burletes de tu casa','Menos consumo, menos CO₂.','hard','high','photo_ai',2000,'one_time','energia','Evitás cientos de kg de CO₂ al año',true,26),
('instala-un-termostato-inteligente','catalog','energia','Instalá un termostato inteligente','Menos consumo, menos CO₂.','medium','medium','photo_ai',750,'one_time','energia','Evitás varios kg de CO₂',true,27),
('instala-paneles-solares-en-el-techo','catalog','energia','Instalá paneles solares en el techo','Menos consumo, menos CO₂.','hard','high','photo_ai',3000,'one_time','energia','Evitás cientos de kg de CO₂ al año',true,28),
('reemplaza-un-electrodomestico-por-uno-eficiente','catalog','energia','Reemplazá un electrodoméstico por uno eficiente','Menos consumo, menos CO₂.','hard','medium','photo_ai',1500,'one_time','energia','Evitás varios kg de CO₂',true,29),
('hace-una-auditoria-energetica-de-tu-casa','catalog','energia','Hacé una auditoría energética de tu casa','Menos consumo, menos CO₂.','medium','medium','honor',750,'one_time','energia','Evitás varios kg de CO₂',true,30),
('cambia-a-una-bomba-de-calor','catalog','energia','Cambiá a una bomba de calor','Menos consumo, menos CO₂.','hard','high','photo_ai',3000,'one_time','energia','Evitás cientos de kg de CO₂ al año',true,31),
('usa-regletas-inteligentes-contra-el-consumo-fant','catalog','energia','Usá regletas inteligentes contra el consumo fantasma','Menos consumo, menos CO₂.','easy','low','photo_ai',500,'one_time','energia','Bajás un poco tu consumo',true,32),
('ajusta-el-termotanque-a-una-temperatura-eficient','catalog','energia','Ajustá el termotanque a una temperatura eficiente','Menos consumo, menos CO₂.','easy','low','honor',300,'one_time','energia','Bajás un poco tu consumo',true,33),
('pasa-una-semana-sin-auto','catalog','movilidad','Pasá una semana sin auto','Moverte limpio.','hard','high','honor',2000,'weekly','movilidad','Evitás muchos kg de CO₂',true,34),
('evita-un-vuelo-de-corta-distancia','catalog','movilidad','Evitá un vuelo de corta distancia','Moverte limpio.','hard','high','honor',2000,'one_time','movilidad','Evitás muchos kg de CO₂',true,35),
('cambiate-a-un-auto-electrico-o-e-bike','catalog','movilidad','Cambiate a un auto eléctrico o e-bike','Moverte limpio.','hard','high','photo_ai',3000,'one_time','movilidad','Evitás muchos kg de CO₂',true,36),
('mantene-la-presion-de-los-neumaticos','catalog','movilidad','Mantené la presión de los neumáticos','Moverte limpio.','easy','low','honor',300,'recurring','movilidad','Ahorrás un poco de combustible',true,37),
('trabaja-desde-casa-y-reduci-dias-de-viaje','catalog','movilidad','Trabajá desde casa y reducí días de viaje','Moverte limpio.','easy','medium','honor',500,'recurring','movilidad','Evitás varios kg de CO₂',true,38),
('sumate-a-un-esquema-de-bicis-compartidas','catalog','movilidad','Sumate a un esquema de bicis compartidas','Moverte limpio.','easy','medium','honor',500,'recurring','movilidad','Evitás varios kg de CO₂',true,39),
('organiza-un-grupo-de-auto-compartido','catalog','movilidad','Organizá un grupo de auto compartido','Moverte limpio.','medium','medium','honor',750,'recurring','movilidad','Evitás varios kg de CO₂',true,40),
('hace-el-compromiso-de-un-ano-sin-volar','catalog','movilidad','Hacé el compromiso de un año sin volar','Moverte limpio.','hard','high','honor',2000,'recurring','movilidad','Evitás muchos kg de CO₂',true,41),
('planta-un-arbol-nativo','catalog','plantas','Plantá un árbol nativo','Sembrá vida.','medium','medium','photo_ai',1000,'one_time','plantas','Ayudás a polinizadores y al aire',true,42),
('empeza-una-huerta-en-el-balcon-o-ventana','catalog','plantas','Empezá una huerta en el balcón o ventana','Sembrá vida.','easy','low','photo_ai',500,'one_time','plantas','Sumás verde a tu entorno',true,43),
('cultiva-tus-propias-verduras-o-hierbas','catalog','plantas','Cultivá tus propias verduras o hierbas','Sembrá vida.','medium','medium','photo_ai',750,'recurring','plantas','Ayudás a polinizadores y al aire',true,44),
('planta-flores-nativas-para-polinizadores','catalog','plantas','Plantá flores nativas para polinizadores','Sembrá vida.','easy','medium','photo_ai',500,'one_time','plantas','Ayudás a polinizadores y al aire',true,45),
('sumate-a-una-huerta-comunitaria','catalog','plantas','Sumate a una huerta comunitaria','Sembrá vida.','medium','medium','photo_ai',750,'recurring','plantas','Ayudás a polinizadores y al aire',true,46),
('converti-parte-del-cesped-en-plantas-nativas','catalog','plantas','Convertí parte del césped en plantas nativas','Sembrá vida.','hard','medium','photo_ai',1500,'one_time','plantas','Ayudás a polinizadores y al aire',true,47),
('deja-un-sector-sin-cortar-para-la-biodiversidad','catalog','plantas','Dejá un sector sin cortar para la biodiversidad','Sembrá vida.','easy','low','honor',300,'recurring','plantas','Sumás verde a tu entorno',true,48),
('hace-bombas-de-semillas-para-espacios-descuidado','catalog','plantas','Hacé bombas de semillas para espacios descuidados','Sembrá vida.','medium','low','honor',500,'recurring','plantas','Sumás verde a tu entorno',true,49),
('cubri-los-canteros-con-mantillo','catalog','plantas','Cubrí los canteros con mantillo','Sembrá vida.','easy','low','honor',300,'recurring','plantas','Sumás verde a tu entorno',true,50),
('sumate-a-una-jornada-de-plantacion-de-arboles','catalog','plantas','Sumate a una jornada de plantación de árboles','Sembrá vida.','medium','medium','photo_ai',750,'recurring','plantas','Ayudás a polinizadores y al aire',true,51),
('construi-un-hotel-de-insectos-o-casa-para-abejas','catalog','animales','Construí un hotel de insectos o casa para abejas','Una mano a la fauna.','medium','medium','photo_ai',750,'one_time','animales','Das refugio y alimento a la fauna',true,52),
('pone-un-comedero-o-bebedero-para-aves','catalog','animales','Poné un comedero o bebedero para aves','Una mano a la fauna.','easy','low','photo_ai',500,'recurring','animales','Ayudás a la fauna local',true,53),
('deja-un-corredor-para-fauna-en-tu-jardin','catalog','animales','Dejá un corredor para fauna en tu jardín','Una mano a la fauna.','medium','medium','honor',750,'one_time','animales','Das refugio y alimento a la fauna',true,54),
('evita-pesticidas-y-herbicidas-en-tu-jardin','catalog','animales','Evitá pesticidas y herbicidas en tu jardín','Una mano a la fauna.','easy','medium','honor',500,'recurring','animales','Das refugio y alimento a la fauna',true,55),
('crea-un-pequeno-estanque-para-anfibios','catalog','animales','Creá un pequeño estanque para anfibios','Una mano a la fauna.','hard','medium','photo_ai',1500,'one_time','animales','Das refugio y alimento a la fauna',true,56),
('adopta-una-mascota-de-un-refugio','catalog','animales','Adoptá una mascota de un refugio','Una mano a la fauna.','medium','medium','photo_ai',1000,'one_time','animales','Das refugio y alimento a la fauna',true,57),
('hace-de-hogar-de-transito-para-animales','catalog','animales','Hacé de hogar de tránsito para animales','Una mano a la fauna.','hard','medium','photo_ai',1500,'recurring','animales','Das refugio y alimento a la fauna',true,58),
('hace-voluntariado-en-un-refugio-o-santuario','catalog','animales','Hacé voluntariado en un refugio o santuario','Una mano a la fauna.','medium','medium','photo_ai',750,'recurring','animales','Das refugio y alimento a la fauna',true,59),
('mantene-a-los-gatos-adentro-para-proteger-aves','catalog','animales','Mantené a los gatos adentro para proteger aves','Una mano a la fauna.','easy','medium','honor',500,'recurring','animales','Das refugio y alimento a la fauna',true,60),
('pone-calcomanias-anti-choque-en-las-ventanas','catalog','animales','Poné calcomanías anti-choque en las ventanas','Una mano a la fauna.','easy','low','photo_ai',300,'one_time','animales','Ayudás a la fauna local',true,61),
('elegi-pescado-de-origen-sustentable','catalog','animales','Elegí pescado de origen sustentable','Una mano a la fauna.','easy','medium','honor',500,'recurring','animales','Das refugio y alimento a la fauna',true,62),
('saca-especies-invasoras-de-tu-zona','catalog','animales','Sacá especies invasoras de tu zona','Una mano a la fauna.','medium','medium','photo_ai',750,'recurring','animales','Das refugio y alimento a la fauna',true,63),
('reporta-fauna-herida-a-un-centro-de-rescate','catalog','animales','Reportá fauna herida a un centro de rescate','Una mano a la fauna.','easy','medium','honor',500,'one_time','animales','Das refugio y alimento a la fauna',true,64),
('evita-productos-con-aceite-de-palma-no-sustentab','catalog','animales','Evitá productos con aceite de palma no sustentable','Una mano a la fauna.','medium','medium','honor',750,'recurring','animales','Das refugio y alimento a la fauna',true,65),
('planta-especies-hospederas-para-mariposas','catalog','animales','Plantá especies hospederas para mariposas','Una mano a la fauna.','easy','medium','photo_ai',500,'one_time','animales','Das refugio y alimento a la fauna',true,66),
('hace-un-lunes-sin-carne-cada-semana','catalog','alimentacion','Hacé un Lunes sin carne cada semana','Comé cuidando el planeta.','easy','high','honor',500,'weekly','alimentacion','Evitás una buena dosis de CO₂ y agua',true,67),
('pasa-una-semana-100-a-base-de-plantas','catalog','alimentacion','Pasá una semana 100% a base de plantas','Comé cuidando el planeta.','hard','high','honor',1500,'weekly','alimentacion','Evitás una buena dosis de CO₂ y agua',true,68),
('compra-productos-locales-y-de-estacion','catalog','alimentacion','Comprá productos locales y de estación','Comé cuidando el planeta.','easy','medium','honor',500,'weekly','alimentacion','Ahorrás agua y emisiones',true,69),
('compra-en-una-feria-de-productores','catalog','alimentacion','Comprá en una feria de productores','Comé cuidando el planeta.','easy','low','honor',300,'weekly','alimentacion','Reducís tu huella de comida',true,70),
('planifica-tus-comidas-para-no-comprar-de-mas','catalog','alimentacion','Planificá tus comidas para no comprar de más','Comé cuidando el planeta.','medium','medium','honor',750,'weekly','alimentacion','Ahorrás agua y emisiones',true,71),
('rescata-comida-excedente-con-apps','catalog','alimentacion','Rescatá comida excedente con apps','Comé cuidando el planeta.','easy','medium','honor',500,'recurring','alimentacion','Ahorrás agua y emisiones',true,72),
('cultiva-hierbas-para-reemplazar-las-envasadas','catalog','alimentacion','Cultivá hierbas para reemplazar las envasadas','Comé cuidando el planeta.','easy','low','photo_ai',300,'one_time','alimentacion','Reducís tu huella de comida',true,73),
('lleva-un-diario-de-desperdicio-de-comida','catalog','alimentacion','Llevá un diario de desperdicio de comida','Comé cuidando el planeta.','medium','medium','honor',750,'weekly','alimentacion','Ahorrás agua y emisiones',true,74),
('compra-ropa-de-segunda-mano-o-vintage','catalog','consumo','Comprá ropa de segunda mano o vintage','Comprá mejor.','easy','medium','honor',500,'recurring','consumo','Evitás producción y residuos',true,75),
('repara-tu-ropa-con-zurcido-visible','catalog','consumo','Repará tu ropa con zurcido visible','Comprá mejor.','medium','low','photo_ai',500,'recurring','consumo','Alargás la vida de las cosas',true,76),
('hace-un-mes-sin-compras-innecesarias','catalog','consumo','Hacé un mes sin compras innecesarias','Comprá mejor.','hard','medium','honor',1500,'recurring','consumo','Evitás producción y residuos',true,77),
('pedi-prestado-o-alquila-en-vez-de-comprar','catalog','consumo','Pedí prestado o alquilá en vez de comprar','Comprá mejor.','medium','low','honor',500,'recurring','consumo','Alargás la vida de las cosas',true,78),
('compra-a-marcas-certificadas-sustentables','catalog','consumo','Comprá a marcas certificadas sustentables','Comprá mejor.','easy','low','honor',300,'recurring','consumo','Alargás la vida de las cosas',true,79),
('elegi-productos-con-minimo-packaging','catalog','consumo','Elegí productos con mínimo packaging','Comprá mejor.','easy','low','honor',300,'recurring','consumo','Alargás la vida de las cosas',true,80),
('revende-o-dona-lo-que-no-usas','catalog','consumo','Revendé o doná lo que no usás','Comprá mejor.','medium','low','honor',500,'recurring','consumo','Alargás la vida de las cosas',true,81),
('usa-una-biblioteca-de-libros-o-de-cosas','catalog','consumo','Usá una biblioteca de libros o de cosas','Comprá mejor.','easy','low','honor',300,'recurring','consumo','Alargás la vida de las cosas',true,82),
('compra-electronica-reacondicionada','catalog','consumo','Comprá electrónica reacondicionada','Comprá mejor.','medium','medium','photo_ai',750,'one_time','consumo','Evitás producción y residuos',true,83),
('cambia-a-productos-recargables-del-hogar','catalog','consumo','Cambiá a productos recargables del hogar','Comprá mejor.','easy','low','honor',300,'recurring','consumo','Alargás la vida de las cosas',true,84),
('limpia-tu-nube-y-borra-archivos-viejos','catalog','digital','Limpiá tu nube y borrá archivos viejos','Aligerá tu huella digital.','easy','low','honor',300,'recurring','digital','Aligerás tu huella digital',true,85),
('alarga-la-vida-de-tu-celular-un-ano-mas','catalog','digital','Alargá la vida de tu celular un año más','Aligerá tu huella digital.','easy','medium','honor',500,'one_time','digital','Reducís energía y e-waste',true,86),
('activa-los-modos-de-ahorro-de-energia','catalog','digital','Activá los modos de ahorro de energía','Aligerá tu huella digital.','easy','low','photo_ai',300,'one_time','digital','Aligerás tu huella digital',true,87),
('desuscribite-de-newsletters-que-no-lees','catalog','digital','Desuscribite de newsletters que no leés','Aligerá tu huella digital.','easy','low','honor',300,'one_time','digital','Aligerás tu huella digital',true,88),
('recicla-tus-dispositivos-viejos-responsablemente','catalog','digital','Reciclá tus dispositivos viejos responsablemente','Aligerá tu huella digital.','medium','medium','photo_ai',750,'one_time','digital','Reducís energía y e-waste',true,89),
('organiza-o-sumate-a-una-limpieza-del-barrio','catalog','comunidad','Organizá o sumate a una limpieza del barrio','Hacelo con otros.','medium','medium','photo_ai',1000,'recurring','comunidad','Multiplicás el impacto con otros',true,90),
('crea-o-sumate-a-un-grupo-ambiental-local','catalog','comunidad','Creá o sumate a un grupo ambiental local','Hacelo con otros.','hard','high','honor',2000,'recurring','comunidad','Generás cambio colectivo real',true,91),
('escribi-a-un-representante-por-un-tema-ambiental','catalog','comunidad','Escribí a un representante por un tema ambiental','Hacelo con otros.','medium','medium','honor',750,'one_time','comunidad','Multiplicás el impacto con otros',true,92),
('dicta-un-taller-o-charla-ambiental','catalog','comunidad','Dictá un taller o charla ambiental','Hacelo con otros.','hard','medium','photo_ai',1500,'recurring','comunidad','Multiplicás el impacto con otros',true,93),
('organiza-un-cafe-de-reparacion-comunitario','catalog','comunidad','Organizá un café de reparación comunitario','Hacelo con otros.','hard','medium','photo_ai',1500,'recurring','comunidad','Multiplicás el impacto con otros',true,94),
('arma-una-biblioteca-de-herramientas-o-de-semilla','catalog','comunidad','Armá una biblioteca de herramientas o de semillas','Hacelo con otros.','hard','medium','photo_ai',1500,'one_time','comunidad','Multiplicás el impacto con otros',true,95),
('lanza-un-reto-de-barrio-contra-barrio','catalog','comunidad','Lanzá un reto de barrio contra barrio','Hacelo con otros.','medium','high','honor',1000,'recurring','comunidad','Generás cambio colectivo real',true,96),
('hace-voluntariado-en-restauracion-de-habitats','catalog','comunidad','Hacé voluntariado en restauración de hábitats','Hacelo con otros.','medium','medium','photo_ai',750,'recurring','comunidad','Multiplicás el impacto con otros',true,97),
('junta-firmas-por-ciclovias-o-espacios-verdes','catalog','comunidad','Juntá firmas por ciclovías o espacios verdes','Hacelo con otros.','medium','medium','honor',750,'one_time','comunidad','Multiplicás el impacto con otros',true,98),
('se-mentor-de-alguien-nuevo-en-la-plataforma','catalog','comunidad','Sé mentor de alguien nuevo en la plataforma','Hacelo con otros.','easy','low','honor',300,'recurring','comunidad','Sumás al barrio',true,99),
('coordina-auto-compartido-en-el-trabajo-o-escuela','catalog','comunidad','Coordiná auto compartido en el trabajo o escuela','Hacelo con otros.','medium','medium','honor',750,'recurring','comunidad','Multiplicás el impacto con otros',true,100),
('participa-de-una-limpieza-de-costa-o-rio','catalog','agua_azul','Participá de una limpieza de costa o río','Cuidá el agua azul.','medium','medium','photo_ai',1000,'recurring','agua_azul','Evitás contaminación del agua',true,101),
('adopta-una-boca-de-tormenta-y-mantenela-despejad','catalog','agua_azul','Adoptá una boca de tormenta y mantenela despejada','Cuidá el agua azul.','medium','medium','photo_ai',750,'recurring','agua_azul','Evitás contaminación del agua',true,102),
('usa-una-bolsa-para-microfibras-al-lavar','catalog','agua_azul','Usá una bolsa para microfibras al lavar','Cuidá el agua azul.','easy','medium','photo_ai',500,'one_time','agua_azul','Evitás contaminación del agua',true,103),
('usa-protector-solar-amigable-con-los-arrecifes','catalog','agua_azul','Usá protector solar amigable con los arrecifes','Cuidá el agua azul.','easy','low','honor',300,'recurring','agua_azul','Cuidás ríos y costas',true,104),
('sumate-a-un-programa-de-monitoreo-de-cuencas','catalog','agua_azul','Sumate a un programa de monitoreo de cuencas','Cuidá el agua azul.','medium','medium','photo_ai',750,'recurring','agua_azul','Evitás contaminación del agua',true,105),
('desecha-medicamentos-correctamente','catalog','agua_azul','Desechá medicamentos correctamente','Cuidá el agua azul.','easy','medium','honor',500,'recurring','agua_azul','Evitás contaminación del agua',true,106),
('evita-quemar-residuos-al-aire-libre','catalog','aire_suelo','Evitá quemar residuos al aire libre','Aire y suelo más sanos.','easy','medium','honor',500,'recurring','aire_suelo','Mejorás aire y suelo locales',true,107),
('usa-cortadora-manual-o-electrica-en-vez-de-nafta','catalog','aire_suelo','Usá cortadora manual o eléctrica en vez de nafta','Aire y suelo más sanos.','medium','low','photo_ai',500,'recurring','aire_suelo','Cuidás el aire y el suelo',true,108),
('mejora-la-salud-del-suelo-sin-labranza','catalog','aire_suelo','Mejorá la salud del suelo sin labranza','Aire y suelo más sanos.','medium','medium','photo_ai',750,'recurring','aire_suelo','Mejorás aire y suelo locales',true,109),
('evita-compost-a-base-de-turba','catalog','aire_suelo','Evitá compost a base de turba','Aire y suelo más sanos.','easy','medium','honor',500,'one_time','aire_suelo','Mejorás aire y suelo locales',true,110),
('planta-para-dar-sombra-y-enfriar-la-ciudad','catalog','aire_suelo','Plantá para dar sombra y enfriar la ciudad','Aire y suelo más sanos.','medium','medium','photo_ai',750,'one_time','aire_suelo','Mejorás aire y suelo locales',true,111),
('reduci-el-uso-de-lena-o-usa-cocinas-mas-limpias','catalog','aire_suelo','Reducí el uso de leña o usá cocinas más limpias','Aire y suelo más sanos.','medium','medium','honor',750,'recurring','aire_suelo','Mejorás aire y suelo locales',true,112),
('arma-un-cantero-alimentado-con-compost','catalog','aire_suelo','Armá un cantero alimentado con compost','Aire y suelo más sanos.','medium','medium','photo_ai',750,'one_time','aire_suelo','Mejorás aire y suelo locales',true,113),
('registra-una-observacion-de-biodiversidad','catalog','ciencia','Registrá una observación de biodiversidad','Ayudá a la ciencia.','easy','medium','photo_ai',500,'recurring','ciencia','Tus datos ayudan a investigar',true,114),
('hace-un-conteo-de-aves','catalog','ciencia','Hacé un conteo de aves','Ayudá a la ciencia.','easy','medium','photo_ai',500,'recurring','ciencia','Tus datos ayudan a investigar',true,115),
('reporta-mediciones-de-calidad-de-aire','catalog','ciencia','Reportá mediciones de calidad de aire','Ayudá a la ciencia.','medium','medium','photo_ai',750,'recurring','ciencia','Tus datos ayudan a investigar',true,116),
('subi-un-geo-tag-de-basura-encontrada','catalog','ciencia','Subí un geo-tag de basura encontrada','Ayudá a la ciencia.','easy','low','photo_ai',300,'recurring','ciencia','Aportás un dato a la ciencia',true,117),
('participa-de-un-bioblitz-urbano','catalog','ciencia','Participá de un bioblitz urbano','Ayudá a la ciencia.','medium','medium','photo_ai',750,'recurring','ciencia','Tus datos ayudan a investigar',true,118),
('monitorea-una-poblacion-local-de-polinizadores','catalog','ciencia','Monitoreá una población local de polinizadores','Ayudá a la ciencia.','medium','medium','photo_ai',750,'recurring','ciencia','Tus datos ayudan a investigar',true,119),
('fotografia-fenologia-floracion-migracion','catalog','ciencia','Fotografiá fenología (floración, migración)','Ayudá a la ciencia.','easy','medium','photo_ai',500,'recurring','ciencia','Tus datos ayudan a investigar',true,120),
('reporta-avistajes-de-especies-invasoras','catalog','ciencia','Reportá avistajes de especies invasoras','Ayudá a la ciencia.','easy','medium','photo_ai',500,'recurring','ciencia','Tus datos ayudan a investigar',true,121),
('arma-un-kit-reutilizable-para-llevar-siempre','catalog','residuos','Armá un kit reutilizable para llevar siempre','Menos basura, más vueltas.','easy','low','honor',300,'one_time','residuos','Desviás residuos del relleno',false,900),
('medi-tu-consumo-de-agua-una-semana','catalog','agua','Medí tu consumo de agua una semana','Cada gota suma.','easy','low','honor',300,'weekly','agua','Ahorrás ~20 L de agua',false,901),
('sella-ventanas-para-el-invierno','catalog','energia','Sellá ventanas para el invierno','Menos consumo, menos CO₂.','medium','medium','photo_ai',750,'one_time','energia','Evitás varios kg de CO₂',false,902),
('proba-una-semana-de-teletrabajo-total','catalog','movilidad','Probá una semana de teletrabajo total','Moverte limpio.','medium','medium','honor',750,'weekly','movilidad','Evitás varios kg de CO₂',false,903),
('arma-un-compost-de-hojas-mantillo','catalog','plantas','Armá un compost de hojas (mantillo)','Sembrá vida.','easy','low','honor',300,'one_time','plantas','Sumás verde a tu entorno',false,904),
('construi-una-caja-nido-para-aves','catalog','animales','Construí una caja nido para aves','Una mano a la fauna.','medium','medium','photo_ai',750,'one_time','animales','Das refugio y alimento a la fauna',false,905),
('proba-una-receta-de-aprovechamiento-total','catalog','alimentacion','Probá una receta de aprovechamiento total','Comé cuidando el planeta.','easy','medium','honor',500,'recurring','alimentacion','Ahorrás agua y emisiones',false,906),
('arma-un-fondo-para-reparar-en-vez-de-reemplazar','catalog','consumo','Armá un fondo para reparar en vez de reemplazar','Comprá mejor.','easy','low','honor',300,'one_time','consumo','Alargás la vida de las cosas',false,907),
('configura-backups-eficientes-y-borra-duplicados','catalog','digital','Configurá backups eficientes y borrá duplicados','Aligerá tu huella digital.','easy','low','honor',300,'one_time','digital','Aligerás tu huella digital',false,908),
('propone-una-huerta-en-tu-edificio','catalog','comunidad','Proponé una huerta en tu edificio','Hacelo con otros.','medium','medium','honor',750,'one_time','comunidad','Multiplicás el impacto con otros',false,909),
('sumate-a-un-dia-de-limpieza-submarina-o-costera','catalog','agua_azul','Sumate a un día de limpieza submarina o costera','Cuidá el agua azul.','medium','medium','photo_ai',1000,'recurring','agua_azul','Evitás contaminación del agua',false,910),
('hace-un-test-de-calidad-de-tu-suelo','catalog','aire_suelo','Hacé un test de calidad de tu suelo','Aire y suelo más sanos.','medium','low','photo_ai',500,'one_time','aire_suelo','Cuidás el aire y el suelo',false,911),
('sumate-a-un-proyecto-de-fenologia-estacional','catalog','ciencia','Sumate a un proyecto de fenología estacional','Ayudá a la ciencia.','easy','medium','photo_ai',500,'recurring','ciencia','Tus datos ayudan a investigar',false,912),
('crea-un-rincon-de-plantas-nativas-en-macetas','catalog','plantas','Creá un rincón de plantas nativas en macetas','Sembrá vida.','easy','low','photo_ai',500,'one_time','plantas','Sumás verde a tu entorno',false,913),
('hace-un-mapa-de-consumo-de-tus-electrodomesticos','catalog','energia','Hacé un mapa de consumo de tus electrodomésticos','Menos consumo, menos CO₂.','medium','low','honor',500,'one_time','energia','Bajás un poco tu consumo',false,914)
on conflict (slug) do nothing;

-- titles (48)
insert into titles (slug,name_es,domain_slug,requirement_type,requirement_value,requirement_domain,rarity,icon,description_es) values
('agua-1','Cuidador del Agua','agua','domain_points',2000,'agua','common','agua','Sumá 2.000 puntos en agua.'),
('agua-2','Guardián del Agua','agua','domain_points',10000,'agua','rare','agua','Sumá 10.000 puntos en agua.'),
('agua-3','Maestro del Agua','agua','domain_points',30000,'agua','epic','agua','Sumá 30.000 puntos en agua.'),
('residuos-1','Reciclador','residuos','domain_points',2000,'residuos','common','residuos','Sumá 2.000 puntos en residuos.'),
('residuos-2','Héroe Cero Residuos','residuos','domain_points',10000,'residuos','rare','residuos','Sumá 10.000 puntos en residuos.'),
('residuos-3','Campeón Circular','residuos','domain_points',30000,'residuos','epic','residuos','Sumá 30.000 puntos en residuos.'),
('animales-1','Amigo de los Animales','animales','domain_points',2000,'animales','common','animales','Sumá 2.000 puntos en animales.'),
('animales-2','Protector de la Fauna','animales','domain_points',10000,'animales','rare','animales','Sumá 10.000 puntos en animales.'),
('animales-3','Guardián Silvestre','animales','domain_points',30000,'animales','epic','animales','Sumá 30.000 puntos en animales.'),
('plantas-1','Jardinero','plantas','domain_points',2000,'plantas','common','plantas','Sumá 2.000 puntos en plantas.'),
('plantas-2','Sembrador','plantas','domain_points',10000,'plantas','rare','plantas','Sumá 10.000 puntos en plantas.'),
('plantas-3','Maestro Verde','plantas','domain_points',30000,'plantas','epic','plantas','Sumá 30.000 puntos en plantas.'),
('movilidad-1','Pedaleador','movilidad','domain_points',2000,'movilidad','common','movilidad','Sumá 2.000 puntos en movilidad.'),
('movilidad-2','Viajero Limpio','movilidad','domain_points',10000,'movilidad','rare','movilidad','Sumá 10.000 puntos en movilidad.'),
('movilidad-3','Maestro de la Movilidad','movilidad','domain_points',30000,'movilidad','epic','movilidad','Sumá 30.000 puntos en movilidad.'),
('energia-1','Ahorrador','energia','domain_points',2000,'energia','common','energia','Sumá 2.000 puntos en energia.'),
('energia-2','Eficiente','energia','domain_points',10000,'energia','rare','energia','Sumá 10.000 puntos en energia.'),
('energia-3','Maestro de la Energía','energia','domain_points',30000,'energia','epic','energia','Sumá 30.000 puntos en energia.'),
('alimentacion-1','Cocina Consciente','alimentacion','domain_points',2000,'alimentacion','common','alimentacion','Sumá 2.000 puntos en alimentacion.'),
('alimentacion-2','Plant-Forward','alimentacion','domain_points',10000,'alimentacion','rare','alimentacion','Sumá 10.000 puntos en alimentacion.'),
('alimentacion-3','Maestro de la Alimentación','alimentacion','domain_points',30000,'alimentacion','epic','alimentacion','Sumá 30.000 puntos en alimentacion.'),
('consumo-1','Comprador Consciente','consumo','domain_points',2000,'consumo','common','consumo','Sumá 2.000 puntos en consumo.'),
('consumo-2','Minimalista','consumo','domain_points',10000,'consumo','rare','consumo','Sumá 10.000 puntos en consumo.'),
('consumo-3','Maestro del Consumo','consumo','domain_points',30000,'consumo','epic','consumo','Sumá 30.000 puntos en consumo.'),
('digital-1','Higiene Digital','digital','domain_points',2000,'digital','common','digital','Sumá 2.000 puntos en digital.'),
('digital-2','Eco-Digital','digital','domain_points',10000,'digital','rare','digital','Sumá 10.000 puntos en digital.'),
('digital-3','Maestro Digital','digital','domain_points',30000,'digital','epic','digital','Sumá 30.000 puntos en digital.'),
('comunidad-1','Vecino Activo','comunidad','domain_points',2000,'comunidad','common','comunidad','Sumá 2.000 puntos en comunidad.'),
('comunidad-2','Organizador','comunidad','domain_points',10000,'comunidad','rare','comunidad','Sumá 10.000 puntos en comunidad.'),
('comunidad-3','Líder Comunitario','comunidad','domain_points',30000,'comunidad','epic','comunidad','Sumá 30.000 puntos en comunidad.'),
('agua-azul-1','Amigo del Mar','agua_azul','domain_points',2000,'agua_azul','common','agua_azul','Sumá 2.000 puntos en agua_azul.'),
('agua-azul-2','Guardián Costero','agua_azul','domain_points',10000,'agua_azul','rare','agua_azul','Sumá 10.000 puntos en agua_azul.'),
('agua-azul-3','Maestro del Océano','agua_azul','domain_points',30000,'agua_azul','epic','agua_azul','Sumá 30.000 puntos en agua_azul.'),
('aire-suelo-1','Cuida-Suelos','aire_suelo','domain_points',2000,'aire_suelo','common','aire_suelo','Sumá 2.000 puntos en aire_suelo.'),
('aire-suelo-2','Aire Limpio','aire_suelo','domain_points',10000,'aire_suelo','rare','aire_suelo','Sumá 10.000 puntos en aire_suelo.'),
('aire-suelo-3','Maestro de la Tierra','aire_suelo','domain_points',30000,'aire_suelo','epic','aire_suelo','Sumá 30.000 puntos en aire_suelo.'),
('ciencia-1','Observador','ciencia','domain_points',2000,'ciencia','common','ciencia','Sumá 2.000 puntos en ciencia.'),
('ciencia-2','Naturalista','ciencia','domain_points',10000,'ciencia','rare','ciencia','Sumá 10.000 puntos en ciencia.'),
('ciencia-3','Maestro Ciudadano','ciencia','domain_points',30000,'ciencia','epic','ciencia','Sumá 30.000 puntos en ciencia.'),
('recien-brotado','Recién Brotado',null,'rank',2,null,'rare','special','Llegaste al rango Brote.'),
('raices-firmes','Raíces Firmes',null,'rank',6,null,'epic','special','Llegaste al rango Árbol.'),
('guardian-del-planeta','Guardián del Planeta',null,'rank',10,null,'epic','special','Llegaste al rango Planeta.'),
('leyenda-viva','Leyenda Viva',null,'rank',11,null,'legendary','special','Alcanzaste Gaia. Sos leyenda.'),
('imparable','Imparable',null,'streak',30,null,'epic','special','Mantené una racha de 30 días.'),
('centenario','Centenario',null,'streak',100,null,'legendary','special','Mantené una racha de 100 días.'),
('verificado','Verificado',null,'verified',10,null,'rare','special','Verificá 10 acciones con foto.'),
('madrugador','Madrugador',null,'special',0,null,'rare','special','Hacé 10 acciones diarias temprano.'),
('constructor-comunidad','Constructor de Comunidad',null,'special',0,null,'epic','special','Creá un proyecto con 10 participantes.')
on conflict (slug) do nothing;

-- badges (25)
insert into badges (slug,name_es,description_es,requirement_type,requirement_value,requirement_domain,rarity,icon) values
('primera-accion','Primera Acción','Tu primera acción completada.','activity_count',1,null,'common','special'),
('diez-acciones','Diez Acciones','Completaste 10 acciones.','activity_count',10,null,'common','special'),
('cincuenta-acciones','Cincuenta Acciones','Completaste 50 acciones.','activity_count',50,null,'rare','special'),
('centurion','100 Acciones','Completaste 100 acciones.','activity_count',100,null,'epic','special'),
('primera-semana','Primera Semana','Racha de 7 días.','streak',7,null,'common','special'),
('racha-de-fuego','Racha de Fuego','Racha de 14 días.','streak',14,null,'rare','special'),
('mes-verde','Mes Verde','Racha de 30 días.','streak',30,null,'rare','special'),
('imparable-badge','Imparable','Racha de 100 días.','streak',100,null,'legendary','special'),
('verificado-x10','Verificado x10','10 acciones verificadas.','verified',10,null,'rare','special'),
('explorador-agua','Explorador del Agua','2.000 puntos en Agua.','domain_points',2000,'agua','rare','agua'),
('manos-tierra','Manos a la Tierra','2.000 puntos en Plantas.','domain_points',2000,'plantas','rare','plantas'),
('cero-residuos','Cero Residuos','2.000 puntos en Residuos.','domain_points',2000,'residuos','rare','residuos'),
('sobre-ruedas','Sobre Ruedas','2.000 puntos en Movilidad.','domain_points',2000,'movilidad','rare','movilidad'),
('ahorrador-badge','Ahorrador','2.000 puntos en Energía.','domain_points',2000,'energia','rare','energia'),
('plato-verde','Plato Verde','2.000 puntos en Alimentación.','domain_points',2000,'alimentacion','rare','alimentacion'),
('amigo-animal','Amigo Animal','2.000 puntos en Animales.','domain_points',2000,'animales','rare','animales'),
('cientifico-ciudadano','Científico Ciudadano','2.000 puntos en Ciencia.','domain_points',2000,'ciencia','rare','ciencia'),
('maestria-agua','Maestría del Agua','10.000 puntos en Agua.','domain_points',10000,'agua','epic','agua'),
('leyenda-verde','Leyenda Verde','Alcanzaste el rango Gaia.','rank',11,null,'legendary','special'),
('primer-arbol','Primer Árbol','Plantaste tu primer árbol.','special',0,null,'rare','special'),
('primer-proyecto','Primer Proyecto','Creaste tu primer proyecto.','special',0,null,'rare','special'),
('polinizador','Polinizador','Ayudaste a los polinizadores.','special',0,null,'rare','special'),
('limpieza-costera','Limpieza Costera','Sumaste a una limpieza costera.','special',0,null,'epic','special'),
('todo-en-un-dia','Todo en un Día','Completaste el set diario.','special',0,null,'common','special'),
('madrugador-badge','Madrugador','Acciones a primera hora.','special',0,null,'rare','special')
on conflict (slug) do nothing;

-- challenges (re-seedable: clear prior seeds first)
delete from challenges;
insert into challenges (type,title_es,domain_slug,target_metric,target_value,reward_points,min_rank_slug,starts_at,ends_at,active) values
('daily','Sumá 2 acciones de Agua hoy','agua','domain_completions',2,300,'semilla',now(),now() + interval '1 days',true),
('daily','Hacé 1 acción de Movilidad','movilidad','domain_completions',1,200,'semilla',now(),now() + interval '1 days',true),
('daily','Completá 3 acciones diarias',null,'daily_actions',3,300,'semilla',now(),now() + interval '1 days',true),
('daily','Sumá 1 acción de Alimentación','alimentacion','domain_completions',1,200,'semilla',now(),now() + interval '1 days',true),
('daily','Reciclá: 2 acciones de Residuos','residuos','domain_completions',2,300,'semilla',now(),now() + interval '1 days',true),
('daily','Día verde: 4 acciones diarias',null,'daily_actions',4,400,'semilla',now(),now() + interval '1 days',true),
('daily','Sumá 1 acción de Energía','energia','domain_completions',1,200,'semilla',now(),now() + interval '1 days',true),
('daily','Cuidá la fauna: 1 acción de Animales','animales','domain_completions',1,200,'semilla',now(),now() + interval '1 days',true),
('daily','Sumá 1 acción de Plantas','plantas','domain_completions',1,200,'semilla',now(),now() + interval '1 days',true),
('daily','Mantené tu racha hoy',null,'daily_actions',1,150,'semilla',now(),now() + interval '1 days',true),
('weekly','Semana del Agua','agua','domain_completions',5,1000,'semilla',now(),now() + interval '7 days',true),
('weekly','Movilidad limpia','movilidad','domain_completions',4,1000,'semilla',now(),now() + interval '7 days',true),
('weekly','Plato a base de plantas','alimentacion','domain_completions',5,1000,'semilla',now(),now() + interval '7 days',true),
('weekly','Reto Cero Residuos','residuos','domain_completions',6,1200,'semilla',now(),now() + interval '7 days',true),
('weekly','Reto comunitario','comunidad','domain_completions',2,1200,'arbol',now(),now() + interval '7 days',true),
('weekly','Maratón verde',null,'completions',12,1500,'semilla',now(),now() + interval '7 days',true),
('seasonal','Semana del Agua','agua','domain_completions',10,2500,'semilla',now(),now() + interval '21 days',true),
('seasonal','Bioblitz de Primavera','ciencia','domain_completions',8,2500,'arbol',now(),now() + interval '21 days',true);

-- example projects (re-seedable: clear official seeds first)
delete from projects where creator_id is null;
insert into projects (creator_id,title,description,type,domain_slug,neighborhood,lat,lng,location_text,event_date,status,min_rank_slug,max_participants,reward_points) values
(null,'Limpieza en el Parque Tres de Febrero','Sumate a una jornada de limpieza en los bosques de Palermo. Llevamos guantes y bolsas.','limpieza','comunidad','Palermo',-34.5712,-58.416,'Palermo, CABA',now() + interval '10 days','active','semilla',100,500),
(null,'Plantación de nativas en Caballito','Plantamos especies nativas en una plaza del barrio. Cupos limitados.','plantacion','plantas','Caballito',-34.619,-58.44,'Caballito, CABA',now() + interval '10 days','active','plantula',40,500),
(null,'Campaña de reciclaje en el edificio','Armamos puntos de separación y educamos a los vecinos.','reciclaje','residuos','Villa Crespo',-34.599,-58.438,'Villa Crespo, CABA',now() + interval '10 days','active','semilla',null,500),
(null,'Limpieza costera en la Costanera Sur','Jornada de limpieza junto a la Reserva Ecológica. Registramos lo recolectado.','limpieza','agua_azul','Puerto Madero',-34.611,-58.353,'Puerto Madero, CABA',now() + interval '10 days','active','semilla',80,500);

-- app_state config
insert into app_state (key,value,is_public) values ('news_feeds','[{"name":"Mongabay Latam","url":"https://es.mongabay.com/feed/"},{"name":"Grist","url":"https://grist.org/feed/"},{"name":"Yale e360","url":"https://e360.yale.edu/feed.xml"},{"name":"The Guardian Environment","url":"https://www.theguardian.com/environment/rss"},{"name":"UN Environment","url":"https://www.unep.org/rss.xml"},{"name":"Mongabay","url":"https://news.mongabay.com/feed/"}]'::jsonb,false) on conflict (key) do update set value=excluded.value;
insert into app_state (key,value,is_public) values ('pip_lines','["¿Qué vas a hacer crecer hoy?","Cada acción cuenta. En serio.","Dale, una más y la rompés.","Tu mundo te lo agradece.","¡Buenísimo! Seguí así.","Pequeños pasos, mundo enorme."]'::jsonb,true) on conflict (key) do update set value=excluded.value;
insert into app_state (key,value,is_public) values ('featured_rotation','{"pointer":0}'::jsonb,false) on conflict (key) do nothing;
insert into app_state (key,value,is_public) values ('gemini_usage','{"day":"","verify":0,"recommend":0,"news":0}'::jsonb,false) on conflict (key) do nothing;

update activities set is_featured = true, featured_week = (now() at time zone 'America/Argentina/Buenos_Aires')::date
  where id in (select id from activities where type='catalog' and active order by created_at limit 2);
insert into app_state (key,value,is_public) values ('current_daily_challenge', (select jsonb_build_object('id', id) from challenges where type='daily' and active order by random() limit 1), true) on conflict (key) do update set value=excluded.value;
