// Rama `agua` — 32 conceptos, 7 gajos (4 en anillo 1, 3 en anillo 2), 25 hojas.
// Puro dato. Ver scripts/academia/CONTRATO.md.

export default {
  rama: 'agua',
  gajos: [
    // ───────────────────────────────────────────────────────────── anillo 1
    {
      slug: 'agua.ciclo-y-cuenca',
      anillo: 1,
      titulo_es: 'El ciclo y la cuenca',
      bajada_es: 'De dónde viene el agua que sale de tu canilla y adónde va la que se va por la rejilla.',
      icono: 'Droplets',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'agua.ciclo_agua',
          titulo_es: 'El agua da vueltas',
          enunciado_es:
            'El agua no se gasta ni se fabrica: se evapora, forma nubes, llueve, corre y vuelve a empezar. Siempre es la misma agua cambiando de lugar.',
          detalle_es:
            'El agua que tomás hoy ya pasó por un río, por una nube y por otros seres vivos muchísimas veces antes.',
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: -1.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'tronco.ciclos_materia', fuerza: 0.5 }],
        },
        {
          slug: 'agua.dulce_es_poca',
          titulo_es: 'Casi toda el agua es salada',
          enunciado_es:
            'La mayor parte del agua del planeta es salada, y del poco de agua dulce que hay, buena parte está congelada o guardada bajo tierra.',
          detalle_es:
            'El agua dulce fácil de usar —ríos, lagos, napas accesibles— es una porción chica del total.',
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -1.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'agua.cuenca_hidrografica',
          titulo_es: 'Qué es una cuenca',
          enunciado_es:
            'Una cuenca es todo el territorio cuya lluvia termina drenando al mismo río, y por eso el agua se gestiona por cuenca y no por barrio ni por provincia.',
          detalle_es:
            'La cuenca no respeta los límites del mapa político: eso es justamente lo que la vuelve difícil de gobernar.',
          fuente: 'acumar',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'agua.ciclo_agua', fuerza: 0.5 }],
        },
        {
          slug: 'agua.cuenca_matanza_riachuelo',
          titulo_es: 'La cuenca donde vivís',
          enunciado_es:
            'La cuenca Matanza-Riachuelo atraviesa la Ciudad de Buenos Aires y varios municipios del conurbano, así que su saneamiento lo coordina un organismo interjurisdiccional: ACUMAR.',
          detalle_es:
            'Nación, Provincia y Ciudad comparten la misma agua, y por eso tuvieron que sentarse en la misma mesa.',
          fuente: 'acumar',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.cuenca_hidrografica'],
        },
        {
          slug: 'agua.rejilla_llega_al_rio',
          titulo_es: 'La rejilla de la esquina es el río',
          enunciado_es:
            'Lo que queda en la calle —basura, aceite, restos de lavado— entra por la rejilla al desagüe pluvial y sale sin tratamiento en un arroyo o en el río.',
          detalle_es:
            'El desagüe de lluvia y la cloaca son dos redes distintas: solo una termina en una planta de tratamiento.',
          fuente: 'acumar',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.todo_esta_conectado', { slug: 'agua.cuenca_hidrografica', fuerza: 0.5 }],
        },
      ],
      hojas: [
        {
          slug: 'agua.ciclo-y-cuenca.1',
          titulo_es: 'El agua que vuelve siempre',
          bajada_es: 'La misma agua, dando vueltas desde hace muchísimo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.ciclo_agua', 'agua.dulce_es_poca'],
        },
        {
          slug: 'agua.ciclo-y-cuenca.2',
          titulo_es: 'Todo cae en la misma cuenca',
          bajada_es: 'La unidad con la que se piensa el agua no es el barrio.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.cuenca_hidrografica', 'agua.ciclo_agua'],
        },
        {
          slug: 'agua.ciclo-y-cuenca.3',
          titulo_es: 'Matanza-Riachuelo, la de acá',
          bajada_es: 'Tres jurisdicciones, un solo río.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.cuenca_matanza_riachuelo', 'agua.cuenca_hidrografica'],
        },
        {
          slug: 'agua.ciclo-y-cuenca.4',
          titulo_es: 'De la rejilla al río',
          bajada_es: 'Dos redes distintas debajo de la misma vereda.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['agua.rejilla_llega_al_rio', 'agua.cuenca_matanza_riachuelo'],
        },
      ],
    },
    {
      slug: 'agua.de-la-canilla',
      anillo: 1,
      titulo_es: 'De la canilla para atrás',
      bajada_es: 'Cómo el agua del río llega potable a tu vaso, y qué la cuida en el camino.',
      icono: 'GlassWater',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'agua.rio_de_la_plata_fuente',
          titulo_es: 'El río que te da de tomar',
          enunciado_es:
            'La mayor parte del agua potable del AMBA se toma del Río de la Plata, se potabiliza en grandes plantas y viaja por la red hasta las casas.',
          detalle_es:
            'La planta General San Martín, en Palermo, es una de las que abastecen a la Ciudad y al conurbano.',
          fuente: 'acuifero-puelche',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'agua.potabilizacion',
          titulo_es: 'Cómo se limpia el agua',
          enunciado_es:
            'Potabilizar es una secuencia: coagulación y floculación para que la suciedad se junte en grumos, sedimentación para que caiga, filtración para lo que quedó y cloración para desinfectar.',
          detalle_es: 'Cada paso saca algo distinto; ninguno alcanza solo.',
          fuente: 'epa',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'agua.rio_de_la_plata_fuente', fuerza: 0.5 }],
        },
        {
          slug: 'agua.cloro_residual',
          titulo_es: 'El gustito a cloro',
          enunciado_es:
            'Queda un resto de cloro en el agua a propósito: es lo que la mantiene desinfectada durante todo el viaje por los caños hasta tu canilla.',
          detalle_es:
            'Si el sabor te molesta, dejá la jarra tapada un rato en la heladera y se va solo.',
          fuente: 'epa',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.potabilizacion'],
        },
        {
          slug: 'agua.agua_de_red_controlada',
          titulo_es: 'El agua de red se controla',
          enunciado_es:
            'El agua de red se trata y se analiza de forma periódica, y esos resultados son información pública que cualquiera puede consultar.',
          detalle_es:
            'La diferencia con una botella no es la confianza que da el envase: es que acá hay un control que se puede leer.',
          fuente: 'acumar',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.potabilizacion', { slug: 'tronco.evidencia_y_fuente', fuerza: 0.5 }],
          misconceptions: [
            {
              slug: 'agua.mito_embotellada',
              creencia_es: 'El agua embotellada es más segura que la de la canilla.',
              correccion_es:
                'La botella convence porque viene cerrada, con marca y con una etiqueta que habla de montañas: se ve el envase y no se ve el control. El agua de red se trata y se analiza de forma periódica y esos resultados son públicos; la embotellada agrega plástico, transporte y precio sin ser sistemáticamente más segura.',
              fuente: 'acumar',
            },
          ],
        },
        {
          slug: 'agua.perdidas_y_medicion',
          titulo_es: 'El agua que se pierde en el camino',
          enunciado_es:
            'Una parte del agua potabilizada nunca llega a una canilla: se pierde en fugas de la red y en las instalaciones de cada casa, y sin medición es difícil saber dónde.',
          detalle_es:
            'Un tanque que rebalsa y una canilla que gotea entran en la misma cuenta que un caño roto en la calle.',
          fuente: 'acuifero-puelche',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [
            { slug: 'agua.rio_de_la_plata_fuente', fuerza: 0.5 },
            { slug: 'tronco.stock_vs_flujo', fuerza: 0.5 },
          ],
        },
      ],
      hojas: [
        {
          slug: 'agua.de-la-canilla.1',
          titulo_es: 'Del río a la planta',
          bajada_es: 'El viaje empieza mucho antes de tu vaso.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.rio_de_la_plata_fuente', 'agua.potabilizacion'],
        },
        {
          slug: 'agua.de-la-canilla.2',
          titulo_es: 'Coagular, filtrar, clorar',
          bajada_es: 'Cuatro pasos y un resto de cloro que hace guardia.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.potabilizacion', 'agua.cloro_residual'],
        },
        {
          slug: 'agua.de-la-canilla.3',
          titulo_es: 'Canilla o botella',
          bajada_es: 'Qué mirás cuando elegís, y qué no se ve.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.agua_de_red_controlada', 'agua.cloro_residual'],
        },
        {
          slug: 'agua.de-la-canilla.4',
          titulo_es: 'Lo que se escapa',
          bajada_es: 'Fugas, tanques y por qué medir cambia todo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['agua.perdidas_y_medicion', 'agua.rio_de_la_plata_fuente'],
        },
      ],
    },
    {
      slug: 'agua.bajo-tus-pies',
      anillo: 1,
      titulo_es: 'El agua que está abajo',
      bajada_es: 'Napas, acuíferos y por qué lo que se tira arriba aparece abajo.',
      icono: 'Layers',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'agua.napa_freatica',
          titulo_es: 'La napa que está más arriba',
          enunciado_es:
            'Debajo del suelo hay agua guardada entre los granos de arena: la primera capa, la freática, es la más cercana a la superficie y la más fácil de contaminar.',
          detalle_es: 'No es un río subterráneo ni una laguna: es agua ocupando los huecos del sedimento.',
          fuente: 'acuifero-puelche',
          anillo: 1,
          dificultad_base: -0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'agua.acuifero_puelche',
          titulo_es: 'El Puelche',
          enunciado_es:
            'El Puelche es el acuífero más usado del norte bonaerense: está más profundo que la freática y lo separa de ella una capa de arcilla que lo protege en parte.',
          detalle_es:
            'Ese techo de arcilla es la razón por la que el Puelche aguantó tanto, y también la razón por la que un pozo mal hecho lo pone en riesgo.',
          fuente: 'acuifero-puelche',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.napa_freatica'],
        },
        {
          slug: 'agua.sobreexplotacion',
          titulo_es: 'Sacar más rápido de lo que entra',
          enunciado_es:
            'Un acuífero se recarga con la lluvia que se infiltra; si se extrae más rápido que esa recarga, el nivel baja y puede entrar agua salada o contaminada en su lugar.',
          detalle_es: null,
          fuente: 'acuifero-puelche',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.acuifero_puelche', 'tronco.stock_vs_flujo'],
        },
        {
          slug: 'agua.nitratos_napas',
          titulo_es: 'Nitratos donde no se ven',
          enunciado_es:
            'Los nitratos que llegan de fertilizantes, pozos ciegos y efluentes se disuelven en el agua subterránea sin cambiarle el color, el olor ni el sabor: solo un análisis los detecta.',
          detalle_es:
            'Que el agua de un pozo se vea limpia dice poco: eso es observación, y acá hace falta medición.',
          fuente: 'nitratos-puelche',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua.napa_freatica', { slug: 'tronco.observacion_vs_inferencia', fuerza: 0.5 }],
        },
        {
          slug: 'agua.pozo_ciego_y_pozo_de_agua',
          titulo_es: 'El pozo ciego y el pozo de agua',
          enunciado_es:
            'En los barrios sin cloacas conviven dos pozos en el mismo terreno: uno entrega el agua y el otro recibe los desechos, y cuando están cerca la freática pasa de uno al otro.',
          detalle_es:
            'Por eso la llegada de la red de agua y cloaca a un barrio es una medida de salud, no solo de comodidad.',
          fuente: 'nitratos-puelche',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua.napa_freatica'],
        },
      ],
      hojas: [
        {
          slug: 'agua.bajo-tus-pies.1',
          titulo_es: 'Agua entre los granos',
          bajada_es: 'Qué hay realmente abajo cuando decimos "napa".',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.napa_freatica', 'agua.acuifero_puelche'],
        },
        {
          slug: 'agua.bajo-tus-pies.2',
          titulo_es: 'Lo que entra y lo que sale',
          bajada_es: 'Una cuenta simple que explica por qué baja el nivel.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.sobreexplotacion', 'agua.acuifero_puelche'],
        },
        {
          slug: 'agua.bajo-tus-pies.3',
          titulo_es: 'Lo que no se ve ni se huele',
          bajada_es: 'Cuando el agua limpia a la vista no alcanza como prueba.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.nitratos_napas', 'agua.napa_freatica'],
        },
        {
          slug: 'agua.bajo-tus-pies.4',
          titulo_es: 'Dos pozos en el mismo patio',
          bajada_es: 'Por qué las cloacas son infraestructura de salud.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['agua.pozo_ciego_y_pozo_de_agua', 'agua.nitratos_napas'],
        },
      ],
    },
    {
      slug: 'agua.agua-invisible',
      anillo: 1,
      titulo_es: 'El agua que no sale de la canilla',
      bajada_es: 'La mayor parte del agua que usás ya venía adentro de lo que comprás.',
      icono: 'ShoppingBasket',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'agua.agua_virtual',
          titulo_es: 'El agua virtual',
          enunciado_es:
            'La mayor parte del agua que consumís no sale de tu canilla: se usó para producir lo que comés, lo que vestís y lo que comprás.',
          detalle_es: 'Es agua que ya se gastó antes de que el producto llegue a tu casa.',
          fuente: 'huella-hidrica',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'tronco.no_todo_pesa_igual', fuerza: 0.5 }],
        },
        {
          slug: 'agua.huella_hidrica',
          titulo_es: 'La huella hídrica',
          enunciado_es:
            'La huella hídrica de un producto es toda el agua que hizo falta para producirlo, sumada a lo largo de la cadena entera y no solo en el último paso.',
          detalle_es: null,
          fuente: 'huella-hidrica',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.agua_virtual', { slug: 'tronco.leer_un_numero', fuerza: 0.5 }],
        },
        {
          slug: 'agua.huella_verde_azul_gris',
          titulo_es: 'Verde, azul y gris',
          enunciado_es:
            'La huella hídrica se separa en tres: verde es la lluvia que aprovecha el cultivo, azul es el agua de río o de napa que se extrae, y gris es la que haría falta para diluir la contaminación generada.',
          detalle_es:
            'Sumarlas en un solo número grande esconde justo lo que importa: de dónde salió cada litro.',
          fuente: 'huella-hidrica',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua.huella_hidrica'],
        },
        {
          slug: 'agua.un_litro_no_vale_igual',
          titulo_es: 'Un litro no vale lo mismo en todos lados',
          enunciado_es:
            'El mismo litro pesa distinto según de dónde salga: sacarlo de una cuenca con lluvia de sobra no es lo mismo que sacarlo de una zona donde el agua ya escasea.',
          detalle_es: null,
          fuente: 'huella-hidrica',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua.huella_verde_azul_gris', 'tronco.no_todo_pesa_igual'],
        },
      ],
      hojas: [
        {
          slug: 'agua.agua-invisible.1',
          titulo_es: 'El agua que ya venía adentro',
          bajada_es: 'Lo que comprás llega mojado, aunque parezca seco.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.agua_virtual', 'agua.huella_hidrica'],
        },
        {
          slug: 'agua.agua-invisible.2',
          titulo_es: 'Tres colores de huella',
          bajada_es: 'Verde, azul y gris no son lo mismo ni de lejos.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.huella_verde_azul_gris', 'agua.huella_hidrica'],
        },
        {
          slug: 'agua.agua-invisible.3',
          titulo_es: 'Depende de dónde salga',
          bajada_es: 'El mismo número, dos historias distintas.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.un_litro_no_vale_igual', 'agua.huella_verde_azul_gris'],
        },
      ],
    },

    // ───────────────────────────────────────────────────────────── anillo 2
    {
      slug: 'agua.cuando-vuelve-sucia',
      anillo: 2,
      titulo_es: 'Cuando el agua vuelve',
      bajada_es: 'Qué pasa con el agua después de usarla, y qué se hizo para limpiar el Riachuelo.',
      icono: 'FlaskConical',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'agua.grises_y_negras',
          titulo_es: 'Aguas grises y aguas negras',
          enunciado_es:
            'El agua que sale de tu casa no es toda igual: las grises vienen de la ducha, el lavarropas y la pileta de la cocina; las negras vienen del inodoro y necesitan tratamiento sí o sí.',
          detalle_es: 'Separarlas permite reutilizar las grises para riego o para el inodoro.',
          fuente: 'epa',
          anillo: 2,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.rejilla_llega_al_rio'],
        },
        {
          slug: 'agua.depuracion_etapas',
          titulo_es: 'Las etapas de una planta cloacal',
          enunciado_es:
            'El tratamiento cloacal va por etapas: el primario separa sólidos, el secundario usa bacterias que se comen la materia orgánica y el terciario, cuando existe, saca nutrientes y desinfecta.',
          detalle_es:
            'Muchas plantas llegan hasta el secundario: el terciario es más caro y es el que cuida al río de los nutrientes.',
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.grises_y_negras'],
        },
        {
          slug: 'agua.eutrofizacion',
          titulo_es: 'Demasiados nutrientes',
          enunciado_es:
            'Cuando al agua le llegan muchos nutrientes de cloacas o de fertilizantes, las algas se multiplican, tapan la luz y al descomponerse consumen el oxígeno que los peces necesitan.',
          detalle_es: 'Es el mismo mecanismo en una laguna del conurbano y en un tramo del río.',
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.depuracion_etapas', { slug: 'tronco.todo_esta_conectado', fuerza: 0.5 }],
        },
        {
          slug: 'agua.floraciones_cianobacterias',
          titulo_es: 'Cuando el agua se pone verde',
          enunciado_es:
            'Con calor y muchos nutrientes aparecen floraciones de cianobacterias que pintan el agua de verde y pueden producir toxinas, y por eso a veces se recomienda no bañarse ni dejar entrar a las mascotas.',
          detalle_es:
            'Si ves el agua verde, espesa o con espuma, no te metas y avisale a una persona adulta.',
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.eutrofizacion'],
        },
        {
          slug: 'agua.fallo_mendoza',
          titulo_es: 'El fallo que creó ACUMAR',
          enunciado_es:
            'En 2008 la Corte Suprema falló en la causa Mendoza y ordenó a la Nación, la Provincia y la Ciudad sanear la cuenca Matanza-Riachuelo: de ahí salen ACUMAR y su plan de saneamiento.',
          detalle_es:
            'Lo empezaron vecinas y vecinos de la cuenca: el derecho a un ambiente sano se puede reclamar y a veces se gana.',
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [
            'agua.cuenca_matanza_riachuelo',
            { slug: 'tronco.derecho_ambiente_sano', fuerza: 0.5 },
          ],
        },
      ],
      hojas: [
        {
          slug: 'agua.cuando-vuelve-sucia.1',
          titulo_es: 'Grises, negras y adónde van',
          bajada_es: 'No toda el agua usada es la misma cosa.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.grises_y_negras', 'agua.depuracion_etapas'],
        },
        {
          slug: 'agua.cuando-vuelve-sucia.2',
          titulo_es: 'Bacterias que trabajan',
          bajada_es: 'Primario, secundario, terciario: quién hace qué.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.depuracion_etapas', 'agua.eutrofizacion'],
        },
        {
          slug: 'agua.cuando-vuelve-sucia.3',
          titulo_es: 'Verde no es buena señal',
          bajada_es: 'De los nutrientes de más a la floración de verano.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.eutrofizacion', 'agua.floraciones_cianobacterias'],
        },
        {
          slug: 'agua.cuando-vuelve-sucia.4',
          titulo_es: 'Un juicio que cambió una cuenca',
          bajada_es: 'Cómo un reclamo de vecinos terminó en un organismo.',
          minutos: 6,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['agua.fallo_mendoza', 'agua.grises_y_negras'],
        },
      ],
    },
    {
      slug: 'agua.ciudad-y-lluvia',
      anillo: 2,
      titulo_es: 'La ciudad cuando llueve',
      bajada_es: 'Por qué el agua que antes se filtraba ahora corre por la calle.',
      icono: 'Building2',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'agua.humedal_esponja',
          titulo_es: 'Los humedales son esponjas',
          enunciado_es:
            'Un humedal absorbe el agua de las crecidas, la suelta despacio y de paso la filtra: hace gratis buena parte del trabajo de una obra hidráulica.',
          detalle_es: 'También guarda carbono y sostiene una cantidad enorme de fauna.',
          fuente: 'ramsar',
          anillo: 2,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.servicios_ecosistemicos'],
        },
        {
          slug: 'agua.suelo_impermeable',
          titulo_es: 'Suelo que no deja pasar',
          enunciado_es:
            'Cada superficie que se cubre con cemento o asfalto es lluvia que ya no se infiltra: esa agua corre por la calle y llega toda junta y al mismo tiempo al desagüe.',
          detalle_es: 'El problema no es solo cuánta agua cae, sino qué tan rápido llega abajo.',
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'agua.ciclo_agua', fuerza: 0.5 }],
        },
        {
          slug: 'agua.arroyos_entubados',
          titulo_es: 'Los arroyos que siguen ahí',
          enunciado_es:
            'Debajo de la Ciudad siguen corriendo arroyos entubados como el Maldonado, el Vega y el Medrano: cambió la superficie, pero el agua sigue buscando el mismo camino bajo.',
          detalle_es: 'Por eso las zonas que se anegan suelen coincidir con los cauces viejos.',
          fuente: 'acuifero-puelche',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.suelo_impermeable', { slug: 'agua.cuenca_hidrografica', fuerza: 0.5 }],
        },
        {
          slug: 'agua.suds_verde',
          titulo_es: 'Hacerle lugar al agua',
          enunciado_es:
            'Jardines de lluvia, veredas permeables, terrazas verdes y zanjas con plantas hacen que parte de la lluvia se infiltre donde cae, en vez de correr toda junta al mismo caño.',
          detalle_es:
            'Un cantero abierto en tu vereda o un patio con tierra en vez de cemento juegan en el mismo equipo que una obra grande.',
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.suelo_impermeable', { slug: 'agua.humedal_esponja', fuerza: 0.5 }],
        },
      ],
      hojas: [
        {
          slug: 'agua.ciudad-y-lluvia.1',
          titulo_es: 'Esponjas que nadie ve',
          bajada_es: 'Lo que hace un humedal antes de que llueva sobre tu barrio.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.humedal_esponja', 'agua.suelo_impermeable'],
        },
        {
          slug: 'agua.ciudad-y-lluvia.2',
          titulo_es: 'Arroyos bajo el asfalto',
          bajada_es: 'Maldonado, Vega y Medrano siguen trabajando.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.arroyos_entubados', 'agua.suelo_impermeable'],
        },
        {
          slug: 'agua.ciudad-y-lluvia.3',
          titulo_es: 'Hacerle lugar a la lluvia',
          bajada_es: 'Veredas, canteros y terrazas que se portan como suelo.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.suds_verde', 'agua.humedal_esponja'],
        },
      ],
    },
    {
      slug: 'agua.derecho-y-decision',
      anillo: 2,
      titulo_es: 'El agua como derecho',
      bajada_es: 'Quién tiene agua segura, cuánta le queda al río y qué se decide con eso.',
      icono: 'Scale',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'agua.derecho_al_agua',
          titulo_es: 'El agua es un derecho',
          enunciado_es:
            'El acceso al agua segura y al saneamiento está reconocido como un derecho humano y es una meta acordada entre países: no es un servicio opcional ni un premio.',
          detalle_es:
            'Por eso el reclamo por cloacas o por agua de red en un barrio es un reclamo de derechos, no un pedido de favor.',
          fuente: 'unesco-ods',
          anillo: 2,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'tronco.derecho_ambiente_sano', fuerza: 0.5 }],
        },
        {
          slug: 'agua.caudal_ecologico',
          titulo_es: 'El río también necesita su parte',
          enunciado_es:
            'El caudal ecológico es el agua que hay que dejar correr para que el río y su humedal sigan funcionando: cuando se reparte un río, ese caudal es uno de los usuarios.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua.humedal_esponja', { slug: 'tronco.servicios_ecosistemicos', fuerza: 0.5 }],
        },
        {
          slug: 'agua.estres_hidrico',
          titulo_es: 'Estrés hídrico',
          enunciado_es:
            'Una región tiene estrés hídrico cuando la demanda se acerca al agua disponible: no es que no haya agua, es que casi toda ya está comprometida.',
          detalle_es:
            'El promedio anual puede verse cómodo y el verano no serlo: el estrés se juega en el momento y en el lugar.',
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua.un_litro_no_vale_igual', { slug: 'tronco.promedio_engana', fuerza: 0.5 }],
        },
        {
          slug: 'agua.desalinizacion_energia',
          titulo_es: 'Sacarle la sal al mar',
          enunciado_es:
            'Desalinizar es técnicamente posible, pero pide mucha energía y deja una salmuera concentrada que hay que devolver a algún lado: es una solución cara, no una canilla infinita.',
          detalle_es:
            'Cuidar la cuenca y arreglar las pérdidas casi siempre entrega más agua por peso invertido.',
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua.estres_hidrico', { slug: 'tronco.jerarquia_decisiones', fuerza: 0.5 }],
        },
      ],
      hojas: [
        {
          slug: 'agua.derecho-y-decision.1',
          titulo_es: 'El agua como derecho',
          bajada_es: 'Qué cambia cuando algo se llama derecho y no servicio.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua.derecho_al_agua', 'agua.caudal_ecologico'],
        },
        {
          slug: 'agua.derecho-y-decision.2',
          titulo_es: 'Cuando el agua ya está repartida',
          bajada_es: 'Estrés hídrico y las soluciones que parecen mágicas.',
          minutos: 6,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua.estres_hidrico', 'agua.desalinizacion_energia'],
        },
        {
          slug: 'agua.derecho-y-decision.3',
          titulo_es: 'El río también cuenta',
          bajada_es: 'Sumar al ecosistema en la lista de usuarios.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua.caudal_ecologico', 'agua.estres_hidrico'],
        },
      ],
    },
  ],
};
