// Rama `agua_azul` — océanos, ríos y humedales.
// Fuente: ACADEMIA/research/03-environmental-curriculum.md §2.11 y §3.3, más §6
// para edad. Mitos asignados: 27 (los humedales son baldíos) y 33 (el plástico
// del mar viene de los barcos).

export default {
  rama: 'agua_azul',
  gajos: [
    {
      slug: 'agua_azul.el-rio-que-tenes-al-lado',
      anillo: 1,
      titulo_es: 'El río que tenés al lado',
      bajada_es: 'El Río de la Plata, el Paraná y por qué el agua marrón no está sucia.',
      icono: 'Waves',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'agua_azul.rio_de_la_plata_estuario',
          titulo_es: 'El estuario más ancho del mundo',
          enunciado_es:
            'El Río de la Plata es un estuario: el lugar donde el agua dulce de los ríos se encuentra con la salada del mar y se mezcla.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 1,
          dificultad_base: -1.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'agua_azul.turbidez_natural',
          titulo_es: 'El color marrón es sedimento',
          enunciado_es:
            'El Río de la Plata es marrón porque arrastra sedimento de toda la cuenca, no porque esté sucio. Turbio y contaminado no son lo mismo.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.rio_de_la_plata_estuario'],
        },
        {
          slug: 'agua_azul.el_parana_y_la_bajante',
          titulo_es: 'El Paraná y la bajante',
          enunciado_es:
            'El Paraná tuvo una bajante histórica que dejó al descubierto el fondo en tramos enteros y afectó el transporte, la pesca y las tomas de agua.',
          detalle_es: null,
          fuente: 'incendios-delta-2020',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.rio_de_la_plata_estuario'],
        },
        {
          slug: 'agua_azul.cianobacterias_balneario',
          titulo_es: 'Cuando cierran la playa',
          enunciado_es:
            'Las floraciones de cianobacterias pueden hacer que el agua no sea apta para bañarse: si el agua está verde y con olor, no se entra ni se deja entrar a las mascotas.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.turbidez_natural'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.el-rio-que-tenes-al-lado.1',
          titulo_es: 'Dulce y salado a la vez',
          bajada_es: 'Qué es un estuario y por qué importa.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.rio_de_la_plata_estuario', 'agua_azul.turbidez_natural'],
        },
        {
          slug: 'agua_azul.el-rio-que-tenes-al-lado.2',
          titulo_es: 'Marrón no es sucio',
          bajada_es: 'Turbidez, sedimento y una confusión muy porteña.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.turbidez_natural', 'agua_azul.cianobacterias_balneario'],
        },
        {
          slug: 'agua_azul.el-rio-que-tenes-al-lado.3',
          titulo_es: 'Cuando baja el río',
          bajada_es: 'La bajante del Paraná y todo lo que tocó.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.el_parana_y_la_bajante', 'agua_azul.rio_de_la_plata_estuario'],
        },
      ],
    },

    {
      slug: 'agua_azul.humedales',
      anillo: 1,
      titulo_es: 'Humedales',
      bajada_es: 'Lo que muchos llaman baldío es la mejor infraestructura que hay.',
      icono: 'Sprout',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'agua_azul.que_es_un_humedal',
          titulo_es: 'Qué es un humedal',
          enunciado_es:
            'Un humedal es un terreno donde el agua manda: se inunda y se seca de forma cíclica, y esa dinámica es la que sostiene todo lo que vive ahí.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 1,
          dificultad_base: -0.8,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'agua_azul.lo_que_hace_un_humedal',
          titulo_es: 'Lo que hace un humedal',
          enunciado_es:
            'Amortigua crecidas, filtra agua, guarda carbono y sostiene una biodiversidad enorme. Todo eso lo hace gratis y sin que nadie lo administre.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.que_es_un_humedal', 'tronco.servicios_ecosistemicos'],
          misconceptions: [
            {
              slug: 'agua_azul.mito_humedal_baldio',
              creencia_es: 'Los humedales son terrenos baldíos, embarrados e inútiles: conviene rellenarlos y construir.',
              correccion_es:
                'Parecen vacíos porque no tienen nada construido encima, y esa es exactamente la trampa. Un humedal amortigua crecidas, filtra agua y guarda carbono; rellenarlo es por lo que las inundaciones del AMBA empeoran cada vez que llueve fuerte.',
              fuente: 'ramsar',
            },
          ],
        },
        {
          slug: 'agua_azul.delta_e_islas',
          titulo_es: 'El Delta e Islas del Paraná',
          enunciado_es:
            'Es un mosaico de islas, arroyos y bosque ribereño que llega hasta el Río de la Plata, y es el humedal más cercano a la mayor concentración urbana del país.',
          detalle_es: null,
          fuente: 'ecorregiones-pba',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.que_es_un_humedal'],
        },
        {
          slug: 'agua_azul.reserva_ramsar_urbana',
          titulo_es: 'Un sitio Ramsar en la ciudad',
          enunciado_es:
            'La Reserva Ecológica Costanera Sur ocupa unas 350 hectáreas sobre un relleno de escombros y es sitio Ramsar desde 2005: registra 343 especies de aves.',
          detalle_es: 'Es la mejor historia local de "si la dejás, vuelve".',
          fuente: 'reserva-costanera-sur',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.lo_que_hace_un_humedal'],
        },
        {
          slug: 'agua_azul.ley_de_humedales',
          titulo_es: 'La ley que no sale',
          enunciado_es:
            'El proyecto de Ley de Humedales se presentó una y otra vez desde 2013 y nunca se sancionó, aunque los grandes incendios lo vuelven a poner en agenda cada vez.',
          detalle_es: null,
          fuente: 'incendios-delta-2020',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.delta_e_islas', 'tronco.presupuestos_minimos'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.humedales.1',
          titulo_es: 'El agua manda',
          bajada_es: 'Qué define a un humedal.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.que_es_un_humedal', 'agua_azul.lo_que_hace_un_humedal'],
        },
        {
          slug: 'agua_azul.humedales.2',
          titulo_es: 'Baldío, ni ahí',
          bajada_es: 'Lo que se pierde cuando se rellena.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.lo_que_hace_un_humedal', 'agua_azul.delta_e_islas'],
        },
        {
          slug: 'agua_azul.humedales.3',
          titulo_es: 'Un humedal a veinte minutos',
          bajada_es: 'La Reserva Ecológica y cómo se armó sola.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.reserva_ramsar_urbana', 'agua_azul.que_es_un_humedal'],
        },
        {
          slug: 'agua_azul.humedales.4',
          titulo_es: 'Diez años de proyecto',
          bajada_es: 'Por qué la Ley de Humedales sigue sin salir.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['agua_azul.ley_de_humedales', 'agua_azul.delta_e_islas'],
        },
      ],
    },

    {
      slug: 'agua_azul.lo-que-llega-desde-tierra',
      anillo: 1,
      titulo_es: 'Lo que llega desde tierra',
      bajada_es: 'La basura marina casi nunca se tira en el mar.',
      icono: 'Trash2',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'agua_azul.origen_terrestre',
          titulo_es: 'De dónde viene la basura marina',
          enunciado_es:
            'La gran mayoría de la basura que hay en el mar se generó en tierra y llegó por ríos, desagües y viento.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
          misconceptions: [
            {
              slug: 'agua_azul.mito_basura_de_barcos',
              creencia_es: 'El plástico del mar lo tiran sobre todo los barcos.',
              correccion_es:
                'Es cómodo pensarlo así porque deja el problema lejos y en manos de otro. La mayor parte se genera en tierra y viaja por ríos y desagües: la basura que se vuela de una vereda del AMBA tiene camino directo al Río de la Plata.',
              fuente: 'unep',
            },
          ],
        },
        {
          slug: 'agua_azul.rio_como_cinta',
          titulo_es: 'El río como cinta transportadora',
          enunciado_es:
            'Un río recoge lo que cae en toda su cuenca: por eso una cuenca mal gestionada se convierte en un caño que descarga al mar.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 1,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.origen_terrestre'],
        },
        {
          slug: 'agua_azul.microplasticos_mar',
          titulo_es: 'Microplásticos',
          enunciado_es:
            'El plástico grande se fragmenta con el sol y el oleaje hasta quedar en trozos diminutos que ya no se pueden recoger.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.origen_terrestre'],
        },
        {
          slug: 'agua_azul.redes_fantasma',
          titulo_es: 'Redes fantasma',
          enunciado_es:
            'Las redes de pesca perdidas siguen atrapando fauna durante años. Es la excepción real al origen terrestre de la basura marina.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['agua_azul.origen_terrestre'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.lo-que-llega-desde-tierra.1',
          titulo_es: 'Empieza en la vereda',
          bajada_es: 'El camino de una botella hasta el mar.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.origen_terrestre', 'agua_azul.rio_como_cinta'],
        },
        {
          slug: 'agua_azul.lo-que-llega-desde-tierra.2',
          titulo_es: 'Cuando ya no se puede juntar',
          bajada_es: 'Microplásticos y por qué evitar gana a limpiar.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.microplasticos_mar', 'agua_azul.origen_terrestre'],
        },
        {
          slug: 'agua_azul.lo-que-llega-desde-tierra.3',
          titulo_es: 'Lo que sí viene de un barco',
          bajada_es: 'Redes perdidas: la excepción que confirma la regla.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.redes_fantasma', 'agua_azul.rio_como_cinta'],
        },
      ],
    },

    {
      slug: 'agua_azul.mar-argentino',
      anillo: 1,
      titulo_es: 'El Mar Argentino',
      bajada_es: 'Una plataforma ancha, dos corrientes y mucha productividad.',
      icono: 'Fish',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'agua_azul.plataforma_ancha',
          titulo_es: 'Una plataforma muy ancha',
          enunciado_es:
            'La plataforma continental argentina es una de las más extensas del mundo: mar poco profundo, con luz llegando al fondo y mucha vida.',
          detalle_es: null,
          fuente: 'milla-201',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'agua_azul.confluencia',
          titulo_es: 'Malvinas y Brasil se encuentran',
          enunciado_es:
            'La corriente fría de Malvinas y la cálida de Brasil se cruzan frente a Mar del Plata, y ese encuentro genera una zona de altísima productividad.',
          detalle_es: null,
          fuente: 'milla-201',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.plataforma_ancha'],
        },
        {
          slug: 'agua_azul.fauna_marina_emblema',
          titulo_es: 'Quiénes viven ahí',
          enunciado_es:
            'La ballena franca austral, el pingüino de Magallanes, el lobo marino, la tonina overa y la franciscana son fauna marina característica de la costa argentina.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.confluencia'],
        },
        {
          slug: 'agua_azul.areas_marinas_protegidas',
          titulo_es: 'Áreas marinas protegidas',
          enunciado_es:
            'Argentina tiene áreas marinas protegidas —Namuncurá–Banco Burdwood y Yaganes entre ellas— donde se restringen actividades para dejar recuperar el fondo y las poblaciones.',
          detalle_es: null,
          fuente: 'milla-201',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.fauna_marina_emblema'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.mar-argentino.1',
          titulo_es: 'Poco profundo y muy vivo',
          bajada_es: 'Por qué la plataforma cambia todo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.plataforma_ancha', 'agua_azul.confluencia'],
        },
        {
          slug: 'agua_azul.mar-argentino.2',
          titulo_es: 'Quién vive en la costa',
          bajada_es: 'Ballenas, pingüinos y delfines rioplatenses.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.fauna_marina_emblema', 'agua_azul.confluencia'],
        },
        {
          slug: 'agua_azul.mar-argentino.3',
          titulo_es: 'Dejar en paz un pedazo',
          bajada_es: 'Qué protege un área marina protegida.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.areas_marinas_protegidas', 'agua_azul.plataforma_ancha'],
        },
      ],
    },

    {
      slug: 'agua_azul.pescar-y-cuidar',
      anillo: 2,
      titulo_es: 'Pescar y cuidar',
      bajada_es: 'Cuota, arrastre, captura incidental y la milla 201.',
      icono: 'Anchor',
      age_groups: ['teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'agua_azul.zee_y_milla_201',
          titulo_es: 'La milla 201',
          enunciado_es:
            'Justo afuera de la Zona Económica Exclusiva argentina opera una flota internacional sobre recursos que migran desde aguas argentinas, en un área sin regulación efectiva.',
          detalle_es: null,
          fuente: 'milla-201',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.plataforma_ancha'],
        },
        {
          slug: 'agua_azul.pesca_de_arrastre',
          titulo_es: 'Pesca de arrastre',
          enunciado_es:
            'Arrastrar una red por el fondo captura mucho, y de paso destruye la estructura del fondo, que tarda años en rearmarse.',
          detalle_es: null,
          fuente: 'fao',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['agua_azul.plataforma_ancha'],
        },
        {
          slug: 'agua_azul.bycatch',
          titulo_es: 'Captura incidental',
          enunciado_es:
            'Los albatros y petreles se enganchan en las líneas de pesca. Las líneas espantapájaros son una solución barata que reduce mucho esas muertes.',
          detalle_es: null,
          fuente: 'aves-argentinas-amenazadas',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['agua_azul.pesca_de_arrastre'],
        },
        {
          slug: 'agua_azul.cuota_y_talla',
          titulo_es: 'Cuota, talla y veda',
          enunciado_es:
            'Una pesquería se administra con tres perillas: cuánto se puede sacar, de qué tamaño mínimo y en qué época no se pesca.',
          detalle_es: null,
          fuente: 'fao',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.zee_y_milla_201'],
        },
        {
          slug: 'agua_azul.sellos_de_pesca',
          titulo_es: 'Los sellos de pesca',
          enunciado_es:
            'Un sello de pesca sostenible dice que alguien externo auditó la pesquería. Vale lo que valga su auditoría, así que conviene saber quién certifica.',
          detalle_es: null,
          fuente: 'fao',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.cuota_y_talla'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.pescar-y-cuidar.1',
          titulo_es: 'Justo afuera del límite',
          bajada_es: 'Qué pasa en la milla 201.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.zee_y_milla_201', 'agua_azul.cuota_y_talla'],
        },
        {
          slug: 'agua_azul.pescar-y-cuidar.2',
          titulo_es: 'Lo que se lleva la red',
          bajada_es: 'Arrastre y captura incidental.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.pesca_de_arrastre', 'agua_azul.bycatch'],
        },
        {
          slug: 'agua_azul.pescar-y-cuidar.3',
          titulo_es: 'Las tres perillas',
          bajada_es: 'Cuánto, de qué tamaño y cuándo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.cuota_y_talla', 'agua_azul.sellos_de_pesca'],
        },
      ],
    },

    {
      slug: 'agua_azul.el-oceano-y-el-clima',
      anillo: 2,
      titulo_es: 'El océano y el clima',
      bajada_es: 'El regulador más grande que tenemos, y lo que le está costando.',
      icono: 'Thermometer',
      age_groups: ['teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'agua_azul.oceano_regulador',
          titulo_es: 'El océano regula el clima',
          enunciado_es:
            'El mar absorbe una parte enorme del calor extra y del CO₂ que emitimos: sin ese amortiguador, el calentamiento en superficie sería mucho mayor.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.stock_vs_flujo'],
        },
        {
          slug: 'agua_azul.bomba_biologica',
          titulo_es: 'La bomba biológica',
          enunciado_es:
            'El plancton captura carbono en la superficie y parte de él se hunde al morir: es un mecanismo que baja carbono al fondo del mar durante siglos.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.oceano_regulador'],
        },
        {
          slug: 'agua_azul.acidificacion',
          titulo_es: 'Acidificación',
          enunciado_es:
            'Cuando el mar absorbe CO₂ su química cambia y se vuelve más ácido, lo que dificulta que los organismos con caparazón o esqueleto calcáreo los formen.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.oceano_regulador'],
        },
        {
          slug: 'agua_azul.tratado_alta_mar',
          titulo_es: 'El Tratado de Alta Mar',
          enunciado_es:
            'Más allá de las zonas nacionales el mar era tierra de nadie. El acuerdo BBNJ crea el marco para proteger áreas en aguas internacionales.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.zee_y_milla_201', 'agua_azul.areas_marinas_protegidas'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.el-oceano-y-el-clima.1',
          titulo_es: 'El amortiguador',
          bajada_es: 'Cuánto calor y cuánto carbono se come el mar.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.oceano_regulador', 'agua_azul.bomba_biologica'],
        },
        {
          slug: 'agua_azul.el-oceano-y-el-clima.2',
          titulo_es: 'El precio de absorber',
          bajada_es: 'Acidificación y quién la sufre primero.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.acidificacion', 'agua_azul.oceano_regulador'],
        },
        {
          slug: 'agua_azul.el-oceano-y-el-clima.3',
          titulo_es: 'Reglas para el mar de nadie',
          bajada_es: 'Qué cambia el Tratado de Alta Mar.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.tratado_alta_mar', 'agua_azul.areas_marinas_protegidas'],
        },
      ],
    },

    {
      slug: 'agua_azul.costa-y-decisiones',
      anillo: 2,
      titulo_es: 'La costa y sus decisiones',
      bajada_es: 'Qué se construye, qué se drena y qué se deja.',
      icono: 'Construction',
      age_groups: ['teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'agua_azul.urbanizar_humedales',
          titulo_es: 'Construir sobre humedal',
          enunciado_es:
            'Rellenar un humedal para urbanizar traslada el agua a otro lado: la crecida no desaparece, se muda al vecino.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.lo_que_hace_un_humedal'],
        },
        {
          slug: 'agua_azul.hidrovia',
          titulo_es: 'La Hidrovía',
          enunciado_es:
            'Mantener el Paraná navegable para buques grandes requiere dragado permanente, y ese dragado modifica el fondo, los sedimentos y los ambientes ribereños.',
          detalle_es: null,
          fuente: 'incendios-delta-2020',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.el_parana_y_la_bajante'],
        },
        {
          slug: 'agua_azul.erosion_costera',
          titulo_es: 'La costa se mueve',
          enunciado_es:
            'Las playas ganan y pierden arena todo el tiempo. Construir muy cerca del agua interrumpe ese movimiento y suele acelerar la erosión.',
          detalle_es: null,
          fuente: 'ecorregiones-pba',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.urbanizar_humedales'],
        },
        {
          slug: 'agua_azul.restaurar_costa',
          titulo_es: 'Devolverle lugar al agua',
          enunciado_es:
            'Recuperar humedales y dejar franjas sin construir suele ser más barato y más duradero que levantar defensas de hormigón cada vez más altas.',
          detalle_es: null,
          fuente: 'ramsar',
          anillo: 3,
          dificultad_base: 0.9,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['agua_azul.erosion_costera', 'tronco.jerarquia_decisiones'],
        },
      ],
      hojas: [
        {
          slug: 'agua_azul.costa-y-decisiones.1',
          titulo_es: 'El agua se muda',
          bajada_es: 'Rellenar acá, inundar allá.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['agua_azul.urbanizar_humedales', 'agua_azul.erosion_costera'],
        },
        {
          slug: 'agua_azul.costa-y-decisiones.2',
          titulo_es: 'Dragar un río grande',
          bajada_es: 'La Hidrovía y lo que mueve además de barcos.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['agua_azul.hidrovia', 'agua_azul.el_parana_y_la_bajante'],
        },
        {
          slug: 'agua_azul.costa-y-decisiones.3',
          titulo_es: 'Hormigón o humedal',
          bajada_es: 'Dos maneras de defender una ciudad del agua.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['agua_azul.restaurar_costa', 'agua_azul.urbanizar_humedales'],
        },
      ],
    },
  ],
};
