// Rama `aire_suelo` — lo que respirás y lo que pisás, que son dos sistemas.
// Fuente: ACADEMIA/research/03-environmental-curriculum.md §2.12 y §3.3 (humo
// del Delta), más §6 para edad. Mito asignado: 5 (el agujero de ozono causa el
// calentamiento global), que la literatura señala como la confusión más
// persistente de toda la enseñanza ambiental.

export default {
  rama: 'aire_suelo',
  gajos: [
    {
      slug: 'aire_suelo.la-atmosfera',
      anillo: 1,
      titulo_es: 'La atmósfera',
      bajada_es: 'De qué está hecha y cómo abriga.',
      icono: 'CloudSun',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'aire_suelo.composicion_atmosfera',
          titulo_es: 'De qué está hecho el aire',
          enunciado_es:
            'El aire es casi todo nitrógeno y oxígeno. Los gases que regulan la temperatura son una fracción muy chica, y por eso cambiarlos un poco cambia mucho.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'aire_suelo.efecto_invernadero_natural',
          titulo_es: 'La frazada que ya estaba',
          enunciado_es:
            'El efecto invernadero natural mantiene el planeta habitable: sin él, la Tierra sería demasiado fría para la vida que conocemos.',
          detalle_es: 'El efecto invernadero no es el problema. Es la vida.',
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: -0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.composicion_atmosfera'],
        },
        {
          slug: 'aire_suelo.efecto_intensificado',
          titulo_es: 'Cuando la frazada engorda',
          enunciado_es:
            'El problema no es que exista el efecto invernadero, sino que aumentó mucho la cantidad de gases que lo producen, y entonces se atrapa más calor del que solía.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.efecto_invernadero_natural'],
        },
        {
          slug: 'aire_suelo.gei_principales',
          titulo_es: 'Los gases que abrigan',
          enunciado_es:
            'Los principales son dióxido de carbono, metano, óxido nitroso y los gases fluorados. No pesan igual ni duran lo mismo en la atmósfera.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.efecto_intensificado'],
        },
        {
          slug: 'aire_suelo.metano_vs_co2',
          titulo_es: 'Metano y CO₂ no son lo mismo',
          enunciado_es:
            'El metano calienta mucho más por molécula pero permanece bastante menos tiempo; el CO₂ calienta menos por molécula y se queda siglos.',
          detalle_es: 'Por eso bajar metano da alivio rápido y bajar CO₂ es lo que decide el largo plazo.',
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.gei_principales', 'tronco.stock_vs_flujo'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.la-atmosfera.1',
          titulo_es: 'Una frazada muy fina',
          bajada_es: 'Qué proporción del aire hace el trabajo térmico.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.composicion_atmosfera', 'aire_suelo.efecto_invernadero_natural'],
        },
        {
          slug: 'aire_suelo.la-atmosfera.2',
          titulo_es: 'El problema no es que exista',
          bajada_es: 'Natural e intensificado, en criollo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.efecto_intensificado', 'aire_suelo.gei_principales'],
        },
        {
          slug: 'aire_suelo.la-atmosfera.3',
          titulo_es: 'Rápido y lento',
          bajada_es: 'Metano y CO₂: dos relojes distintos.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.metano_vs_co2', 'aire_suelo.gei_principales'],
        },
      ],
    },

    {
      slug: 'aire_suelo.ozono-aparte',
      anillo: 1,
      titulo_es: 'El ozono es otra cosa',
      bajada_es: 'Dos problemas distintos que casi todo el mundo mezcla.',
      icono: 'Sun',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'aire_suelo.capa_de_ozono',
          titulo_es: 'Qué hace la capa de ozono',
          enunciado_es:
            'La capa de ozono está en la estratósfera y filtra buena parte de la radiación ultravioleta que llega a la superficie.',
          detalle_es: null,
          fuente: 'ncse-ozono',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.composicion_atmosfera'],
          misconceptions: [
            {
              slug: 'aire_suelo.mito_ozono_calentamiento',
              creencia_es: 'El agujero de la capa de ozono es lo que causa el calentamiento global.',
              correccion_es:
                'La trampa es que los dos suenan a "problema del cielo" y aparecieron en las noticias en la misma época. Pero son mecanismos separados: el ozono se agota por los CFC, pasa en la estratósfera y afecta la radiación ultravioleta; el calentamiento lo causan los gases de efecto invernadero, pasa en la tropósfera y atrapa calor.',
              fuente: 'ncse-ozono',
            },
          ],
        },
        {
          slug: 'aire_suelo.cfc_y_montreal',
          titulo_es: 'Los CFC y el Protocolo de Montreal',
          enunciado_es:
            'Cuando se identificó que ciertos gases industriales destruían el ozono, se acordó dejarlos de fabricar, y la capa empezó a recuperarse.',
          detalle_es: 'Es el mejor caso conocido de un problema ambiental global que se atacó y funcionó.',
          fuente: 'ncse-ozono',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.capa_de_ozono'],
        },
        {
          slug: 'aire_suelo.ozono_troposferico',
          titulo_es: 'El ozono de abajo, que sí molesta',
          enunciado_es:
            'A nivel del suelo el ozono no protege: se forma con el sol a partir de los contaminantes del tránsito y es irritante para las vías respiratorias.',
          detalle_es: null,
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.capa_de_ozono'],
        },
        {
          slug: 'aire_suelo.dos_problemas_dos_soluciones',
          titulo_es: 'Dos problemas, dos soluciones',
          enunciado_es:
            'Confundirlos lleva a la conclusión equivocada: dejar de usar aerosoles no baja las emisiones de CO₂, y bajar el CO₂ no arregla el ozono.',
          detalle_es: null,
          fuente: 'ncse-ozono',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.cfc_y_montreal', 'aire_suelo.efecto_intensificado'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.ozono-aparte.1',
          titulo_es: 'Arriba, filtrando',
          bajada_es: 'Qué hace realmente la capa de ozono.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.capa_de_ozono', 'aire_suelo.cfc_y_montreal'],
        },
        {
          slug: 'aire_suelo.ozono-aparte.2',
          titulo_es: 'Un problema que se arregló',
          bajada_es: 'Montreal, y por qué vale contarlo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.cfc_y_montreal', 'aire_suelo.dos_problemas_dos_soluciones'],
        },
        {
          slug: 'aire_suelo.ozono-aparte.3',
          titulo_es: 'El mismo gas, otro lugar',
          bajada_es: 'Ozono arriba protege, abajo irrita.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.ozono_troposferico', 'aire_suelo.capa_de_ozono'],
        },
      ],
    },

    {
      slug: 'aire_suelo.el-aire-que-respiras',
      anillo: 1,
      titulo_es: 'El aire que respirás',
      bajada_es: 'PM2.5, NO₂ y de dónde salen en el AMBA.',
      icono: 'Wind',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'aire_suelo.material_particulado',
          titulo_es: 'PM2.5 y PM10',
          enunciado_es:
            'Son partículas tan chicas que no se ven ni se filtran en la nariz. Las de 2,5 micrones llegan hasta lo más profundo del pulmón.',
          detalle_es: null,
          fuente: 'epa',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'aire_suelo.fuentes_amba',
          titulo_es: 'De dónde sale en el AMBA',
          enunciado_es:
            'Las fuentes principales son el tránsito, la industria, la quema de residuos y, en episodios, la quema de pastizales del Delta.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.material_particulado'],
        },
        {
          slug: 'aire_suelo.humo_del_delta',
          titulo_es: 'El humo del Delta',
          enunciado_es:
            'Los incendios del delta del Paraná de 2020 arrasaron cientos de miles de hectáreas de humedal y llevaron humo hasta Rosario y el AMBA.',
          detalle_es: null,
          fuente: 'incendios-delta-2020',
          anillo: 1,
          dificultad_base: 0.0,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['aire_suelo.fuentes_amba'],
        },
        {
          slug: 'aire_suelo.inversion_termica',
          titulo_es: 'Inversión térmica',
          enunciado_es:
            'En ciertas noches frías y sin viento se forma una tapa de aire cálido arriba que impide que el aire de abajo se mezcle, y todo lo emitido queda a nivel del suelo.',
          detalle_es: null,
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.fuentes_amba'],
        },
        {
          slug: 'aire_suelo.aire_interior',
          titulo_es: 'El aire de adentro',
          enunciado_es:
            'Cocinar, calefaccionar mal ventilado o usar ciertos productos de limpieza puede dejar el aire de una casa peor que el de la calle.',
          detalle_es: 'Ventilar cruzado unos minutos es la medida más barata que existe.',
          fuente: 'epa',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.material_particulado'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.el-aire-que-respiras.1',
          titulo_es: 'Lo que no se ve',
          bajada_es: 'PM2.5: por qué el tamaño es todo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.material_particulado', 'aire_suelo.fuentes_amba'],
        },
        {
          slug: 'aire_suelo.el-aire-que-respiras.2',
          titulo_es: 'Abrir dos ventanas',
          bajada_es: 'El aire de tu casa también cuenta.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.aire_interior', 'aire_suelo.material_particulado'],
        },
        {
          slug: 'aire_suelo.el-aire-que-respiras.3',
          titulo_es: 'Días sin viento',
          bajada_es: 'Inversión térmica y humo que no se va.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.inversion_termica', 'aire_suelo.humo_del_delta'],
        },
      ],
    },

    {
      slug: 'aire_suelo.el-suelo-esta-vivo',
      anillo: 1,
      titulo_es: 'El suelo está vivo',
      bajada_es: 'No es tierra: es un ecosistema con horizontes.',
      icono: 'Layers',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'aire_suelo.perfil_y_horizontes',
          titulo_es: 'El perfil del suelo',
          enunciado_es:
            'Si cortás el suelo verticalmente ves capas distintas: arriba la materia orgánica, después el suelo mineral, después la roca en camino de deshacerse.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 1,
          dificultad_base: -0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'aire_suelo.materia_organica',
          titulo_es: 'La materia orgánica',
          enunciado_es:
            'Es lo que le da al suelo su color oscuro, su capacidad de retener agua y su fertilidad. Se construye en décadas y se pierde en pocas temporadas.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.perfil_y_horizontes'],
        },
        {
          slug: 'aire_suelo.suelo_pampeano',
          titulo_es: 'El suelo pampeano',
          enunciado_es:
            'La Pampa tiene uno de los suelos más fértiles del mundo, formado bajo miles de años de pastizal con raíces profundas.',
          detalle_es: null,
          fuente: 'ecorregiones-pba',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.materia_organica'],
        },
        {
          slug: 'aire_suelo.carbono_del_suelo',
          titulo_es: 'El suelo guarda carbono',
          enunciado_es:
            'Hay más carbono almacenado en los suelos del mundo que en toda la vegetación: cuidar el suelo es una política climática, no solo agrícola.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.materia_organica'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.el-suelo-esta-vivo.1',
          titulo_es: 'Cortarlo y mirarlo',
          bajada_es: 'Las capas de un suelo, de arriba a abajo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.perfil_y_horizontes', 'aire_suelo.materia_organica'],
        },
        {
          slug: 'aire_suelo.el-suelo-esta-vivo.2',
          titulo_es: 'Por qué la Pampa es la Pampa',
          bajada_es: 'Miles de años de raíces.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.suelo_pampeano', 'aire_suelo.materia_organica'],
        },
        {
          slug: 'aire_suelo.el-suelo-esta-vivo.3',
          titulo_es: 'Un sumidero bajo tus pies',
          bajada_es: 'Cuánto carbono hay en el suelo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.carbono_del_suelo', 'aire_suelo.suelo_pampeano'],
        },
      ],
    },

    {
      slug: 'aire_suelo.degradar-y-recuperar',
      anillo: 2,
      titulo_es: 'Degradar y recuperar',
      bajada_es: 'Erosión, salinización y qué se puede revertir.',
      icono: 'TrendingDown',
      age_groups: ['teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'aire_suelo.erosion',
          titulo_es: 'Erosión hídrica y eólica',
          enunciado_es:
            'Un suelo sin cobertura vegetal se lo lleva el agua o el viento, y lo primero que se va es justo la capa superior, que es la fértil.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.materia_organica'],
        },
        {
          slug: 'aire_suelo.compactacion',
          titulo_es: 'Compactación',
          enunciado_es:
            'El paso repetido de maquinaria pesada aplasta los poros del suelo: entra menos aire, entra menos agua y las raíces no pueden bajar.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.perfil_y_horizontes'],
        },
        {
          slug: 'aire_suelo.salinizacion',
          titulo_es: 'Salinización',
          enunciado_es:
            'Regar mal en zonas secas deja sales que el agua no alcanza a lavar, y con el tiempo el suelo deja de servir para cultivar.',
          detalle_es: null,
          fuente: 'fao',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.erosion'],
        },
        {
          slug: 'aire_suelo.siembra_directa',
          titulo_es: 'Siembra directa: alcances y límites',
          enunciado_es:
            'No arar reduce la erosión y ayuda a conservar materia orgánica, pero por sí sola no resuelve la compactación ni la dependencia de agroquímicos.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.erosion', 'aire_suelo.compactacion'],
        },
        {
          slug: 'aire_suelo.desertificacion',
          titulo_es: 'Desertificación',
          enunciado_es:
            'Es la degradación acumulada de tierras en zonas secas hasta que pierden su capacidad productiva, y en la Argentina afecta a buena parte del territorio.',
          detalle_es: null,
          fuente: 'fao',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.salinizacion'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.degradar-y-recuperar.1',
          titulo_es: 'Lo primero que se va',
          bajada_es: 'Erosión: por qué se pierde justo lo bueno.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.erosion', 'aire_suelo.compactacion'],
        },
        {
          slug: 'aire_suelo.degradar-y-recuperar.2',
          titulo_es: 'Sal donde no llueve',
          bajada_es: 'Salinización y desertificación.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.salinizacion', 'aire_suelo.desertificacion'],
        },
        {
          slug: 'aire_suelo.degradar-y-recuperar.3',
          titulo_es: 'No arar no alcanza',
          bajada_es: 'Qué resuelve y qué no la siembra directa.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.siembra_directa', 'aire_suelo.erosion'],
        },
      ],
    },

    {
      slug: 'aire_suelo.pasivos-ambientales',
      anillo: 2,
      titulo_es: 'Pasivos ambientales',
      bajada_es: 'Lo que quedó en el suelo mucho después de que cerró la fábrica.',
      icono: 'AlertTriangle',
      age_groups: ['teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'aire_suelo.que_es_un_pasivo',
          titulo_es: 'Qué es un pasivo ambiental',
          enunciado_es:
            'Es la contaminación que queda en un sitio después de que la actividad que la generó terminó, y que alguien va a tener que pagar o convivir con ella.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'aire_suelo.metales_pesados',
          titulo_es: 'Metales pesados',
          enunciado_es:
            'Plomo, cromo y mercurio no se degradan: se quedan en el suelo y en el sedimento, y pueden pasar al agua o a los cultivos.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['aire_suelo.que_es_un_pasivo'],
        },
        {
          slug: 'aire_suelo.riachuelo_curtiembres',
          titulo_es: 'El caso del Riachuelo',
          enunciado_es:
            'En la Cuenca Matanza-Riachuelo conviven décadas de vertidos industriales con barrios enteros: el saneamiento es tan social como técnico.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['aire_suelo.metales_pesados'],
        },
        {
          slug: 'aire_suelo.biorremediacion',
          titulo_es: 'Biorremediación y fitorremediación',
          enunciado_es:
            'Hay bacterias y plantas que degradan o acumulan contaminantes. Funcionan, son baratas y son lentas: no reemplazan a evitar el vertido.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.metales_pesados'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.pasivos-ambientales.1',
          titulo_es: 'La fábrica cerró, el problema no',
          bajada_es: 'Qué es un pasivo ambiental.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.que_es_un_pasivo', 'aire_suelo.metales_pesados'],
        },
        {
          slug: 'aire_suelo.pasivos-ambientales.2',
          titulo_es: 'Décadas de vertidos',
          bajada_es: 'El Riachuelo como caso testigo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.riachuelo_curtiembres', 'aire_suelo.que_es_un_pasivo'],
        },
        {
          slug: 'aire_suelo.pasivos-ambientales.3',
          titulo_es: 'Plantas que limpian',
          bajada_es: 'Biorremediación: potente y lenta.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.biorremediacion', 'aire_suelo.metales_pesados'],
        },
      ],
    },

    {
      slug: 'aire_suelo.medir-el-aire',
      anillo: 2,
      titulo_es: 'Medir el aire',
      bajada_es: 'Índices, estaciones y qué significa "aire bueno".',
      icono: 'Gauge',
      age_groups: ['teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'aire_suelo.indice_calidad_aire',
          titulo_es: 'El índice de calidad del aire',
          enunciado_es:
            'Resume varios contaminantes en un solo número con colores. Es útil para decidir si salir a correr, y esconde cuál de todos es el que está alto.',
          detalle_es: null,
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.material_particulado', 'tronco.leer_un_numero'],
        },
        {
          slug: 'aire_suelo.donde_esta_la_estacion',
          titulo_es: 'Dónde está la estación importa',
          enunciado_es:
            'Una estación de monitoreo mide donde está: en una avenida da distinto que en un parque a tres cuadras, y las dos mediciones son correctas.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.indice_calidad_aire'],
        },
        {
          slug: 'aire_suelo.promedio_y_pico',
          titulo_es: 'Promedio anual y pico horario',
          enunciado_es:
            'Un promedio anual bueno puede convivir con picos que enferman: para salud importan las dos cosas, y son dos límites distintos.',
          detalle_es: null,
          fuente: 'epa',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.donde_esta_la_estacion', 'tronco.promedio_engana'],
        },
        {
          slug: 'aire_suelo.liquenes_indicadores',
          titulo_es: 'Los líquenes como medidores',
          enunciado_es:
            'Los líquenes son muy sensibles a la contaminación del aire: mirar cuáles crecen en los troncos de una cuadra da una lectura sin instrumentos.',
          detalle_es: null,
          fuente: 'argentinat',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['aire_suelo.material_particulado'],
        },
      ],
      hojas: [
        {
          slug: 'aire_suelo.medir-el-aire.1',
          titulo_es: 'Un número y un color',
          bajada_es: 'Qué te dice y qué te esconde el índice.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['aire_suelo.indice_calidad_aire', 'aire_suelo.donde_esta_la_estacion'],
        },
        {
          slug: 'aire_suelo.medir-el-aire.2',
          titulo_es: 'El promedio y el pico',
          bajada_es: 'Dos límites distintos, los dos necesarios.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['aire_suelo.promedio_y_pico', 'aire_suelo.indice_calidad_aire'],
        },
        {
          slug: 'aire_suelo.medir-el-aire.3',
          titulo_es: 'Medir mirando un tronco',
          bajada_es: 'Líquenes: un sensor que ya está puesto.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['aire_suelo.liquenes_indicadores', 'aire_suelo.donde_esta_la_estacion'],
        },
      ],
    },
  ],
};
