// Rama `animales`, parte B — conservación, bienestar animal y fauna urbana.
// Fuente: ACADEMIA/research/03-environmental-curriculum.md §2.6 niveles 3, 4 y 5,
// §3.1 (ecorregiones), §3.2 (fauna emblemática) y §3.3 (Buenos Aires), más §6
// para las reglas de edad. Mitos asignados: 6, 10, 12, 13, 14, 15, 16, 17, 30 y 31.
//
// Segunda mitad de la rama insignia; los gajos arrancan en sort_order 8, después
// de los siete de `animales-a.mjs`.
//
// REGLA DE EDAD, ACÁ MÁS QUE EN NINGÚN LADO. Tráfico de fauna, maltrato, caza y
// faena van `sensible: true` y sin `kid`. Para cuentas infantiles queda la
// contracara positiva —tenencia responsable, no alimentar fauna, no comprar
// animales silvestres— sin describir qué les pasa a los animales traficados. Y
// ningún contenido kid le pide a un chico manipular fauna: siempre "avisale a
// una persona adulta".

export default {
  rama: 'animales',
  gajos: [
    {
      slug: 'animales.la-fauna-de-tu-barrio',
      anillo: 1,
      titulo_es: 'La fauna de tu barrio',
      bajada_es: 'Quiénes viven en Buenos Aires sin que los invitemos.',
      icono: 'Bird',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 8,
      conceptos: [
        {
          slug: 'animales.aves_porteñas',
          titulo_es: 'Las aves que ya conocés',
          enunciado_es:
            'Hornero, benteveo, calandria, chingolo, zorzal, torcaza y cotorra son parte del paisaje sonoro de cualquier barrio del AMBA.',
          detalle_es: 'El hornero es el ave nacional argentina.',
          fuente: 'ebird',
          anillo: 1,
          dificultad_base: -1.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'animales.rapaces_urbanas',
          titulo_es: 'Las rapaces de la ciudad',
          enunciado_es:
            'Caranchos, chimangos, gavilanes mixtos y lechucitas vizcacheras viven y cazan dentro del área metropolitana.',
          detalle_es: null,
          fuente: 'ebird',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.aves_porteñas'],
        },
        {
          slug: 'animales.mamiferos_urbanos',
          titulo_es: 'Mamíferos que no ves',
          enunciado_es:
            'La comadreja overa, el coipo y varios murciélagos viven en el AMBA. Son casi todos nocturnos, y por eso pasan desapercibidos.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.aves_porteñas'],
        },
        {
          slug: 'animales.lagarto_overo',
          titulo_es: 'El lagarto overo',
          enunciado_es:
            'Es el reptil más grande que vas a ver en la Reserva Ecológica: come de todo, toma sol para regular su temperatura y no es agresivo si lo dejás tranquilo.',
          detalle_es: null,
          fuente: 'reserva-costanera-sur',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.mamiferos_urbanos'],
        },
        {
          slug: 'animales.cotorra_es_nativa',
          titulo_es: 'La cotorra es nativa',
          enunciado_es:
            'La cotorra (Myiopsitta monachus) es una especie nativa argentina, aunque sea abundante y a veces conflictiva. La paloma doméstica, el gorrión y el estornino son las introducidas.',
          detalle_es: null,
          fuente: 'invasoras-mayds',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.aves_porteñas'],
          misconceptions: [
            {
              slug: 'animales.mito_cotorra_plaga',
              creencia_es: 'Las cotorras y las palomas son plagas exóticas que invadieron la ciudad.',
              correccion_es:
                'Se las mete en la misma bolsa porque las dos son abundantes y molestan, y ahí está el error: abundante no es lo mismo que exótica. La cotorra es nativa de la Argentina; las introducidas son la paloma doméstica, el gorrión y el estornino.',
              fuente: 'invasoras-mayds',
            },
          ],
        },
        {
          slug: 'animales.sinantropia',
          titulo_es: 'Especies que aprendieron a vivir con nosotros',
          enunciado_es:
            'Algunas especies prosperan justo donde hay gente, porque encuentran comida constante y pocos depredadores. Se las llama sinantrópicas.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cotorra_es_nativa'],
        },
      ],
      hojas: [
        {
          slug: 'animales.la-fauna-de-tu-barrio.1',
          titulo_es: 'Las que ya escuchaste',
          bajada_es: 'Hornero, benteveo, calandria y compañía.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.aves_porteñas', 'animales.rapaces_urbanas'],
        },
        {
          slug: 'animales.la-fauna-de-tu-barrio.2',
          titulo_es: 'Los que salen de noche',
          bajada_es: 'Comadrejas, coipos, murciélagos y un lagarto grande.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.mamiferos_urbanos', 'animales.lagarto_overo'],
        },
        {
          slug: 'animales.la-fauna-de-tu-barrio.3',
          titulo_es: 'Abundante no es exótica',
          bajada_es: 'La cotorra, la paloma y una confusión muy repetida.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.cotorra_es_nativa', 'animales.sinantropia'],
        },
      ],
    },

    {
      slug: 'animales.convivir-bien',
      anillo: 1,
      titulo_es: 'Convivir bien',
      bajada_es: 'Qué hacer y qué no cuando te cruzás con fauna.',
      icono: 'HeartHandshake',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 9,
      conceptos: [
        {
          slug: 'animales.no_alimentar',
          titulo_es: 'No se alimenta fauna silvestre',
          enunciado_es:
            'Darles de comer los vuelve dependientes, los junta en grupos donde se contagian enfermedades, les da una dieta que no les corresponde y los acostumbra a la gente.',
          detalle_es: 'Y esa costumbre casi siempre termina mal para el animal.',
          fuente: 'protocolo-fauna-cba',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
          misconceptions: [
            {
              slug: 'animales.mito_alimentar_fauna',
              creencia_es: 'Darles de comer a los animales silvestres los ayuda.',
              correccion_es:
                'Nace de un impulso bueno, que es justo lo que la vuelve difícil de discutir. Pero genera dependencia, desnutrición por dieta inadecuada, agrupamientos donde se transmiten enfermedades, y habituación a las personas. Ayudar de verdad es dejar comida disponible en el ambiente, no en la mano.',
              fuente: 'protocolo-fauna-cba',
            },
          ],
        },
        {
          slug: 'animales.volanton_vs_pichon',
          titulo_es: 'Volantón y pichón no son lo mismo',
          enunciado_es:
            'Un volantón ya tiene plumas y está aprendiendo a volar: sus padres lo siguen alimentando en el suelo. Un pichón sin plumas sí necesita ayuda.',
          detalle_es:
            'Ante un volantón, lo correcto es dejarlo donde está o subirlo a una rama cercana y alejar a las mascotas.',
          fuente: 'protocolo-fauna-cba',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.no_alimentar'],
          misconceptions: [
            {
              slug: 'animales.mito_pichon_caido',
              creencia_es: 'Si encontrás un pichón en el suelo hay que llevárselo a casa para salvarlo.',
              correccion_es:
                'Parece lo más compasivo y por eso se hace tanto. La mayoría de los pajaritos que se encuentran en el suelo son volantones: están emplumados, están aprendiendo a volar y sus padres los siguen alimentando ahí. Llevárselo es separarlo de su familia. Dejalo donde está o subilo a una rama, alejá a las mascotas y avisale a una persona adulta si está claramente herido.',
              fuente: 'protocolo-fauna-cba',
            },
          ],
        },
        {
          slug: 'animales.animal_herido_que_hacer',
          titulo_es: 'Si encontrás un animal silvestre herido',
          enunciado_es:
            'No lo manipules sin protección, no le des agua ni comida, ponelo en una caja de cartón ventilada, oscura y silenciosa, no lo muestres ni lo fotografíes de cerca, y contactá a la autoridad de fauna.',
          detalle_es:
            'Si sos chico, la parte que te toca es avisarle a una persona adulta: la caja y el llamado los hace ella.',
          fuente: 'protocolo-fauna-cba',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.volanton_vs_pichon'],
        },
        {
          slug: 'animales.centros_de_rescate',
          titulo_es: 'A quién se llama',
          enunciado_es:
            'La Red Federal de Centros de Rescate articula los centros del país, y en la Ciudad de Buenos Aires funciona el Centro de Rescate de Fauna Silvestre del Ecoparque.',
          detalle_es: null,
          fuente: 'red-centros-rescate',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.animal_herido_que_hacer'],
        },
        {
          slug: 'animales.viboras_no_atacan',
          titulo_es: 'Las serpientes no atacan',
          enunciado_es:
            'Una serpiente muerde para defenderse, no para agredir. La mayoría de las especies argentinas no son venenosas, y la respuesta correcta es alejarse.',
          detalle_es: 'Matarlas además es ilegal cuando la especie está protegida.',
          fuente: 'ley-22421-fauna',
          anillo: 1,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.no_alimentar'],
          misconceptions: [
            {
              slug: 'animales.mito_viboras_atacan',
              creencia_es: 'Las víboras atacan a la gente, así que si ves una hay que matarla.',
              correccion_es:
                'El miedo es real y viejo, pero la conducta que se le atribuye no. Las serpientes muerden defendiéndose, casi siempre cuando alguien las pisa o intenta agarrarlas. La mayoría de las especies argentinas no son venenosas, alejarse resuelve el 100 % de los casos, y matarlas es ilegal para las especies protegidas.',
              fuente: 'ley-22421-fauna',
            },
          ],
        },
        {
          slug: 'animales.apex_no_cazan_gente',
          titulo_es: 'Los grandes depredadores evitan a la gente',
          enunciado_es:
            'Pumas, yaguaretés y tiburones esquivan a las personas. Los encuentros graves son rarísimos comparados con el miedo que les tenemos.',
          detalle_es: 'Y son especies clave: sacarlos desarma la estructura trófica entera.',
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.viboras_no_atacan'],
          misconceptions: [
            {
              slug: 'animales.mito_apex_maquinas_de_matar',
              creencia_es: 'Los tiburones, los pumas y los yaguaretés son máquinas de matar humanos.',
              correccion_es:
                'La imagen viene del cine y de que los ataques, cuando ocurren, son noticia mundial. En los hechos evitan a las personas, y son especies clave: cuando desaparecen, la estructura trófica entera se reorganiza y el ecosistema se empobrece.',
              fuente: 'sarem-2019',
            },
          ],
        },
      ],
      hojas: [
        {
          slug: 'animales.convivir-bien.1',
          titulo_es: 'No les des de comer',
          bajada_es: 'Por qué el gesto más tierno es el que más daña.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.no_alimentar', 'animales.sinantropia'],
        },
        {
          slug: 'animales.convivir-bien.2',
          titulo_es: 'El pajarito del suelo',
          bajada_es: 'Volantón o pichón, y qué hacer con cada uno.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.volanton_vs_pichon', 'animales.animal_herido_que_hacer'],
        },
        {
          slug: 'animales.convivir-bien.3',
          titulo_es: 'A quién se llama',
          bajada_es: 'Centros de rescate y el protocolo completo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.centros_de_rescate', 'animales.animal_herido_que_hacer'],
        },
        {
          slug: 'animales.convivir-bien.4',
          titulo_es: 'Miedos que no se sostienen',
          bajada_es: 'Serpientes, pumas y la distancia entre fama y datos.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.viboras_no_atacan', 'animales.apex_no_cazan_gente'],
        },
      ],
    },

    {
      slug: 'animales.el-carpincho-y-el-humedal',
      anillo: 1,
      titulo_es: 'El carpincho y el humedal',
      bajada_es: 'El mejor caso local para entender un conflicto de uso del suelo.',
      icono: 'Waves',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 10,
      conceptos: [
        {
          slug: 'animales.carpincho_quien_es',
          titulo_es: 'Quién es el carpincho',
          enunciado_es:
            'Es el roedor vivo más grande del mundo: herbívoro, semiacuático y muy social. Vive en grupos y necesita agua cerca.',
          detalle_es: null,
          fuente: 'conicet-carpinchos',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'animales.carpincho_ingeniero',
          titulo_es: 'Lo que hace en el humedal',
          enunciado_es:
            'Al pastar y moverse abre caminos y mantiene abiertos espacios de agua: modifica el ambiente de un modo que otras especies aprovechan.',
          detalle_es: null,
          fuente: 'conicet-carpinchos',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.carpincho_quien_es'],
        },
        {
          slug: 'animales.nordelta',
          titulo_es: 'Nordelta, al revés de como se cuenta',
          enunciado_es:
            'El barrio se construyó sobre el humedal donde los carpinchos ya vivían. No es una invasión de fauna: es un conflicto de uso del suelo.',
          detalle_es: null,
          fuente: 'conicet-carpinchos',
          anillo: 1,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.carpincho_ingeniero'],
          misconceptions: [
            {
              slug: 'animales.mito_carpinchos_invaden',
              creencia_es: 'Los carpinchos son roedores peligrosos que invadieron los barrios.',
              correccion_es:
                'Suena convincente porque uno ve los animales aparecer "de golpe" en las fotos. Pero el orden fue el inverso: el barrio se levantó sobre su humedal. Son herbívoros, sociales y no agresivos, y lo que hay que discutir es cómo se ocupó ese suelo, no cómo sacarlos.',
              fuente: 'conicet-carpinchos',
            },
          ],
        },
        {
          slug: 'animales.conflicto_es_de_uso',
          titulo_es: 'Casi todo conflicto con fauna es de uso del suelo',
          enunciado_es:
            'Cuando un animal "aparece donde no debería", casi siempre lo que se movió fue el límite de lo construido, no el animal.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.nordelta'],
        },
      ],
      hojas: [
        {
          slug: 'animales.el-carpincho-y-el-humedal.1',
          titulo_es: 'El roedor más grande del mundo',
          bajada_es: 'Quién es y qué necesita.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.carpincho_quien_es', 'animales.carpincho_ingeniero'],
        },
        {
          slug: 'animales.el-carpincho-y-el-humedal.2',
          titulo_es: 'Quién llegó primero',
          bajada_es: 'Nordelta, contado en el orden correcto.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.nordelta', 'animales.conflicto_es_de_uso'],
        },
        {
          slug: 'animales.el-carpincho-y-el-humedal.3',
          titulo_es: 'El límite que se movió',
          bajada_es: 'Un patrón que se repite en todo el país.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.conflicto_es_de_uso', 'animales.carpincho_ingeniero'],
        },
      ],
    },

    {
      slug: 'animales.cuanto-queda',
      anillo: 2,
      titulo_es: 'Cuánto queda',
      bajada_es: 'Cómo se mide el riesgo de extinción y qué significan las siglas.',
      icono: 'ListChecks',
      age_groups: ['teen', 'adult'],
      sort_order: 11,
      conceptos: [
        {
          slug: 'animales.biodiversidad_tres_niveles',
          titulo_es: 'Biodiversidad en tres niveles',
          enunciado_es:
            'Diversidad genética dentro de una especie, diversidad de especies y diversidad de ecosistemas. Perder cualquiera de las tres empobrece el sistema.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.que_es_ecosistema'],
        },
        {
          slug: 'animales.categorias_uicn',
          titulo_es: 'Las categorías de la Lista Roja',
          enunciado_es:
            'EX, EW, CR, EN, VU, NT, LC, DD y NE. Las tres categorías de amenaza son En Peligro Crítico, En Peligro y Vulnerable.',
          detalle_es: null,
          fuente: 'iucn-categorias',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.biodiversidad_tres_niveles'],
        },
        {
          slug: 'animales.dd_no_es_esta_bien',
          titulo_es: 'DD no significa "está bien"',
          enunciado_es:
            'Datos Insuficientes quiere decir que no sabemos. Algunas especies DD están entre las más comprometidas justamente porque nadie las evaluó.',
          detalle_es: null,
          fuente: 'iucn-red-list',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.categorias_uicn'],
          misconceptions: [
            {
              slug: 'animales.mito_dd_esta_bien',
              creencia_es: 'Si una especie figura como "Datos Insuficientes" es porque está bien.',
              correccion_es:
                'La sigla se lee como si fuera una categoría tranquilizadora, y es lo contrario: significa que no hay información para evaluarla. Varias especies DD están entre las más comprometidas precisamente porque nadie fue a mirarlas.',
              fuente: 'iucn-red-list',
            },
          ],
        },
        {
          slug: 'animales.nacional_vs_global',
          titulo_es: 'Nacional y global no coinciden',
          enunciado_es:
            'Una especie puede estar en Preocupación Menor a nivel mundial y En Peligro en la Argentina, porque acá su población es chica o está en el borde de su distribución.',
          detalle_es: null,
          fuente: 'iucn-categorias',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.categorias_uicn'],
        },
        {
          slug: 'animales.sarem_numeros',
          titulo_es: 'Los mamíferos argentinos, en números',
          enunciado_es:
            'La categorización de SAREM de 2019 evaluó 417 especies de mamíferos nativos: 98 quedaron amenazadas y el 92,7 % enfrenta al menos una amenaza.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.categorias_uicn', 'tronco.leer_un_numero'],
        },
        {
          slug: 'animales.aves_amenazadas_ar',
          titulo_es: 'Las aves argentinas amenazadas',
          enunciado_es:
            'Alrededor del 12 % de las aves silvestres del país —113 especies— están amenazadas, frente a 80 en la década de 1990.',
          detalle_es: null,
          fuente: 'aves-argentinas-amenazadas',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.sarem_numeros'],
        },
      ],
      hojas: [
        {
          slug: 'animales.cuanto-queda.1',
          titulo_es: 'Tres niveles de diversidad',
          bajada_es: 'Genes, especies y ecosistemas.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.biodiversidad_tres_niveles', 'animales.categorias_uicn'],
        },
        {
          slug: 'animales.cuanto-queda.2',
          titulo_es: 'Nueve siglas',
          bajada_es: 'La Lista Roja y la trampa del DD.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.categorias_uicn', 'animales.dd_no_es_esta_bien'],
        },
        {
          slug: 'animales.cuanto-queda.3',
          titulo_es: 'Acá y en el mundo',
          bajada_es: 'Por qué las categorías no coinciden.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.nacional_vs_global', 'animales.sarem_numeros'],
        },
        {
          slug: 'animales.cuanto-queda.4',
          titulo_es: 'Los números argentinos',
          bajada_es: 'Mamíferos y aves, con su fuente.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.aves_amenazadas_ar', 'animales.sarem_numeros'],
        },
      ],
    },

    {
      slug: 'animales.que-las-amenaza',
      anillo: 2,
      titulo_es: 'Qué las amenaza',
      bajada_es: 'Las amenazas reales, ordenadas por peso.',
      icono: 'TriangleAlert',
      age_groups: ['teen', 'adult'],
      sort_order: 12,
      conceptos: [
        {
          slug: 'animales.perdida_de_habitat',
          titulo_es: 'La amenaza número uno',
          enunciado_es:
            'La pérdida y degradación del hábitat afecta a cerca del 80 % de los mamíferos argentinos: está muy por encima de cualquier otra causa.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.sarem_numeros'],
        },
        {
          slug: 'animales.fragmentacion',
          titulo_es: 'Fragmentación y efecto borde',
          enunciado_es:
            'Partir un ambiente en pedazos aislados es peor que perder la misma superficie de una sola vez: quedan poblaciones chicas, separadas y con más borde expuesto.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.perdida_de_habitat'],
        },
        {
          slug: 'animales.atropellamientos',
          titulo_es: 'Atropellamientos en ruta',
          enunciado_es:
            'El 22 % de los mamíferos argentinos está afectado por atropellamientos: para varias especies es una de las principales causas de muerte.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.perdida_de_habitat'],
        },
        {
          slug: 'animales.perros_y_gatos',
          titulo_es: 'Perros y gatos domésticos',
          enunciado_es:
            'La depredación por perros afecta al 22 % de los mamíferos argentinos, un peso comparable al de los atropellamientos. Los gatos con acceso al exterior impactan sobre todo a las aves.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.atropellamientos'],
          misconceptions: [
            {
              slug: 'animales.mito_perros_sueltos',
              creencia_es: 'Los perros sueltos no le hacen nada a la fauna: son animales domésticos.',
              correccion_es:
                'Cuesta verlo porque el perro que uno conoce es el de casa. Pero a escala de país la depredación por perros afecta al 22 % de las especies de mamíferos argentinos, un peso comparable al de los atropellamientos en ruta. Correa en zonas naturales no es un capricho.',
              fuente: 'sarem-2019',
            },
          ],
        },
        {
          slug: 'animales.especies_invasoras',
          titulo_es: 'Especies exóticas invasoras',
          enunciado_es:
            'El castor en Tierra del Fuego, el visón americano, el jabalí, el ciervo colorado y el mejillón dorado están entre las que más transforman ambientes en la Argentina.',
          detalle_es: null,
          fuente: 'invasoras-mayds',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.fragmentacion'],
        },
        {
          slug: 'animales.soltar_no_es_liberar',
          titulo_es: 'Soltar una mascota no es liberarla',
          enunciado_es:
            'Es abandono, y además introduce especies y enfermedades. Tortugas, peces y conejos soltados "en la naturaleza" suelen morir o convertirse en un problema ecológico.',
          detalle_es: null,
          fuente: 'invasoras-mayds',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.especies_invasoras'],
          misconceptions: [
            {
              slug: 'animales.mito_soltar_es_liberar',
              creencia_es: 'Si no podés tener más a tu mascota, soltarla en el campo o en un río es devolverle la libertad.',
              correccion_es:
                'La palabra "liberar" es la que engaña. Un animal criado en cautiverio no sabe buscar comida ni evitar depredadores, así que casi siempre muere; y el que sobrevive puede volverse invasor o traer enfermedades a la fauna local. Lo correcto es buscarle un hogar o contactar a la autoridad de fauna.',
              fuente: 'invasoras-mayds',
            },
          ],
        },
      ],
      hojas: [
        {
          slug: 'animales.que-las-amenaza.1',
          titulo_es: 'Ordenadas por peso',
          bajada_es: 'Hábitat primero, y por bastante.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.perdida_de_habitat', 'animales.fragmentacion'],
        },
        {
          slug: 'animales.que-las-amenaza.2',
          titulo_es: 'Rutas y perros',
          bajada_es: 'Dos amenazas del mismo tamaño.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.atropellamientos', 'animales.perros_y_gatos'],
        },
        {
          slug: 'animales.que-las-amenaza.3',
          titulo_es: 'Las que no estaban',
          bajada_es: 'Invasoras, y por qué soltar no es liberar.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.especies_invasoras', 'animales.soltar_no_es_liberar'],
        },
      ],
    },

    {
      slug: 'animales.tenencia-responsable',
      anillo: 2,
      titulo_es: 'Tenencia responsable',
      bajada_es: 'Las cinco libertades, y qué implica cada una.',
      icono: 'Dog',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 13,
      conceptos: [
        {
          slug: 'animales.sintiencia',
          titulo_es: 'Sentir es la base',
          enunciado_es:
            'Los animales sintientes pueden experimentar dolor, miedo y bienestar. Ese es el punto de partida de todo lo que sigue.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'animales.cinco_libertades',
          titulo_es: 'Las cinco libertades',
          enunciado_es:
            'Libre de hambre y sed; libre de incomodidad; libre de dolor, lesión y enfermedad; libre para expresar comportamiento natural; libre de miedo y angustia.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 2,
          dificultad_base: 0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.sintiencia'],
        },
        {
          slug: 'animales.cuidado_basico',
          titulo_es: 'Lo que implica en la práctica',
          enunciado_es:
            'Identificación, vacunación antirrábica, desparasitación, paseo con correa, recolección de heces y no abandonar. Todo eso es parte de las cinco libertades, no un extra.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cinco_libertades'],
        },
        {
          slug: 'animales.castracion',
          titulo_es: 'Castración',
          enunciado_es:
            'Es la herramienta ética de control poblacional: evita camadas que terminan en la calle y reduce varios problemas de salud.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cuidado_basico'],
        },
        {
          slug: 'animales.adoptar',
          titulo_es: 'Adoptar antes que comprar',
          enunciado_es:
            'Adoptar le da lugar a un animal que ya existe y necesita hogar, en vez de generar demanda de una camada nueva.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 2,
          dificultad_base: 0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.castracion'],
        },
        {
          slug: 'animales.gato_puertas_adentro',
          titulo_es: 'El gato, mejor adentro',
          enunciado_es:
            'Un gato con acceso libre al exterior caza aves y pequeños mamíferos aunque esté bien alimentado, y además vive menos.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.perros_y_gatos'],
        },
        {
          slug: 'animales.cinco_dominios',
          titulo_es: 'De las cinco libertades a los cinco dominios',
          enunciado_es:
            'El modelo más nuevo no se conforma con evitar el sufrimiento: evalúa también si el animal tiene experiencias positivas.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 3,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.cinco_libertades'],
        },
      ],
      hojas: [
        {
          slug: 'animales.tenencia-responsable.1',
          titulo_es: 'Las cinco libertades',
          bajada_es: 'El marco completo, en criollo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.sintiencia', 'animales.cinco_libertades'],
        },
        {
          slug: 'animales.tenencia-responsable.2',
          titulo_es: 'Lo que hay que hacer sí o sí',
          bajada_es: 'Chip, vacunas, correa y castración.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.cuidado_basico', 'animales.castracion'],
        },
        {
          slug: 'animales.tenencia-responsable.3',
          titulo_es: 'Adoptar, y tener el gato adentro',
          bajada_es: 'Dos decisiones con efecto grande.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.adoptar', 'animales.gato_puertas_adentro'],
        },
        {
          slug: 'animales.tenencia-responsable.4',
          titulo_es: 'Más que no sufrir',
          bajada_es: 'Los cinco dominios y el bienestar positivo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.cinco_dominios', 'animales.cinco_libertades'],
        },
      ],
    },

    {
      slug: 'animales.no-son-mascotas',
      anillo: 2,
      titulo_es: 'La fauna silvestre no es mascota',
      bajada_es: 'Tráfico, tenencia ilegal y qué hacer al respecto.',
      icono: 'ShieldAlert',
      age_groups: ['teen', 'adult'],
      sort_order: 14,
      conceptos: [
        {
          slug: 'animales.no_es_mascota',
          titulo_es: 'Loros, tortugas y monos no son mascotas',
          enunciado_es:
            'La fauna silvestre tiene necesidades de espacio, dieta y comportamiento que una casa no puede cubrir, y en la Argentina su tenencia está regulada por ley.',
          detalle_es: null,
          fuente: 'ley-22421-fauna',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cinco_libertades'],
        },
        {
          slug: 'animales.comprar_es_demanda',
          titulo_es: 'Comprar no rescata: genera demanda',
          enunciado_es:
            'Cada animal comprado le avisa al circuito que hay mercado. Lo que corresponde es denunciar, no comprar.',
          detalle_es: null,
          fuente: 'ley-22421-fauna',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.no_es_mascota'],
          misconceptions: [
            {
              slug: 'animales.mito_comprar_rescata',
              creencia_es: 'Si comprás el loro o la tortuga que estaba en una jaula, lo estás rescatando.',
              correccion_es:
                'La intención es genuina y por eso el argumento circula tanto. Pero la compra le confirma al vendedor que hay mercado y financia la próxima captura. Rescatar de verdad es denunciar ante la autoridad de fauna.',
              fuente: 'ley-22421-fauna',
            },
          ],
        },
        {
          slug: 'animales.cardenal_amarillo',
          titulo_es: 'El cardenal amarillo',
          enunciado_es:
            'Está En Peligro y su principal amenaza es directamente el tráfico como ave de jaula, por su canto.',
          detalle_es: null,
          fuente: 'aves-argentinas-amenazadas',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.comprar_es_demanda'],
        },
        {
          slug: 'animales.cites',
          titulo_es: 'CITES',
          enunciado_es:
            'Regula el comercio internacional de especies con tres apéndices: el I prohíbe el comercio con fines comerciales, el II lo permite bajo permiso y el III lista especies protegidas por un país.',
          detalle_es: null,
          fuente: 'cites',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.comprar_es_demanda'],
        },
        {
          slug: 'animales.leyes_fauna_ar',
          titulo_es: 'Las leyes que aplican acá',
          enunciado_es:
            'La Ley 22.421 declara de interés público la conservación de la fauna y regula caza, transporte y comercio; la Ley 14.346 penaliza el maltrato animal.',
          detalle_es: null,
          fuente: 'ley-22421-fauna',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.cites'],
        },
        {
          slug: 'animales.como_denunciar',
          titulo_es: 'Cómo se denuncia',
          enunciado_es:
            'Se avisa a la autoridad de fauna con lugar, fecha y foto si se puede sacar sin exponerse. No hay que intentar rescatar por cuenta propia.',
          detalle_es: null,
          fuente: 'red-centros-rescate',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.leyes_fauna_ar', 'animales.centros_de_rescate'],
        },
      ],
      hojas: [
        {
          slug: 'animales.no-son-mascotas.1',
          titulo_es: 'Una casa no alcanza',
          bajada_es: 'Por qué la fauna silvestre no se tiene.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.no_es_mascota', 'animales.comprar_es_demanda'],
        },
        {
          slug: 'animales.no-son-mascotas.2',
          titulo_es: 'Un pájaro que canta demasiado bien',
          bajada_es: 'El cardenal amarillo y el tráfico.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.cardenal_amarillo', 'animales.cites'],
        },
        {
          slug: 'animales.no-son-mascotas.3',
          titulo_es: 'Qué dice la ley y a quién se avisa',
          bajada_es: 'Ley 22.421, Ley 14.346 y el canal correcto.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.leyes_fauna_ar', 'animales.como_denunciar'],
        },
      ],
    },

    {
      slug: 'animales.traerlos-de-vuelta',
      anillo: 3,
      titulo_es: 'Traerlos de vuelta',
      bajada_es: 'Rewilding, reintroducción y los casos argentinos.',
      icono: 'Undo2',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 15,
      conceptos: [
        {
          slug: 'animales.rewilding',
          titulo_es: 'Qué es el rewilding',
          enunciado_es:
            'Es devolver a un ecosistema las especies que perdió, para que vuelvan a cumplir su función, y no solo para que estén.',
          detalle_es: null,
          fuente: 'rewilding-argentina',
          anillo: 3,
          dificultad_base: 0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.especie_clave'],
        },
        {
          slug: 'animales.etapas_reintroduccion',
          titulo_es: 'Las etapas de una reintroducción',
          enunciado_es:
            'Cría, corral de presuelta para que aprendan el lugar, liberación, y monitoreo por años. Saltearse una etapa es perder los animales.',
          detalle_es: null,
          fuente: 'rewilding-argentina',
          anillo: 3,
          dificultad_base: 0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.rewilding'],
        },
        {
          slug: 'animales.guacamayo_rojo',
          titulo_es: 'El guacamayo rojo volvió',
          enunciado_es:
            'Estuvo extinto en la Argentina por más de 150 años y fue reintroducido en Iberá: hoy vuelve a volar sobre los esteros.',
          detalle_es: null,
          fuente: 'rewilding-argentina',
          anillo: 3,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.etapas_reintroduccion'],
        },
        {
          slug: 'animales.yaguarete_ibera',
          titulo_es: 'El yaguareté en Iberá',
          enunciado_es:
            'Es Monumento Natural Nacional y está En Peligro Crítico en la Argentina, con núcleos en Selva Paranaense, Yungas y Chaco, más las reintroducciones de Iberá y El Impenetrable.',
          detalle_es: null,
          fuente: 'rewilding-argentina',
          anillo: 3,
          dificultad_base: 0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.guacamayo_rojo'],
        },
        {
          slug: 'animales.ex_situ_in_situ',
          titulo_es: 'Ex situ e in situ',
          enunciado_es:
            'Conservar in situ es proteger a la especie donde vive; ex situ es hacerlo fuera, en centros de cría. La segunda tiene sentido como apoyo de la primera, no como reemplazo.',
          detalle_es: null,
          fuente: 'ecoparque-conservacion',
          anillo: 3,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.etapas_reintroduccion'],
        },
        {
          slug: 'animales.corredores_y_pasafaunas',
          titulo_es: 'Corredores y pasafaunas',
          enunciado_es:
            'Conectar parches de ambiente permite que las poblaciones se mezclen; un pasafauna sobre una ruta reduce atropellamientos y reconecta lo que la ruta separó.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.fragmentacion'],
        },
      ],
      hojas: [
        {
          slug: 'animales.traerlos-de-vuelta.1',
          titulo_es: 'Devolver una función',
          bajada_es: 'Qué es y qué no es el rewilding.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.rewilding', 'animales.etapas_reintroduccion'],
        },
        {
          slug: 'animales.traerlos-de-vuelta.2',
          titulo_es: 'Ciento cincuenta años después',
          bajada_es: 'El guacamayo rojo y el yaguareté en Iberá.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.guacamayo_rojo', 'animales.yaguarete_ibera'],
        },
        {
          slug: 'animales.traerlos-de-vuelta.3',
          titulo_es: 'Volver a conectar',
          bajada_es: 'Corredores, pasafaunas y poblaciones que se mezclan.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.corredores_y_pasafaunas', 'animales.ex_situ_in_situ'],
        },
      ],
    },

    {
      slug: 'animales.discusiones-abiertas',
      anillo: 3,
      titulo_es: 'Discusiones abiertas',
      bajada_es: 'Casos donde hay debate real y conviene presentarlo como debate.',
      icono: 'MessagesSquare',
      age_groups: ['teen', 'adult'],
      sort_order: 16,
      conceptos: [
        {
          slug: 'animales.zoologicos_debate',
          titulo_es: 'Zoológicos: el debate',
          enunciado_es:
            'Instituciones como el Ecoparque o Temaikèn hacen cría, rescate e investigación reales. La discusión ética sobre el cautiverio también es real, y las dos cosas conviven.',
          detalle_es: 'Acá no hay veredicto: hay un debate con argumentos de los dos lados.',
          fuente: 'ecoparque-conservacion',
          anillo: 3,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.ex_situ_in_situ'],
          misconceptions: [
            {
              slug: 'animales.mito_zoologicos_solo_entretienen',
              creencia_es: 'Los zoológicos y acuarios existen solo para entretener.',
              correccion_es:
                'Es una simplificación de las dos puntas. Instituciones como el Ecoparque o Temaikèn hacen cría para reintroducción, rescate de fauna decomisada e investigación. Y a la vez la objeción ética al cautiverio es legítima y sigue abierta. Lo correcto es presentarlo como debate, no como veredicto.',
              fuente: 'ecoparque-conservacion',
            },
          ],
        },
        {
          slug: 'animales.ecoparque',
          titulo_es: 'Del Zoológico al Ecoparque',
          enunciado_es:
            'El antiguo Zoológico de Buenos Aires se transformó en Ecoparque, con programas de conservación y el traslado de animales a santuarios y centros de referencia.',
          detalle_es: null,
          fuente: 'ecoparque-conservacion',
          anillo: 3,
          dificultad_base: 0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.zoologicos_debate'],
        },
        {
          slug: 'animales.uso_sustentable',
          titulo_es: 'Uso sustentable: el caso del yacaré',
          enunciado_es:
            'El Proyecto Yacaré usó el aprovechamiento regulado para darle valor a la especie y a su humedal, y las poblaciones se recuperaron. Es un modelo que se discute y que en este caso funcionó.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 3,
          dificultad_base: 0.9,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.zoologicos_debate'],
        },
        {
          slug: 'animales.animales_de_produccion',
          titulo_es: 'Animales de producción',
          enunciado_es:
            'El bienestar en los sistemas productivos —espacio, transporte, faena— es un campo con normas propias y con discusión abierta sobre cuánto alcanzan.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.cinco_dominios'],
        },
        {
          slug: 'animales.tres_erres_experimentacion',
          titulo_es: 'Las 3R de la experimentación',
          enunciado_es:
            'Reemplazar el uso de animales cuando se puede, reducir la cantidad al mínimo necesario y refinar los procedimientos para que sufran menos.',
          detalle_es: null,
          fuente: 'gcba-cinco-libertades',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.animales_de_produccion'],
        },
        {
          slug: 'animales.one_health',
          titulo_es: 'Una sola salud',
          enunciado_es:
            'La salud humana, la animal y la de los ecosistemas son el mismo problema: la mayoría de las enfermedades emergentes vienen de ese cruce.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 3,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.perdida_de_habitat'],
        },
      ],
      hojas: [
        {
          slug: 'animales.discusiones-abiertas.1',
          titulo_es: 'Dos argumentos válidos',
          bajada_es: 'Zoológicos, Ecoparque y la discusión que sigue abierta.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.zoologicos_debate', 'animales.ecoparque'],
        },
        {
          slug: 'animales.discusiones-abiertas.2',
          titulo_es: 'Cuando usar conserva',
          bajada_es: 'El Proyecto Yacaré, contado completo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.uso_sustentable', 'animales.animales_de_produccion'],
        },
        {
          slug: 'animales.discusiones-abiertas.3',
          titulo_es: 'Un solo sistema de salud',
          bajada_es: 'Las 3R y por qué One Health cambia el marco.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.tres_erres_experimentacion', 'animales.one_health'],
        },
      ],
    },
  ],
};
