// Rama `animales`, parte A — fundamentos, taxonomía y ecología.
// Fuente: ACADEMIA/research/03-environmental-curriculum.md §2.6 niveles 1 y 2,
// más §6 para edad. Mitos asignados: 8 (murciélagos), 9 (cotorras y palomas) y
// 11 (sapos y arañas).
//
// La rama insignia del árbol, partida en dos archivos por tamaño. Acá van los
// gajos 1 a 7; conservación, bienestar y fauna urbana están en `animales-b.mjs`
// desde el sort_order 8.
//
// Todo este archivo es apto para cuentas infantiles salvo donde se indica: el
// nivel 1 abre con asombro y relación, nunca con pérdida, y la depredación se
// cuenta en marco ecológico ("el yaguareté come carpinchos y así el pastizal se
// mantiene sano"), nunca con detalle gráfico.

export default {
  rama: 'animales',
  gajos: [
    {
      slug: 'animales.quien-es-quien',
      anillo: 1,
      titulo_es: 'Quién es quién',
      bajada_es: 'Los grandes grupos, y cómo se reconocen.',
      icono: 'PawPrint',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'animales.ser_vivo',
          titulo_es: 'Qué hace que algo esté vivo',
          enunciado_es:
            'Un ser vivo nace, usa energía, responde a lo que pasa alrededor, crece y deja descendencia. Una piedra no hace nada de eso.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -1.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'animales.vertebrados_invertebrados',
          titulo_es: 'Con columna y sin columna',
          enunciado_es:
            'Los vertebrados tienen columna vertebral; los invertebrados no. La enorme mayoría de los animales del planeta son invertebrados.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -1.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.ser_vivo'],
        },
        {
          slug: 'animales.cinco_clases',
          titulo_es: 'Las cinco clases de vertebrados',
          enunciado_es:
            'Peces, anfibios, reptiles, aves y mamíferos. Cada grupo tiene su forma de respirar, de reproducirse y de manejar la temperatura.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -1.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.vertebrados_invertebrados'],
        },
        {
          slug: 'animales.artropodos',
          titulo_es: 'Artrópodos: el grupo más numeroso',
          enunciado_es:
            'Insectos, arácnidos, crustáceos y miriápodos comparten esqueleto externo y patas articuladas. Son el grupo con más especies del planeta.',
          detalle_es: 'Los insectos tienen seis patas; las arañas, ocho.',
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.vertebrados_invertebrados'],
        },
        {
          slug: 'animales.moluscos',
          titulo_es: 'Moluscos',
          enunciado_es:
            'Caracoles, babosas, almejas y pulpos: cuerpo blando, muchas veces con concha, y un papel enorme en ríos y mares.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.8,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.vertebrados_invertebrados'],
        },
        {
          slug: 'animales.metamorfosis',
          titulo_es: 'Metamorfosis completa e incompleta',
          enunciado_es:
            'Algunos insectos pasan por huevo, larva, pupa y adulto —como la mariposa—; otros nacen parecidos al adulto y solo van creciendo, como la langosta.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.artropodos'],
        },
        {
          slug: 'animales.oviparo_viviparo',
          titulo_es: 'Ovíparo, vivíparo y ovovivíparo',
          enunciado_es:
            'Poner huevos, gestar dentro del cuerpo, o incubar los huevos adentro hasta que nacen: tres formas distintas de traer crías al mundo.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cinco_clases'],
        },
        {
          slug: 'animales.ectotermo_endotermo',
          titulo_es: '"Sangre fría" es un mal nombre',
          enunciado_es:
            'Un ectotermo regula su temperatura con el ambiente —por eso una lagartija se asolea— y un endotermo la genera por dentro. Nada de eso implica que la sangre esté fría.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cinco_clases'],
        },
      ],
      hojas: [
        {
          slug: 'animales.quien-es-quien.1',
          titulo_es: 'Vivo o no vivo',
          bajada_es: 'La pregunta más básica y la más útil.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.ser_vivo', 'animales.vertebrados_invertebrados'],
        },
        {
          slug: 'animales.quien-es-quien.2',
          titulo_es: 'Las cinco clases',
          bajada_es: 'Peces, anfibios, reptiles, aves y mamíferos.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.cinco_clases', 'animales.oviparo_viviparo'],
        },
        {
          slug: 'animales.quien-es-quien.3',
          titulo_es: 'Seis patas y ocho patas',
          bajada_es: 'Artrópodos, moluscos y cómo distinguirlos.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.artropodos', 'animales.moluscos'],
        },
        {
          slug: 'animales.quien-es-quien.4',
          titulo_es: 'De huevo a mariposa',
          bajada_es: 'Metamorfosis, y por qué el sol le importa a una lagartija.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.metamorfosis', 'animales.ectotermo_endotermo'],
        },
      ],
    },

    {
      slug: 'animales.donde-y-como-viven',
      anillo: 1,
      titulo_es: 'Dónde y cómo viven',
      bajada_es: 'Hábitat, nicho, qué comen y cómo se las arreglan.',
      icono: 'Home',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'animales.habitat_vs_nicho',
          titulo_es: 'Hábitat y nicho',
          enunciado_es:
            'El hábitat es la dirección: dónde vive. El nicho es el oficio: qué come, cuándo sale, con quién compite y qué papel cumple.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.que_es_ecosistema'],
        },
        {
          slug: 'animales.tipos_de_alimentacion',
          titulo_es: 'Quién come qué',
          enunciado_es:
            'Herbívoros comen plantas, carnívoros comen animales, omnívoros las dos cosas, detritívoros restos, y carroñeros lo que ya estaba muerto.',
          detalle_es: 'Los últimos dos son los que mantienen limpio el sistema.',
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.8,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.ser_vivo'],
        },
        {
          slug: 'animales.camuflaje',
          titulo_es: 'Camuflaje',
          enunciado_es:
            'Parecerse al fondo es la forma más común de no ser visto, y funciona tanto para no ser comido como para poder cazar.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.habitat_vs_nicho'],
        },
        {
          slug: 'animales.mimetismo_aposematismo',
          titulo_es: 'Imitar y advertir',
          enunciado_es:
            'El mimetismo es parecerse a otra especie para aprovechar su fama; el aposematismo es lo contrario: colores llamativos que avisan "no me comas".',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.camuflaje'],
        },
        {
          slug: 'animales.huellas_y_rastros',
          titulo_es: 'Huellas y rastros',
          enunciado_es:
            'Casi nunca ves al animal, pero sí lo que dejó: huellas, plumas, madrigueras, restos de comida o egagrópilas. Leer rastros es la forma más accesible de conocer la fauna de un lugar.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.habitat_vs_nicho'],
        },
        {
          slug: 'animales.cantos',
          titulo_es: 'Cantos y llamadas',
          enunciado_es:
            'Muchas aves y anfibios se identifican antes por el oído que por la vista: el canto marca territorio, busca pareja y avisa peligro.',
          detalle_es: null,
          fuente: 'ebird',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.huellas_y_rastros'],
        },
        {
          slug: 'animales.actividad_dia_noche',
          titulo_es: 'De día, de noche y en el medio',
          enunciado_es:
            'Diurno, nocturno o crepuscular: repartirse las horas es una de las maneras más elegantes de que dos especies no compitan por lo mismo.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.habitat_vs_nicho'],
        },
      ],
      hojas: [
        {
          slug: 'animales.donde-y-como-viven.1',
          titulo_es: 'Dirección y oficio',
          bajada_es: 'La diferencia entre hábitat y nicho.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.habitat_vs_nicho', 'animales.actividad_dia_noche'],
        },
        {
          slug: 'animales.donde-y-como-viven.2',
          titulo_es: 'Quién come qué',
          bajada_es: 'Y quiénes se encargan de limpiar.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.tipos_de_alimentacion', 'animales.habitat_vs_nicho'],
        },
        {
          slug: 'animales.donde-y-como-viven.3',
          titulo_es: 'Esconderse o gritar',
          bajada_es: 'Camuflaje, mimetismo y colores de advertencia.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.camuflaje', 'animales.mimetismo_aposematismo'],
        },
        {
          slug: 'animales.donde-y-como-viven.4',
          titulo_es: 'Leer lo que dejaron',
          bajada_es: 'Huellas, plumas y cantos.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.huellas_y_rastros', 'animales.cantos'],
        },
      ],
    },

    {
      slug: 'animales.como-se-nombran',
      anillo: 1,
      titulo_es: 'Cómo se nombran',
      bajada_es: 'Por qué el nombre científico importa.',
      icono: 'Tag',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'animales.nombre_comun_confunde',
          titulo_es: 'El nombre común cambia de pueblo en pueblo',
          enunciado_es:
            'La misma especie puede tener cinco nombres distintos según la región, y el mismo nombre puede referirse a especies diferentes.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'animales.nomenclatura_binomial',
          titulo_es: 'Dos palabras, un solo animal',
          enunciado_es:
            'El nombre científico tiene género y especie, y es el mismo en todo el mundo: un carpincho es Hydrochoerus hydrochaeris en cualquier idioma.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.nombre_comun_confunde'],
        },
        {
          slug: 'animales.jerarquia_linneana',
          titulo_es: 'Las cajas dentro de cajas',
          enunciado_es:
            'Dominio, reino, filo, clase, orden, familia, género y especie: cada nivel agrupa al anterior, y cuanto más abajo, más parecidos son entre sí.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.nomenclatura_binomial'],
        },
        {
          slug: 'animales.arbol_filogenetico',
          titulo_es: 'El árbol de parentesco',
          enunciado_es:
            'Un árbol filogenético muestra quién comparte antepasado con quién: agrupa por historia evolutiva, no por parecido.',
          detalle_es: 'Por eso un delfín está más cerca de una vaca que de un tiburón.',
          fuente: 'sib-apn',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.jerarquia_linneana'],
        },
        {
          slug: 'animales.especie_biologica',
          titulo_es: 'Qué es una especie',
          enunciado_es:
            'La definición más usada es la de poblaciones que se cruzan entre sí y dejan descendencia fértil, y tiene excepciones conocidas.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.jerarquia_linneana'],
        },
      ],
      hojas: [
        {
          slug: 'animales.como-se-nombran.1',
          titulo_es: 'Un bicho, cinco nombres',
          bajada_es: 'Por qué el nombre común no alcanza.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.nombre_comun_confunde', 'animales.nomenclatura_binomial'],
        },
        {
          slug: 'animales.como-se-nombran.2',
          titulo_es: 'Cajas dentro de cajas',
          bajada_es: 'La jerarquía, de dominio a especie.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.jerarquia_linneana', 'animales.nomenclatura_binomial'],
        },
        {
          slug: 'animales.como-se-nombran.3',
          titulo_es: 'Parecerse no es ser pariente',
          bajada_es: 'El delfín, la vaca y el tiburón.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.arbol_filogenetico', 'animales.especie_biologica'],
        },
      ],
    },

    {
      slug: 'animales.quien-come-a-quien',
      anillo: 1,
      titulo_es: 'Quién come a quién',
      bajada_es: 'Redes tróficas, energía y por qué hay pocos depredadores.',
      icono: 'Network',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'animales.cadena_vs_red',
          titulo_es: 'Cadena o red',
          enunciado_es:
            'Una cadena trófica es una línea simple; en la realidad casi todos comen varias cosas y son comidos por varias, así que es una red.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.tipos_de_alimentacion'],
        },
        {
          slug: 'animales.niveles_troficos',
          titulo_es: 'Los niveles tróficos',
          enunciado_es:
            'Productores, consumidores primarios, secundarios y terciarios, y descomponedores cerrando el circuito.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cadena_vs_red'],
        },
        {
          slug: 'animales.regla_del_diez',
          titulo_es: 'La regla del 10 %',
          enunciado_es:
            'De un nivel al siguiente se transmite alrededor de una décima parte de la energía: por eso hay muchísimos herbívoros y muy pocos grandes depredadores.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: 0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.niveles_troficos'],
        },
        {
          slug: 'animales.descomponedores',
          titulo_es: 'Los que cierran el ciclo',
          enunciado_es:
            'Hongos, bacterias e invertebrados del suelo devuelven los nutrientes al sistema. Sin ellos, todo se detendría bajo una pila de restos.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.niveles_troficos', 'tronco.ciclos_materia'],
        },
        {
          slug: 'animales.bioacumulacion',
          titulo_es: 'Bioacumulación',
          enunciado_es:
            'Algunas sustancias no se eliminan y se van juntando en el cuerpo de un organismo a lo largo de su vida.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.niveles_troficos'],
        },
        {
          slug: 'animales.biomagnificacion',
          titulo_es: 'Biomagnificación',
          enunciado_es:
            'Como cada nivel se come muchos individuos del anterior, esas sustancias se concentran cada vez más a medida que se sube en la red trófica.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.bioacumulacion', 'animales.regla_del_diez'],
        },
      ],
      hojas: [
        {
          slug: 'animales.quien-come-a-quien.1',
          titulo_es: 'No es una línea',
          bajada_es: 'De la cadena a la red.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.cadena_vs_red', 'animales.niveles_troficos'],
        },
        {
          slug: 'animales.quien-come-a-quien.2',
          titulo_es: 'Por qué hay pocos pumas',
          bajada_es: 'La regla del 10 %, explicada con el pastizal.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.regla_del_diez', 'animales.niveles_troficos'],
        },
        {
          slug: 'animales.quien-come-a-quien.3',
          titulo_es: 'Los que limpian',
          bajada_es: 'Descomponedores y el cierre del ciclo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.descomponedores', 'animales.cadena_vs_red'],
        },
        {
          slug: 'animales.quien-come-a-quien.4',
          titulo_es: 'Lo que se va concentrando',
          bajada_es: 'Bioacumulación y biomagnificación.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.bioacumulacion', 'animales.biomagnificacion'],
        },
      ],
    },

    {
      slug: 'animales.vivir-con-otros',
      anillo: 1,
      titulo_es: 'Vivir con otros',
      bajada_es: 'Mutualismo, competencia, y quienes polinizan.',
      icono: 'Flower2',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'animales.relaciones_interespecificas',
          titulo_es: 'Las formas de convivir',
          enunciado_es:
            'Mutualismo (ganan los dos), comensalismo (uno gana y al otro le da igual), parasitismo (uno gana a costa del otro), competencia y depredación.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.habitat_vs_nicho'],
        },
        {
          slug: 'animales.polinizacion',
          titulo_es: 'Polinización',
          enunciado_es:
            'Muchísimas plantas necesitan que un animal lleve el polen de una flor a otra: es un mutualismo del que depende buena parte de lo que comemos.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.relaciones_interespecificas'],
        },
        {
          slug: 'animales.polinizadores_nativos',
          titulo_es: 'Los polinizadores nativos',
          enunciado_es:
            'Además de la abeja de miel están las abejas sin aguijón como la yateí y los abejorros nativos, que polinizan plantas que la abeja europea no toca.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.polinizacion'],
        },
        {
          slug: 'animales.bombus_dahlbomii',
          titulo_es: 'El abejorro patagónico',
          enunciado_es:
            'El Bombus dahlbomii, el abejorro nativo más grande de la Patagonia, retrocedió fuertemente tras la introducción de abejorros europeos para polinización comercial.',
          detalle_es: null,
          fuente: 'invasoras-mayds',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['animales.polinizadores_nativos'],
        },
        {
          slug: 'animales.zoocoria',
          titulo_es: 'Semillas que viajan en animales',
          enunciado_es:
            'Muchos frutos existen para que un animal se los coma y deje la semilla lejos: sin esos animales, la planta no se dispersa.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.relaciones_interespecificas'],
        },
        {
          slug: 'animales.murcielagos_urbanos',
          titulo_es: 'Los murciélagos de tu barrio',
          enunciado_es:
            'Los murciélagos urbanos de Buenos Aires son insectívoros: comen miles de mosquitos por noche y se orientan por ecolocalización con una precisión extraordinaria.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.tipos_de_alimentacion'],
          misconceptions: [
            {
              slug: 'animales.mito_murcielagos',
              creencia_es: 'Los murciélagos son ratas voladoras, se te enredan en el pelo y chupan sangre.',
              correccion_es:
                'La fama viene del cine y de que vuelan de noche, cuando no se los ve bien. Los murciélagos urbanos argentinos son insectívoros y controlan mosquitos; se orientan por ecolocalización con precisión milimétrica, así que enredarse en un pelo es justo lo que no les pasa. De más de 1.400 especies en el mundo, solo tres se alimentan de sangre.',
              fuente: 'sib-apn',
            },
          ],
        },
        {
          slug: 'animales.sapos_y_aranas',
          titulo_es: 'Sapos y arañas trabajan gratis',
          enunciado_es:
            'Los sapos y las arañas de casa son depredadores de insectos: donde están ellos hay menos mosquitos, moscas y cucarachas.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.tipos_de_alimentacion'],
          misconceptions: [
            {
              slug: 'animales.mito_sapos_aranas',
              creencia_es: 'Los sapos causan verrugas y a las arañas de casa hay que matarlas.',
              correccion_es:
                'Son dos creencias viejas que se repiten sin pensarlas. Las verrugas las causa un virus, no un sapo. Y las arañas de casa comen justamente los insectos que sí transmiten enfermedades: matarlas te deja peor que antes.',
              fuente: 'sib-apn',
            },
          ],
        },
      ],
      hojas: [
        {
          slug: 'animales.vivir-con-otros.1',
          titulo_es: 'Cinco maneras de convivir',
          bajada_es: 'Del mutualismo a la depredación.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.relaciones_interespecificas', 'animales.zoocoria'],
        },
        {
          slug: 'animales.vivir-con-otros.2',
          titulo_es: 'Quién poliniza lo que comés',
          bajada_es: 'Abejas nativas, abejorros y la yateí.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.polinizacion', 'animales.polinizadores_nativos'],
        },
        {
          slug: 'animales.vivir-con-otros.3',
          titulo_es: 'Mala fama, buen trabajo',
          bajada_es: 'Murciélagos, sapos y arañas.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.murcielagos_urbanos', 'animales.sapos_y_aranas'],
        },
        {
          slug: 'animales.vivir-con-otros.4',
          titulo_es: 'Un abejorro que se fue',
          bajada_es: 'Qué pasó con el Bombus dahlbomii.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['animales.bombus_dahlbomii', 'animales.polinizadores_nativos'],
        },
      ],
    },

    {
      slug: 'animales.piezas-clave',
      anillo: 2,
      titulo_es: 'Piezas clave',
      bajada_es: 'Especies que sostienen más de lo que ocupan.',
      icono: 'Key',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'animales.especie_clave',
          titulo_es: 'Especie clave',
          enunciado_es:
            'Es la que tiene un efecto sobre el ecosistema mucho mayor que su abundancia: si se va, el sistema se reorganiza entero.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.cadena_vs_red', 'tronco.todo_esta_conectado'],
        },
        {
          slug: 'animales.cascada_trofica',
          titulo_es: 'Cascada trófica',
          enunciado_es:
            'Cuando cambia el nivel de arriba, el efecto baja por toda la red: sacar un depredador puede terminar cambiando la vegetación.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.especie_clave'],
        },
        {
          slug: 'animales.top_down_bottom_up',
          titulo_es: 'Desde arriba o desde abajo',
          enunciado_es:
            'Un sistema puede estar controlado por los depredadores (top-down) o por la disponibilidad de alimento y nutrientes (bottom-up). Casi siempre es una mezcla.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 2,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['animales.cascada_trofica'],
        },
        {
          slug: 'animales.ingenieros_del_ecosistema',
          titulo_es: 'Ingenieros del ecosistema',
          enunciado_es:
            'Algunas especies modifican físicamente el ambiente y crean hábitat para otras: el carpincho abre caminos en el humedal, el tuco-tuco airea el suelo.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.especie_clave'],
        },
        {
          slug: 'animales.paraguas_bandera',
          titulo_es: 'Paraguas, bandera e indicadora',
          enunciado_es:
            'Una especie paraguas protege a muchas otras si se protege su territorio; una bandera moviliza apoyo; una indicadora avisa cómo está el ambiente.',
          detalle_es: 'El yaguareté es las tres cosas a la vez.',
          fuente: 'rewilding-argentina',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.especie_clave'],
        },
        {
          slug: 'animales.especies_indicadoras',
          titulo_es: 'Bichos que miden el ambiente',
          enunciado_es:
            'Los líquenes, los anfibios y los macroinvertebrados de arroyo son sensibles a la contaminación: encontrarlos o no dice cómo está el lugar.',
          detalle_es: null,
          fuente: 'argentinat',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.paraguas_bandera'],
        },
      ],
      hojas: [
        {
          slug: 'animales.piezas-clave.1',
          titulo_es: 'Pocas y decisivas',
          bajada_es: 'Qué hace clave a una especie clave.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.especie_clave', 'animales.ingenieros_del_ecosistema'],
        },
        {
          slug: 'animales.piezas-clave.2',
          titulo_es: 'El efecto que baja',
          bajada_es: 'Cascadas tróficas, con ejemplos.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.cascada_trofica', 'animales.top_down_bottom_up'],
        },
        {
          slug: 'animales.piezas-clave.3',
          titulo_es: 'Tres roles, un yaguareté',
          bajada_es: 'Paraguas, bandera e indicadora.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.paraguas_bandera', 'animales.especies_indicadoras'],
        },
      ],
    },

    {
      slug: 'animales.los-que-viajan',
      anillo: 2,
      titulo_es: 'Los que viajan',
      bajada_es: 'Migraciones que empiezan o terminan en la Argentina.',
      icono: 'Plane',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'animales.que_es_migrar',
          titulo_es: 'Qué es migrar',
          enunciado_es:
            'Es moverse de forma regular entre dos zonas, siguiendo la comida o el clima, y volver. No es lo mismo que dispersarse una vez.',
          detalle_es: null,
          fuente: 'aves-argentinas',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.habitat_vs_nicho'],
        },
        {
          slug: 'animales.playero_rojizo',
          titulo_es: 'El playero rojizo',
          enunciado_es:
            'Viaja entre Tierra del Fuego y el Ártico canadiense todos los años, y depende de unos pocos sitios de descanso donde recupera peso.',
          detalle_es: null,
          fuente: 'aves-argentinas-amenazadas',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.que_es_migrar'],
        },
        {
          slug: 'animales.samborombon',
          titulo_es: 'La bahía de Samborombón',
          enunciado_es:
            'Es una parada clave para chorlos y playeros migratorios: un humedal costero bonaerense del que depende gente que vuela medio continente.',
          detalle_es: null,
          fuente: 'aves-argentinas',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.playero_rojizo'],
        },
        {
          slug: 'animales.ballena_franca',
          titulo_es: 'La ballena franca austral',
          enunciado_es:
            'Usa Península Valdés como área de cría y se alimenta mucho más al sur: su recuperación es uno de los grandes casos de éxito de conservación del país.',
          detalle_es: null,
          fuente: 'sarem-2019',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.que_es_migrar'],
        },
        {
          slug: 'animales.eslabon_debil',
          titulo_es: 'Una ruta vale lo que su eslabón más débil',
          enunciado_es:
            'Si se degrada un solo sitio de descanso, toda la ruta migratoria falla, aunque el resto esté perfecto.',
          detalle_es: null,
          fuente: 'aves-argentinas',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['animales.samborombon', 'tronco.escala_local_global'],
        },
      ],
      hojas: [
        {
          slug: 'animales.los-que-viajan.1',
          titulo_es: 'Ir y volver',
          bajada_es: 'Qué cuenta como migración.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['animales.que_es_migrar', 'animales.ballena_franca'],
        },
        {
          slug: 'animales.los-que-viajan.2',
          titulo_es: 'De Tierra del Fuego al Ártico',
          bajada_es: 'El viaje del playero rojizo.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['animales.playero_rojizo', 'animales.samborombon'],
        },
        {
          slug: 'animales.los-que-viajan.3',
          titulo_es: 'Una sola parada rota',
          bajada_es: 'Por qué la ruta entera depende de un humedal.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['animales.eslabon_debil', 'animales.samborombon'],
        },
      ],
    },
  ],
};
