// Rama `ciencia` — cómo se sabe lo que se sabe, y cómo sumar tus propios datos.
// Fuente: ACADEMIA/research/03-environmental-curriculum.md §2.13 y §3.5, más §6
// para edad. Mitos asignados: 19 (el clima siempre cambió) y 20 (un invierno
// frío desmiente el calentamiento).
//
// Es la rama de NAAEE Strand 1 (indagación, análisis e interpretación) y la que
// le da a todo el resto del árbol su respuesta a "¿y vos cómo lo sabés?".

export default {
  rama: 'ciencia',
  gajos: [
    {
      slug: 'ciencia.mirar-bien',
      anillo: 1,
      titulo_es: 'Mirar bien',
      bajada_es: 'Observar es una habilidad, y se entrena.',
      icono: 'Eye',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'ciencia.registro_completo',
            titulo_es: 'Qué, dónde, cuándo y quién',
          enunciado_es:
            'Una observación sirve como dato cuando dice qué se vio, dónde, cuándo y quién la registró. Sin esos cuatro campos es una anécdota.',
          detalle_es: null,
          fuente: 'gbif',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.observacion_vs_inferencia'],
        },
        {
          slug: 'ciencia.darwin_core',
          titulo_es: 'Darwin Core',
          enunciado_es:
            'Es el estándar que define esos campos mínimos para que un registro hecho en Berazategui se pueda combinar con uno hecho en Noruega.',
          detalle_es: null,
          fuente: 'gbif',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.registro_completo'],
        },
        {
          slug: 'ciencia.foto_testigo',
          titulo_es: 'La foto testigo',
          enunciado_es:
            'Una foto convierte tu identificación en algo que otra persona puede revisar: por eso los registros con imagen valen más que los que solo tienen un nombre.',
          detalle_es: null,
          fuente: 'argentinat',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.registro_completo'],
        },
        {
          slug: 'ciencia.esfuerzo_de_observacion',
          titulo_es: 'Cuánto miraste también es dato',
          enunciado_es:
            'Anotar cuánto tiempo estuviste buscando cambia todo: "cero golondrinas en dos horas" dice algo; "cero golondrinas" no dice nada.',
          detalle_es: null,
          fuente: 'ebird',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.registro_completo'],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.mirar-bien.1',
          titulo_es: 'Los cuatro campos',
          bajada_es: 'Lo mínimo para que una observación sea un dato.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.registro_completo', 'ciencia.foto_testigo'],
        },
        {
          slug: 'ciencia.mirar-bien.2',
          titulo_es: 'Que otro lo pueda revisar',
          bajada_es: 'Por qué la foto cambia el peso de tu registro.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.foto_testigo', 'ciencia.registro_completo'],
        },
        {
          slug: 'ciencia.mirar-bien.3',
          titulo_es: 'El cero que sí informa',
          bajada_es: 'Registrar el esfuerzo, no solo el hallazgo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.esfuerzo_de_observacion', 'ciencia.darwin_core'],
        },
      ],
    },

    {
      slug: 'ciencia.sumar-datos',
      anillo: 1,
      titulo_es: 'Sumar tus datos',
      bajada_es: 'Ciencia ciudadana: dónde cargar lo que viste.',
      icono: 'Binoculars',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'ciencia.que_es_ciencia_ciudadana',
          titulo_es: 'Qué es la ciencia ciudadana',
          enunciado_es:
            'Es investigación real hecha con datos que aporta cualquiera: la escala que consigue un grupo grande de personas no la consigue ningún equipo solo.',
          detalle_es: null,
          fuente: 'argentinat',
          anillo: 1,
          dificultad_base: -0.8,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'ciencia.argentinat',
          titulo_es: 'ArgentiNat',
          enunciado_es:
            'Cargás una foto con fecha y lugar, la comunidad ayuda a identificarla, y si alcanza consenso el registro pasa a calidad investigativa y llega a GBIF.',
          detalle_es: null,
          fuente: 'argentinat',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.que_es_ciencia_ciudadana', 'ciencia.foto_testigo'],
        },
        {
          slug: 'ciencia.ebird_y_coas',
          titulo_es: 'eBird y los COA',
          enunciado_es:
            'Los Clubes de Observadores de Aves de Aves Argentinas salen a campo con protocolo y cargan sus listados en eBird: la Reserva Ecológica es uno de los sitios más registrados del país.',
          detalle_es: null,
          fuente: 'ebird',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.que_es_ciencia_ciudadana'],
        },
        {
          slug: 'ciencia.censos_coordinados',
          titulo_es: 'Los censos coordinados',
          enunciado_es:
            'Cuando mucha gente cuenta lo mismo el mismo día —como en el Censo Neotropical de Aves Acuáticas— se obtiene una foto simultánea imposible de conseguir de otra forma.',
          detalle_es: null,
          fuente: 'aves-argentinas',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.ebird_y_coas'],
        },
        {
          slug: 'ciencia.gbif_agrega',
          titulo_es: 'Dónde termina tu registro',
          enunciado_es:
            'GBIF junta registros de todo el mundo publicados con el mismo estándar, y ahí es donde tu observación de una plaza puede entrar en un estudio.',
          detalle_es: null,
          fuente: 'gbif',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.darwin_core', 'ciencia.argentinat'],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.sumar-datos.1',
          titulo_es: 'Ciencia con vos adentro',
          bajada_es: 'Qué es y por qué funciona.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.que_es_ciencia_ciudadana', 'ciencia.argentinat'],
        },
        {
          slug: 'ciencia.sumar-datos.2',
          titulo_es: 'Salir con protocolo',
          bajada_es: 'Los COA, eBird y una salida bien registrada.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.ebird_y_coas', 'ciencia.censos_coordinados'],
        },
        {
          slug: 'ciencia.sumar-datos.3',
          titulo_es: 'De tu plaza a un estudio',
          bajada_es: 'El camino completo de un registro.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.gbif_agrega', 'ciencia.argentinat'],
        },
      ],
    },

    {
      slug: 'ciencia.medir-el-ambiente',
      anillo: 1,
      titulo_es: 'Medir el ambiente',
      bajada_es: 'Herramientas que convierten un lugar en números.',
      icono: 'Activity',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'ciencia.bioindicadores',
          titulo_es: 'Bichos que miden',
          enunciado_es:
            'Algunos organismos solo viven donde se cumplen ciertas condiciones: encontrarlos —o no— dice cómo está el ambiente sin necesidad de un laboratorio.',
          detalle_es: 'Los líquenes indican calidad de aire; los macroinvertebrados, calidad de agua.',
          fuente: 'argentinat',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.que_es_ecosistema'],
        },
        {
          slug: 'ciencia.camaras_trampa',
          titulo_es: 'Cámaras trampa',
          enunciado_es:
            'Una cámara que se dispara con el movimiento registra fauna esquiva sin que nadie esté presente, y de noche.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'ciencia.bioacustica',
          titulo_es: 'Escuchar en vez de mirar',
          enunciado_es:
            'Grabar el paisaje sonoro permite identificar especies por su canto, incluso las que nunca se dejan ver.',
          detalle_es: null,
          fuente: 'sib-apn',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.camaras_trampa'],
        },
        {
          slug: 'ciencia.edna',
          titulo_es: 'ADN ambiental',
          enunciado_es:
            'Un litro de agua de un arroyo lleva rastros de ADN de casi todo lo que pasó por ahí: se puede saber qué especies hay sin ver ni capturar ninguna.',
          detalle_es: null,
          fuente: 'gbif',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.bioindicadores'],
        },
        {
          slug: 'ciencia.teledeteccion',
          titulo_es: 'Mirar desde arriba',
          enunciado_es:
            'Las imágenes satelitales permiten seguir el desmonte, los incendios o la sequía en el tiempo, y comparar el mismo lugar entre dos fechas.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: [],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.medir-el-ambiente.1',
          titulo_es: 'Organismos que informan',
          bajada_es: 'Líquenes, macroinvertebrados y lo que dicen.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.bioindicadores', 'ciencia.camaras_trampa'],
        },
        {
          slug: 'ciencia.medir-el-ambiente.2',
          titulo_es: 'Sin estar ahí',
          bajada_es: 'Cámaras, grabadoras y ADN en el agua.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.bioacustica', 'ciencia.edna'],
        },
        {
          slug: 'ciencia.medir-el-ambiente.3',
          titulo_es: 'El mismo lugar, dos fechas',
          bajada_es: 'Qué se ve desde un satélite.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.teledeteccion', 'ciencia.camaras_trampa'],
        },
      ],
    },

    {
      slug: 'ciencia.leer-un-grafico',
      anillo: 1,
      titulo_es: 'Leer un gráfico',
      bajada_es: 'Dónde miran los ojos y dónde está la trampa.',
      icono: 'LineChart',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'ciencia.ejes_y_escalas',
          titulo_es: 'Mirá los ejes',
          enunciado_es:
            'Un eje que no arranca en cero, o una escala logarítmica sin avisar, cambian por completo la forma de una curva sin cambiar un solo dato.',
          detalle_es: null,
          fuente: 'chequeado',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.leer_un_numero'],
        },
        {
          slug: 'ciencia.serie_vs_punto',
          titulo_es: 'Una serie, no un punto',
          enunciado_es:
            'Un dato aislado casi nunca significa algo: lo que informa es la serie, porque muestra si eso es lo normal o la excepción.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.ejes_y_escalas'],
          misconceptions: [
            {
              slug: 'ciencia.mito_invierno_frio',
              creencia_es: 'Este invierno hizo muchísimo frío, así que el calentamiento global no puede ser cierto.',
              correccion_es:
                'Es tentador porque se apoya en algo que uno vivió en el cuerpo. Pero tiempo no es clima: una ola de frío es un punto en una serie ruidosa, y la tendencia se mide en décadas y sobre todo el planeta.',
              fuente: 'ipcc-ar6',
            },
          ],
        },
        {
          slug: 'ciencia.barras_de_error',
          titulo_es: 'Las barras de error',
          enunciado_es:
            'Una barra de error dice cuánta confianza hay en el número. Un dato con barras es más honesto que uno sin ellas, no menos confiable.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.incertidumbre'],
        },
        {
          slug: 'ciencia.muestreo_y_sesgo',
          titulo_es: 'A quién mediste',
          enunciado_es:
            'Si la muestra no representa a la población, el resultado describe a la muestra y a nadie más. En ciencia ciudadana el sesgo típico es medir donde es cómodo llegar.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.esfuerzo_de_observacion'],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.leer-un-grafico.1',
          titulo_es: 'La forma miente, los ejes no',
          bajada_es: 'Cómo se estira una curva sin tocar los datos.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.ejes_y_escalas', 'ciencia.serie_vs_punto'],
        },
        {
          slug: 'ciencia.leer-un-grafico.2',
          titulo_es: 'Un día no es una tendencia',
          bajada_es: 'Tiempo, clima y el invierno que "desmiente" todo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.serie_vs_punto', 'ciencia.ejes_y_escalas'],
        },
        {
          slug: 'ciencia.leer-un-grafico.3',
          titulo_es: 'Cuánto se sabe',
          bajada_es: 'Barras de error y sesgo de muestreo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.barras_de_error', 'ciencia.muestreo_y_sesgo'],
        },
      ],
    },

    {
      slug: 'ciencia.como-se-construye',
      anillo: 2,
      titulo_es: 'Cómo se construye el conocimiento',
      bajada_es: 'Revisión, réplica y consenso.',
      icono: 'BookOpen',
      age_groups: ['teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'ciencia.revision_por_pares',
          titulo_es: 'Revisión por pares',
          enunciado_es:
            'Antes de publicarse, un trabajo lo revisan especialistas que no participaron. No garantiza que sea correcto: garantiza que pasó por un filtro.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.evidencia_y_fuente'],
        },
        {
          slug: 'ciencia.preprint',
          titulo_es: 'Preprint',
          enunciado_es:
            'Un preprint es un trabajo publicado antes de la revisión: es útil para ir rápido y hay que leerlo sabiendo que todavía no pasó el filtro.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.revision_por_pares'],
        },
        {
          slug: 'ciencia.replica',
          titulo_es: 'Que se pueda repetir',
          enunciado_es:
            'Un resultado vale más cuando otro equipo, con otros datos, llega a lo mismo. La réplica es lo que separa un hallazgo de una casualidad.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.revision_por_pares'],
        },
        {
          slug: 'ciencia.atribucion_climatica',
          titulo_es: 'Cómo se sabe que es nuestro',
          enunciado_es:
            'La atribución compara lo que se observa con modelos que corren con y sin emisiones humanas: la diferencia entre esos dos mundos es la evidencia.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 3,
          dificultad_base: 0.9,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.replica', 'tronco.consenso_cientifico'],
          misconceptions: [
            {
              slug: 'ciencia.mito_clima_siempre_cambio',
              creencia_es: 'El clima siempre cambió, así que lo de ahora también es natural.',
              correccion_es:
                'La primera mitad es cierta y por eso convence: el clima varió muchas veces. Lo que cambia el argumento son la velocidad y la causa. El ritmo actual no tiene precedente en los registros y los estudios de atribución señalan las emisiones humanas, no un ciclo natural.',
              fuente: 'ipcc-ar6',
            },
          ],
        },
        {
          slug: 'ciencia.escenarios_ssp',
          titulo_es: 'Los escenarios no son predicciones',
          enunciado_es:
            'Un escenario climático dice "si pasa esto, entonces aquello". No predice el futuro: describe consecuencias de decisiones que todavía no se tomaron.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.atribucion_climatica'],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.como-se-construye.1',
          titulo_es: 'Quién lo revisó',
          bajada_es: 'Pares, preprints y qué significa cada cosa.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.revision_por_pares', 'ciencia.preprint'],
        },
        {
          slug: 'ciencia.como-se-construye.2',
          titulo_es: 'Que otro llegue a lo mismo',
          bajada_es: 'La réplica como prueba de fuego.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.replica', 'ciencia.revision_por_pares'],
        },
        {
          slug: 'ciencia.como-se-construye.3',
          titulo_es: 'Dos mundos comparados',
          bajada_es: 'Cómo se atribuye el cambio climático.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.atribucion_climatica', 'ciencia.escenarios_ssp'],
        },
      ],
    },

    {
      slug: 'ciencia.desinformacion',
      anillo: 2,
      titulo_es: 'Desinformación ambiental',
      bajada_es: 'Cómo se arma una duda y cómo se desarma.',
      icono: 'ShieldQuestion',
      age_groups: ['teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'ciencia.fabricar_duda',
          titulo_es: 'Fabricar duda',
          enunciado_es:
            'No hace falta convencer a nadie de lo contrario: alcanza con instalar que "todavía se discute" para frenar cualquier decisión.',
          detalle_es: null,
          fuente: 'chequeado',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.consenso_cientifico'],
        },
        {
          slug: 'ciencia.cherry_picking',
          titulo_es: 'Elegir el pedacito que conviene',
          enunciado_es:
            'Recortar una serie larga justo donde la curva hace lo que uno quiere es la técnica más común y la más fácil de detectar: pedí la serie completa.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.serie_vs_punto'],
        },
        {
          slug: 'ciencia.falso_equilibrio',
          titulo_es: 'Falso equilibrio',
          enunciado_es:
            'Poner a dos personas a discutir de igual a igual sugiere que la evidencia está repartida mitad y mitad, aunque no lo esté.',
          detalle_es: null,
          fuente: 'chequeado',
          anillo: 2,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.fabricar_duda'],
        },
        {
          slug: 'ciencia.como_verificar',
          titulo_es: 'Cómo verificar en cinco minutos',
          enunciado_es:
            'Buscá la fuente primaria, fijate la fecha, mirá si alguien independiente lo verificó y preguntate a quién le conviene que lo creas.',
          detalle_es: null,
          fuente: 'chequeado',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.evidencia_y_fuente'],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.desinformacion.1',
          titulo_es: 'La duda como producto',
          bajada_es: 'Para qué sirve decir "todavía se discute".',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.fabricar_duda', 'ciencia.falso_equilibrio'],
        },
        {
          slug: 'ciencia.desinformacion.2',
          titulo_es: 'Pedí la serie completa',
          bajada_es: 'El recorte que cambia la conclusión.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.cherry_picking', 'ciencia.serie_vs_punto'],
        },
        {
          slug: 'ciencia.desinformacion.3',
          titulo_es: 'Cinco minutos y cuatro preguntas',
          bajada_es: 'Un método rápido que funciona.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.como_verificar', 'ciencia.cherry_picking'],
          // El gajo entero es teen+ porque analiza campañas de desinformación;
          // esta hoja hereda esa edad aunque el método de verificación en sí
          // sirva desde chico.
        },
      ],
    },

    {
      slug: 'ciencia.investigar-vos',
      anillo: 2,
      titulo_es: 'Investigar vos',
      bajada_es: 'De una pregunta a un resultado que se puede mostrar.',
      icono: 'FlaskConical',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'ciencia.pregunta_investigable',
          titulo_es: 'Una pregunta investigable',
          enunciado_es:
            'Una buena pregunta se puede responder con algo que puedas medir. "¿Está mal el río?" no; "¿cuántos macroinvertebrados hay por muestra en estos dos puntos?" sí.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.observacion_vs_inferencia'],
        },
        {
          slug: 'ciencia.variable_y_control',
          titulo_es: 'Variable y control',
          enunciado_es:
            'Para saber si algo influye hay que compararlo contra un caso igual donde eso no pasa. Sin control, no sabés si el cambio lo causó lo que vos hiciste.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.pregunta_investigable', 'tronco.correlacion_causalidad'],
        },
        {
          slug: 'ciencia.precision_vs_exactitud',
          titulo_es: 'Precisión y exactitud',
          enunciado_es:
            'Precisión es que las mediciones se parezcan entre sí; exactitud es que se parezcan al valor real. Se puede ser muy preciso y estar sistemáticamente equivocado.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.barras_de_error'],
        },
        {
          slug: 'ciencia.mostrar_resultados',
          titulo_es: 'Mostrar lo que encontraste',
          enunciado_es:
            'Un resultado se comunica con el método adelante: qué mediste, cómo, cuántas veces y qué no pudiste controlar. Eso es lo que lo vuelve creíble.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['ciencia.variable_y_control'],
        },
      ],
      hojas: [
        {
          slug: 'ciencia.investigar-vos.1',
          titulo_es: 'Preguntar algo medible',
          bajada_es: 'Cómo se afila una pregunta.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['ciencia.pregunta_investigable', 'ciencia.variable_y_control'],
        },
        {
          slug: 'ciencia.investigar-vos.2',
          titulo_es: 'Comparar contra algo',
          bajada_es: 'Por qué siempre hace falta un control.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['ciencia.variable_y_control', 'ciencia.mostrar_resultados'],
        },
        {
          slug: 'ciencia.investigar-vos.3',
          titulo_es: 'Preciso y equivocado',
          bajada_es: 'La diferencia que arruina mediciones.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['ciencia.precision_vs_exactitud', 'ciencia.mostrar_resultados'],
        },
      ],
    },
  ],
};
