// Rama `comunidad` — lo que se decide entre varios.
// Fuente: ACADEMIA/research/03-environmental-curriculum.md §2.10, §3.4 (leyes) y
// §3.5 (organizaciones), más §6 para edad. El mito 32 (el impacto individual no
// sirve) ya está escrito en tronco.mjs y NO se repite acá.
//
// Es la rama donde vive NAAEE Strand 4 —responsabilidad personal y cívica— y es
// también, según la investigación de eco-ansiedad, el factor protector más
// fuerte para adolescentes: la acción colectiva, no la culpa individual.

export default {
  rama: 'comunidad',
  gajos: [
    {
      slug: 'comunidad.lo-que-es-de-todos',
      anillo: 1,
      titulo_es: 'Lo que es de todos',
      bajada_es: 'Cómo se cuida algo que no tiene un solo dueño.',
      icono: 'Handshake',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'comunidad.bien_comun',
          titulo_es: 'El bien común',
          enunciado_es:
            'Hay cosas que no son de nadie en particular y son de todos a la vez: el aire, una plaza, el agua de un río.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -1.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'comunidad.tragedia_de_los_comunes',
          titulo_es: 'La tragedia de los comunes',
          enunciado_es:
            'Si cada persona usa un recurso compartido pensando solo en su propio beneficio, el recurso se agota aunque a nadie le convenga que se agote.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.bien_comun'],
        },
        {
          slug: 'comunidad.ostrom',
          titulo_es: 'Y cómo se evita',
          enunciado_es:
            'La tragedia no es inevitable: las comunidades que se ponen reglas propias, se controlan entre sí y pueden sancionar, gestionan recursos comunes durante generaciones.',
          detalle_es: 'Es el trabajo por el que Elinor Ostrom ganó el Nobel de Economía.',
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.tragedia_de_los_comunes'],
        },
        {
          slug: 'comunidad.reglas_que_funcionan',
          titulo_es: 'Reglas que funcionan',
          enunciado_es:
            'Una regla ambiental funciona cuando quienes la cumplen participaron en escribirla, la pueden monitorear y ven que a quien no la cumple le pasa algo.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.ostrom'],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.lo-que-es-de-todos.1',
          titulo_es: 'De nadie y de todos',
          bajada_es: 'El aire, la plaza, el río.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.bien_comun', 'comunidad.tragedia_de_los_comunes'],
        },
        {
          slug: 'comunidad.lo-que-es-de-todos.2',
          titulo_es: 'No es inevitable',
          bajada_es: 'Comunidades que sí lo resolvieron.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.ostrom', 'comunidad.tragedia_de_los_comunes'],
        },
        {
          slug: 'comunidad.lo-que-es-de-todos.3',
          titulo_es: 'Qué hace que una regla se cumpla',
          bajada_es: 'Participar, mirar y poder sancionar.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.reglas_que_funcionan', 'comunidad.ostrom'],
        },
      ],
    },

    {
      slug: 'comunidad.tu-barrio',
      anillo: 1,
      titulo_es: 'Tu barrio',
      bajada_es: 'A quién se le reclama y cómo se hace.',
      icono: 'MapPin',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'comunidad.quien_hace_que',
          titulo_es: 'Quién hace qué',
          enunciado_es:
            'La recolección, el arbolado y el alumbrado suelen ser municipales o comunales; el agua y las cloacas, de una empresa o ente; los parques nacionales, de Nación. Saber a quién le corresponde es la mitad del reclamo.',
          detalle_es: null,
          fuente: 'ley-25675-ambiente',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'comunidad.como_se_reclama',
          titulo_es: 'Cómo se hace un reclamo',
          enunciado_es:
            'Un reclamo sirve más cuando tiene lugar exacto, fecha, foto y número de seguimiento: eso lo vuelve rastreable y comparable con otros.',
          detalle_es: 'En la Ciudad de Buenos Aires ese canal es el 147.',
          fuente: 'ley-25831-info',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.quien_hace_que'],
        },
        {
          slug: 'comunidad.comuna_y_junta',
          titulo_es: 'La comuna y su junta',
          enunciado_es:
            'En la Ciudad de Buenos Aires las comunas tienen juntas comunales electas, con reuniones abiertas donde se pueden llevar temas del barrio.',
          detalle_es: null,
          fuente: 'ley-25831-info',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.quien_hace_que'],
        },
        {
          slug: 'comunidad.presupuesto_participativo',
          titulo_es: 'Presupuesto participativo',
          enunciado_es:
            'Algunos municipios dejan que los vecinos decidan en qué se gasta una parte del presupuesto, y ahí entran plazas, arbolado y separación de residuos.',
          detalle_es: null,
          fuente: 'ley-25831-info',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.comuna_y_junta'],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.tu-barrio.1',
          titulo_es: 'A quién le toca',
          bajada_es: 'Municipio, provincia, Nación o empresa.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.quien_hace_que', 'comunidad.como_se_reclama'],
        },
        {
          slug: 'comunidad.tu-barrio.2',
          titulo_es: 'Un reclamo que sirve',
          bajada_es: 'Lugar, fecha, foto y número.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.como_se_reclama', 'comunidad.comuna_y_junta'],
        },
        {
          slug: 'comunidad.tu-barrio.3',
          titulo_es: 'Decidir en qué se gasta',
          bajada_es: 'Presupuesto participativo, en criollo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.presupuesto_participativo', 'comunidad.comuna_y_junta'],
        },
      ],
    },

    {
      slug: 'comunidad.derecho-a-saber',
      anillo: 1,
      titulo_es: 'Derecho a saber',
      bajada_es: 'Pedir información ambiental es un derecho, no un favor.',
      icono: 'FileSearch',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'comunidad.acceso_informacion_25831',
          titulo_es: 'La Ley 25.831',
          enunciado_es:
            'Cualquier persona puede pedirle al Estado información ambiental, sin explicar para qué la quiere y sin acreditar ningún interés.',
          detalle_es: null,
          fuente: 'ley-25831-info',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.acceso_informacion'],
        },
        {
          slug: 'comunidad.escazu_tres_derechos',
          titulo_es: 'Los tres derechos de Escazú',
          enunciado_es:
            'El Acuerdo de Escazú garantiza tres cosas juntas: acceso a la información ambiental, participación en las decisiones y acceso a la justicia.',
          detalle_es: null,
          fuente: 'escazu',
          anillo: 1,
          dificultad_base: 0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.acceso_informacion_25831'],
        },
        {
          slug: 'comunidad.defensores_ambientales',
          titulo_es: 'Quienes defienden el ambiente',
          enunciado_es:
            'Escazú es el primer acuerdo del mundo con obligaciones específicas de protección para las personas que defienden derechos humanos en asuntos ambientales.',
          detalle_es: null,
          fuente: 'escazu',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['comunidad.escazu_tres_derechos'],
        },
        {
          slug: 'comunidad.datos_abiertos',
          titulo_es: 'Datos abiertos',
          enunciado_es:
            'Organismos como ACUMAR publican sus mediciones en portales abiertos: cualquiera puede bajar la serie y mirarla por su cuenta.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.acceso_informacion_25831', 'tronco.evidencia_y_fuente'],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.derecho-a-saber.1',
          titulo_es: 'Preguntar sin dar explicaciones',
          bajada_es: 'Qué te tiene que contestar el Estado.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.acceso_informacion_25831', 'comunidad.escazu_tres_derechos'],
        },
        {
          slug: 'comunidad.derecho-a-saber.2',
          titulo_es: 'Los datos ya están publicados',
          bajada_es: 'Portales abiertos y cómo leerlos.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.datos_abiertos', 'comunidad.acceso_informacion_25831'],
        },
        {
          slug: 'comunidad.derecho-a-saber.3',
          titulo_es: 'Proteger a quien denuncia',
          bajada_es: 'Lo que Escazú agrega y por qué hizo falta.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.defensores_ambientales', 'comunidad.escazu_tres_derechos'],
        },
      ],
    },

    {
      slug: 'comunidad.hacer-juntos',
      anillo: 1,
      titulo_es: 'Hacer juntos',
      bajada_es: 'Huertas, compost, limpiezas y cooperativas.',
      icono: 'Users',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'comunidad.huerta_comunitaria',
          titulo_es: 'La huerta comunitaria',
          enunciado_es:
            'Una huerta compartida produce comida, pero sobre todo produce vecinos que se conocen: es de las formas más rápidas de armar red en un barrio.',
          detalle_es: null,
          fuente: 'inta',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'comunidad.compost_comunitario',
          titulo_es: 'Compostaje comunitario',
          enunciado_es:
            'Una compostera de manzana o de edificio saca del relleno la fracción más pesada de la basura y devuelve tierra a las macetas del barrio.',
          detalle_es: null,
          fuente: 'ley-1854-basura-cero',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.huerta_comunitaria'],
        },
        {
          slug: 'comunidad.cooperativas_recuperadores',
          titulo_es: 'Las cooperativas de recuperadores',
          enunciado_es:
            'En la Ciudad de Buenos Aires los Centros Verdes los operan cooperativas de recuperadores urbanos: son parte del sistema formal de reciclado, no algo aparte.',
          detalle_es: null,
          fuente: 'faccyr',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'comunidad.jornadas_de_limpieza',
          titulo_es: 'Las jornadas de limpieza',
          enunciado_es:
            'Una limpieza de costa o de plaza sirve el doble si además se registra qué se encontró: eso convierte una tarde de trabajo en un dato.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.hacer-juntos.1',
          titulo_es: 'Una huerta hace vecinos',
          bajada_es: 'Lo que crece además de las verduras.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.huerta_comunitaria', 'comunidad.compost_comunitario'],
        },
        {
          slug: 'comunidad.hacer-juntos.2',
          titulo_es: 'Quién recicla de verdad',
          bajada_es: 'Cartoneros, cooperativas y Centros Verdes.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.cooperativas_recuperadores', 'comunidad.compost_comunitario'],
        },
        {
          slug: 'comunidad.hacer-juntos.3',
          titulo_es: 'Limpiar y anotar',
          bajada_es: 'Cómo una limpieza se convierte en evidencia.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.jornadas_de_limpieza', 'comunidad.huerta_comunitaria'],
        },
      ],
    },

    {
      slug: 'comunidad.participar-en-serio',
      anillo: 2,
      titulo_es: 'Participar en serio',
      bajada_es: 'Audiencias, amparos y el fallo que cambió una cuenca.',
      icono: 'Gavel',
      age_groups: ['teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'comunidad.audiencia_publica',
          titulo_es: 'La audiencia pública',
          enunciado_es:
            'Antes de aprobar obras o normas de impacto ambiental hay instancias donde cualquiera puede inscribirse y exponer. Lo que se dice queda registrado y hay que responderlo.',
          detalle_es: 'No es vinculante, y eso también es parte de entenderla.',
          fuente: 'ley-25675-ambiente',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.escazu_tres_derechos'],
        },
        {
          slug: 'comunidad.evaluacion_impacto',
          titulo_es: 'Evaluación de impacto ambiental',
          enunciado_es:
            'Un proyecto grande tiene que estimar sus impactos antes de hacerse, y ese estudio es público: es el documento sobre el que se discute en la audiencia.',
          detalle_es: null,
          fuente: 'ley-25675-ambiente',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.audiencia_publica'],
        },
        {
          slug: 'comunidad.amparo_ambiental',
          titulo_es: 'El amparo ambiental',
          enunciado_es:
            'Cuando un daño ambiental afecta a un colectivo, la ley permite que alguien reclame en nombre de todos: el bien afectado es común, así que la legitimación también.',
          detalle_es: null,
          fuente: 'ley-25675-ambiente',
          anillo: 2,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.evaluacion_impacto', 'tronco.derecho_ambiente_sano'],
        },
        {
          slug: 'comunidad.fallo_mendoza_caso',
          titulo_es: 'El fallo Mendoza como caso testigo',
          enunciado_es:
            'En 2008 la Corte Suprema ordenó sanear la Cuenca Matanza-Riachuelo y creó una autoridad tripartita para hacerlo: ACUMAR nació de una sentencia.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.amparo_ambiental'],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.participar-en-serio.1',
          titulo_es: 'Anotarse y hablar',
          bajada_es: 'Qué es y qué no es una audiencia pública.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.audiencia_publica', 'comunidad.evaluacion_impacto'],
        },
        {
          slug: 'comunidad.participar-en-serio.2',
          titulo_es: 'Reclamar por todos',
          bajada_es: 'Por qué el daño colectivo tiene una puerta propia.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.amparo_ambiental', 'comunidad.fallo_mendoza_caso'],
        },
        {
          slug: 'comunidad.participar-en-serio.3',
          titulo_es: 'Una sentencia que creó un organismo',
          bajada_es: 'Mendoza, ACUMAR y lo que siguió.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.fallo_mendoza_caso', 'comunidad.audiencia_publica'],
        },
      ],
    },

    {
      slug: 'comunidad.justicia-ambiental',
      anillo: 2,
      titulo_es: 'Justicia ambiental',
      bajada_es: 'El daño no se reparte parejo, y eso no es casualidad.',
      icono: 'Scale',
      age_groups: ['teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'comunidad.quien_pone_el_cuerpo',
          titulo_es: 'Quién pone el cuerpo',
          enunciado_es:
            'Los basurales, las industrias contaminantes y las zonas inundables casi nunca están donde vive quien decide: el costo ambiental suele caer sobre los barrios más pobres.',
          detalle_es: null,
          fuente: 'acumar',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['tronco.individual_y_colectivo'],
        },
        {
          slug: 'comunidad.pueblos_indigenas_consulta',
          titulo_es: 'Consulta previa, libre e informada',
          enunciado_es:
            'Cuando un proyecto afecta territorios de pueblos indígenas, el Convenio 169 de la OIT exige consultarlos antes, con información completa y sin presión.',
          detalle_es: null,
          fuente: 'ley-27621-eai',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.escazu_tres_derechos'],
        },
        {
          slug: 'comunidad.saberes_locales',
          titulo_es: 'Los saberes que ya estaban',
          enunciado_es:
            'La Ley 27.621 incorpora explícitamente los saberes de los pueblos indígenas a la educación ambiental: no como folclore, como conocimiento.',
          detalle_es: null,
          fuente: 'ley-27621-eai',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.educacion_ambiental_ley'],
        },
        {
          slug: 'comunidad.asambleas_socioambientales',
          titulo_es: 'Las asambleas socioambientales',
          enunciado_es:
            'En la Argentina hay una tradición larga de asambleas vecinales que se organizan alrededor de un conflicto ambiental concreto y sostienen el reclamo por años.',
          detalle_es: null,
          fuente: 'escazu',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.quien_pone_el_cuerpo'],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.justicia-ambiental.1',
          titulo_es: 'Dónde se pone lo que molesta',
          bajada_es: 'El mapa del daño no es aleatorio.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.quien_pone_el_cuerpo', 'comunidad.asambleas_socioambientales'],
        },
        {
          slug: 'comunidad.justicia-ambiental.2',
          titulo_es: 'Preguntar antes',
          bajada_es: 'Consulta previa: qué significa "informada".',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.pueblos_indigenas_consulta', 'comunidad.saberes_locales'],
        },
        {
          slug: 'comunidad.justicia-ambiental.3',
          titulo_es: 'Vecinos que no aflojan',
          bajada_es: 'Las asambleas y cómo sostienen un reclamo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.asambleas_socioambientales', 'comunidad.quien_pone_el_cuerpo'],
        },
      ],
    },

    {
      slug: 'comunidad.organizar-una-campana',
      anillo: 2,
      titulo_es: 'Organizar una campaña',
      bajada_es: 'De la bronca a un plan que alguien puede seguir.',
      icono: 'Megaphone',
      // Kid incluido a propósito: organizar un pedido concreto con el curso y
      // saber que preocuparse está bien es justo lo que la investigación sobre
      // eco-ansiedad señala como protector a esta edad.
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'comunidad.un_pedido_concreto',
          titulo_es: 'Un pedido concreto',
          enunciado_es:
            'Una campaña necesita un pedido que alguien identificable pueda conceder: "más conciencia" no se puede firmar, "tres cestos en la plaza" sí.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.quien_hace_que'],
        },
        {
          slug: 'comunidad.mapeo_colectivo',
          titulo_es: 'Mapeo colectivo',
          enunciado_es:
            'Marcar entre varios lo que pasa en un territorio —basurales, faltantes de arbolado, zonas que se inundan— produce evidencia que antes no existía.',
          detalle_es: null,
          fuente: 'argentinat',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.un_pedido_concreto'],
        },
        {
          slug: 'comunidad.alianzas',
          titulo_es: 'Escuela, barrio y municipio',
          enunciado_es:
            'Las campañas que prosperan suelen combinar tres actores: quien tiene el problema, quien tiene la legitimidad y quien tiene la firma.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['comunidad.un_pedido_concreto'],
        },
        {
          slug: 'comunidad.eficacia_colectiva',
          titulo_es: 'La eficacia colectiva',
          enunciado_es:
            'Sentir que un grupo puede lograr algo es lo que sostiene la acción en el tiempo, y es el mejor antídoto que se conoce contra la angustia ambiental.',
          detalle_es:
            'La investigación sobre eco-ansiedad es clara: la agencia y la acción colectiva protegen; el discurso de catástrofe paraliza.',
          fuente: 'ecoansiedad-review',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.individual_y_colectivo'],
        },
        {
          slug: 'comunidad.sentir_y_seguir',
          titulo_es: 'Que te importe está bien',
          enunciado_es:
            'Preocuparse por esto es una respuesta razonable, no un problema personal. Nombrarlo, compartirlo y hacer algo concreto con otros es lo que lo vuelve llevadero.',
          detalle_es: null,
          fuente: 'ecoansiedad-review',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
      ],
      hojas: [
        {
          slug: 'comunidad.organizar-una-campana.1',
          titulo_es: 'Pedir algo que se pueda dar',
          bajada_es: 'La diferencia entre una queja y un pedido.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['comunidad.un_pedido_concreto', 'comunidad.mapeo_colectivo'],
        },
        {
          slug: 'comunidad.organizar-una-campana.2',
          titulo_es: 'Quién tiene la firma',
          bajada_es: 'Armar la alianza mínima que funciona.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['comunidad.alianzas', 'comunidad.un_pedido_concreto'],
        },
        {
          slug: 'comunidad.organizar-una-campana.3',
          titulo_es: 'Sostenerlo en el tiempo',
          bajada_es: 'Por qué hacerlo con otros cansa menos.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['comunidad.eficacia_colectiva', 'comunidad.sentir_y_seguir'],
        },
      ],
    },
  ],
};
