// Rama `consumo` — 30 conceptos, 7 gajos (4 en anillo 1, 3 en anillo 2), 23 hojas.
// Puro dato. Sin lógica. Ver scripts/academia/CONTRATO.md.

export default {
  rama: 'consumo',
  gajos: [
    // ───────────────────────────────────────── anillo 1 ─────────────────────────────────────────
    {
      slug: 'consumo.necesidad-y-deseo',
      anillo: 1,
      titulo_es: 'Necesidad y deseo',
      bajada_es: 'Antes de comprar algo hay una pregunta que cambia todo lo que viene después.',
      icono: 'ShoppingBag',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'consumo.necesidad_vs_deseo',
          titulo_es: 'Necesidad y deseo no son lo mismo',
          enunciado_es:
            'Una necesidad es algo que te falta para vivir bien; un deseo es algo que querés tener. Separar las dos cosas antes de comprar es la decisión ambiental más barata que existe.',
          detalle_es:
            'No se trata de no desear nada. Se trata de saber cuál de las dos está manejando el changuito.',
          fuente: 'unesco-ods',
          anillo: 1,
          dificultad_base: -1.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'consumo.publicidad_y_deseo',
          titulo_es: 'El ciclo del deseo',
          enunciado_es:
            'La publicidad no vende solo objetos: fabrica ganas nuevas cada temporada, y esas ganas se apagan al poco tiempo de comprar.',
          detalle_es:
            'Reconocer el ciclo —ganas, compra, alivio corto, ganas nuevas— no te vuelve inmune, pero te da un segundo de ventaja.',
          fuente: 'unesco-ods',
          anillo: 1,
          dificultad_base: -0.8,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'consumo.necesidad_vs_deseo', fuerza: 0.6 }],
        },
        {
          slug: 'consumo.la_compra_evitada',
          titulo_es: 'La compra que no hacés',
          enunciado_es:
            'Lo que no se fabrica no gasta materiales, agua ni energía: por eso, en la jerarquía de decisiones, la opción de menor impacto casi siempre es la compra que no llegás a hacer.',
          detalle_es: 'Reciclar viene tercero. Primero está no necesitarlo, y después usar menos.',
          fuente: 'yale-reciclaje',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.jerarquia_decisiones'],
        },
        {
          slug: 'consumo.usar_lo_que_ya_tenes',
          titulo_es: 'Lo que ya está en tu casa',
          enunciado_es:
            'El objeto con menos huella suele ser el que ya tenés: cada vez que alargás su uso, evitás que se fabrique otro.',
          detalle_es:
            'Vale para la campera del año pasado, la mochila que te queda del hermano y el celular que todavía anda.',
          fuente: 'ellen-macarthur',
          anillo: 1,
          dificultad_base: -1.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
      ],
      hojas: [
        {
          slug: 'consumo.necesidad-y-deseo.1',
          titulo_es: 'Lo que necesito y lo que quiero',
          bajada_es: 'Dos palabras que parecen sinónimos y no lo son.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.necesidad_vs_deseo', 'consumo.publicidad_y_deseo'],
        },
        {
          slug: 'consumo.necesidad-y-deseo.2',
          titulo_es: 'Cómo se fabrican las ganas',
          bajada_es: 'Quién decide qué te falta, y cuánto le dura el efecto.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.publicidad_y_deseo', 'consumo.la_compra_evitada'],
        },
        {
          slug: 'consumo.necesidad-y-deseo.3',
          titulo_es: 'La opción que no está en la vidriera',
          bajada_es: 'La compra que no hacés y la cosa que ya tenés.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: [
            'consumo.la_compra_evitada',
            'consumo.usar_lo_que_ya_tenes',
            'consumo.necesidad_vs_deseo',
          ],
        },
      ],
    },

    {
      slug: 'consumo.que-dura-y-que-se-arregla',
      anillo: 1,
      titulo_es: 'Lo que dura y lo que se arregla',
      bajada_es: 'Por qué las cosas parecen durar menos que antes, y qué se puede hacer.',
      icono: 'Wrench',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'consumo.vida_util',
          titulo_es: 'Cuánto sirve de verdad',
          enunciado_es:
            'La vida útil es cuánto tiempo un objeto sirve de verdad; no siempre coincide con lo que dura la garantía, ni con lo que dura de moda.',
          detalle_es: null,
          fuente: 'ellen-macarthur',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'consumo.obsolescencia_programada',
          titulo_es: 'Diseñado para durar poco',
          enunciado_es:
            'Hay productos pensados para fallar o quedar desactualizados a los pocos años: una vida útil corta no siempre es mala suerte, a veces es diseño.',
          detalle_es:
            'La contracara también existe: hay fábricas que compiten justamente por durar, y eso se puede elegir.',
          fuente: 'ellen-macarthur',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['consumo.vida_util'],
        },
        {
          slug: 'consumo.obsolescencia_percibida',
          titulo_es: 'Anda bien, pero parece viejo',
          enunciado_es:
            'La obsolescencia percibida no rompe nada: te convence de que lo que tenés quedó viejo aunque funcione perfecto.',
          detalle_es: 'Cambia el color, el borde o el nombre del modelo. El aparato es el mismo.',
          fuente: 'unesco-ods',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['consumo.vida_util', { slug: 'consumo.publicidad_y_deseo', fuerza: 0.6 }],
        },
        {
          slug: 'consumo.costo_por_uso',
          titulo_es: 'El precio dividido por los usos',
          enunciado_es:
            'Dividí el precio por la cantidad de veces que lo vas a usar: ese número compara dos productos mucho mejor que el número de la etiqueta.',
          detalle_es:
            'Una campera cara que usás cientos de veces puede salir menos por uso que una barata que usás tres.',
          fuente: 'unesco-ods',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.leer_un_numero', { slug: 'consumo.vida_util', fuerza: 0.7 }],
        },
        {
          slug: 'consumo.derecho_a_reparar',
          titulo_es: 'Derecho a reparar',
          enunciado_es:
            'El derecho a reparar es que quien compra algo pueda arreglarlo: con repuestos disponibles, manuales abiertos y alguien más que el service oficial.',
          detalle_es:
            'Un objeto que se abre con un destornillador común vive mucho más que uno pegado.',
          fuente: 'ellen-macarthur',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['consumo.vida_util'],
        },
      ],
      hojas: [
        {
          slug: 'consumo.que-dura-y-que-se-arregla.1',
          titulo_es: 'Cuánto dura una cosa',
          bajada_es: 'Vida útil, garantía y moda: tres relojes distintos.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.vida_util', 'consumo.obsolescencia_programada'],
        },
        {
          slug: 'consumo.que-dura-y-que-se-arregla.2',
          titulo_es: 'Funciona, pero parece viejo',
          bajada_es: 'Lo que se rompe y lo que solo te convencen de que se rompió.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.obsolescencia_percibida', 'consumo.vida_util'],
        },
        {
          slug: 'consumo.que-dura-y-que-se-arregla.3',
          titulo_es: 'La cuenta que conviene hacer',
          bajada_es: 'Cómo comparar dos precios sin que te ganen los ceros.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['consumo.costo_por_uso', 'consumo.vida_util'],
        },
        {
          slug: 'consumo.que-dura-y-que-se-arregla.4',
          titulo_es: 'Abrirlo en vez de tirarlo',
          bajada_es: 'Repuestos, manuales y quién tiene permiso de destornillar.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: [
            'consumo.derecho_a_reparar',
            'consumo.obsolescencia_programada',
            'consumo.costo_por_uso',
          ],
        },
      ],
    },

    {
      slug: 'consumo.la-ropa-que-usamos',
      anillo: 1,
      titulo_es: 'La ropa que usamos',
      bajada_es: 'La prenda más sustentable suele estar colgada en tu placard.',
      icono: 'Shirt',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'consumo.fast_fashion',
          titulo_es: 'Moda rápida',
          enunciado_es:
            'La moda rápida saca colecciones nuevas todo el tiempo y a precio bajo: se compra más ropa, se la usa menos veces y se la descarta antes.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'consumo.publicidad_y_deseo', fuerza: 0.5 }],
        },
        {
          slug: 'consumo.microfibras_lavado',
          titulo_es: 'Lo que suelta el lavarropas',
          enunciado_es:
            'Cada lavado de una prenda sintética suelta microfibras plásticas diminutas que se van con el agua por la cloaca.',
          detalle_es:
            'Lavar con la carga llena y menos seguido suelta menos fibras, y de paso gasta menos agua.',
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.todo_esta_conectado'],
        },
        {
          slug: 'consumo.ropa_segunda_mano',
          titulo_es: 'Ropa que sigue circulando',
          enunciado_es:
            'Una prenda que pasa a otra persona —feria americana, intercambio con amigas, herencia entre primos— sigue dando servicio sin que se fabrique una nueva.',
          detalle_es:
            'Un intercambio de ropa con tu curso o tu edificio mueve decenas de prendas en una tarde.',
          fuente: 'ellen-macarthur',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'consumo.usar_lo_que_ya_tenes', fuerza: 0.6 }],
        },
        {
          slug: 'consumo.trazabilidad_ropa',
          titulo_es: 'Quién hizo tu remera',
          enunciado_es:
            'Casi ninguna etiqueta cuenta en qué taller y en qué condiciones se cosió la prenda: la trazabilidad es poder seguir esa cadena hasta el principio.',
          detalle_es: 'Preguntarle a la marca dónde se cose es una pregunta legítima y barata.',
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['consumo.fast_fashion'],
        },
        {
          slug: 'consumo.talleres_textiles_amba',
          titulo_es: 'El precio que no está en la etiqueta',
          enunciado_es:
            'En el AMBA se documentaron talleres textiles clandestinos donde se cose ropa en condiciones de trabajo forzado: parte de lo que abarata una prenda pasa por ahí.',
          detalle_es:
            'Hay marcas que publican su lista de talleres. Que se pueda pedir esa lista ya cambia algo aguas arriba.',
          fuente: 'chequeado',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['consumo.trazabilidad_ropa'],
        },
      ],
      hojas: [
        {
          slug: 'consumo.la-ropa-que-usamos.1',
          titulo_es: 'Moda que corre',
          bajada_es: 'Colecciones nuevas todo el tiempo: qué cambia eso en tu placard.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.fast_fashion', 'consumo.ropa_segunda_mano'],
        },
        {
          slug: 'consumo.la-ropa-que-usamos.2',
          titulo_es: 'Lo que sale del lavarropas',
          bajada_es: 'Fibras que no se ven y adónde van con el agua.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.microfibras_lavado', 'consumo.fast_fashion'],
        },
        {
          slug: 'consumo.la-ropa-que-usamos.3',
          titulo_es: 'La ropa que ya existe',
          bajada_es: 'Segunda vuelta, intercambio y cuidado de la prenda.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: [
            'consumo.ropa_segunda_mano',
            'consumo.microfibras_lavado',
            'consumo.fast_fashion',
          ],
        },
        {
          slug: 'consumo.la-ropa-que-usamos.4',
          titulo_es: 'Quién la hizo',
          bajada_es: 'Seguir la cadena de una prenda hasta la máquina de coser.',
          minutos: 6,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['consumo.trazabilidad_ropa', 'consumo.talleres_textiles_amba'],
        },
      ],
    },

    {
      slug: 'consumo.tu-huella',
      anillo: 1,
      titulo_es: 'Tu huella, en serio',
      bajada_es: 'Cómo se mide lo que consumimos, sin que el número te aplaste.',
      icono: 'Footprints',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'consumo.huella_ecologica',
          titulo_es: 'La huella ecológica',
          enunciado_es:
            'La huella ecológica estima cuánta superficie de planeta hace falta para sostener una forma de vivir, y la compara con la superficie que hay disponible.',
          detalle_es:
            'Es una estimación, no una balanza exacta. Sirve para comparar, no para retar a nadie.',
          fuente: 'global-footprint',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'tronco.por_persona_vs_total', fuerza: 0.6 }],
        },
        {
          slug: 'consumo.dia_de_sobregiro',
          titulo_es: 'El Día de Sobregiro de la Tierra',
          enunciado_es:
            'El Día de Sobregiro de la Tierra es la fecha en la que la humanidad ya usó todo lo que el planeta regenera en un año; lo que sigue se toma prestado.',
          detalle_es:
            'Cada país tiene su propia fecha, y la fecha se mueve: es un número que se puede empujar para adelante.',
          fuente: 'global-footprint',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['consumo.huella_ecologica', 'tronco.stock_vs_flujo'],
        },
        {
          slug: 'consumo.huella_de_materiales',
          titulo_es: 'Los kilos que no ves',
          enunciado_es:
            'Detrás de cada objeto hay materiales que nunca aparecen en la caja: lo que se extrajo, se movió y se descartó para poder fabricarlo.',
          detalle_es: 'Por eso un objeto chico puede arrastrar una mochila enorme de materiales.',
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'tronco.no_todo_pesa_igual', fuerza: 0.5 }],
        },
        {
          slug: 'consumo.cambiar_material_no_alcanza',
          titulo_es: 'Cambiar el material no arregla el descartable',
          enunciado_es:
            'Si un objeto se sigue usando una sola vez, cambiarle el material lo mejora poco: lo que más pesa es cuántas veces se usa antes de tirarlo.',
          detalle_es:
            'Por eso la bolsa que gana no es la de tal o cual material, sino la que volvés a llevar en la mochila decenas de veces.',
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.no_todo_pesa_igual', { slug: 'consumo.costo_por_uso', fuerza: 0.5 }],
          misconceptions: [
            {
              slug: 'consumo.mito_bolsa_papel',
              creencia_es: 'Las bolsas de papel siempre son mejores que las de plástico.',
              correccion_es:
                'La trampa es tentadora: el papel se ve natural, se rompe solo y no queda flotando en el río. Pero producirlo pide más energía y más agua, y pesa más para transportar, así que la de papel recién empata si la reusás varias veces o la compostás. La que gana de verdad es la reutilizable que usás muchas decenas de veces.',
              fuente: 'unep',
            },
          ],
        },
      ],
      hojas: [
        {
          slug: 'consumo.tu-huella.1',
          titulo_es: 'Cuánto planeta usamos',
          bajada_es: 'Una medida que compara formas de vivir con superficie real.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.huella_ecologica', 'consumo.huella_de_materiales'],
        },
        {
          slug: 'consumo.tu-huella.2',
          titulo_es: 'La fecha en que el año se acaba antes',
          bajada_es: 'Qué mide el Día de Sobregiro y qué la mueve.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.dia_de_sobregiro', 'consumo.huella_ecologica'],
        },
        {
          slug: 'consumo.tu-huella.3',
          titulo_es: '¿Papel o plástico?',
          bajada_es: 'La pregunta de la caja del súper, y por qué está mal planteada.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: [
            'consumo.cambiar_material_no_alcanza',
            'consumo.huella_de_materiales',
            'consumo.huella_ecologica',
          ],
        },
      ],
    },

    // ───────────────────────────────────────── anillo 2 ─────────────────────────────────────────
    {
      slug: 'consumo.marketing-verde',
      anillo: 2,
      titulo_es: 'Leer la promesa verde',
      bajada_es: 'Cómo se arma un anuncio ambiental y cómo se le busca la costura.',
      icono: 'BadgeCheck',
      age_groups: ['teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'consumo.greenwashing',
          titulo_es: 'Qué es el greenwashing',
          enunciado_es:
            'Greenwashing es cuando una marca invierte más en parecer sustentable que en serlo, y la comunicación tapa lo que el producto no cambió.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 2,
          dificultad_base: -0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.evidencia_y_fuente'],
        },
        {
          slug: 'consumo.pecados_del_greenwashing',
          titulo_es: 'Las costuras de una promesa verde',
          enunciado_es:
            'Los anuncios verdes engañosos se repiten en pocas formas: el falso trade-off, la falta de prueba, la vaguedad, la irrelevancia, la mentira, el sello inventado y el "mal menor".',
          detalle_es:
            'La vaguedad es la más común: "ecológico", "natural" o "verde" no dicen nada si no aclaran respecto de qué.',
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['consumo.greenwashing'],
        },
        {
          slug: 'consumo.sellos_y_certificaciones',
          titulo_es: 'El sello y quién lo firma',
          enunciado_es:
            'Un sello vale por quién lo audita: hay certificaciones con criterios públicos y control de un tercero independiente, y hay dibujitos verdes que la marca se puso sola.',
          detalle_es: 'Buscá el nombre del que certifica. Si no aparece, ya sabés bastante.',
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['consumo.greenwashing', { slug: 'tronco.evidencia_y_fuente', fuerza: 0.5 }],
        },
        {
          slug: 'consumo.promesas_a_futuro',
          titulo_es: 'Prometer para dentro de veinte años',
          enunciado_es:
            'Una promesa de neutralidad para dentro de décadas no cambia lo que se emite hoy, y compensar en otro lado no es lo mismo que dejar de emitir.',
          detalle_es:
            'La pregunta útil es corta: ¿qué baja este año, y quién lo verifica?',
          fuente: 'carbon-brief',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.compensacion_no_es_evitar', 'consumo.greenwashing'],
        },
      ],
      hojas: [
        {
          slug: 'consumo.marketing-verde.1',
          titulo_es: 'Parecer o ser',
          bajada_es: 'Qué es el greenwashing y en qué formas aparece.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.greenwashing', 'consumo.pecados_del_greenwashing'],
        },
        {
          slug: 'consumo.marketing-verde.2',
          titulo_es: 'Sellos, etiquetas y auditorías',
          bajada_es: 'Cómo se distingue una certificación de un dibujito.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.sellos_y_certificaciones', 'consumo.greenwashing'],
        },
        {
          slug: 'consumo.marketing-verde.3',
          titulo_es: 'Promesas con fecha lejana',
          bajada_es: 'Neutralidad, compensación y la pregunta que las ordena.',
          minutos: 6,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: [
            'consumo.promesas_a_futuro',
            'consumo.pecados_del_greenwashing',
            'consumo.sellos_y_certificaciones',
          ],
        },
      ],
    },

    {
      slug: 'consumo.usar-sin-comprar',
      anillo: 2,
      titulo_es: 'Usar sin comprar',
      bajada_es: 'Casi todo lo que tenemos se usa pocas horas al año.',
      icono: 'Share2',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'consumo.consumo_colaborativo',
          titulo_es: 'Compartir en vez de duplicar',
          enunciado_es:
            'Muchos objetos que compramos se usan unas pocas horas al año: compartirlos, prestarlos o alquilarlos da el mismo servicio con muchas menos cosas fabricadas.',
          detalle_es: 'El taladro es el ejemplo clásico: se compra para hacer unos pocos agujeros.',
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [{ slug: 'consumo.costo_por_uso', fuerza: 0.6 }],
        },
        {
          slug: 'consumo.biblioteca_de_objetos',
          titulo_es: 'Una biblioteca, pero de cosas',
          enunciado_es:
            'Una biblioteca de objetos presta herramientas, ollas grandes o carpas como una biblioteca presta libros: una sola compra le sirve a todo un barrio.',
          detalle_es:
            'Se arranca simple: una lista compartida en el grupo del edificio o del curso ya es una.',
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['consumo.consumo_colaborativo'],
        },
        {
          slug: 'consumo.servitizacion',
          titulo_es: 'Producto como servicio',
          enunciado_es:
            'Cuando pagás por el uso y no por el objeto, el fabricante sigue siendo el dueño: le conviene que dure, que se pueda reparar y que después vuelva.',
          detalle_es:
            'Es el modelo de las bicis y los monopatines de alquiler, y también el de alquilar herramientas grandes.',
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [
            'consumo.consumo_colaborativo',
            { slug: 'consumo.derecho_a_reparar', fuerza: 0.5 },
          ],
        },
        {
          slug: 'consumo.suficiencia',
          titulo_es: '¿Cuánto alcanza?',
          enunciado_es:
            'La suficiencia es preguntarse cuánto alcanza en vez de cuánto se puede: no es privarse, es elegir la cantidad que hace falta.',
          detalle_es:
            'Minimalismo y decrecimiento no son sinónimos: uno habla de tu casa, el otro discute el tamaño de una economía.',
          fuente: 'unesco-ods',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.efecto_rebote', { slug: 'consumo.necesidad_vs_deseo', fuerza: 0.7 }],
        },
      ],
      hojas: [
        {
          slug: 'consumo.usar-sin-comprar.1',
          titulo_es: 'Cosas que duermen',
          bajada_es: 'Cuántas horas al año se usa lo que tenemos guardado.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.consumo_colaborativo', 'consumo.biblioteca_de_objetos'],
        },
        {
          slug: 'consumo.usar-sin-comprar.2',
          titulo_es: 'Pagar por usar',
          bajada_es: 'Qué cambia cuando el dueño del objeto sigue siendo el que lo fabrica.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.servitizacion', 'consumo.consumo_colaborativo'],
        },
        {
          slug: 'consumo.usar-sin-comprar.3',
          titulo_es: 'Cuánto alcanza',
          bajada_es: 'La pregunta que evita que el ahorro se vuelva a gastar.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: [
            'consumo.suficiencia',
            'consumo.consumo_colaborativo',
            'consumo.biblioteca_de_objetos',
          ],
        },
      ],
    },

    {
      slug: 'consumo.economia-circular',
      anillo: 2,
      titulo_es: 'Circular en serio',
      bajada_es: 'De la línea recta que termina en la basura a un sistema que vuelve a empezar.',
      icono: 'RefreshCw',
      age_groups: ['teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'consumo.economia_circular',
          titulo_es: 'Los tres principios',
          enunciado_es:
            'La economía circular propone tres cosas a la vez: eliminar residuos y contaminación desde el diseño, mantener productos y materiales en uso, y regenerar la naturaleza.',
          detalle_es:
            'No es reciclar más: es diseñar para que el residuo no aparezca, y reciclar cuando ya no queda otra.',
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: -0.1,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.ciclos_materia', { slug: 'consumo.vida_util', fuerza: 0.6 }],
        },
        {
          slug: 'consumo.ciclos_tecnico_y_biologico',
          titulo_es: 'Dos ciclos que no se mezclan',
          enunciado_es:
            'En el ciclo biológico los materiales vuelven a la tierra y se compostan; en el técnico circulan entre productos sin degradarse. Un objeto que pega los dos y no se puede separar arruina los dos caminos.',
          detalle_es: 'El envase de papel con película plástica es el caso típico.',
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['consumo.economia_circular'],
        },
        {
          slug: 'consumo.cadena_de_suministro',
          titulo_es: 'La cadena detrás del objeto',
          enunciado_es:
            'Entre la mina y la góndola hay una cadena larga de países, fábricas y transportes; la trazabilidad es poder ver esa cadena en vez de imaginarla.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.escala_local_global'],
        },
        {
          slug: 'consumo.minerales_de_conflicto',
          titulo_es: 'Minerales en zonas de conflicto',
          enunciado_es:
            'Parte de los minerales que llevan los aparatos electrónicos se extrae en zonas con conflicto armado, y esa venta puede financiar a los grupos que pelean.',
          detalle_es:
            'Por eso alargar la vida de un celular no es solo ahorro: es demanda de extracción que no se pide.',
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['consumo.cadena_de_suministro'],
        },
      ],
      hojas: [
        {
          slug: 'consumo.economia-circular.1',
          titulo_es: 'Del descarte al diseño',
          bajada_es: 'Los tres principios, y por qué reciclar viene último.',
          minutos: 6,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['consumo.economia_circular', 'consumo.ciclos_tecnico_y_biologico'],
        },
        {
          slug: 'consumo.economia-circular.2',
          titulo_es: 'Rastrear el objeto',
          bajada_es: 'De la góndola para atrás: quién, dónde y con qué.',
          minutos: 6,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['consumo.cadena_de_suministro', 'consumo.economia_circular'],
        },
        {
          slug: 'consumo.economia-circular.3',
          titulo_es: 'Lo que hay adentro de un celular',
          bajada_es: 'Minerales, distancias y por qué conviene que dure.',
          minutos: 6,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['consumo.minerales_de_conflicto', 'consumo.cadena_de_suministro'],
        },
      ],
    },
  ],
};
