// Rama `digital` — la nube es física y tu celular pesa.
// Fuente de contenido: ACADEMIA/research/03-environmental-curriculum.md §2.9,
// más §6 para las reglas de edad. Los dos mitos asignados son el 25 (mandar
// menos emails) y el 26 (la nube no es física).

export default {
  rama: 'digital',
  gajos: [
    {
      slug: 'digital.la-nube-es-fisica',
      anillo: 1,
      titulo_es: 'La nube es física',
      bajada_es: 'Galpones, servidores, refrigeración y electricidad. Nada de eso está en el aire.',
      icono: 'Server',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'digital.que_es_un_centro_de_datos',
          titulo_es: 'Qué es un centro de datos',
          enunciado_es:
            'Un centro de datos es un galpón lleno de computadoras encendidas todo el día, con su propio sistema de refrigeración y su propia conexión eléctrica.',
          detalle_es: 'Cuando algo "está en la nube", está ahí.',
          fuente: 'iea-energia',
          anillo: 1,
          dificultad_base: -1.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
          misconceptions: [
            {
              slug: 'digital.mito_nube_no_es_fisica',
              creencia_es: 'La nube no es física: los archivos están "en el aire", no en ningún lado.',
              correccion_es:
                'La metáfora es tan buena que tapa la cosa. La nube son galpones con servidores, refrigeración y electricidad, y la IEA proyecta que su demanda eléctrica se duplique hacia 2030, hasta unos 945 TWh.',
              fuente: 'iea-energia',
            },
          ],
        },
        {
          slug: 'digital.la_electricidad_de_la_nube',
          titulo_es: 'La electricidad de la nube',
          enunciado_es:
            'La IEA proyecta que la demanda eléctrica de los centros de datos se duplique hacia 2030, hasta alrededor de 945 TWh: algo menos del 3 % de la electricidad mundial.',
          detalle_es: 'Es mucho y es poco a la vez, y las dos cosas importan para decidir dónde poner el esfuerzo.',
          fuente: 'iea-energia',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.que_es_un_centro_de_datos', 'tronco.orden_de_magnitud'],
        },
        {
          slug: 'digital.refrigerar_cuesta',
          titulo_es: 'Refrigerar también cuesta',
          enunciado_es:
            'Una parte importante de la energía de un centro de datos no se va en calcular: se va en sacarle el calor a las máquinas que calculan.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['digital.que_es_un_centro_de_datos'],
        },
        {
          slug: 'digital.pue',
          titulo_es: 'PUE: cuánta energía se va en lo que no calcula',
          enunciado_es:
            'El PUE compara toda la energía que entra a un centro de datos con la que llega efectivamente a los servidores. Cuanto más cerca de 1, menos se pierde en refrigeración y pérdidas.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.refrigerar_cuesta', 'tronco.leer_un_numero'],
        },
      ],
      hojas: [
        {
          slug: 'digital.la-nube-es-fisica.1',
          titulo_es: 'Dónde está "la nube"',
          bajada_es: 'Spoiler: en un galpón con aire acondicionado.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.que_es_un_centro_de_datos', 'digital.refrigerar_cuesta'],
        },
        {
          slug: 'digital.la-nube-es-fisica.2',
          titulo_es: 'Cuánta luz consume',
          bajada_es: 'Un número grande, puesto en escala.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.la_electricidad_de_la_nube', 'digital.que_es_un_centro_de_datos'],
        },
        {
          slug: 'digital.la-nube-es-fisica.3',
          titulo_es: 'La energía que no calcula',
          bajada_es: 'Qué mide el PUE y por qué a las empresas les importa.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.pue', 'digital.refrigerar_cuesta'],
        },
      ],
    },

    {
      slug: 'digital.tu-dispositivo',
      anillo: 1,
      titulo_es: 'Tu dispositivo',
      bajada_es: 'Lo que más pesa de tu celular ya pasó antes de que lo prendieras.',
      icono: 'Smartphone',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'digital.carbono_embebido',
          titulo_es: 'El carbono que ya viene adentro',
          enunciado_es:
            'En un celular, la mayor parte de la huella de carbono se generó fabricándolo, no usándolo.',
          detalle_es: 'Extraer los minerales, refinarlos, fabricar los chips y armarlo pesan más que años de uso.',
          fuente: 'carbon-brief',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'digital.alargar_la_vida_util',
          titulo_es: 'Alargar la vida útil es la acción digital más fuerte',
          enunciado_es:
            'Como el grueso del impacto está en la fabricación, usar el mismo teléfono dos años más pesa mucho más que cualquier ahorro durante el uso.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['digital.carbono_embebido'],
        },
        {
          slug: 'digital.reparar_y_bateria',
          titulo_es: 'La batería es lo primero que se muere',
          enunciado_es:
            'En muchos dispositivos lo que falla primero es la batería, y cambiarla cuesta una fracción de lo que cuesta —en plata y en materiales— comprar uno nuevo.',
          detalle_es: null,
          fuente: 'ellen-macarthur',
          anillo: 1,
          dificultad_base: -0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['digital.alargar_la_vida_util'],
        },
        {
          slug: 'digital.raee',
          titulo_es: 'RAEE: la basura electrónica',
          enunciado_es:
            'Los residuos de aparatos eléctricos y electrónicos tienen metales valiosos y también sustancias peligrosas: no van al tacho común.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'digital.mineria_urbana',
          titulo_es: 'Minería urbana',
          enunciado_es:
            'Recuperar metales de aparatos viejos suele requerir menos energía que extraerlos de una mina, y evita abrir una mina nueva.',
          detalle_es: null,
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.raee'],
        },
        {
          slug: 'digital.minerales_criticos',
          titulo_es: 'Litio, cobalto y compañía',
          enunciado_es:
            'Los aparatos electrónicos dependen de minerales cuya extracción tiene costos ambientales y sociales concretos en los lugares donde se saca.',
          detalle_es: null,
          fuente: 'unep',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: true,
          requiere: ['digital.carbono_embebido'],
        },
      ],
      hojas: [
        {
          slug: 'digital.tu-dispositivo.1',
          titulo_es: 'Lo que ya pesó',
          bajada_es: 'El carbono que traía tu celular de fábrica.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.carbono_embebido', 'digital.alargar_la_vida_util'],
        },
        {
          slug: 'digital.tu-dispositivo.2',
          titulo_es: 'Dos años más',
          bajada_es: 'Por qué la batería decide casi todo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.reparar_y_bateria', 'digital.alargar_la_vida_util'],
        },
        {
          slug: 'digital.tu-dispositivo.3',
          titulo_es: 'Dónde va lo que ya no anda',
          bajada_es: 'RAEE, y por qué no van al tacho común.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.raee', 'digital.carbono_embebido'],
        },
        {
          slug: 'digital.tu-dispositivo.4',
          titulo_es: 'Minas y celulares',
          bajada_es: 'De dónde salen los minerales y qué se puede recuperar.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['digital.minerales_criticos', 'digital.mineria_urbana'],
        },
      ],
    },

    {
      slug: 'digital.lo-que-si-y-lo-que-no',
      anillo: 1,
      titulo_es: 'Lo que sí y lo que no',
      bajada_es: 'Dónde está el impacto de verdad y dónde solo hay ruido.',
      icono: 'Scale',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'digital.el_email_no_es_el_problema',
          titulo_es: 'El correo no es el problema',
          enunciado_es:
            'La huella de un correo individual es despreciable frente a la fabricación de dispositivos y a la electricidad de los centros de datos.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 1,
          dificultad_base: -0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.no_todo_pesa_igual'],
          misconceptions: [
            {
              slug: 'digital.mito_menos_emails',
              creencia_es: 'Mandar menos correos y borrar los viejos salva el planeta.',
              correccion_es:
                'Es tentador porque es una acción concreta y visible, pero está en el orden de magnitud equivocado. Los impactos digitales que pesan son la fabricación del dispositivo y la electricidad de los centros de datos: alargar dos años la vida de tu teléfono supera un año entero de higiene de correo.',
              fuente: 'carbon-brief',
            },
          ],
        },
        {
          slug: 'digital.streaming_y_resolucion',
          titulo_es: 'Streaming: la resolución y la red',
          enunciado_es:
            'Mirar en resolución más baja y por wifi en vez de datos móviles reduce el consumo asociado, aunque el efecto por hora sigue siendo modesto.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 1,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['digital.el_email_no_es_el_problema'],
        },
        {
          slug: 'digital.datos_zombis',
          titulo_es: 'Datos zombis',
          enunciado_es:
            'Muchos archivos guardados en la nube no se abren nunca más, pero se siguen replicando y ocupando espacio encendido.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.que_es_un_centro_de_datos'],
        },
        {
          slug: 'digital.modo_oscuro',
          titulo_es: 'El modo oscuro (y su tamaño real)',
          enunciado_es:
            'En pantallas OLED el modo oscuro ahorra algo de energía, pero es un efecto chico: sirve como ejemplo de escala, no como estrategia.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.no_todo_pesa_igual'],
        },
      ],
      hojas: [
        {
          slug: 'digital.lo-que-si-y-lo-que-no.1',
          titulo_es: 'Borrar correos no alcanza',
          bajada_es: 'El mito más querido del ambientalismo digital.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.el_email_no_es_el_problema', 'digital.streaming_y_resolucion'],
        },
        {
          slug: 'digital.lo-que-si-y-lo-que-no.2',
          titulo_es: 'Archivos que nadie abre',
          bajada_es: 'Lo que queda encendido por las dudas.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.datos_zombis', 'digital.que_es_un_centro_de_datos'],
        },
        {
          slug: 'digital.lo-que-si-y-lo-que-no.3',
          titulo_es: 'Efectos chicos, bien medidos',
          bajada_es: 'El modo oscuro como lección de escala.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.modo_oscuro', 'digital.el_email_no_es_el_problema'],
        },
      ],
    },

    {
      slug: 'digital.acceso-y-justicia',
      anillo: 1,
      titulo_es: 'Acceso y justicia',
      bajada_es: 'Quién tiene conexión, quién pone el territorio y quién decide.',
      icono: 'Users',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'digital.brecha_digital',
          titulo_es: 'La brecha digital',
          enunciado_es:
            'No todo el mundo tiene la misma conexión ni los mismos dispositivos, y eso cambia quién puede estudiar, trabajar o hacer un trámite.',
          detalle_es: null,
          fuente: 'unesco-ods',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'digital.donde_se_instalan',
          titulo_es: 'Dónde se instalan los centros de datos',
          enunciado_es:
            'Un centro de datos necesita electricidad barata, agua para refrigerar y terreno: esas tres cosas hacen que su instalación sea una discusión local.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.refrigerar_cuesta', 'tronco.escala_local_global'],
        },
        {
          slug: 'digital.diseno_web_liviano',
          titulo_es: 'Diseño web sostenible',
          enunciado_es:
            'Una página liviana carga más rápido, gasta menos batería y funciona en conexiones peores: la eficiencia y el acceso van juntos.',
          detalle_es: null,
          fuente: 'unesco-ods',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.brecha_digital'],
        },
        {
          slug: 'digital.derecho_a_desconectar',
          titulo_es: 'Desconectar también cuenta',
          enunciado_es:
            'El diseño que empuja a usar más —notificaciones, autoplay, rachas— tiene un costo de atención, y decidir cuándo apagar es parte de un uso consciente.',
          detalle_es: null,
          fuente: 'unesco-ods',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: [],
        },
      ],
      hojas: [
        {
          slug: 'digital.acceso-y-justicia.1',
          titulo_es: 'Quién queda afuera',
          bajada_es: 'La conexión como problema de equidad.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.brecha_digital', 'digital.diseno_web_liviano'],
        },
        {
          slug: 'digital.acceso-y-justicia.2',
          titulo_es: 'El galpón en tu provincia',
          bajada_es: 'Electricidad, agua y terreno: por qué se discute.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.donde_se_instalan', 'digital.refrigerar_cuesta'],
        },
        {
          slug: 'digital.acceso-y-justicia.3',
          titulo_es: 'Apagar a propósito',
          bajada_es: 'El diseño que empuja y la decisión de parar.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.derecho_a_desconectar', 'digital.brecha_digital'],
        },
      ],
    },

    {
      slug: 'digital.ia-y-computo',
      anillo: 2,
      titulo_es: 'IA y cómputo',
      bajada_es: 'Entrenar, inferir, refrigerar: dónde está el gasto.',
      icono: 'Cpu',
      age_groups: ['teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'digital.entrenar_vs_usar',
          titulo_es: 'Entrenar y usar no cuestan igual',
          enunciado_es:
            'Entrenar un modelo grande concentra un gasto energético alto una vez; usarlo gasta poco por consulta pero se multiplica por millones de consultas.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.la_electricidad_de_la_nube', 'tronco.stock_vs_flujo'],
        },
        {
          slug: 'digital.agua_de_refrigeracion',
          titulo_es: 'El agua de refrigerar',
          enunciado_es:
            'Muchos centros de datos usan agua para refrigerar, y eso los pone a competir por un recurso local que puede estar bajo estrés.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.refrigerar_cuesta'],
        },
        {
          slug: 'digital.cripto_pow_pos',
          titulo_es: 'Proof-of-work y proof-of-stake',
          enunciado_es:
            'Algunas criptomonedas gastan energía a propósito para validar transacciones; otras cambiaron ese mecanismo por uno que consume órdenes de magnitud menos.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 2,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.la_electricidad_de_la_nube'],
        },
        {
          slug: 'digital.eficiencia_y_rebote',
          titulo_es: 'Chips más eficientes, más cómputo',
          enunciado_es:
            'Cada generación de chips calcula más por vatio, y sin embargo el consumo total crece: la eficiencia abarata el cómputo y se usa más.',
          detalle_es: 'Es el efecto rebote, aplicado a la informática.',
          fuente: 'iea-energia',
          anillo: 3,
          dificultad_base: 0.9,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.efecto_rebote', 'digital.entrenar_vs_usar'],
        },
      ],
      hojas: [
        {
          slug: 'digital.ia-y-computo.1',
          titulo_es: 'Una vez y muchas veces',
          bajada_es: 'Entrenar concentra; usar se multiplica.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.entrenar_vs_usar', 'digital.la_electricidad_de_la_nube'],
        },
        {
          slug: 'digital.ia-y-computo.2',
          titulo_es: 'Agua para enfriar',
          bajada_es: 'Cuando el galpón compite con el pueblo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.agua_de_refrigeracion', 'digital.donde_se_instalan'],
        },
        {
          slug: 'digital.ia-y-computo.3',
          titulo_es: 'Gastar energía a propósito',
          bajada_es: 'Qué valida una cripto y a qué costo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.cripto_pow_pos', 'digital.entrenar_vs_usar'],
        },
        {
          slug: 'digital.ia-y-computo.4',
          titulo_es: 'Más eficiente, más total',
          bajada_es: 'El rebote, en versión informática.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['digital.eficiencia_y_rebote', 'digital.entrenar_vs_usar'],
        },
      ],
    },

    {
      slug: 'digital.consumir-tecnologia',
      anillo: 2,
      titulo_es: 'Consumir tecnología',
      bajada_es: 'Comprar menos, elegir mejor y reclamar que dure.',
      icono: 'ShoppingBag',
      age_groups: ['teen', 'adult'],
      sort_order: 6,
      conceptos: [
        {
          slug: 'digital.obsolescencia_de_software',
          titulo_es: 'Cuando lo que caduca es el software',
          enunciado_es:
            'Un aparato que funciona perfecto puede quedar inutilizable porque dejó de recibir actualizaciones: la obsolescencia no siempre es del hardware.',
          detalle_es: null,
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.alargar_la_vida_util'],
        },
        {
          slug: 'digital.reacondicionado',
          titulo_es: 'Reacondicionado',
          enunciado_es:
            'Comprar un dispositivo reacondicionado evita toda la huella de fabricar uno nuevo, que es justamente donde está el grueso del impacto.',
          detalle_es: null,
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.carbono_embebido'],
        },
        {
          slug: 'digital.derecho_a_reparar_tec',
          titulo_es: 'Que se pueda abrir',
          enunciado_es:
            'Un aparato reparable necesita tornillos en vez de pegamento, repuestos disponibles y manuales públicos. Eso se decide en el diseño, no después.',
          detalle_es: null,
          fuente: 'ellen-macarthur',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.reparar_y_bateria'],
        },
        {
          slug: 'digital.huella_de_la_compra',
          titulo_es: 'La compra que no hiciste',
          enunciado_es:
            'En tecnología, la decisión con más impacto sigue siendo no comprar: ningún modelo nuevo, por eficiente que sea, compensa la fabricación evitada.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.reacondicionado', 'tronco.jerarquia_decisiones'],
        },
      ],
      hojas: [
        {
          slug: 'digital.consumir-tecnologia.1',
          titulo_es: 'Anda, pero ya no',
          bajada_es: 'La obsolescencia que llega por software.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.obsolescencia_de_software', 'digital.alargar_la_vida_util'],
        },
        {
          slug: 'digital.consumir-tecnologia.2',
          titulo_es: 'Usado y como nuevo',
          bajada_es: 'Por qué el reacondicionado gana por goleada.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.reacondicionado', 'digital.carbono_embebido'],
        },
        {
          slug: 'digital.consumir-tecnologia.3',
          titulo_es: 'Tornillos, no pegamento',
          bajada_es: 'Reparable se decide en la mesa de diseño.',
          minutos: 4,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.derecho_a_reparar_tec', 'digital.huella_de_la_compra'],
        },
      ],
    },

    {
      slug: 'digital.medir-lo-digital',
      anillo: 2,
      titulo_es: 'Medir lo digital',
      bajada_es: 'Cómo se calcula una huella que no se ve.',
      icono: 'Gauge',
      age_groups: ['teen', 'adult'],
      sort_order: 7,
      conceptos: [
        {
          slug: 'digital.alcances_de_una_empresa_tec',
          titulo_es: 'Los alcances de una tecnológica',
          enunciado_es:
            'Buena parte de las emisiones de una empresa tecnológica no están en sus oficinas: están en la fabricación de lo que vende y en la energía de terceros.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.leer_un_numero'],
        },
        {
          slug: 'digital.energia_renovable_contratada',
          titulo_es: 'Comprar renovable no es consumir renovable',
          enunciado_es:
            'Una empresa puede comprar certificados de energía renovable y seguir tomando electricidad de una red que en ese momento quema gas: coincidir en tiempo y lugar es lo difícil.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 3,
          dificultad_base: 0.9,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['digital.alcances_de_una_empresa_tec', 'tronco.compensacion_no_es_evitar'],
        },
        {
          slug: 'digital.transparencia_de_datos',
          titulo_es: 'Lo que no se publica',
          enunciado_es:
            'Muchas cifras de consumo digital son estimaciones: cuando una empresa no publica sus datos, la incertidumbre es parte del resultado y hay que decirlo.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.incertidumbre'],
        },
        {
          slug: 'digital.comparar_con_algo',
          titulo_es: 'Comparar con algo conocido',
          enunciado_es:
            'Un número digital solo significa algo comparado con otro: "el 3 % de la electricidad mundial" dice mucho más que "945 TWh".',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.orden_de_magnitud', 'digital.la_electricidad_de_la_nube'],
        },
      ],
      hojas: [
        {
          slug: 'digital.medir-lo-digital.1',
          titulo_es: 'Dónde emite una tecnológica',
          bajada_es: 'Casi nunca en la oficina.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 1,
          conceptos: ['digital.alcances_de_una_empresa_tec', 'digital.comparar_con_algo'],
        },
        {
          slug: 'digital.medir-lo-digital.2',
          titulo_es: 'Renovable en el papel',
          bajada_es: 'La diferencia entre comprar y consumir.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['digital.energia_renovable_contratada', 'digital.alcances_de_una_empresa_tec'],
        },
        {
          slug: 'digital.medir-lo-digital.3',
          titulo_es: 'Cuando falta el dato',
          bajada_es: 'Estimar bien y decir que estimaste.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['digital.transparencia_de_datos', 'digital.comparar_con_algo'],
        },
      ],
    },
  ],
};
