// El tronco — la base común. Todo el mundo lo camina primero y es lo único que
// el anillo 1 usa como compuerta general: los `tronco.*` son los únicos slugs a
// los que una rama puede apuntar desde afuera, y por eso el DAG entre módulos
// no puede cerrarse en un ciclo.
//
// Contenido: ACADEMIA/research/03-environmental-curriculum.md §1 (marcos),
// §2.13 (ciencia) y §6 (edad). Marco de agencia, sin catástrofe: el tronco es
// lo primero que ve una cuenta infantil.

export default {
  rama: 'tronco',
  gajos: [
    {
      slug: 'tronco.sistemas-vivos',
      anillo: 1,
      titulo_es: 'Sistemas vivos',
      bajada_es: 'Nada está solo: todo lo que vive está enganchado con otra cosa.',
      icono: 'Sprout',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 1,
      conceptos: [
        {
          slug: 'tronco.que_es_ecosistema',
          titulo_es: 'Qué es un ecosistema',
          enunciado_es:
            'Un ecosistema son los seres vivos de un lugar, el ambiente físico que los rodea y —sobre todo— las relaciones entre ellos.',
          detalle_es:
            'La palabra clave es "relaciones": un ecosistema no es una lista de especies, es lo que se hacen entre sí.',
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -1.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'tronco.todo_esta_conectado',
          titulo_es: 'Todo está conectado',
          enunciado_es:
            'Tocar una parte de un ecosistema mueve otras partes, incluso las que parecen no tener nada que ver.',
          detalle_es: null,
          fuente: 'ipbes-global',
          anillo: 1,
          dificultad_base: -1.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.que_es_ecosistema'],
        },
        {
          slug: 'tronco.servicios_ecosistemicos',
          titulo_es: 'Lo que la naturaleza hace por nosotros',
          enunciado_es:
            'Los ecosistemas hacen trabajo gratis que nos sostiene: filtran agua, polinizan cultivos, dan sombra y guardan carbono.',
          detalle_es: 'Se los llama servicios ecosistémicos. Se notan sobre todo cuando faltan.',
          fuente: 'ipbes-global',
          anillo: 1,
          dificultad_base: -0.7,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.que_es_ecosistema'],
        },
        {
          slug: 'tronco.escala_local_global',
          titulo_es: 'Lo local y lo global',
          enunciado_es:
            'Un mismo problema ambiental se ve distinto según la escala: lo que resuelve una cuadra puede no mover nada a nivel país, y al revés.',
          detalle_es: null,
          fuente: 'unesco-ods',
          anillo: 1,
          dificultad_base: -0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.todo_esta_conectado'],
        },
        {
          slug: 'tronco.ciclos_materia',
          titulo_es: 'La materia da vueltas',
          enunciado_es:
            'En la naturaleza la materia no desaparece: circula. El agua, el carbono y los nutrientes hacen ciclos que vuelven a empezar.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 1,
          dificultad_base: -0.8,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.que_es_ecosistema'],
        },
      ],
      hojas: [
        {
          slug: 'tronco.sistemas-vivos.1',
          titulo_es: 'Qué es un ecosistema',
          bajada_es: 'Empezamos por la palabra que sostiene todas las demás.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['tronco.que_es_ecosistema', 'tronco.todo_esta_conectado'],
        },
        {
          slug: 'tronco.sistemas-vivos.2',
          titulo_es: 'El trabajo que no se cobra',
          bajada_es: 'Sombra, agua limpia y polinización: quién los hace.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['tronco.servicios_ecosistemicos', 'tronco.que_es_ecosistema'],
        },
        {
          slug: 'tronco.sistemas-vivos.3',
          titulo_es: 'Vueltas que no terminan',
          bajada_es: 'El agua y el carbono no se gastan: cambian de lugar.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 3,
          conceptos: ['tronco.ciclos_materia', 'tronco.todo_esta_conectado'],
        },
        {
          slug: 'tronco.sistemas-vivos.4',
          titulo_es: 'Tu cuadra y el planeta',
          bajada_es: 'Cuándo una acción chica alcanza y cuándo no.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 4,
          conceptos: ['tronco.escala_local_global', 'tronco.servicios_ecosistemicos'],
        },
      ],
    },

    {
      slug: 'tronco.leer-numeros',
      anillo: 1,
      titulo_es: 'Leer un número ambiental',
      bajada_es: 'Un número sin unidad y sin fuente no dice nada. Con las dos, dice todo.',
      icono: 'Ruler',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 2,
      conceptos: [
        {
          slug: 'tronco.leer_un_numero',
          titulo_es: 'Unidad, escala y fuente',
          enunciado_es:
            'Un número ambiental solo significa algo si sabés su unidad, respecto de qué se mide y quién lo publicó.',
          detalle_es: '"Reducimos un 40 %" no dice nada hasta que aparece "¿respecto de qué año?".',
          fuente: 'chequeado',
          anillo: 1,
          dificultad_base: -0.9,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'tronco.orden_de_magnitud',
          titulo_es: 'Orden de magnitud',
          enunciado_es:
            'Antes de comparar dos cosas conviene preguntarse si están en la misma escala: diez, mil o un millón cambian la decisión, no el detalle.',
          detalle_es: null,
          fuente: 'owid-alimentos',
          anillo: 1,
          dificultad_base: -0.4,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.leer_un_numero'],
        },
        {
          slug: 'tronco.por_persona_vs_total',
          titulo_es: 'Por persona o en total',
          enunciado_es:
            'El mismo dato cambia de sentido según se exprese en total o por persona: un país grande emite mucho y puede emitir poco por habitante.',
          detalle_es: null,
          fuente: 'owid-impactos-alimentos',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.leer_un_numero'],
        },
        {
          slug: 'tronco.promedio_engana',
          titulo_es: 'Cuándo el promedio engaña',
          enunciado_es:
            'Un promedio esconde la distribución: si unos pocos consumen muchísimo, el promedio no describe a casi nadie.',
          detalle_es: null,
          fuente: 'chequeado',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.leer_un_numero', { slug: 'tronco.por_persona_vs_total', fuerza: 0.5 }],
        },
        {
          slug: 'tronco.stock_vs_flujo',
          titulo_es: 'Stock y flujo',
          enunciado_es:
            'Emitir menos cada año frena la subida pero no la revierte: el CO₂ se acumula, así que lo que importa es el stock, no el caudal.',
          detalle_es:
            'Por eso "reducir emisiones" y "dejar de aumentar la concentración" no son lo mismo.',
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.7,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.orden_de_magnitud'],
        },
      ],
      hojas: [
        {
          slug: 'tronco.leer-numeros.1',
          titulo_es: 'Con qué unidad',
          bajada_es: 'Litros, kilos, kilovatios: si no está la unidad, no hay dato.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['tronco.leer_un_numero', 'tronco.orden_de_magnitud'],
        },
        {
          slug: 'tronco.leer-numeros.2',
          titulo_es: 'Grande, gigante o enorme',
          bajada_es: 'Entrenar la intuición de escala vale más que memorizar cifras.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['tronco.orden_de_magnitud', 'tronco.leer_un_numero'],
        },
        {
          slug: 'tronco.leer-numeros.3',
          titulo_es: 'Total o por persona',
          bajada_es: 'La misma tabla, dos conclusiones opuestas.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['tronco.por_persona_vs_total', 'tronco.promedio_engana'],
        },
        {
          slug: 'tronco.leer-numeros.4',
          titulo_es: 'La bañadera y la canilla',
          bajada_es: 'Por qué bajar emisiones no baja la concentración.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['tronco.stock_vs_flujo', 'tronco.orden_de_magnitud'],
        },
      ],
    },

    {
      slug: 'tronco.como-se-sabe',
      anillo: 1,
      titulo_es: 'Cómo se sabe lo que se sabe',
      bajada_es: 'Observar, medir, dudar y volver a medir. También sirve para el WhatsApp familiar.',
      icono: 'Microscope',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 3,
      conceptos: [
        {
          slug: 'tronco.observacion_vs_inferencia',
          titulo_es: 'Observación e inferencia',
          enunciado_es:
            'Observar es registrar lo que pasa; inferir es explicar por qué. Confundirlas es la fuente más común de error.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 1,
          dificultad_base: -0.6,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'tronco.evidencia_y_fuente',
          titulo_es: 'De dónde salió el dato',
          enunciado_es:
            'Una afirmación ambiental vale lo que vale su fuente: quién midió, cuándo y con qué método.',
          detalle_es: null,
          fuente: 'chequeado',
          anillo: 1,
          dificultad_base: -0.5,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.observacion_vs_inferencia'],
        },
        {
          slug: 'tronco.correlacion_causalidad',
          titulo_es: 'Correlación no es causalidad',
          enunciado_es:
            'Que dos cosas suban juntas no prueba que una cause la otra: puede haber una tercera causa, o pura casualidad.',
          detalle_es: null,
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.evidencia_y_fuente'],
        },
        {
          slug: 'tronco.incertidumbre',
          titulo_es: 'La incertidumbre no es ignorancia',
          enunciado_es:
            'Un rango de error dice cuánto se sabe, no que no se sepa nada. Un dato con barras de error es más confiable que uno sin ellas.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.6,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.evidencia_y_fuente'],
        },
        {
          slug: 'tronco.consenso_cientifico',
          titulo_es: 'Cómo se construye un consenso',
          enunciado_es:
            'El consenso científico no es una votación: es lo que queda en pie después de que muchos equipos independientes intentan refutarlo.',
          detalle_es: null,
          fuente: 'ipcc-ar6',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.correlacion_causalidad'],
        },
      ],
      hojas: [
        {
          slug: 'tronco.como-se-sabe.1',
          titulo_es: 'Lo que viste y lo que pensás',
          bajada_es: 'Separar el registro de la explicación.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['tronco.observacion_vs_inferencia', 'tronco.evidencia_y_fuente'],
        },
        {
          slug: 'tronco.como-se-sabe.2',
          titulo_es: 'Pedile la fuente',
          bajada_es: 'Tres preguntas que desarman casi cualquier dato dudoso.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['tronco.evidencia_y_fuente', 'tronco.observacion_vs_inferencia'],
        },
        {
          slug: 'tronco.como-se-sabe.3',
          titulo_es: 'Juntos no es por eso',
          bajada_es: 'La trampa favorita de los gráficos.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['tronco.correlacion_causalidad', 'tronco.incertidumbre'],
        },
        {
          slug: 'tronco.como-se-sabe.4',
          titulo_es: 'Qué significa "hay consenso"',
          bajada_es: 'Y por qué no es lo mismo que "todos opinan igual".',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['tronco.consenso_cientifico', 'tronco.incertidumbre'],
        },
      ],
    },

    {
      slug: 'tronco.donde-pesa',
      anillo: 2,
      titulo_es: 'Dónde pesa tu acción',
      bajada_es: 'Qué mueve la aguja de verdad, y dónde deja de moverla.',
      icono: 'Scale',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 4,
      conceptos: [
        {
          slug: 'tronco.no_todo_pesa_igual',
          titulo_es: 'No todas las acciones pesan igual',
          enunciado_es:
            'Dos acciones que se sienten igual de virtuosas pueden diferir cien veces en impacto real. La sensación no es una medida.',
          detalle_es: null,
          fuente: 'owid-alimentos',
          anillo: 2,
          dificultad_base: 0.1,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.orden_de_magnitud'],
        },
        {
          slug: 'tronco.individual_y_colectivo',
          titulo_es: 'Lo individual y lo colectivo',
          enunciado_es:
            'La acción individual importa sobre todo como puerta de entrada a la acción colectiva: cambia hábitos, mercados y reglas cuando se organiza.',
          detalle_es:
            'Ni "no sirve para nada" ni "con reciclar en casa alcanza". Las dos frases fallan por el mismo lado.',
          fuente: 'naaee-guidelines',
          anillo: 2,
          dificultad_base: 0.3,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.escala_local_global'],
          misconceptions: [
            {
              slug: 'tronco.mito_individual_no_sirve',
              creencia_es: 'El impacto individual no sirve para nada (o, al revés: con reciclar en casa alcanza).',
              correccion_es:
                'Las dos versiones fallan igual. La conducta individual pesa sobre todo como entrada a la acción colectiva, política y de consumo, que es donde cambian las reglas.',
              fuente: 'naaee-guidelines',
            },
          ],
        },
        {
          slug: 'tronco.efecto_rebote',
          titulo_es: 'El efecto rebote',
          enunciado_es:
            'Cuando algo se vuelve más eficiente suele usarse más, y parte del ahorro se pierde. Eficiencia no es lo mismo que reducción.',
          detalle_es: null,
          fuente: 'iea-energia',
          anillo: 3,
          dificultad_base: 0.9,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.no_todo_pesa_igual'],
        },
        {
          slug: 'tronco.compensacion_no_es_evitar',
          titulo_es: 'Compensar no es evitar',
          enunciado_es:
            'Pagar una compensación de carbono no borra la emisión: la traslada a un proyecto que puede tardar décadas en absorberla, si la absorbe.',
          detalle_es: null,
          fuente: 'carbon-brief',
          anillo: 3,
          dificultad_base: 1.0,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.stock_vs_flujo'],
        },
        {
          slug: 'tronco.jerarquia_decisiones',
          titulo_es: 'Evitar, reducir, sustituir, compensar',
          enunciado_es:
            'Frente a cualquier impacto el orden es siempre el mismo: primero evitarlo, después reducirlo, después sustituirlo y recién al final compensarlo.',
          detalle_es: null,
          fuente: 'epa',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.no_todo_pesa_igual'],
        },
      ],
      hojas: [
        {
          slug: 'tronco.donde-pesa.1',
          titulo_es: 'Cien veces de diferencia',
          bajada_es: 'Dos acciones que parecen iguales y no lo son.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['tronco.no_todo_pesa_igual', 'tronco.jerarquia_decisiones'],
        },
        {
          slug: 'tronco.donde-pesa.2',
          titulo_es: 'Vos solo y vos con otros',
          bajada_es: 'Dónde termina lo que podés hacer en tu casa.',
          minutos: 5,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 2,
          conceptos: ['tronco.individual_y_colectivo', 'tronco.escala_local_global'],
        },
        {
          slug: 'tronco.donde-pesa.3',
          titulo_es: 'Cuando ahorrar hace gastar',
          bajada_es: 'El rebote, explicado con la luz de tu casa.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['tronco.efecto_rebote', 'tronco.no_todo_pesa_igual'],
        },
        {
          slug: 'tronco.donde-pesa.4',
          titulo_es: 'El último recurso',
          bajada_es: 'Por qué compensar va al final de la lista.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['tronco.compensacion_no_es_evitar', 'tronco.jerarquia_decisiones'],
        },
      ],
    },

    {
      slug: 'tronco.reglas-del-juego',
      anillo: 2,
      titulo_es: 'Las reglas del juego',
      bajada_es: 'Quién decide, con qué ley y dónde entrás vos.',
      icono: 'Landmark',
      age_groups: ['kid', 'teen', 'adult'],
      sort_order: 5,
      conceptos: [
        {
          slug: 'tronco.derecho_ambiente_sano',
          titulo_es: 'Derecho a un ambiente sano',
          enunciado_es:
            'El artículo 41 de la Constitución argentina reconoce el derecho a un ambiente sano y, en la misma frase, el deber de preservarlo.',
          detalle_es: null,
          fuente: 'ley-25675-ambiente',
          anillo: 2,
          dificultad_base: 0.0,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: [],
        },
        {
          slug: 'tronco.presupuestos_minimos',
          titulo_es: 'Presupuestos mínimos',
          enunciado_es:
            'Una ley de presupuestos mínimos fija el piso de protección para todo el país; cada provincia puede exigir más, nunca menos.',
          detalle_es: null,
          fuente: 'ley-25675-ambiente',
          anillo: 2,
          dificultad_base: 0.5,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.derecho_ambiente_sano'],
        },
        {
          slug: 'tronco.principio_precautorio',
          titulo_es: 'El principio precautorio',
          enunciado_es:
            'Cuando hay riesgo de daño grave o irreversible, la falta de certeza científica no puede usarse como excusa para no actuar.',
          detalle_es: null,
          fuente: 'ley-25675-ambiente',
          anillo: 3,
          dificultad_base: 0.8,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.presupuestos_minimos', { slug: 'tronco.incertidumbre', fuerza: 0.6 }],
        },
        {
          slug: 'tronco.educacion_ambiental_ley',
          titulo_es: 'La educación ambiental es ley',
          enunciado_es:
            'La Ley 27.621 hace obligatoria y transversal la educación ambiental integral en todos los niveles, y la extiende a la educación no formal.',
          detalle_es: null,
          fuente: 'ley-27621-eai',
          anillo: 2,
          dificultad_base: 0.2,
          age_groups: ['kid', 'teen', 'adult'],
          sensible: false,
          requiere: ['tronco.derecho_ambiente_sano'],
        },
        {
          slug: 'tronco.acceso_informacion',
          titulo_es: 'Podés pedir la información',
          enunciado_es:
            'El acceso a la información ambiental es un derecho: cualquier persona puede pedirla al Estado sin explicar para qué la quiere.',
          detalle_es: null,
          fuente: 'escazu',
          anillo: 2,
          dificultad_base: 0.4,
          age_groups: ['teen', 'adult'],
          sensible: false,
          requiere: ['tronco.derecho_ambiente_sano'],
        },
      ],
      hojas: [
        {
          slug: 'tronco.reglas-del-juego.1',
          titulo_es: 'Un derecho y un deber',
          bajada_es: 'El artículo 41, en criollo.',
          minutos: 4,
          age_groups: ['kid', 'teen', 'adult'],
          sort_order: 1,
          conceptos: ['tronco.derecho_ambiente_sano', 'tronco.educacion_ambiental_ley'],
        },
        {
          slug: 'tronco.reglas-del-juego.2',
          titulo_es: 'El piso y el techo',
          bajada_es: 'Qué puede hacer Nación y qué puede hacer tu provincia.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 2,
          conceptos: ['tronco.presupuestos_minimos', 'tronco.derecho_ambiente_sano'],
        },
        {
          slug: 'tronco.reglas-del-juego.3',
          titulo_es: 'En la duda, cuidar',
          bajada_es: 'El principio precautorio y por qué existe.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 3,
          conceptos: ['tronco.principio_precautorio', 'tronco.presupuestos_minimos'],
        },
        {
          slug: 'tronco.reglas-del-juego.4',
          titulo_es: 'Preguntar es gratis',
          bajada_es: 'Cómo se pide un dato ambiental y quién tiene que dártelo.',
          minutos: 5,
          age_groups: ['teen', 'adult'],
          sort_order: 4,
          conceptos: ['tronco.acceso_informacion', 'tronco.derecho_ambiente_sano'],
        },
      ],
    },
  ],
};
