// Agua — en casa, en la vereda y en el verano.
import { d, c, agua, aguaCaliente, elec, suma, nada, medida, por } from '../dsl.mjs';

const dom = 'agua';

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('ducha-corta-5-min', 'Bañate en 5 minutos', {
    dom, e: 'easy', i: 'medium', min: 5, rut: true, ahorra: true, lugar: 'casa',
    corto: 'Una ducha larga tira unos 10 litros por minuto, y casi todos calentados con gas.',
    desc: 'La ducha es el mayor gasto de agua caliente de una casa. La Guía de Ahorro de Energía de la Ciudad recomienda no pasar de 10 minutos y, mejor, quedarse en 5. Tres minutos menos son unos 30 litros y el gas que hacía falta para calentarlos.',
    pasos: ['Elegí una canción o poné un timer de 5 minutos antes de abrir la ducha.', 'Mojate, cerrá para enjabonarte y abrí sólo para enjuagarte.', 'Cuando termina la canción, cerrás.'],
    ef: aguaCaliente(30), fuente: 'gcba-energia', tags: ['ducha', 'gas'], hereda: ['agua-cronometro-ducha'],
  }),
  d('agua-cerrar-mientras-shampoo', 'Cerrá la ducha mientras te enjabonás', {
    dom, e: 'easy', i: 'medium', min: 1, rut: true, ahorra: true,
    corto: 'El shampoo y el jabón no necesitan el agua corriendo: son dos minutos de ducha que se van solos.',
    desc: 'Mientras te enjabonás el pelo o el cuerpo, la ducha abierta tira agua caliente que nadie usa. Cerrarla esos dos minutos ahorra unos 20 litros y el gas de calentarlos, sin que la ducha sea más corta.',
    pasos: ['Mojate y cerrá la canilla.', 'Enjabonate el pelo y el cuerpo con la ducha cerrada.', 'Abrí de nuevo sólo para enjuagarte.'],
    ef: aguaCaliente(20), fuente: 'aysa', tags: ['ducha'],
  }),
  d('agua-balde-ducha-fria', 'Juntá en un balde el agua fría de la ducha', {
    dom, e: 'easy', i: 'medium', min: 2, rut: true,
    corto: 'Mientras esperás que salga caliente se van 5 a 8 litros de agua limpia por la rejilla.',
    desc: 'Esos primeros litros fríos son agua potable que se tira sin usar. En un balde sirven para el inodoro, para baldear el patio o para regar. Es uno de los gestos que más agua rescata sin cambiar nada de tu ducha.',
    pasos: ['Dejá un balde en el baño.', 'Ponelo bajo la ducha mientras esperás que salga caliente.', 'Usá esa agua para el inodoro, las plantas o el piso.'],
    ef: agua(6), tags: ['ducha', 'reuso'], hereda: ['reutiliza-el-agua-para-regar-las-plantas'],
  }),
  d('cerra-la-canilla-mientras-te-cepillas-o-enjabona', 'Cerrá la canilla mientras te lavás los dientes', {
    dom, e: 'easy', i: 'low', min: 2, rut: true,
    corto: 'Dos minutos de canilla abierta son unos 10 litros que se van sin tocarte.',
    desc: 'Lavarse los dientes lleva dos minutos y la canilla abierta tira unos 5 litros por minuto. Abrirla sólo para mojar el cepillo y para enjuagarte alcanza de sobra. Si lo hacés dos veces por día, son más de 7.000 litros al año.',
    pasos: ['Mojá el cepillo y cerrá la canilla.', 'Cepillate con la canilla cerrada.', 'Enjuagate con un vaso o abriendo un momento.'],
    ef: agua(10), fuente: 'aysa', tags: ['baño', 'chicos'],
  }),
  d('agua-manos-canilla-cerrada', 'Enjabonate las manos con la canilla cerrada', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Los 20 segundos de jabón son 20 segundos de canilla abierta que no hacen falta.',
    desc: 'Lavarse bien las manos lleva unos 20 segundos de jabón. Con la canilla abierta todo ese tiempo se van 2 litros por lavado; con varios lavados por día, la cuenta crece rápido. Cerrarla mientras te frotás no cambia nada de la higiene.',
    pasos: ['Mojate las manos y cerrá la canilla.', 'Frotá con jabón, también entre los dedos.', 'Abrí para enjuagarte.'],
    ef: agua(4), tags: ['baño', 'chicos'],
  }),
  d('lava-los-platos-con-la-canilla-cerrada', 'Enjaboná los platos con la canilla cerrada', {
    dom, e: 'easy', i: 'low', min: 2, rut: true, ahorra: true, lugar: 'casa',
    corto: 'Lavar con el agua corriendo es de los mayores desperdicios de la cocina.',
    desc: 'Con la canilla abierta mientras enjabonás se van unos 6 litros por minuto. Enjabonar todo primero y enjuagar todo junto, de una pasada, usa una fracción. Si lavás con agua caliente, además ahorrás gas.',
    pasos: ['Juntá los platos y cerrá la canilla.', 'Enjaboná todo con la esponja.', 'Enjuagá todo junto, de una sola vez.'],
    ef: agua(20), tags: ['cocina'], hereda: ['agua-secar-sin-enjuagar-doble'],
  }),
  d('pone-el-lavarropas-solo-cuando-este-lleno', 'Poné el lavarropas sólo con carga completa', {
    dom, e: 'easy', i: 'medium', min: 1, ahorra: true,
    corto: 'Un lavado a medias usa casi la misma agua y la misma luz que uno lleno.',
    desc: 'El lavarropas gasta casi lo mismo con media carga que llena: unos 50 litros por lavado en un automático. Esperar a completar el tambor ahorra lavados enteros a lo largo del mes. La guía de la Ciudad lo pone primero en su lista del lavarropas.',
    pasos: ['Juntá la ropa hasta completar la carga.', 'Si es urgente una sola prenda, lavala a mano.', 'Cuando esté lleno, lavá.'],
    ef: suma(agua(40), elec(0.3)), fuente: 'gcba-energia', tags: ['lavarropas'], hereda: ['energia-lavarropas-carga-completa'],
  }),
  d('agua-programa-corto', 'Elegí el programa corto o eco del lavarropas', {
    dom, e: 'easy', i: 'medium', min: 1, ahorra: true,
    corto: 'La ropa de todos los días no necesita el ciclo más largo.',
    desc: 'La ropa usada un día no está sucia de verdad: el programa corto o eco la deja igual, con menos agua y menos luz. Guardá el ciclo largo para toallas, sábanas o ropa de trabajo con barro.',
    pasos: ['Mirá qué tan sucia está la carga.', 'Si es ropa de uso diario, elegí el programa corto o eco.', 'Usá agua fría salvo que haya manchas difíciles.'],
    ef: suma(agua(20), elec(0.3)), fuente: 'gcba-energia', tags: ['lavarropas'],
  }),
  d('agua-usar-dos-veces', 'Usá la ropa más de una vez antes de lavarla', {
    dom, e: 'easy', i: 'medium', min: 1,
    corto: 'Un jean, un buzo o un pantalón aguantan varias puestas: lavarlos de más los gasta y tira agua.',
    desc: 'Mucha ropa va al lavarropas por costumbre, no porque esté sucia. Si no tiene manchas ni olor, aireala una noche y volvé a usarla. Cada prenda que no se lava es parte de un lavado menos: agua, luz y una prenda que dura más.',
    pasos: ['Antes de tirar algo al canasto, fijate si está sucio de verdad.', 'Si no, colgalo al aire una noche.', 'Volvé a usarlo.'],
    ef: suma(agua(15), elec(0.1)), tags: ['ropa', 'lavarropas'], hereda: ['agua-ropa-menos-lavados'],
  }),
  d('agua-manchas-a-mano', 'Sacá una mancha a mano en vez de lavar todo', {
    dom, e: 'easy', i: 'low', min: 3,
    corto: 'Una mancha chica no justifica un lavado entero.',
    desc: 'Frotar una mancha con un poco de jabón y agua salva una prenda que si no iría al lavarropas. Es más rápido, usa medio litro en vez de decenas, y la prenda se gasta menos.',
    pasos: ['Mojá sólo la parte manchada.', 'Frotá con jabón blanco o detergente.', 'Enjuagá, dejá secar y seguí usándola.'],
    ef: agua(10), tags: ['ropa'],
  }),
  d('agua-lavar-verduras-en-bowl', 'Lavá las verduras en un bowl, no bajo el chorro', {
    dom, e: 'easy', i: 'low', min: 2, rut: true, lugar: 'casa',
    corto: 'Esa agua después riega perfecto una maceta.',
    desc: 'Lavar la verdura bajo la canilla abierta tira varios litros por vez. En un bowl o una fuente con agua queda igual de limpia, y el agua que sobra sirve para regar.',
    pasos: ['Llená un bowl con agua.', 'Lavá ahí las verduras y las frutas, frotando las que tengan tierra.', 'Usá el agua que quedó para regar.'],
    ef: agua(10), tags: ['cocina', 'reuso'],
  }),
  d('agua-remojar-ollas', 'Dejá la olla en remojo en vez de rasparla bajo el chorro', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Diez minutos de remojo ahorran diez minutos de canilla abierta.',
    desc: 'Lo pegado sale solo si lo dejás en remojo mientras comés. Rasparlo con el agua corriendo es de lo que más agua tira en la cocina, y además cansa.',
    pasos: ['Apenas sirvas, poné un poco de agua y detergente en la olla.', 'Dejala mientras comés.', 'Lavala después, ya sin esfuerzo.'],
    ef: agua(12), tags: ['cocina'],
  }),
  d('agua-descongelar-heladera', 'Descongelá en la heladera, no bajo la canilla', {
    dom, e: 'easy', i: 'low', min: 1, rut: true, edad: 'ta',
    corto: 'Descongelar con agua corriendo tira decenas de litros por vez.',
    desc: 'Pasar lo congelado a la heladera la noche anterior descongela de forma pareja y segura, sin gastar agua. Además el frío que suelta ayuda a la heladera.',
    pasos: ['A la noche, pensá qué vas a cocinar mañana.', 'Pasalo del freezer a la heladera, en un plato.', 'Al otro día está listo.'],
    ef: agua(20), tags: ['cocina'], hereda: ['agua-descongelar-en-heladera'],
  }),
  d('agua-regar-temprano', 'Regá temprano o al atardecer', {
    dom, e: 'easy', i: 'low', min: 5, est: ['primavera', 'verano'],
    corto: 'Al mediodía buena parte del riego se evapora antes de llegar a la raíz.',
    desc: 'En los meses de calor, regar al mediodía es regar el aire. AySA recomienda hacerlo muy temprano o al caer el sol: la tierra lo absorbe, las plantas lo aprovechan y necesitás menos agua para el mismo resultado.',
    pasos: ['Regá antes de las 9 o después de las 19.', 'Regá la tierra, al pie de la planta, no las hojas.', 'Si la tierra está húmeda a un dedo de profundidad, esperá.'],
    ef: agua(5), fuente: 'aysa', tags: ['riego', 'plantas'], hereda: ['rega-tus-plantas-al-amanecer-o-atardecer', 'pla-regar-a-la-tierra'],
  }),
  d('agua-tapon-en-la-pileta', 'Poné el tapón antes de abrir la canilla', {
    dom, e: 'easy', i: 'low', min: 1,
    corto: 'Para lavarte la cara o las manos alcanza con un poco de agua en la pileta.',
    desc: 'Con el tapón puesto usás un litro de agua en vez de dejar correr varios. Sirve para lavarte la cara, afeitarte o enjuagar algo chico.',
    pasos: ['Tapá la pileta.', 'Llenala un poco.', 'Usá esa agua para lo que tengas que hacer.'],
    ef: agua(3), tags: ['baño'],
  }),
  d('agua-inodoro-no-papelera', 'No uses el inodoro como tacho de basura', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Cada descarga de más son unos 9 litros por un pañuelito.',
    desc: 'Pañuelos, pelos, algodones o colillas en el inodoro gastan una descarga entera y tapan cañerías. Al tacho del baño van mejor: menos agua y menos problemas en la cloaca.',
    pasos: ['Dejá un tachito con tapa en el baño.', 'Tirá ahí pañuelos, algodones y pelos.', 'Descargá el inodoro sólo cuando lo usaste.'],
    ef: agua(9), tags: ['baño'],
  }),
  d('agua-reusar-agua-pastas', 'Regá con el agua que te sobró', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'La de la pava, la del vaso o la de hervir verduras: fría, es agua para las plantas.',
    desc: 'En una casa sobra agua limpia todo el tiempo: el fondo de la pava, el vaso que quedó, la cocción de las verduras sin sal. Una vez fría, regar con ella es agua que no sale de la canilla.',
    pasos: ['Dejá una jarra o botella cerca de la pileta de la cocina.', 'Volcá ahí el agua limpia que te sobre.', 'Cuando se enfríe, regá con ella.'],
    ef: agua(3), tags: ['reuso', 'mate', 'plantas'], hereda: ['agua-hervir-verduras-reusar-caldo', 'agua-regar-con-el-agua-del-mate', 'agua-hervir-justa'],
  }),
  d('agua-escoba-no-manguera', 'Barré la vereda en vez de baldearla', {
    dom, e: 'easy', i: 'medium', min: 10, lugar: 'calle', rut: true,
    corto: 'Baldear con manguera tira más de 10 litros por minuto en la vereda.',
    desc: 'Baldear la vereda es una costumbre muy nuestra, y una de las que más agua potable tira. Con escoba y pala queda igual de limpia; si hace falta, un balde con un poco de agua alcanza para lo pegado.',
    pasos: ['Barré con escoba y juntá con pala.', 'Si hay algo pegado, usá un balde, no la manguera.', 'Tirá lo juntado a la basura, no a la alcantarilla.'],
    ef: agua(80), fuente: 'aysa', tags: ['vereda'],
  }),
  d('agua-no-jugar-con-manguera', 'Refrescate sin dejar la manguera abierta', {
    dom, e: 'easy', i: 'medium', min: 5, edad: 'kt', est: ['verano'], lugar: 'casa',
    corto: 'Un rato de manguera abierta son cientos de litros.',
    desc: 'En verano dan ganas de jugar con la manguera, pero abierta tira más de 10 litros por minuto. Un balde, una pileta chica o una toalla mojada refrescan igual y el agua alcanza para todos, sobre todo en los días en que la red no da abasto.',
    pasos: ['Llená un balde o una pileta chica.', 'Jugá o refrescate con esa agua.', 'Cuando termines, regá las plantas con lo que quedó.'],
    ef: agua(100), tags: ['verano', 'chicos'],
  }),
  d('agua-tapa-pileta', 'Tapá la pileta a la noche', {
    dom, e: 'easy', i: 'medium', min: 3, req: ['pileta'], est: ['verano'],
    corto: 'Una pileta destapada pierde por evaporación decenas de litros por día.',
    desc: 'El sol y el viento evaporan varios milímetros de pileta por día: en una pileta chica son decenas de litros que después se reponen con la manguera. Taparla cuando nadie la usa también la mantiene limpia por más tiempo.',
    pasos: ['Cuando termines de usarla, cubrila con su lona o una manta térmica.', 'Sacala recién cuando la vayan a usar.'],
    ef: agua(30), tags: ['pileta', 'verano'], hereda: ['agua-cubrir-pileta', 'agua-tapar-la-pileta-o-fuente'],
  }),
  d('agua-ola-de-calor', 'En días de calor, dejá para otro día lo que gasta mucha agua', {
    dom, e: 'easy', i: 'medium', min: 2, est: ['verano'],
    corto: 'Cuando hace mucho calor, las plantas potabilizadoras trabajan al límite.',
    desc: 'En las olas de calor el consumo se dispara y AySA pide priorizar el agua para tomar, cocinar y la higiene. Lavar el auto, baldear o llenar la pileta pueden esperar a un día fresco, y así no le falta presión a nadie.',
    pasos: ['Si hoy hace mucho calor, no laves el auto ni baldees la vereda.', 'Si tenés que llenar algo grande, hacelo de noche.', 'Guardá agua en la heladera para tomar.'],
    ef: agua(50), fuente: 'aysa', tags: ['verano', 'calor'],
  }),
  d('agua-deshumidificador', 'Juntá el agua que gotea del aire acondicionado', {
    dom, e: 'easy', i: 'low', min: 2, req: ['aire'], est: ['verano'],
    corto: 'Un split puede largar varios litros por día de agua limpia que caen al balcón.',
    desc: 'El aire acondicionado saca la humedad del ambiente y la tira por la manguera de desagote. Es agua destilada: no sirve para tomar, pero sí para el inodoro, el piso o las plantas.',
    pasos: ['Poné un balde o un bidón donde gotea el desagote.', 'Al final del día, usalo para el inodoro, el piso o regar.'],
    ef: agua(8), tags: ['verano', 'reuso'],
  }),
  d('agua-guardian-del-dia', 'Sé guardián del agua de tu casa por un día', {
    dom, e: 'easy', i: 'low', min: 10, edad: 'k', adulto: true,
    corto: 'Una misión: que hoy ninguna canilla quede abierta sin que nadie la use.',
    desc: 'Hoy sos el guardián del agua. Tu trabajo es revisar canillas, avisar con buena onda cuando alguien deja el agua corriendo y anotar cuántas veces lo salvaste. Al final del día, contale a tu familia cuánta agua cuidaron.',
    pasos: ['Recorré la casa y fijate que ninguna canilla gotee.', 'Si ves agua corriendo sin usar, avisá.', 'A la noche contá cuántas veces cuidaste el agua.'],
    ef: agua(10), tags: ['chicos', 'mision'],
  }),
  d('agua-afeitarse-vaso', 'Afeitate con la pileta tapada, no con la canilla abierta', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'Enjuagar la maquinita en un poco de agua alcanza.',
    desc: 'Afeitarse con la canilla abierta tira varios litros cada vez. Con un vaso o la pileta tapada con un poco de agua se enjuaga igual de bien.',
    pasos: ['Tapá la pileta o llená un vaso.', 'Enjuagá ahí la maquinita entre pasada y pasada.'],
    ef: agua(8), tags: ['baño'],
  }),
  d('agua-hielo-a-la-planta', 'Los hielos que sobran, a una maceta', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'k',
    corto: 'Se derriten despacio y riegan sin encharcar.',
    desc: 'Cuando sobran hielos del vaso o de la cubetera, en vez de tirarlos en la pileta podés ponerlos en una maceta. Se derriten de a poco y la planta toma el agua sin que se escurra.',
    pasos: ['Juntá los hielos que sobraron.', 'Ponelos sobre la tierra de una maceta, sin tocar el tallo.'],
    ef: agua(1), tags: ['chicos', 'plantas'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('agua-medi-tu-ducha', 'Medí cuánta agua sale de tu ducha', {
    dom, e: 'easy', i: 'medium', min: 5, formato: 'aprender', frec: 'one_time', edad: 'kta', adulto: true,
    corto: 'Con un balde y un reloj sabés cuántos litros por minuto te bañan.',
    desc: 'Un experimento de 30 segundos: si sabés cuánto larga tu ducha por minuto, sabés cuánto gasta cada baño. La mayoría sale entre 8 y 15 litros por minuto; multiplicado por los minutos de ducha, el número sorprende.',
    pasos: ['Poné un balde bajo la ducha abierta como siempre durante 30 segundos.', 'Medí cuántos litros juntaste (un balde común marca las rayitas) y multiplicá por 2.', 'Multiplicá por los minutos que dura tu ducha: ese es tu gasto.'],
    ef: nada(), tags: ['ducha', 'experimento'],
  }),
  c('agua-revisar-el-medidor', 'Buscá pérdidas ocultas con el medidor', {
    dom, e: 'easy', i: 'medium', min: 10, edad: 'ta', cool: 2160,
    corto: 'Una pérdida dentro de la pared puede correr meses sin que la escuches.',
    desc: 'Si tenés medidor de agua, es la forma más fácil de saber si hay una pérdida escondida. Con todo cerrado, el medidor no se tiene que mover. Si se mueve, algo pierde, y conviene buscarlo antes de que aparezca la mancha de humedad.',
    pasos: ['Cerrá todas las canillas y no uses agua por una hora.', 'Anotá el número del medidor al empezar y al terminar.', 'Si cambió, hay una pérdida: revisá inodoros, canillas y el tanque.'],
    ef: nada(), tags: ['perdidas'], hereda: ['agua-leer-medidor'],
  }),
  c('agua-revisar-perdida-inodoro', 'Hacé la prueba del colorante en el inodoro', {
    dom, e: 'easy', i: 'medium', min: 25, edad: 'kta', adulto: true, cool: 2160,
    corto: 'La pérdida del inodoro es la más común y la que menos se ve.',
    desc: 'Una válvula gastada deja correr agua de la mochila al inodoro todo el día, en silencio: pueden ser cientos de litros diarios. La prueba es fácil y la puede hacer cualquiera en casa.',
    pasos: ['Echá unas gotas de colorante de comida (o un poco de café) en la mochila.', 'No descargues durante 20 minutos.', 'Si el agua del inodoro se tiñó, hay pérdida: hay que cambiar la válvula o el flotante.'],
    ef: nada(), tags: ['perdidas', 'baño', 'experimento'],
  }),
  c('arregla-una-canilla-o-inodoro-que-pierde', 'Arreglá una canilla que gotea', {
    dom, e: 'medium', i: 'high', min: 30, edad: 'ta', costo: 'bajo', ahorra: true, frec: 'recurring', cool: 720,
    corto: 'Una gota por segundo son unos 30 litros por día, todos los días.',
    desc: 'Casi siempre es el cuerito o el vástago, que cuestan poco y se cambian con una llave. AySA pide reparar rápido cualquier pérdida: una canilla que gotea tira en un mes lo que una familia toma en meses.',
    pasos: ['Cerrá la llave de paso de esa canilla o de la casa.', 'Desarmá la canilla y cambiá el cuerito o el vástago (en la ferretería te dan el mismo).', 'Si no te animás, pedile a alguien que sepa: el arreglo es corto.'],
    ef: agua(900), fuente: 'aysa', tags: ['perdidas', 'arreglo'],
  }),
  c('agua-aireador-canilla', 'Poné aireadores en las canillas', {
    dom, e: 'easy', i: 'high', min: 10, edad: 'ta', costo: 'bajo', ahorra: true, frec: 'one_time',
    corto: 'Cuestan poco, se enroscan a mano y bajan el caudal entre 35% y 50%.',
    desc: 'El aireador mezcla aire con el agua: el chorro se siente igual pero sale bastante menos. La Guía de Ahorro de Energía de la Ciudad calcula entre un 35% y un 50% menos de consumo en esa canilla.',
    pasos: ['Fijate si tu canilla tiene rosca en la punta (casi todas tienen).', 'Comprá un aireador de la medida en la ferretería.', 'Enroscalo a mano en lugar del que tiene.'],
    ef: agua(300), fuente: 'gcba-energia', tags: ['arreglo', 'cocina', 'baño'],
  }),
  c('agua-botella-en-mochila-inodoro', 'Poné una botella con agua en la mochila del inodoro', {
    dom, e: 'easy', i: 'medium', min: 10, edad: 'ta', frec: 'one_time',
    corto: 'Ocupa lugar dentro de la mochila: cada descarga usa un litro menos.',
    desc: 'En los inodoros de descarga única, una botella llena dentro de la mochila hace que cada descarga use menos agua sin que se note. Con cinco descargas diarias, son unos 150 litros por mes.',
    pasos: ['Llená una botella de 1 litro con agua (o con arena para que no flote) y tapala.', 'Abrí la tapa de la mochila y ponela en un costado, lejos del flotante y la válvula.', 'Descargá y fijate que todo funcione igual.'],
    ef: agua(150), tags: ['baño'],
  }),
  c('agua-revisar-tanque', 'Revisá que el tanque no rebalse', {
    dom, e: 'easy', i: 'medium', min: 15, edad: 'a', cool: 4320,
    corto: 'Un flotante trabado puede tirar agua por el rebalse todo el día.',
    desc: 'Si tu casa tiene tanque de reserva, el flotante corta el agua cuando se llena. Si se traba, el agua se va por el caño de rebalse sin que nadie lo vea. Conviene mirarlo dos veces por año, y aprovechar para ver si está limpio y tapado.',
    pasos: ['Subí con cuidado o mirá el caño de rebalse desde abajo.', 'Si sale agua de forma constante, el flotante no corta: hay que regularlo o cambiarlo.', 'Fijate que el tanque esté tapado y limpio.'],
    ef: nada(), tags: ['perdidas', 'tanque'],
  }),
  c('agua-juntar-lluvia', 'Armá un recolector de agua de lluvia', {
    dom, e: 'medium', i: 'high', min: 45, req: ['balcon'], edad: 'ta', frec: 'one_time',
    corto: 'Un tacho bajo la bajada del techo junta cientos de litros en una tormenta.',
    desc: 'Un milímetro de lluvia sobre un metro cuadrado de techo es un litro de agua. Un tacho o bidón con tapa bajo la bajada pluvial junta agua de sobra para regar todo el mes. Tapado y vaciado seguido, no cría mosquitos.',
    pasos: ['Conseguí un tacho o bidón grande con tapa.', 'Ponelo bajo la bajada del techo o de la canaleta, con una malla arriba para frenar hojas.', 'Usá esa agua para regar y vaciala dentro de la semana para que no críe mosquitos.'],
    ef: agua(400), tags: ['lluvia', 'riego', 'dengue'], hereda: ['instala-un-sistema-de-recoleccion-de-agua-de-llu'],
  }),
  c('agua-balde-de-lluvia', 'Poné un balde a juntar lluvia', {
    dom, e: 'easy', i: 'low', min: 2, edad: 'kta', cool: 72,
    corto: 'La próxima vez que llueva, sacá un balde: esa agua riega sin cloro.',
    desc: 'No hace falta un sistema: un balde o una palangana al aire libre durante una lluvia junta varios litros. A las plantas les gusta más que la de la canilla.',
    pasos: ['Cuando empiece a llover, sacá un balde al patio o al balcón.', 'Usá esa agua para regar en los días siguientes.', 'Vaciá lo que quede antes de una semana, para que no críe mosquitos.'],
    ef: agua(10), tags: ['lluvia', 'chicos'],
  }),
  c('reutiliza-aguas-grises-para-el-jardin', 'Regá el jardín con el agua del lavarropas', {
    dom, e: 'medium', i: 'medium', min: 15, req: ['jardin'], edad: 'ta', cool: 168,
    corto: 'El agua del último enjuague sale casi limpia y riega de sobra.',
    desc: 'El enjuague del lavarropas son decenas de litros que se van por la cloaca. Si usás jabón suave y sin lavandina, esa agua sirve para regar el pasto y los árboles (mejor no la huerta).',
    pasos: ['Poné la manguera de desagote en un balde o un tacho durante el último enjuague.', 'Usá esa agua para el pasto o los árboles, no para verduras que se comen crudas.', 'No lo hagas si lavaste con lavandina.'],
    ef: agua(60), tags: ['reuso', 'lavarropas', 'riego'],
  }),
  c('agua-pelopincho-reusar', 'Reusá el agua de la pileta inflable', {
    dom, e: 'easy', i: 'high', min: 30, req: ['pileta'], est: ['verano'], edad: 'kta', adulto: true, cool: 168,
    corto: 'Una pelopincho son cientos de litros: no hace falta tirarlos por la rejilla.',
    desc: 'Cuando la vacíes, esa agua todavía sirve: para regar, para limpiar el patio o el auto, para el inodoro. Y si le cambiás menos seguido el agua (con un colador de hojas y tapándola), dura más.',
    pasos: ['Antes de vaciarla, regá con baldes las plantas y el pasto.', 'Usá otra parte para limpiar el patio o el auto.', 'Vaciá el resto en tierra, no en la vereda.'],
    ef: agua(300), tags: ['pileta', 'verano', 'reuso'],
  }),
  c('agua-balde-lavar-auto', 'Lavá el auto con balde, no con manguera', {
    dom, e: 'easy', i: 'high', min: 30, req: ['auto'], edad: 'ta', cool: 168,
    corto: 'Una manguera abierta tira cientos de litros; con dos baldes alcanza.',
    desc: 'Lavar el auto con la manguera corriendo puede gastar 300 litros. Con un balde para enjabonar y otro para enjuagar, menos de 30. Y si lo hacés a la sombra, el jabón no se seca y necesitás menos agua.',
    pasos: ['Llená un balde con agua y detergente y otro con agua limpia.', 'Lavá por partes con una esponja y enjuagá con un trapo.', 'Usá la manguera sólo para un enjuague corto final, si hace falta.'],
    ef: agua(250), tags: ['auto'], hereda: ['agua-balde-en-vez-de-manguera'],
  }),
  c('instala-un-cabezal-de-ducha-de-bajo-caudal', 'Cambiá la flor de la ducha por una de bajo caudal', {
    dom, e: 'easy', i: 'high', min: 15, edad: 'a', costo: 'bajo', ahorra: true, frec: 'one_time',
    corto: 'Se enrosca a mano y baja el consumo de cada ducha sin que se note.',
    desc: 'Las flores de ducha eficientes mezclan aire con el agua y bajan el caudal de 12–15 a 7–9 litros por minuto. En una casa de cuatro personas son miles de litros de agua caliente por mes, y gas que no se quema.',
    pasos: ['Mirá la rosca de tu flor actual (casi todas son estándar).', 'Comprá una flor de bajo caudal en la ferretería o el corralón.', 'Desenroscá la vieja, poné cinta de teflón y enroscá la nueva.'],
    ef: aguaCaliente(500), fuente: 'gcba-energia', tags: ['ducha', 'arreglo'],
  }),
  c('agua-avisar-perdida-calle', 'Reportá una pérdida de agua en la calle', {
    dom, e: 'easy', i: 'medium', min: 5, edad: 'ta', lugar: 'calle', formato: 'social', cool: 720,
    corto: 'Un caño roto en la vereda tira miles de litros antes de que alguien avise.',
    desc: 'Si ves agua limpia saliendo de la vereda, de una tapa o de la calle sin que haya llovido, casi seguro es un caño roto. Las empresas de agua tienen línea y web para reportarlo: un aviso con la dirección exacta acelera el arreglo.',
    pasos: ['Anotá la dirección exacta (calle, altura y esquina).', 'Sacá una foto si podés.', 'Reportalo a la empresa de agua de tu ciudad o al municipio.'],
    ef: nada(), fuente: 'aysa', tags: ['perdidas', 'barrio'], hereda: ['reporta-una-perdida-de-agua-en-la-via-publica'],
  }),
  c('agua-ensenar-a-alguien', 'Enseñale a alguien un truco para ahorrar agua', {
    dom, e: 'easy', i: 'medium', min: 5, formato: 'social', cool: 336,
    corto: 'Lo que contás se multiplica: cada persona que cambia un hábito ahorra todo el año.',
    desc: 'Contarle a alguien de tu casa, tu escuela o tu trabajo un truco concreto (el balde en la ducha, la prueba del inodoro, regar temprano) tiene más impacto que hacerlo solo, porque se repite en otra casa.',
    pasos: ['Elegí un truco que hagas vos.', 'Contáselo a alguien explicando por qué sirve.', 'Si lo prueba, contale cuánta agua ahorra.'],
    ef: nada(), tags: ['compartir'],
  }),
  c('agua-calcular-huella', 'Anotá cuánta agua usás en un día', {
    dom, e: 'medium', i: 'medium', min: 15, formato: 'aprender', frec: 'one_time', edad: 'kta', adulto: true,
    corto: 'La OMS dice que con 50 litros por persona se cubre lo básico; en Buenos Aires se consumen muchos más.',
    desc: 'Contar duchas, descargas, lavados y riegos de un día y multiplicarlos por lo que gasta cada uno da tu número. AySA registra consumos de hasta 250 litros por habitante en verano, cuando la OMS considera que 50 alcanzan para lo básico.',
    pasos: ['Anotá durante un día cada uso: ducha (10 L/min), inodoro (9 L), lavarropas (50 L), platos, riego.', 'Sumalos.', 'Elegí el uso más grande y pensá cómo bajarlo.'],
    ef: nada(), fuente: 'oms-agua-potable', tags: ['experimento'],
  }),
  c('agua-acequia-limpia', 'Limpiá la acequia de tu vereda', {
    dom, e: 'medium', i: 'medium', min: 20, reg: ['cuyo'], lugar: 'calle', edad: 'ta', cool: 336,
    corto: 'En Cuyo la acequia riega el árbol de tu vereda: tapada de basura, no llega el agua.',
    desc: 'Las acequias son las que mantienen vivo el arbolado de las ciudades de Cuyo. Mantener limpio el tramo frente a tu casa (sin bolsas, hojas acumuladas ni escombros) deja correr el agua hasta los árboles de toda la cuadra.',
    pasos: ['Sacá bolsas, plásticos y hojas acumuladas del tramo de tu vereda.', 'No tires restos de poda ni agua con jabón a la acequia.', 'Tirá lo que juntaste a la basura.'],
    ef: nada(), tags: ['acequia', 'arbol', 'barrio'],
  }),
  c('agua-riego-por-goteo-casero', 'Armá un riego por goteo con una botella', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['balcon'], edad: 'kta', adulto: true, frec: 'one_time',
    corto: 'Una botella con agujeritos riega despacio, justo en la raíz, sin que se evapore.',
    desc: 'En las zonas secas del país el riego por goteo es la forma más eficiente de regar: el agua va de a poco a la raíz y no se pierde por el costado. Con una botella de plástico se arma en minutos y le das una segunda vida.',
    pasos: ['Hacé 3 o 4 agujeritos chicos en la tapa de una botella.', 'Llenala de agua y enterrala boca abajo junto a la planta.', 'Rellenala cuando se vacíe.'],
    ef: agua(30), tags: ['riego', 'plantas', 'reuso'],
  }),
];
