// Alimentación — que no se tire comida, de estación, del barrio y rica.
// Sin encuadre anti-carne (decisión del dueño, F1.2): aprovechamiento,
// estación, legumbres y desperdicio cero.
import { d, c, comida, gasKwh, plastico, suma, nada } from '../dsl.mjs';

const dom = 'alimentacion';

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('res-primero-lo-que-vence', 'Cociná primero lo que está por vencer', {
    dom, e: 'easy', i: 'medium', min: 3, rut: true, ahorra: true,
    corto: 'Lo viejo adelante, lo nuevo atrás: así no se pierde nada en el fondo de la heladera.',
    desc: 'Buena parte de la comida que se tira en las casas se compró y se olvidó. El PNUMA calcula que los hogares desperdician casi un 60% de toda la comida que se tira en el mundo. Revisar qué está por vencer antes de decidir qué cocinar es la forma más simple de no sumar a esa cuenta.',
    pasos: ['Abrí la heladera y la alacena antes de decidir qué cocinar.', 'Elegí lo que vence primero o lo que está más maduro.', 'Armá la comida alrededor de eso.'],
    ef: comida(0.15), fuente: 'unep-food-waste-2024', tags: ['desperdicio', 'cocina'],
  }),
  d('aprovecha-las-sobras-dia-sin-desperdicio', 'Comé las sobras de ayer', {
    dom, e: 'easy', i: 'medium', min: 2, rut: true, ahorra: true,
    corto: 'Lo que sobró ayer es el almuerzo de hoy: comida ya hecha, sin gastar nada más.',
    desc: 'Las sobras que quedan en la heladera son lo primero que se tira. Planear comerlas (tal cual o transformadas en otra cosa) evita tirar comida, y gas, y plata.',
    pasos: ['Mirá qué quedó de ayer.', 'Comelo tal cual o transformalo: tarta, revuelto, empanadas, ensalada.'],
    ef: comida(0.3), tags: ['desperdicio', 'sobras'],
  }),
  d('ali-porcion-justa', 'Serví de a poco y repetí si querés', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Lo que queda en el plato casi siempre va a la basura; lo que queda en la olla, no.',
    desc: 'Servirse de más es la forma más común de tirar comida en la mesa. Si servís de a poco y repetís con hambre, lo que sobra queda en la olla y se guarda.',
    pasos: ['Serví un poco menos de lo que creés que vas a comer.', 'Si te quedás con hambre, repetí.'],
    ef: comida(0.1), tags: ['desperdicio', 'chicos'],
  }),
  d('alim-congela-lo-que-sobro', 'Congelá lo que no vas a llegar a comer', {
    dom, e: 'easy', i: 'medium', min: 3, rut: true, ahorra: true,
    corto: 'El freezer frena el desperdicio: lo que se olvida en la heladera termina en la basura.',
    desc: 'Si ves que algo no lo vas a comer a tiempo (sobras, pan, fruta madura, carne que compraste de más), porcionalo y congelalo ese mismo día con la fecha escrita. Así no se pierde y lo tenés listo para un día sin tiempo.',
    pasos: ['Porcioná lo que sobró en recipientes o bolsas chicas.', 'Escribí qué es y la fecha.', 'Congelalo el mismo día.'],
    ef: comida(0.3), tags: ['desperdicio', 'freezer'], hereda: ['res-congelar-lo-que-sobra', 'ali-congelar-en-porciones'],
  }),
  d('ali-pan-duro', 'Rescatá el pan duro', {
    dom, e: 'easy', i: 'low', min: 5, rut: true,
    corto: 'Tostadas, budín o pan rallado para las milanesas: nunca es basura.',
    desc: 'El pan es de lo que más se tira. El que quedó duro sirve para tostadas, croutons, budín de pan o pan rallado (rallado y guardado en un frasco dura semanas).',
    pasos: ['Cortalo en rodajas para tostar, o en cubitos para croutons.', 'Lo que no uses, rallalo y guardalo en un frasco.'],
    ef: comida(0.1), tags: ['desperdicio', 'pan'],
  }),
  d('ali-verduras-de-estacion', 'Comprá fruta y verdura de estación', {
    dom, e: 'easy', i: 'low', min: 2, lugar: 'compras',
    corto: 'Lo de estación está en su mejor momento: más rico, más barato y sin cámaras ni invernaderos.',
    desc: 'La fruta y verdura de estación no necesita meses de cámara de frío ni invernaderos calefaccionados. En la verdulería se nota: está más barata y más rica. Preguntá qué entró esta semana.',
    pasos: ['Preguntá en la verdulería qué está de estación.', 'Armá la compra de la semana con eso.'],
    tags: ['estacion', 'compras', 'verduleria'], hereda: ['come-una-comida-sin-carne-hoy'],
    mercado: ['alimentos-frescos', 'frutas-y-verduras', 'De estación y de cerca. Estos productores y comercios están en el programa de Brote.'],
  }),
  d('ali-legumbres-hoy', 'Sumá legumbres a una comida', {
    dom, e: 'easy', i: 'medium', min: 5, rut: true, ahorra: true,
    corto: 'Lentejas, garbanzos y porotos: proteína barata con una huella mínima.',
    desc: 'Las legumbres dan proteína y fibra con muy poca agua, tierra y emisiones, y fijan nitrógeno en el suelo donde crecen. Un guiso de lentejas, garbanzos en la ensalada o porotos en la sopa: hay mil formas.',
    pasos: ['Elegí una legumbre que tengas o que consigas suelta.', 'Sumala a una comida: guiso, ensalada, hamburguesas caseras, hummus.'],
    fuente: 'owid-alimentos', tags: ['legumbres', 'cocina'], hereda: ['alim-cocina-con-legumbres'],
    mercado: ['almacen-granel', 'legumbres-y-cereales', 'Legumbres sueltas, a granel. Estos negocios están en el programa de Brote.'],
  }),
  d('alim-cocina-solo-con-lo-que-hay', 'Hacé una comida sin comprar nada', {
    dom, e: 'easy', i: 'medium', min: 20, ahorra: true,
    corto: 'La alacena esconde comida que se vence antes de usarse.',
    desc: 'Antes de ir a comprar, armá una comida sólo con lo que ya hay: el arroz del fondo, la lata que quedó, la verdura que hay que usar. Es la forma más directa de que nada se venza olvidado.',
    pasos: ['Mirá qué hay en la heladera, el freezer y la alacena.', 'Armá una comida con eso (una búsqueda de recetas por ingrediente ayuda).'],
    ef: comida(0.2), tags: ['desperdicio', 'cocina'], hereda: ['ali-receta-con-lo-que-hay'],
  }),
  d('ali-cocinar-de-mas-para-manana', 'Cociná doble y guardá para mañana', {
    dom, e: 'easy', i: 'low', min: 5, edad: 'ta', rut: true, ahorra: true,
    corto: 'Cocinar una vez para dos comidas usa casi la mitad de gas.',
    desc: 'Hacer el doble de lo mismo tarda casi lo mismo y gasta mucho menos que cocinar dos veces. Mañana tenés el almuerzo resuelto o la vianda lista.',
    pasos: ['Duplicá la receta.', 'Guardá la mitad en la heladera o el freezer apenas se enfríe.'],
    ef: gasKwh(0.5), tags: ['cocina', 'vianda'],
  }),
  d('ali-cascaras-y-tallos', 'Cociná con tallos, hojas y cáscaras', {
    dom, e: 'easy', i: 'low', min: 10, edad: 'ta',
    corto: 'Los tallos del brócoli, las hojas de la remolacha y la cáscara de la papa se comen.',
    desc: 'Mucho de lo que se tira al pelar es comestible y nutritivo. Los tallos del brócoli salteados, las hojas de remolacha en una tortilla o las cáscaras de papa al horno son comida, no basura.',
    pasos: ['Lavá bien las verduras antes de cortarlas.', 'Usá tallos y hojas en sopas, tortillas o salteados.', 'Lo que no se come, al compost.'],
    ef: comida(0.1), tags: ['desperdicio', 'cocina'], hereda: ['res-usar-tallos-y-cascaras'],
  }),
  d('ali-fruta-madura-licuado', 'Hacé un licuado o una compota con la fruta muy madura', {
    dom, e: 'easy', i: 'low', min: 10, adulto: true,
    corto: 'La banana con manchitas es la más dulce: perfecta para un licuado o un budín.',
    desc: 'La fruta que ya nadie quiere comer porque está muy madura es ideal para licuados, compotas, budines o mermeladas. Si no da para hoy, pelala, cortala y congelala para usarla después.',
    pasos: ['Juntá la fruta muy madura.', 'Hacé un licuado, una compota o un budín.', 'Si no da para hoy, cortala y congelala.'],
    ef: comida(0.2), tags: ['desperdicio', 'fruta', 'chicos'],
  }),
  d('alim-llevate-la-vianda', 'Llevate la comida en vianda', {
    dom, e: 'easy', i: 'medium', min: 5, dias: 'habil', lugar: 'calle', rut: true, ahorra: true,
    corto: 'La comida para llevar viene siempre con envases de un solo uso; tu vianda, no.',
    desc: 'Llevar la comida de casa al trabajo, la escuela o la facu ahorra plata y todos los envases de la comida comprada. Y si cocinaste doble ayer, ya está hecha.',
    pasos: ['A la noche, dejá lista la vianda en un tupper.', 'Sumá una botella de agua y cubiertos de casa.'],
    ef: plastico(0.03), tags: ['vianda', 'plastico', 'trabajo', 'escuela'],
  }),
  d('ali-feria-o-verduleria', 'Comprá en la verdulería o la feria del barrio', {
    dom, e: 'easy', i: 'low', min: 15, lugar: 'compras',
    corto: 'Menos envases, menos kilómetros, y sostenés al comercio de tu barrio.',
    desc: 'En la verdulería o la feria la fruta y la verdura vienen sin bandejas ni film, comprás la cantidad justa y caminando. Además le das trabajo al comercio del barrio.',
    pasos: ['Llevá tu bolsa.', 'Comprá la fruta y verdura de la semana en la verdulería o la feria.', 'Pedí la cantidad justa, aunque sea una sola papa.'],
    ef: plastico(0.02), tags: ['compras', 'verduleria', 'barrio'], hereda: ['reduci-los-lacteos-hoy'],
    mercado: ['alimentos-frescos', 'frutas-y-verduras', 'Si no tenés feria cerca, estos productores del programa de Brote venden directo.'],
  }),
  d('ali-fruta-fea', 'Elegí la fruta o la verdura fea', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'compras',
    corto: 'Es igual de buena, y es la primera que se tira por su forma.',
    desc: 'Las frutas torcidas, con marcas o desparejas son igual de ricas y nutritivas, pero son las que se descartan primero en el campo y en la verdulería. Elegirlas a propósito evita que se pierdan.',
    pasos: ['En la verdulería, elegí a propósito la fruta o verdura con marcas o forma rara.', 'Si hay cajón de "ofertas" de maduras, aprovechalo para licuados o salsas.'],
    ef: comida(0.1), tags: ['desperdicio', 'verduleria'], hereda: ['alim-compra-fruta-fea'],
  }),
  d('ali-menos-desperdicio-pan', 'Comprá el pan justo para hoy', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'compras',
    corto: 'El pan es de lo que más se tira: mejor un poco menos y fresco.',
    desc: 'Comprar en la panadería la cantidad que se va a comer hoy (y congelar lo que sobra apenas llega a casa) evita la bolsa de pan duro que termina en la basura.',
    pasos: ['Pensá cuánto pan se come hoy en tu casa.', 'Comprá eso.', 'Si sobra, congelalo en rodajas.'],
    ef: comida(0.1), tags: ['pan', 'desperdicio'],
  }),
  d('ali-media-porcion', 'Pedí media porción si sabés que no la terminás', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', lugar: 'calle',
    corto: 'Las porciones de afuera son grandes: lo que queda en el plato se tira.',
    desc: 'En muchos restaurantes y rotiserías se puede pedir media porción o compartir un plato. Si no, pedí que te pongan lo que sobra para llevar.',
    pasos: ['Preguntá si hay media porción o si se puede compartir.', 'Si sobra, pedí que te lo envuelvan (mejor en tu tupper).'],
    ef: comida(0.15), tags: ['desperdicio'],
  }),
  d('ali-asado-justo', 'Calculá el asado para que no sobre', {
    dom, e: 'easy', i: 'medium', min: 5, req: ['parrilla'], dias: 'finde', edad: 'ta',
    corto: 'Comprar "por las dudas" es la mejor forma de que sobre y se tire.',
    desc: 'Para un asado se calculan unos 300 a 400 gramos por persona entre todos los cortes, contando achuras y chorizos. Comprar lo justo (y pensar antes qué se hace con lo que sobra) evita tirar comida y plata.',
    pasos: ['Contá cuántos van a comer y calculá unos 350 g por persona.', 'Sumá verduras a la parrilla para acompañar.', 'Pensá antes qué hacés con lo que sobre.'],
    ef: comida(0.3), tags: ['asado', 'desperdicio'],
  }),
  d('ali-sobras-asado', 'Aprovechá lo que sobró del asado', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['parrilla'],
    corto: 'Sándwiches, empanadas, picadillo o un revuelto: el asado del domingo rinde el lunes.',
    desc: 'La carne y las verduras que sobran del asado son la base de varias comidas: sándwiches, empanadas, un picadillo para tarta o un revuelto. Guardadas en la heladera ese mismo día, duran dos o tres días.',
    pasos: ['Guardá lo que sobró apenas termina el asado.', 'Al otro día, picalo para empanadas, tarta o sándwiches.'],
    ef: comida(0.3), tags: ['asado', 'sobras', 'desperdicio'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('planifica-tus-comidas-para-no-comprar-de-mas', 'Armá el menú de la semana antes de comprar', {
    dom, e: 'medium', i: 'high', min: 20, edad: 'ta', ahorra: true, cool: 168,
    corto: 'Casi todo lo que se tira se compró sin plan.',
    desc: 'Decidir qué se come en la semana y hacer la lista a partir de eso es lo que más baja el desperdicio en las casas. Comprás menos, gastás menos y la comida no se vence en el fondo de la heladera.',
    pasos: ['Revisá qué hay en la heladera y la alacena.', 'Anotá las comidas de la semana, usando primero lo que hay.', 'Hacé la lista sólo con lo que falta, y respetala.'],
    ef: comida(0.5), tags: ['desperdicio', 'compras', 'planificar'], hereda: ['res-planificar-compra'],
  }),
  c('ali-heladera-ordenada', 'Ordená la heladera: lo viejo adelante', {
    dom, e: 'easy', i: 'medium', min: 15, edad: 'kta', adulto: true, cool: 168,
    corto: 'Lo que no ves, se pudre.',
    desc: 'Una heladera ordenada muestra lo que hay: lo que vence primero adelante, las sobras en recipientes transparentes y un estante para "comer primero". Así se compra menos y se tira menos.',
    pasos: ['Sacá todo y tirá (al compost) lo que ya no sirve.', 'Volvé a poner lo más viejo adelante y lo nuevo atrás.', 'Armá un estante o una caja de "comer primero".'],
    ef: comida(0.3), tags: ['desperdicio', 'heladera', 'chicos'],
  }),
  c('alim-guarda-bien-cada-alimento', 'Aprendé dónde se guarda cada alimento', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'aprender', frec: 'one_time', edad: 'kta',
    corto: 'Mal guardada, la verdura dura días en vez de semanas.',
    desc: 'El tomate y la banana fuera de la heladera; la lechuga envuelta en un repasador húmedo; las papas lejos de las cebollas y a oscuras; las hierbas en un vaso con agua. Saber esto hace que la compra dure el doble.',
    pasos: ['Buscá cómo se conserva cada fruta y verdura que comprás seguido.', 'Reorganizá la cocina según eso.'],
    tags: ['desperdicio', 'heladera'],
  }),
  c('alim-entende-las-fechas-de-vencimiento', 'Aprendé a leer las dos fechas de los envases', {
    dom, e: 'easy', i: 'medium', min: 10, formato: 'aprender', frec: 'one_time', edad: 'kta',
    corto: '"Consumir preferentemente antes de" no quiere decir vencido.',
    desc: '"Consumir antes de" es una fecha de seguridad. "Consumir preferentemente antes de" es de calidad: muchos alimentos secos (arroz, fideos, galletitas, latas) siguen bien después. Confundirlas manda a la basura comida en buen estado. Con carne, pescado y lácteos frescos, la fecha manda.',
    pasos: ['Revisá la alacena buscando las dos leyendas.', 'Lo que tiene "preferentemente" y pasó la fecha, miralo, olelo y probalo antes de tirarlo.', 'Lo fresco con fecha vencida, no se come.'],
    fuente: 'fao', tags: ['desperdicio', 'etiquetas'],
  }),
  c('ali-caldo-con-restos', 'Hacé caldo con las cáscaras y los tallos', {
    dom, e: 'medium', i: 'medium', min: 60, edad: 'ta', cool: 168,
    corto: 'Las puntas de cebolla, los tallos y las cáscaras dan un caldo mejor que el de cubito.',
    desc: 'Juntá en una bolsa en el freezer las puntas de cebolla, zanahoria, apio, puerro, tallos de perejil y cáscaras limpias. Cuando esté llena, hervila una hora: tenés caldo casero, sin envase y con lo que ibas a tirar.',
    pasos: ['Juntá restos limpios de verdura en una bolsa en el freezer.', 'Cuando esté llena, hervilos una hora con agua y sal.', 'Colá y congelá el caldo en porciones.'],
    ef: comida(0.3), tags: ['desperdicio', 'cocina'],
  }),
  c('compra-en-una-feria-de-productores', 'Comprá en una feria de productores', {
    dom, e: 'easy', i: 'medium', min: 60, formato: 'salida', lugar: 'compras', edad: 'kta', cool: 168,
    corto: 'Comprar directo deja más plata a quien produce y menos envases en el medio.',
    desc: 'Las ferias de productores, de la agricultura familiar y las de la economía popular venden fruta, verdura, huevos, quesos y miel de la zona, de estación y sin intermediarios. Es comida fresca y un ingreso justo para quien la produce.',
    pasos: ['Buscá la feria de productores más cercana (municipio, universidad, organizaciones).', 'Llevá bolsas y frascos.', 'Hacé ahí una parte de la compra de la semana.'],
    ef: plastico(0.05), tags: ['feria', 'compras', 'productores'], hereda: ['pasa-una-semana-100-a-base-de-plantas'],
    mercado: ['alimentos-frescos', null, 'Si no tenés feria cerca, estos productores del programa de Brote venden directo.'],
  }),
  c('ali-leer-etiqueta', 'Fijate de dónde viene lo que comprás', {
    dom, e: 'easy', i: 'low', min: 10, formato: 'aprender', edad: 'kta', cool: 720,
    corto: 'Saber el origen cambia lo que elegís.',
    desc: 'Mirá la etiqueta de cinco productos que comprás siempre: ¿de qué provincia o de qué país vienen? Muchas veces hay una opción producida mucho más cerca, igual de buena.',
    pasos: ['Elegí cinco productos que compres seguido.', 'Buscá en la etiqueta dónde se elaboraron.', 'Para alguno, buscá una opción de tu provincia o región.'],
    ef: nada(), tags: ['compras', 'etiquetas'], hereda: ['compra-productos-locales-y-de-estacion'],
    mercado: ['alimentos-frescos', null, 'Estos negocios del programa de Brote cuentan de dónde viene lo que venden, con su nivel de evidencia.'],
  }),
  c('rescata-comida-excedente-con-apps', 'Rescatá comida que un comercio iba a tirar', {
    dom, e: 'easy', i: 'high', min: 20, formato: 'salida', edad: 'ta', ahorra: true, cool: 168,
    corto: 'Panaderías, verdulerías y locales tiran comida buena al cerrar.',
    desc: 'Muchas panaderías venden el pan del día anterior a mitad de precio, las verdulerías tienen cajones de fruta madura, y hay apps que ofrecen bolsas sorpresa de excedentes a la hora del cierre. Es comida buena que si no, va a la basura.',
    pasos: ['Preguntá en tu panadería o verdulería si venden lo del día anterior o lo maduro.', 'O buscá si en tu ciudad hay alguna app de excedentes.', 'Retirá antes del cierre.'],
    ef: comida(1), tags: ['desperdicio', 'barrio'],
  }),
  c('ali-banco-alimentos', 'Doná alimentos a un comedor o un banco de alimentos', {
    dom, e: 'easy', i: 'high', min: 30, formato: 'social', edad: 'kta', adulto: true, cool: 720,
    corto: 'Lo que en una casa sobra, en un comedor alcanza para muchos.',
    desc: 'Los bancos de alimentos de la Red Argentina rescatan comida apta que la industria y los comercios no venden y la reparten a comedores. También reciben donaciones de no perecederos. Llevar lo que no vas a usar antes de que venza es comida que no se pierde.',
    pasos: ['Revisá la alacena: lo que no vas a usar y no está vencido.', 'Buscá el comedor, la parroquia o el banco de alimentos más cercano.', 'Llevalo o sumate a una colecta.'],
    ef: nada(), fuente: 'red-bancos-alimentos', tags: ['solidario', 'desperdicio'],
  }),
  c('lleva-un-diario-de-desperdicio-de-comida', 'Anotá durante una semana la comida que tirás', {
    dom, e: 'medium', i: 'medium', min: 10, formato: 'reto', frec: 'one_time', edad: 'ta',
    corto: 'No se puede reducir lo que no se mide.',
    desc: 'Durante siete días, cada vez que tirás comida, anotá qué fue y por qué (se venció, sobró, se olvidó). Al final de la semana aparece el patrón: casi siempre son las mismas dos o tres cosas.',
    pasos: ['Pegá una hoja en la heladera.', 'Cada vez que tires comida, anotá qué y por qué.', 'Al final, elegí lo que más se repite y cambiá eso.'],
    ef: nada(), tags: ['desperdicio', 'experimento'],
  }),
  c('alim-cocina-de-mas-para-la-semana', 'Cociná en tanda para varios días', {
    dom, e: 'medium', i: 'medium', min: 120, edad: 'ta', ahorra: true, cool: 168,
    corto: 'Una tarde de cocina resuelve la semana con mucho menos gas por porción.',
    desc: 'Elegir un día para cocinar varias preparaciones (legumbres, un guiso, una salsa, verduras al horno) aprovecha el horno y las hornallas de una vez, y deja la semana resuelta sin delivery.',
    pasos: ['Elegí dos o tres preparaciones que se conserven bien.', 'Cociná todo el mismo día, aprovechando el horno caliente.', 'Porcioná y guardá en heladera y freezer.'],
    ef: gasKwh(2), tags: ['cocina', 'planificar', 'vianda'],
  }),
  c('ali-aprovechamiento-receta', 'Hacé una tarta, empanadas o un revuelto con lo que quedó', {
    dom, e: 'easy', i: 'medium', min: 40, edad: 'kta', adulto: true, cool: 72,
    corto: 'Las grandes recetas de la cocina de casa nacieron para no tirar nada.',
    desc: 'Una tarta de verduras, empanadas, un revuelto o una sopa crema son la mejor forma de usar ese medio zapallo, las sobras de pollo o la verdura que se está poniendo fea. Es cocina de aprovechamiento, de toda la vida.',
    pasos: ['Juntá lo que hay que usar ya.', 'Elegí la receta que mejor lo aproveche: tarta, empanadas, revuelto o sopa.', 'Si hacés de más, congelá.'],
    ef: comida(0.3), tags: ['desperdicio', 'cocina', 'chicos'],
  }),
  c('ali-conservas', 'Hacé una conserva con fruta o verdura de estación', {
    dom, e: 'medium', i: 'medium', min: 90, est: ['verano', 'otono'], edad: 'ta', cool: 336,
    corto: 'Mermeladas, tomates en frasco o escabeches: la estación guardada para todo el año.',
    desc: 'Cuando la fruta o el tomate están en su mejor momento y más baratos, hacer conservas guarda esa abundancia para el invierno. Esterilizando bien los frascos, duran meses.',
    pasos: ['Comprá fruta o tomate de estación en cantidad.', 'Hervé los frascos y tapas 10 minutos para esterilizarlos.', 'Prepará la mermelada o la salsa, envasá en caliente y tapá.'],
    ef: comida(0.5), tags: ['estacion', 'conservas', 'cocina'],
  }),
  c('ali-dia-de-legumbres', 'Elegí un día fijo de la semana para legumbres', {
    dom, e: 'easy', i: 'high', min: 30, formato: 'reto', frec: 'weekly', edad: 'ta',
    corto: 'Una costumbre semanal rinde más que un cambio aislado.',
    desc: 'Un "miércoles de lentejas" o un "jueves de garbanzos" es una forma fácil de sumar legumbres sin pensarlo cada día: proteína barata, rica y con una huella mínima. Y ayuda a planificar la compra.',
    pasos: ['Elegí un día de la semana.', 'Ese día, la comida principal lleva legumbres.', 'Probá una receta distinta cada semana.'],
    fuente: 'owid-alimentos', tags: ['legumbres', 'reto', 'cocina'],
    mercado: ['almacen-granel', 'legumbres-y-cereales', 'Legumbres sueltas, a granel. Estos negocios están en el programa de Brote.'],
  }),
];
