// Animales y vida silvestre — aves, insectos, mascotas responsables y fauna que no se compra.
import { d, c, elec, nada } from '../dsl.mjs';

const dom = 'animales';

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('deja-agua-para-las-aves-o-animales-hoy', 'Dejá agua fresca para las aves', {
    dom, e: 'easy', i: 'medium', min: 3, est: ['primavera', 'verano'], rut: true,
    corto: 'En los días de calor, el agua es más urgente que la comida.',
    desc: 'En la ciudad casi no quedan charcos ni bebederos naturales. Un plato playo con agua limpia en el balcón, el patio o la vereda ayuda a benteveos, horneros, zorzales y abejas a pasar el calor. Cambiala todos los días para que no críe mosquitos.',
    pasos: ['Llená un plato playo con agua limpia (con una piedra en el medio para que se posen los insectos).', 'Ponelo en un lugar alto o despejado, lejos de donde se esconden los gatos.', 'Cambiá el agua todos los días.'],
    ef: nada(), tags: ['aves', 'verano', 'chicos'],
  }),
  d('ani-agua-perros-calle', 'Dejá agua fresca para los perros y gatos de la cuadra', {
    dom, e: 'easy', i: 'low', min: 3, est: ['verano'], lugar: 'calle', adulto: true,
    corto: 'En una ola de calor, un balde de agua en la vereda puede salvar a un animal.',
    desc: 'Los perros y gatos que viven en la calle o pasan el día afuera sufren mucho el calor. Un recipiente con agua fresca a la sombra, en tu vereda o en la puerta del comercio, es una ayuda enorme.',
    pasos: ['Llená un recipiente pesado (que no se dé vuelta) con agua fresca.', 'Ponelo a la sombra en tu vereda.', 'Cambiá el agua a la mañana y a la tarde.'],
    ef: nada(), tags: ['perro', 'gato', 'verano', 'calle'],
  }),
  d('ani-no-alimentar-fauna', 'No le des comida humana a la fauna', {
    dom, e: 'easy', i: 'medium', min: 1, lugar: 'naturaleza',
    corto: 'Pan a los patos, galletitas a las palomas o a los carpinchos: les hace mal.',
    desc: 'La comida humana enferma a los animales silvestres, los acostumbra a depender de nosotros y los vuelve agresivos o invasivos. En plazas, costas, reservas y barrios cerrados, lo mejor que podés hacer por ellos es mirar sin dar de comer.',
    pasos: ['En plazas, lagos y reservas, no les des comida.', 'Guardá tu comida cerrada en los picnics.', 'Si ves a alguien hacerlo, contale con buena onda por qué les hace mal.'],
    ef: nada(), tags: ['fauna', 'chicos'], hereda: ['anim-no-alimentes-fauna-silvestre'],
  }),
  d('anim-levanta-la-caca-del-perro', 'Levantá siempre lo que hace tu perro', {
    dom, e: 'easy', i: 'medium', min: 1, req: ['perro'], lugar: 'calle', rut: true,
    corto: 'Lo que queda en la vereda termina en el arroyo con la primera lluvia.',
    desc: 'Las heces en la vereda o la plaza llevan parásitos que afectan a chicos y a otros animales, y con la lluvia llegan a los desagües y los ríos. Una bolsita (mejor reusada) y el tacho más cercano resuelven todo.',
    pasos: ['Salí a pasear siempre con bolsitas (reusá bolsas de pan o de verdura).', 'Levantá todo y tiralo cerrado en un cesto.'],
    ef: nada(), tags: ['perro', 'barrio'],
  }),
  d('ani-perro-con-correa-en-reservas', 'Llevá al perro con correa en plazas y reservas', {
    dom, e: 'easy', i: 'medium', min: 1, req: ['perro'], lugar: 'naturaleza',
    corto: 'Un perro suelto en una reserva espanta aves que anidan en el piso.',
    desc: 'En reservas, costas y plazas con fauna, muchas aves anidan en el pasto o en la orilla. Un perro suelto, aunque sea manso, las asusta y puede destruir nidos. Con correa, el paseo es igual de bueno.',
    pasos: ['En reservas, costas y zonas con aves, llevá al perro con correa.', 'Respetá los carteles de "no se permiten perros".'],
    ef: nada(), tags: ['perro', 'aves', 'reserva'],
  }),
  d('mantene-a-los-gatos-adentro-para-proteger-aves', 'Dejá al gato adentro de noche', {
    dom, e: 'easy', i: 'medium', min: 1, req: ['gato'], rut: true,
    corto: 'Los gatos son de las principales causas de muerte de aves en las ciudades.',
    desc: 'Un estudio en Nature Communications estimó que los gatos domésticos matan miles de millones de aves por año en EE. UU. De noche y al amanecer es cuando más cazan. Dejarlo adentro esas horas cuida a las aves y también a tu gato (autos, peleas, enfermedades).',
    pasos: ['Antes de que oscurezca, entrá al gato.', 'Dejale juego y una ventana para mirar afuera.'],
    ef: nada(), fuente: 'loss-2013-gatos', tags: ['gato', 'aves'],
  }),
  d('anim-apaga-las-luces-de-noche', 'Apagá las luces de afuera cuando no hacen falta', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'La luz artificial desorienta a insectos, aves migratorias y murciélagos.',
    desc: 'Las luces exteriores prendidas toda la noche atraen insectos hasta agotarlos y confunden a las aves que migran de noche. Apagarlas (o usar un sensor de movimiento) cuida la noche y la factura.',
    pasos: ['Apagá las luces del patio, el balcón o el frente cuando no las uses.', 'Si necesitás seguridad, usá un sensor de movimiento y luz cálida.'],
    ef: elec(0.1), tags: ['noche', 'insectos', 'aves'],
  }),
  d('ani-sacar-insecto-afuera', 'Sacá afuera al bicho en vez de matarlo', {
    dom, e: 'easy', i: 'low', min: 2, edad: 'k',
    corto: 'Una araña, una vaquita o un grillo adentro de casa sólo se perdió.',
    desc: 'Muchos insectos y arañas que entran a casa son inofensivos y útiles: comen mosquitos o polinizan. Con un vaso y una hoja los podés sacar afuera sin lastimarlos. Si no sabés qué bicho es, pedile ayuda a un adulto.',
    pasos: ['Poné un vaso sobre el bicho.', 'Deslizá una hoja por debajo.', 'Llevalo afuera y soltalo en una planta.'],
    ef: nada(), tags: ['insectos', 'chicos'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('pone-un-comedero-o-bebedero-para-aves', 'Armá un bebedero para aves', {
    dom, e: 'easy', i: 'medium', min: 20, req: ['balcon'], edad: 'kta', adulto: true, frec: 'one_time',
    corto: 'Un bebedero constante sostiene muchas más aves de las que imaginás.',
    desc: 'Con un plato playo, la tapa de una maceta o una botella cortada armás un bebedero que dura años. Colgado o en un lugar alto, despejado y lejos de los gatos, se vuelve un punto de encuentro de pájaros del barrio.',
    pasos: ['Usá un recipiente playo (2 o 3 cm de agua) con una piedra en el medio.', 'Ponelo en altura, cerca de un arbusto pero lejos de donde se esconde un gato.', 'Lavalo y cambiá el agua seguido.'],
    ef: nada(), tags: ['aves', 'chicos'], hereda: ['ani-bebedero-aves'],
  }),
  c('pone-calcomanias-anti-choque-en-las-ventanas', 'Marcá los vidrios donde chocan los pájaros', {
    dom, e: 'easy', i: 'medium', min: 20, edad: 'kta', adulto: true, frec: 'one_time',
    corto: 'Los vidrios reflejan el cielo y las aves no los ven.',
    desc: 'Un estudio publicado en The Condor estimó que cientos de millones de aves mueren por año al chocar contra vidrios. Marcarlos con calcomanías, cinta o puntos a menos de 10 cm de distancia les avisa que hay un obstáculo.',
    pasos: ['Identificá los vidrios grandes donde viste o escuchaste choques.', 'Pegá calcomanías, tiras de cinta o puntos de témpera separados unos 10 cm.', 'Cuanto más del vidrio cubras, mejor.'],
    ef: nada(), fuente: 'loss-2014-vidrios', tags: ['aves', 'chicos'], hereda: ['ani-cinta-en-ventanas'],
  }),
  c('anim-pone-una-caja-nido', 'Colocá una caja nido', {
    dom, e: 'medium', i: 'medium', min: 60, req: ['jardin'], est: ['otono', 'invierno'], edad: 'kta', adulto: true, frec: 'one_time',
    corto: 'Cada vez quedan menos huecos en árboles viejos donde las aves puedan anidar.',
    desc: 'Una caja de madera sin tratar, con el agujero del tamaño justo, colgada antes de la primavera en un árbol o una pared, puede recibir ratonas, golondrinas o carpinteros. Se arma con madera recuperada.',
    pasos: ['Armá una caja de madera sin pintar con un agujero de 3 cm.', 'Colgala a más de 2 metros, mirando al este o al sur, antes de que empiece la primavera.', 'No la revises seguido: mirá de lejos.'],
    ef: nada(), fuente: 'aves-argentinas', tags: ['aves', 'nidos', 'chicos'],
  }),
  c('construi-un-hotel-de-insectos-o-casa-para-abejas', 'Armá un refugio para abejas nativas', {
    dom, e: 'medium', i: 'medium', min: 45, req: ['balcon'], edad: 'kta', adulto: true, frec: 'one_time',
    corto: 'Las abejas solitarias polinizan muchísimo y casi no tienen dónde anidar.',
    desc: 'En la Argentina hay cientos de especies de abejas nativas que no pican y no viven en colmenas. Un manojo de cañas huecas o un tronco con agujeros, al sol, les da lugar para poner huevos.',
    pasos: ['Juntá cañas huecas de distintos diámetros y cortalas de 15 cm.', 'Atalas o metelas en una lata o caja, con los agujeros hacia afuera.', 'Colgalo al sol, a un metro del piso, cerca de flores.'],
    ef: nada(), fuente: 'ipbes-polinizadores', tags: ['polinizadores', 'insectos', 'chicos'], hereda: ['ani-refugio-insectos'],
  }),
  c('planta-especies-hospederas-para-mariposas', 'Plantá la planta de una mariposa', {
    dom, e: 'easy', i: 'medium', min: 30, req: ['balcon'], est: ['otono', 'primavera'], edad: 'kta', frec: 'one_time',
    corto: 'Sin la planta donde ponen los huevos, no hay mariposas.',
    desc: 'Cada mariposa necesita una planta para sus orugas: la pasionaria o mburucuyá para la espejito, el "algodoncillo" (asclepias) para la monarca, la ruda para la limonera. Plantar una hospedera es ver todo el ciclo en tu balcón.',
    pasos: ['Elegí una planta hospedera de tu zona (mburucuyá, asclepias, ruda).', 'Plantala al sol.', 'No la fumigues: las orugas que se la comen son las futuras mariposas.'],
    ef: nada(), tags: ['polinizadores', 'mariposas', 'chicos'],
  }),
  c('evita-pesticidas-y-herbicidas-en-tu-jardin', 'Dejá los venenos fuera del jardín', {
    dom, e: 'easy', i: 'high', min: 15, req: ['balcon'], edad: 'ta', cool: 2160,
    corto: 'Un insecticida no distingue entre una plaga y una abeja.',
    desc: 'Los insecticidas y herbicidas de jardín matan polinizadores, contaminan la tierra y llegan al agua. Casi siempre hay alternativas: sacar a mano, agua con jabón blanco contra pulgones, plantas aromáticas que ahuyentan.',
    pasos: ['Revisá qué venenos tenés y no compres más.', 'Probá alternativas: agua con jabón blanco, sacar a mano, atraer vaquitas de San Antonio.', 'Llevá los restos de veneno a residuos especiales.'],
    ef: nada(), fuente: 'ipbes-polinizadores', tags: ['polinizadores', 'jardin'], hereda: ['air-no-usar-veneno'],
  }),
  c('anim-castra-a-tu-mascota', 'Castrá a tu perro o tu gata', {
    dom, e: 'medium', i: 'high', min: 120, req: ['mascota'], edad: 'a', frec: 'one_time',
    corto: 'La sobrepoblación es la causa de fondo del abandono.',
    desc: 'Una perra o una gata sin castrar puede tener decenas de crías en su vida, y muchas terminan en la calle. Muchos municipios hacen castraciones gratuitas o a bajo costo en quirófanos móviles.',
    pasos: ['Averiguá en tu municipio o con una veterinaria las castraciones gratuitas o de bajo costo.', 'Sacá turno.', 'Seguí los cuidados de los días posteriores.'],
    ef: nada(), tags: ['perro', 'gato', 'mascota'],
  }),
  c('adopta-una-mascota-de-un-refugio', 'Si vas a sumar una mascota, adoptala', {
    dom, e: 'medium', i: 'high', min: 120, formato: 'social', edad: 'a', frec: 'one_time',
    corto: 'Cada adopción libera un lugar para el próximo animal rescatado.',
    desc: 'Refugios, rescatistas y municipios tienen perros y gatos de todas las edades, castrados y vacunados, buscando casa. Adoptar es darle un hogar a uno y hacerle lugar a otro en el refugio. Es una decisión para muchos años: pensala bien.',
    pasos: ['Pensá si tenés tiempo, espacio y recursos para una mascota por muchos años.', 'Contactá refugios o rescatistas de tu zona.', 'Conocé al animal antes de decidir.'],
    ef: nada(), tags: ['adopcion', 'perro', 'gato'],
  }),
  c('hace-de-hogar-de-transito-para-animales', 'Sé hogar de tránsito para un animal', {
    dom, e: 'hard', i: 'high', min: 300, formato: 'social', edad: 'a', rango: 'plantula', cool: 720,
    corto: 'Un tránsito es lo que permite que un refugio siga rescatando.',
    desc: 'Cuidar a un perro o un gato por unas semanas, mientras le buscan familia, le da un lugar seguro y libera espacio en el refugio. Los rescatistas suelen cubrir la comida y el veterinario.',
    pasos: ['Contactá un refugio o rescatista y ofrecete como tránsito.', 'Acordá cuánto tiempo y qué cubren ellos.', 'Ayudá a difundirlo para que encuentre familia.'],
    ef: nada(), tags: ['adopcion', 'perro', 'gato'],
  }),
  c('hace-voluntariado-en-un-refugio-o-santuario', 'Hacé voluntariado en un refugio', {
    dom, e: 'medium', i: 'medium', min: 180, formato: 'social', edad: 'ta', cool: 336,
    corto: 'Los refugios funcionan casi siempre con muy pocas manos.',
    desc: 'Pasear perros, limpiar, socializar gatos, ayudar en una jornada de adopción o en la difusión: un refugio necesita de todo. Una mañana por mes ya hace diferencia.',
    pasos: ['Buscá refugios o centros de rescate cerca.', 'Preguntá qué necesitan y en qué horarios.', 'Comprometete a algo que puedas sostener.'],
    ef: nada(), tags: ['voluntariado', 'perro', 'gato'],
  }),
  c('ani-adoptar-no-comprar', 'Difundí un animal en adopción', {
    dom, e: 'easy', i: 'medium', min: 10, formato: 'social', edad: 'ta', lugar: 'celular', cool: 168,
    corto: 'Compartir un caso ayuda de verdad: muchas adopciones salen así.',
    desc: 'Los refugios y rescatistas dependen de la difusión. Compartir la foto y los datos de un perro o gato en adopción en tus redes o grupos del barrio llega a gente que quizás está buscando justo eso.',
    pasos: ['Buscá un animal en adopción de un refugio o rescatista de tu zona.', 'Compartí la publicación con sus datos de contacto.'],
    ef: nada(), tags: ['adopcion', 'compartir'],
  }),
  c('reporta-fauna-herida-a-un-centro-de-rescate', 'Agendá el centro de rescate de fauna de tu zona', {
    dom, e: 'easy', i: 'medium', min: 10, formato: 'aprender', frec: 'one_time', edad: 'kta', adulto: true,
    corto: 'Un animal silvestre mal manipulado casi nunca sobrevive: saber a quién llamar es la ayuda.',
    desc: 'Si encontrás un animal silvestre herido (un ave, una comadreja, una tortuga, un zorro), lo mejor es no tocarlo y llamar a un centro de rescate. La Red de Centros de Rescate del Ministerio de Ambiente tiene contactos en todo el país: tené el tuyo agendado.',
    pasos: ['Buscá el centro de rescate de fauna más cercano en la Red de Centros de Rescate.', 'Guardá el teléfono en tu celular.', 'Si encontrás un animal herido, no lo alimentes ni lo manipules: llamalos.'],
    ef: nada(), fuente: 'red-centros-rescate', tags: ['fauna', 'rescate'],
  }),
  c('ani-pichon-caido', 'Aprendé qué hacer si encontrás un pichón en el piso', {
    dom, e: 'easy', i: 'medium', min: 10, formato: 'aprender', frec: 'one_time', edad: 'kta',
    corto: 'Muchos "pichones caídos" son volantones aprendiendo a volar, con los padres cerca.',
    desc: 'En primavera es común encontrar pichones en el piso. Si tiene plumas y salta, es un volantón: sus padres lo siguen alimentando y lo mejor es dejarlo (o subirlo a una rama cercana). Si no tiene plumas, se puede intentar devolverlo al nido. Llevarlo a casa casi siempre lo condena.',
    pasos: ['Si tiene plumas y salta: dejalo, o subilo a un arbusto cercano, y alejate.', 'Si no tiene plumas: buscá el nido y devolvelo con cuidado.', 'Si está herido, llamá a un centro de rescate.'],
    ef: nada(), fuente: 'aves-argentinas', tags: ['aves', 'nidos', 'chicos'],
  }),
  c('ani-no-comprar-fauna-silvestre', 'Nunca compres un animal silvestre como mascota', {
    dom, e: 'easy', i: 'high', min: 10, formato: 'aprender', frec: 'one_time', edad: 'kta',
    corto: 'Loros, cardenales, tortugas de tierra o monos vienen del tráfico de fauna.',
    desc: 'El tráfico de fauna es una de las principales amenazas para especies argentinas como el cardenal amarillo o la tortuga terrestre. Por cada animal que llega a una jaula, muchos mueren en el camino. Comprar, tener o regalar fauna silvestre está prohibido por la ley de fauna.',
    pasos: ['No compres ni aceptes animales silvestres (aves, tortugas, monos, reptiles).', 'Si ves venta de fauna en la calle o en internet, denunciala a la autoridad de fauna de tu provincia.'],
    ef: nada(), fuente: 'ley-22421-fauna', tags: ['fauna', 'trafico', 'chicos'],
  }),
  c('ani-tortuga-no-liberar', 'Nunca sueltes una mascota exótica en la naturaleza', {
    dom, e: 'easy', i: 'high', min: 5, formato: 'aprender', frec: 'one_time', edad: 'kta',
    corto: 'La tortuga de orejas rojas que alguien soltó en un lago es hoy una especie invasora.',
    desc: 'Tortugas acuáticas, peces de pecera, conejos o ardillas soltados en la naturaleza compiten con la fauna nativa y transmiten enfermedades. Varias ya son invasoras en la Argentina. Si no podés cuidar a tu mascota, buscale otra familia.',
    pasos: ['Si ya no podés tener a tu mascota exótica, buscale un nuevo hogar responsable.', 'Nunca la sueltes en un lago, una plaza o una reserva.'],
    ef: nada(), fuente: 'invasoras-mayds', tags: ['invasoras', 'fauna'],
  }),
  c('ani-sin-pirotecnia', 'Festejá sin pirotecnia', {
    dom, e: 'easy', i: 'medium', min: 5, formato: 'social', est: ['verano'], edad: 'kta', cool: 720,
    corto: 'Los estruendos aterran a perros, gatos, aves y a personas con hipersensibilidad auditiva.',
    desc: 'En las fiestas, la pirotecnia sonora hace que miles de mascotas escapen o se lastimen y espanta aves de sus nidos. Hay muchas formas de festejar sin estruendos: luces, música, una ronda de deseos.',
    pasos: ['No compres pirotecnia sonora.', 'Si tenés mascotas, dejalas adentro y acompañadas a la medianoche.', 'Proponé en tu familia o barrio un festejo sin estruendos.'],
    ef: nada(), tags: ['fiestas', 'perro', 'gato', 'aves'],
  }),
  c('ani-ruta-con-fauna', 'Manejá despacio en rutas que cruzan monte o parques', {
    dom, e: 'easy', i: 'high', min: 5, req: ['auto'], edad: 'a', cool: 720,
    corto: 'Los atropellamientos en ruta son una amenaza real para el yaguareté, el oso hormiguero o el zorro.',
    desc: 'En rutas que atraviesan parques nacionales, montes o humedales, la velocidad es la diferencia entre ver un animal y atropellarlo, sobre todo al amanecer y al anochecer. En el Parque Nacional Iguazú se instalaron reductores y pasafaunas por esto.',
    pasos: ['En rutas que cruzan áreas naturales, respetá las velocidades reducidas.', 'Al amanecer y al anochecer, andá todavía más despacio.', 'Si ves un animal atropellado, avisá a guardaparques o a la policía rural.'],
    ef: nada(), fuente: 'apn-atropellamiento-iguazu', tags: ['ruta', 'fauna', 'auto'],
  }),
  c('anim-elegi-cosmetica-sin-testeo', 'Elegí cosmética no testeada en animales', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'salida', edad: 'ta', lugar: 'compras', cool: 2160,
    corto: 'El testeo en animales sigue siendo habitual en muchas marcas.',
    desc: 'Champús, cremas y maquillaje de muchas marcas todavía se prueban en animales. Las que no lo hacen suelen indicarlo con un sello reconocido. La próxima vez que repongas algo, buscá una opción así.',
    pasos: ['Cuando se te termine un producto de higiene o cosmética, buscá la versión sin testeo.', 'Fijate en el sello, no sólo en la palabra en el frente.'],
    ef: nada(), tags: ['compras', 'animales'],
  }),
  c('anim-revisa-antes-de-podar', 'Revisá que no haya nidos antes de podar o cortar', {
    dom, e: 'easy', i: 'medium', min: 10, req: ['jardin'], est: ['primavera', 'verano'], edad: 'ta', cool: 720,
    corto: 'Una poda en primavera puede tirar abajo una nidada entera.',
    desc: 'De septiembre a enero muchas aves anidan en arbustos, enredaderas y árboles. Antes de podar o de cortar un cerco, mirá con atención: si hay un nido activo, esperá a que los pichones vuelen.',
    pasos: ['Antes de podar, mirá el interior del arbusto o el árbol.', 'Si hay un nido con huevos o pichones, posponé la poda.', 'Mejor aún: hacé las podas en invierno.'],
    ef: nada(), tags: ['aves', 'nidos', 'poda'], hereda: ['ani-revisar-antes-de-podar'],
  }),
  c('saca-especies-invasoras-de-tu-zona', 'Sacá una planta invasora de tu jardín', {
    dom, e: 'medium', i: 'medium', min: 60, req: ['jardin'], edad: 'ta', cool: 720,
    corto: 'Una invasora sin control desplaza a todo lo que estaba antes.',
    desc: 'Ligustros, crataegus, acacia negra, lirio amarillo o mora blanca son plantas exóticas que se escapan de los jardines e invaden montes y costas. El Ministerio de Ambiente tiene la lista oficial: si tenés alguna, reemplazala por una nativa.',
    pasos: ['Revisá la lista oficial de especies exóticas invasoras.', 'Si tenés alguna, sacala (con raíz y antes de que dé semillas).', 'Plantá una nativa en su lugar.'],
    ef: nada(), fuente: 'invasoras-mayds', tags: ['invasoras', 'nativas', 'jardin'],
  }),
  c('deja-un-corredor-para-fauna-en-tu-jardin', 'Dejá un paso para la fauna en el cerco', {
    dom, e: 'easy', i: 'medium', min: 20, req: ['jardin'], edad: 'ta', frec: 'one_time',
    corto: 'Un jardín cerrado por todos lados es una isla para la fauna.',
    desc: 'Un hueco de 15 cm en el cerco o la base del tejido deja pasar sapos, comadrejas, cuises o tortugas de un jardín a otro sin que puedan entrar perros grandes. Unir jardines es unir hábitat.',
    pasos: ['Elegí un punto del cerco o el tejido que dé a otro jardín o a un baldío.', 'Abrí un hueco de unos 15 cm a ras del suelo.'],
    ef: nada(), tags: ['fauna', 'jardin'],
  }),
  c('crea-un-pequeno-estanque-para-anfibios', 'Armá un pequeño estanque para sapos y ranas', {
    dom, e: 'hard', i: 'high', min: 240, req: ['jardin'], edad: 'a', rango: 'plantula', frec: 'one_time',
    corto: 'Los sapos y las ranas desaparecen cuando se seca el último charco.',
    desc: 'Un estanque chico, con bordes en pendiente y plantas acuáticas, se llena de vida en una temporada: sapos, libélulas, aves que vienen a tomar. Sin peces, los renacuajos y las libélulas controlan los mosquitos.',
    pasos: ['Cavá un pozo de unos 50 cm de profundidad con bordes en pendiente.', 'Cubrilo con una lona o un recipiente grande y llenalo con agua de lluvia.', 'Sumá plantas acuáticas nativas y piedras en un borde para que puedan salir.'],
    ef: nada(), tags: ['anfibios', 'jardin', 'biodiversidad'],
  }),
  c('ani-collar-con-cascabel', 'Ponele un cascabel al gato si sale', {
    dom, e: 'easy', i: 'medium', min: 5, req: ['gato'], edad: 'kta', frec: 'one_time',
    corto: 'Les avisa a las aves que está cerca.',
    desc: 'Si tu gato sale al patio o al techo, un collar de liberación rápida con cascabel les da a las aves unos segundos para escapar. Combinado con dejarlo adentro de noche, baja mucho la caza.',
    pasos: ['Comprá un collar de liberación rápida (se abre si se engancha).', 'Ponele un cascabel.', 'Fijate que entren dos dedos entre el collar y el cuello.'],
    ef: nada(), tags: ['gato', 'aves'],
  }),
];
