// Consumo — comprar menos y mejor, reparar, reusar, prestar, heredar.
import { d, c, plastico, prendas, nada, medida, por } from '../dsl.mjs';

const dom = 'consumo';

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('con-lista-y-nada-mas', 'Comprá sólo lo que está en la lista', {
    dom, e: 'easy', i: 'medium', min: 2, lugar: 'compras', edad: 'ta', rut: true, ahorra: true,
    corto: 'Lo que se compra por impulso casi nunca se usa del todo.',
    desc: 'Las góndolas están pensadas para que te lleves más de lo que fuiste a buscar. Ir con la lista y respetarla ahorra plata, envases y comida que después se vence.',
    pasos: ['Antes de salir, anotá lo que falta de verdad.', 'En el negocio, comprá sólo eso.', 'Si ves algo que "te tienta", anotalo y decidilo la próxima vez.'],
    ef: { r: 0.05, c: 0.1 }, tags: ['compras'],
  }),
  d('con-cuidar-para-que-dure', 'Cuidá algo para que te dure más', {
    dom, e: 'easy', i: 'low', min: 10,
    corto: 'Guardar, limpiar y colgar bien es la forma más barata de consumir menos.',
    desc: 'Las zapatillas que se limpian, la ropa que se cuelga, la mochila que se cierra bien o el celular con funda duran mucho más. Lo que dura no hay que comprarlo de nuevo.',
    pasos: ['Elegí algo que uses mucho: zapatillas, mochila, campera.', 'Limpialo y guardalo bien.', 'Si tiene un detalle roto, arreglalo antes de que crezca.'],
    ef: nada(), tags: ['cuidar', 'chicos'],
  }),
  d('con-espera-24-horas', 'Antes de comprar algo que no necesitás hoy, esperá un día', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true, ahorra: true,
    corto: 'La mayoría de las ganas de comprar se pasan en 24 horas.',
    desc: 'Muchas compras online o en la calle se deciden en segundos. Dejarla en el carrito o anotarla y volver a pensarla mañana separa lo que necesitás de lo que te tentó.',
    pasos: ['Si querés comprar algo que no es urgente, no lo compres ahora.', 'Anotalo o dejalo en el carrito.', 'Mañana preguntate si lo seguís queriendo.'],
    ef: nada(), tags: ['compras', 'impulso'],
  }),
  d('con-usa-lo-que-ya-tenes', 'Antes de comprar, fijate si ya tenés algo que sirva', {
    dom, e: 'easy', i: 'low', min: 3, rut: true, ahorra: true,
    corto: 'Muchas veces lo que vamos a comprar ya está en un cajón.',
    desc: 'Un cable, una herramienta, una prenda, un recipiente: antes de salir a comprar, buscá en casa o preguntá a alguien de tu familia. Lo que ya existe es lo más sustentable que hay.',
    pasos: ['Antes de comprar algo, buscalo en casa.', 'Si no está, preguntá a familia o amigos si tienen para prestarte.'],
    ef: nada(), tags: ['compras', 'reuso'],
  }),
  d('con-cose-un-boton', 'Cosé un botón o un descosido', {
    dom, e: 'easy', i: 'low', min: 10, adulto: true,
    corto: 'Un botón que falta no es motivo para que una prenda quede en el fondo del placard.',
    desc: 'Muchas prendas dejan de usarse por un detalle: un botón, un dobladillo, una costura abierta. Con aguja, hilo y diez minutos vuelven a estar en uso.',
    pasos: ['Buscá una prenda que no usás por un detalle.', 'Enhebrá una aguja con hilo del mismo color.', 'Cosé el botón o cerrá la costura con puntadas chicas.'],
    ef: { c: 0.2, r: 0.02 }, tags: ['ropa', 'arreglo', 'chicos'],
  }),
  d('elegi-productos-con-minimo-packaging', 'Elegí el producto con menos envase', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'compras',
    corto: 'El envase se tira casi siempre el mismo día que se compra.',
    desc: 'Entre dos productos parecidos, el que viene con menos envoltorio genera menos basura. Fruta suelta en vez de en bandeja, un paquete en vez de porciones individuales, cartón en vez de plástico.',
    pasos: ['Mirá el envase antes de elegir.', 'Elegí la opción suelta, la más simple o la de cartón.'],
    ef: plastico(0.02), tags: ['compras', 'plastico'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('compra-ropa-de-segunda-mano-o-vintage', 'Comprá ropa usada en vez de nueva', {
    dom, e: 'easy', i: 'high', min: 30, formato: 'salida', edad: 'ta', lugar: 'compras', ahorra: true, cool: 168,
    corto: 'Una prenda que ya existe no necesita agua, algodón ni una fábrica.',
    desc: 'La industria textil es una de las que más agua usa y más residuos genera, según el PNUMA. Ferias americanas, tiendas de segunda mano, apps de usados o los grupos del barrio tienen ropa en buen estado a una fracción del precio.',
    pasos: ['La próxima prenda que necesites, buscala primero usada.', 'Probá ferias americanas, apps de usados o grupos de intercambio.', 'Contá cuántas prendas compraste usadas.'],
    medida: medida('¿Cuántas prendas compraste usadas?', 'prenda', 'prendas', { min: 1, max: 3, def: 1, por: por(prendas(1)) }),
    fuente: 'unep-moda', tags: ['ropa', 'usado'], hereda: ['agua-ropa-segunda-mano'],
  }),
  c('revende-o-dona-lo-que-no-usas', 'Doná o vendé algo que no usás hace un año', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'social', edad: 'kta', adulto: true, cool: 336,
    corto: 'Lo que a vos te sobra, a alguien le falta.',
    desc: 'Ropa, juguetes, libros, utensilios o muebles que no se usan ocupan lugar en casa y podrían estar sirviendo. Donarlos a un ropero comunitario, una parroquia o un refugio, o venderlos usados, los mantiene en uso y fuera de la basura.',
    pasos: ['Elegí algo en buen estado que no hayas usado en un año.', 'Decidí: donar (ropero, comedor, escuela) o vender (apps de usados, feria).', 'Entregalo limpio y en condiciones.'],
    ef: { r: 1, c: 1 }, tags: ['donar', 'usado'], hereda: ['dona-cosas-que-ya-no-usas-en-vez-de-tirarlas', 'res-donar-lo-que-no-usas'],
  }),
  c('pedi-prestado-o-alquila-en-vez-de-comprar', 'Pedí prestado algo que vas a usar una vez', {
    dom, e: 'easy', i: 'high', min: 15, formato: 'social', edad: 'kta', ahorra: true, cool: 336,
    corto: 'Un taladro se usa, en promedio, unos minutos en toda su vida.',
    desc: 'Herramientas, la escalera, una carpa, un disfraz o un libro: para algo que vas a usar una vez, pedirlo prestado a un vecino o a la familia evita fabricar uno más que después queda guardado.',
    pasos: ['Antes de comprar algo para usar una vez, preguntá quién te lo puede prestar.', 'Devolvelo limpio y a tiempo.', 'Ofrecé lo tuyo cuando te lo pidan.'],
    ef: { c: 3, r: 0.5 }, tags: ['prestar', 'barrio'], hereda: ['res-prestar-en-vez-de-comprar'],
  }),
  c('repara-algo-en-vez-de-tirarlo', 'Repará algo en vez de reemplazarlo', {
    dom, e: 'medium', i: 'high', min: 45, edad: 'ta', ahorra: true, cool: 336,
    corto: 'Reparar evita a la vez un residuo y una compra.',
    desc: 'Una silla floja, una lámpara que no prende, un cierre roto, unas auriculares sin un cable: casi todo se arregla con un tutorial, una herramienta prestada o un repuesto barato. Lo que se repara no se fabrica de nuevo.',
    pasos: ['Elegí algo roto que tengas guardado.', 'Buscá un tutorial con la marca y el modelo.', 'Conseguí el repuesto y arreglalo (o pedí ayuda a alguien que sepa).'],
    ef: { c: 5, r: 1 }, fuente: 'circularity-gap-2025', tags: ['arreglo'], hereda: ['res-reparar-algo-roto', 'con-reparar-antes-de-reemplazar'],
  }),
  c('con-arreglo-en-el-barrio', 'Llevá algo a arreglar al zapatero, la modista o el técnico', {
    dom, e: 'easy', i: 'high', min: 30, formato: 'salida', edad: 'ta', lugar: 'calle', ahorra: true, cool: 336,
    corto: 'Los oficios de arreglo del barrio salvan cosas que parecen perdidas.',
    desc: 'Zapateros, modistas, relojeros, técnicos de celulares y de electrodomésticos: en casi todos los barrios hay alguien que arregla. Un taco, un cierre, una pantalla o un motor cuestan mucho menos que lo nuevo, y sostienen un oficio.',
    pasos: ['Juntá algo que no usás por un arreglo pendiente.', 'Buscá el zapatero, la modista o el técnico más cercano.', 'Preguntá presupuesto antes de decidir comprar otro.'],
    ef: { c: 3, r: 0.5 }, tags: ['arreglo', 'barrio'],
  }),
  c('repara-tu-ropa-con-zurcido-visible', 'Zurcí una prenda rota', {
    dom, e: 'medium', i: 'medium', min: 30, edad: 'ta', cool: 168,
    corto: 'Un zurcido, a la vista o escondido, alarga años la vida de una prenda.',
    desc: 'Un agujero en un buzo o en las rodillas de un jean no es el fin. Un zurcido con hilo del mismo color o, al revés, de un color que resalte, deja la prenda lista para seguir.',
    pasos: ['Elegí una prenda con un agujero o un roce.', 'Con aguja e hilo, tejé hilos en un sentido y después cruzados en el otro sobre el agujero.', 'Si es grande, poné un parche del lado de adentro.'],
    ef: prendas(0.5), tags: ['ropa', 'arreglo'], hereda: ['agua-arreglar-prenda'],
  }),
  c('organiza-o-participa-de-un-intercambio-de-ropa', 'Organizá o sumate a un intercambio de ropa', {
    dom, e: 'medium', i: 'high', min: 90, formato: 'social', edad: 'kta', adulto: true, cool: 720,
    corto: 'Lo que a vos te sobra es lo que otra persona está por comprar.',
    desc: 'Un intercambio entre amigos, en la escuela o en el club: cada uno lleva ropa limpia y en buen estado y se lleva lo que le sirve. Lo que queda, se dona. Es ropa nueva para todos sin fabricar nada.',
    pasos: ['Convocá a amigos, compañeros o vecinos y elegí un lugar.', 'Pedí que traigan ropa limpia y en buen estado.', 'Al final, doná lo que no se llevó nadie.'],
    ef: prendas(2), tags: ['ropa', 'intercambio'], hereda: ['con-intercambio-con-amigos'],
  }),
  c('con-utiles-del-ano-pasado', 'Reusá los útiles del año pasado', {
    dom, e: 'easy', i: 'medium', min: 20, est: ['verano', 'otono'], edad: 'kta', cool: 2160,
    corto: 'La cartuchera, la mochila y los cuadernos a medio usar siguen sirviendo.',
    desc: 'Antes de la vuelta a clases, revisá lo que quedó del año pasado: lápices, cartuchera, carpetas, la mochila, las hojas en blanco de los cuadernos. Comprar sólo lo que falta ahorra plata y plástico.',
    pasos: ['Juntá todos los útiles del año pasado.', 'Separá lo que sigue sirviendo.', 'Hacé la lista sólo con lo que falta de verdad.'],
    ef: { r: 0.3, c: 0.5 }, tags: ['escuela', 'chicos'], hereda: ['cons-usa-una-lapicera-recargable'],
  }),
  c('con-guardapolvo-heredado', 'Pasá o heredá un guardapolvo o un uniforme', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'social', est: ['verano', 'otono'], edad: 'kta', adulto: true, cool: 4320,
    corto: 'Los chicos crecen rápido: un guardapolvo sirve a varios.',
    desc: 'Guardapolvos, uniformes, ropa de gimnasia o de fútbol quedan chicos en un año y en perfecto estado. Pasarlos a un hermano, un primo, un vecino o a la cooperadora de la escuela es ropa que sigue sirviendo.',
    pasos: ['Juntá los guardapolvos o uniformes que ya no entran.', 'Lavalos y ofrecelos a familia, vecinos o a la cooperadora de la escuela.'],
    ef: prendas(1), tags: ['escuela', 'ropa', 'chicos'],
  }),
  c('con-juguetes-intercambio', 'Intercambiá o doná juguetes que ya no usás', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'social', edad: 'kta', adulto: true, cool: 720,
    corto: 'Un juguete guardado puede ser el juguete favorito de otro chico.',
    desc: 'Los juguetes en buen estado que ya no se usan pueden intercambiarse con amigos o donarse a un jardín, un comedor o un hospital. Así se juega más con lo que ya existe.',
    pasos: ['Elegí juguetes completos y en buen estado que ya no uses.', 'Proponé un intercambio con amigos o primos.', 'Lo que quede, donalo con un adulto.'],
    ef: { r: 0.5, c: 1 }, tags: ['juguetes', 'donar', 'chicos'],
  }),
  c('usa-una-biblioteca-de-libros-o-de-cosas', 'Sacá un libro de la biblioteca en vez de comprarlo', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'salida', edad: 'kta', cool: 336,
    corto: 'Un mismo libro puede leerlo todo un barrio.',
    desc: 'Las bibliotecas populares, escolares y municipales prestan libros gratis (muchas también revistas, películas y juegos). Leer prestado ahorra papel, plata y lugar en la biblioteca de casa.',
    pasos: ['Buscá la biblioteca popular o municipal más cercana.', 'Asociate (suele ser gratis o muy barato).', 'Sacá el próximo libro que ibas a comprar.'],
    ef: { c: 1, r: 0.3 }, tags: ['libros', 'barrio'],
  }),
  c('compra-electronica-reacondicionada', 'Comprá un celular o una compu usados o reacondicionados', {
    dom, e: 'medium', i: 'high', min: 60, formato: 'salida', frec: 'recurring', cool: 4320, edad: 'a', ahorra: true,
    corto: 'Casi toda la huella de un aparato se genera al fabricarlo.',
    desc: 'La mayor parte de las emisiones de un celular o una notebook se producen antes de prenderlo por primera vez. Uno reacondicionado o usado en buen estado, con garantía, cumple igual y evita fabricar otro.',
    pasos: ['Cuando necesites cambiar de aparato, buscá primero reacondicionados con garantía.', 'Revisá batería, pantalla y que esté liberado.', 'Llevá el viejo a reciclaje o vendelo.'],
    ef: { c: 25, r: 0.2 }, fuente: 'ewaste-monitor', tags: ['electronicos', 'usado'],
  }),
  c('con-regla-30-dias', 'Esperá 30 días antes de una compra grande', {
    dom, e: 'easy', i: 'medium', min: 5, formato: 'reto', edad: 'ta', ahorra: true, cool: 720,
    corto: 'Si en un mes lo seguís queriendo, es una buena compra.',
    desc: 'Para algo caro (un aparato, ropa de marca, un mueble), anotalo con la fecha y esperá un mes. Muchas veces las ganas se pasan o aparece una opción usada o prestada. Si no, comprás con la cabeza fría.',
    pasos: ['Anotá lo que querés comprar y la fecha.', 'Esperá 30 días.', 'Volvé a preguntarte si lo necesitás, y si no hay una opción usada.'],
    ef: nada(), tags: ['compras', 'impulso'], hereda: ['cons-espera-antes-de-comprar'],
  }),
  c('cons-elegi-lo-que-se-puede-reparar', 'Elegí productos que se puedan reparar', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'aprender', edad: 'ta', cool: 720,
    corto: 'Si no se abre ni tiene repuestos, está diseñado para tirarse.',
    desc: 'Antes de comprar un aparato, una mochila o unas zapatillas, mirá si tiene repuestos, si se abre con tornillos y si hay service en tu ciudad. Lo que se puede arreglar dura más, aunque cueste un poco más.',
    pasos: ['Antes de comprar, buscá si hay repuestos y service de esa marca.', 'Preferí lo que se abre con tornillos y no con pegamento.', 'Guardá la garantía.'],
    ef: nada(), fuente: 'ue-derecho-reparar', tags: ['compras', 'arreglo'], hereda: ['con-elegir-durable'],
  }),
  c('cons-regala-una-experiencia', 'Regalá una experiencia en vez de un objeto', {
    dom, e: 'easy', i: 'medium', min: 20, formato: 'social', edad: 'kta', cool: 720,
    corto: 'Una salida, una clase o un día juntos no genera residuos ni queda en un cajón.',
    desc: 'Para el próximo cumpleaños, regalá algo para hacer: una entrada, una clase, una salida a la naturaleza, una comida hecha por vos, un vale por un favor. Se recuerda más y no se tira.',
    pasos: ['Pensá qué le gusta hacer a esa persona.', 'Armá el regalo: una entrada, una salida o un vale escrito a mano.'],
    ef: nada(), tags: ['regalos'],
  }),
  c('cons-envolve-sin-papel-nuevo', 'Envolvé un regalo sin papel nuevo', {
    dom, e: 'easy', i: 'low', min: 10, edad: 'kta', cool: 168,
    corto: 'El papel de regalo plastificado no se recicla y dura minutos.',
    desc: 'Un pañuelo, un repasador, una bolsa de tela, una revista o un diario envuelven igual de lindo. La tela, además, es parte del regalo.',
    pasos: ['Usá una tela, un pañuelo o papel que ya tengas.', 'Atalo con un piolín o una cinta reusada.'],
    ef: { r: 0.05, c: 0.05 }, tags: ['regalos', 'chicos'], hereda: ['res-regalo-sin-papel'],
  }),
  c('con-regalo-hecho-a-mano', 'Hacé un regalo con tus manos', {
    dom, e: 'easy', i: 'low', min: 60, edad: 'kta', cool: 720,
    corto: 'Lo hecho a mano no se compra, no viene en blíster y se recuerda.',
    desc: 'Un dibujo, una tarjeta, galletitas, un frasco con una planta o algo tejido. Un regalo hecho por vos usa lo que ya tenés y dice más que cualquier cosa comprada.',
    pasos: ['Elegí algo que sepas hacer o quieras aprender.', 'Usá materiales que tengas en casa.', 'Envolvelo sin papel nuevo.'],
    ef: nada(), tags: ['regalos', 'chicos'],
  }),
  c('cambia-a-productos-recargables-del-hogar', 'Comprá los productos de limpieza en recarga', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'salida', edad: 'ta', lugar: 'compras', cool: 720,
    corto: 'En la línea de limpieza, el envase pesa más que el producto.',
    desc: 'Detergente, lavandina, jabón líquido y suavizante se venden sueltos en muchas dietéticas, almacenes y "químicas" de barrio, o en versión concentrada. Rellenar los mismos bidones evita decenas de envases por año.',
    pasos: ['Guardá los envases vacíos de limpieza.', 'Buscá un local que venda sueltos o recargas.', 'Rellenalos, o elegí la versión concentrada.'],
    ef: plastico(0.1), tags: ['plastico', 'limpieza'], hereda: ['agua-jabon-concentrado'],
  }),
  c('res-pila-recargable', 'Pasate a pilas recargables', {
    dom, e: 'easy', i: 'medium', min: 10, frec: 'one_time', edad: 'ta', costo: 'bajo', ahorra: true,
    corto: 'Una pila recargable reemplaza cientos de descartables.',
    desc: 'Para los controles, los juguetes y todo lo que gasta pilas seguido, unas recargables con su cargador se pagan solas en poco tiempo y evitan juntar pilas usadas en el cajón.',
    pasos: ['Contá qué aparatos gastan pilas seguido.', 'Comprá recargables de ese tamaño y un cargador.', 'Llevá las descartables que te queden a un punto de pilas.'],
    ef: { r: 0.2, c: 1 }, tags: ['pilas'],
  }),
  c('res-cepillo-recargable', 'Usá un cepillo de dientes de bambú o de cabezal recambiable', {
    dom, e: 'easy', i: 'low', min: 5, edad: 'kta', lugar: 'compras', cool: 2160,
    corto: 'Cada persona tira varios cepillos de plástico por año.',
    desc: 'Los cepillos de mango de bambú o los de cabezal recambiable cumplen igual y generan mucho menos plástico. Cuando lo cambies, el de bambú puede servir para limpiar rincones.',
    pasos: ['La próxima vez que cambies el cepillo, elegí uno de bambú o de cabezal recambiable.', 'Usá el viejo para limpiar juntas o zapatillas.'],
    ef: plastico(0.02), tags: ['plastico', 'baño'],
  }),
  c('con-gestion-menstrual-reutilizable', 'Probá productos de gestión menstrual reutilizables', {
    dom, e: 'easy', i: 'high', min: 15, frec: 'one_time', edad: 'ta', ahorra: true,
    corto: 'Una copa o unas toallitas de tela reemplazan cientos de descartables por año.',
    desc: 'La copa menstrual, las toallitas de tela y la ropa interior absorbente duran años. Reemplazan miles de toallitas y tampones descartables a lo largo de la vida, ahorran plata y no van a la basura ni al inodoro.',
    pasos: ['Informate sobre las opciones (copa, toallitas de tela, ropa interior absorbente).', 'Probá la que te resulte más cómoda.', 'Seguí las indicaciones de limpieza.'],
    ef: plastico(1.5), tags: ['plastico', 'baño'],
  }),
  c('cons-desuscribite-de-promociones', 'Desuscribite de los mails de promociones', {
    dom, e: 'easy', i: 'low', min: 10, edad: 'ta', frec: 'recurring', cool: 2160, lugar: 'celular',
    corto: 'Las promociones existen para crear la necesidad que no tenías.',
    desc: 'Los mails y notificaciones de ofertas son la puerta a compras que no estaban en tus planes. Darte de baja de los que no te sirven es menos tentación, menos compras por impulso y un mail más ordenado.',
    pasos: ['Buscá en tu mail las promociones de tiendas.', 'Tocá "desuscribirse" al pie de cada una.', 'Desactivá las notificaciones de ofertas de las apps de compras.'],
    ef: nada(), tags: ['compras', 'digital'], hereda: ['con-desuscribirse-promos'],
  }),
  c('compra-productos-con-contenido-reciclado', 'Elegí productos hechos con material reciclado', {
    dom, e: 'easy', i: 'low', min: 10, lugar: 'compras', edad: 'ta', cool: 720,
    corto: 'Reciclar sólo cierra el círculo si alguien compra lo reciclado.',
    desc: 'Papel higiénico, cuadernos, bolsas, botellas o ropa hechos con material reciclado le dan valor a lo que separás en tu casa. Mirá la etiqueta: muchos dicen el porcentaje.',
    pasos: ['En la próxima compra de papel, cuadernos o bolsas, buscá la opción reciclada.', 'Fijate en la etiqueta el porcentaje de material reciclado.'],
    ef: { c: 0.5 }, tags: ['reciclaje', 'compras'],
  }),
  c('hace-un-mes-sin-compras-innecesarias', 'Hacé un mes sin compras que no sean necesarias', {
    dom, e: 'hard', i: 'high', min: 30, formato: 'reto', edad: 'ta', rango: 'plantula', ahorra: true, cool: 720,
    corto: 'Un mes comprando sólo comida, remedios y lo imprescindible.',
    desc: 'Durante treinta días, nada de ropa, aparatos, decoración ni compras por impulso: sólo lo necesario. Es un reto, y casi siempre deja algo: la cuenta de lo que no hacía falta, y plata ahorrada.',
    pasos: ['Definí qué es "necesario" para vos (comida, remedios, transporte, arreglos).', 'Durante 30 días, no compres nada fuera de esa lista.', 'Anotá las ganas de comprar que se te pasaron solas.'],
    ef: { c: 10, r: 2 }, tags: ['reto', 'compras'],
  }),
  c('res-cajas-para-mudanza', 'Pedí cajas usadas en vez de comprar', {
    dom, e: 'easy', i: 'low', min: 20, formato: 'salida', edad: 'ta', ahorra: true, cool: 2160,
    corto: 'Almacenes y verdulerías tiran cajas en buen estado todos los días.',
    desc: 'Para una mudanza, un envío o para guardar cosas, las cajas que los comercios del barrio desarman todos los días sirven perfecto y son gratis.',
    pasos: ['Preguntá en el almacén, la verdulería o la farmacia si te guardan cajas.', 'Pasá a buscarlas al cierre.'],
    ef: { r: 1, c: 1 }, tags: ['reuso', 'barrio'],
  }),
  c('con-alquila-ropa-de-fiesta', 'Pedí prestada o alquilá la ropa para una fiesta', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'social', edad: 'ta', ahorra: true, cool: 720,
    corto: 'Un traje o un vestido de fiesta se usa una noche y queda colgado años.',
    desc: 'Para un casamiento, unos 15 o una graduación, pedir prestado o alquilar lo que te vas a poner una sola vez es ropa que no se fabrica para quedar guardada.',
    pasos: ['Preguntá a amigos o familia si tienen algo de tu talle.', 'Si no, buscá un alquiler de ropa de fiesta.', 'Devolvelo limpio.'],
    ef: prendas(1), tags: ['ropa', 'prestar'],
  }),
];
