// Energía — luz, gas, cocina, frío y calor. La mayoría te ahorra plata en la factura.
import { d, c, elec, gasKwh, suma, nada } from '../dsl.mjs';

const dom = 'energia';
const frio = ['otono', 'invierno'];
const calor = ['primavera', 'verano'];

export default [
  // ── Luz y aparatos ─────────────────────────────────────────────────────────
  d('apaga-las-luces-de-los-ambientes-vacios', 'Apagá la luz al salir de cada ambiente', {
    dom, e: 'easy', i: 'low', min: 1, rut: true, ahorra: true,
    corto: 'La iluminación puede ser hasta un tercio del consumo eléctrico de una casa.',
    desc: 'Una lámpara prendida en una pieza vacía es consumo puro. La Guía de Ahorro de Energía de la Ciudad calcula que la luz puede llegar a un tercio de la factura eléctrica: apagar al salir, aunque sea por un rato, es la forma más simple de bajarla.',
    pasos: ['Cada vez que salgas de un ambiente, mirá si queda alguien.', 'Si no, apagá la luz.', 'A la noche, recorré la casa y apagá lo que quedó prendido.'],
    ef: elec(0.1), fuente: 'gcba-energia', tags: ['luz', 'chicos'],
  }),
  d('energia-luz-natural', 'Aprovechá la luz del día antes de prender una lámpara', {
    dom, e: 'easy', i: 'low', min: 1, rut: true, ahorra: true,
    corto: 'Una persiana abierta reemplaza varias lámparas.',
    desc: 'Durante el día, abrir cortinas y persianas y acomodarse cerca de la ventana para estudiar o trabajar evita prender luces que no hacen falta. Las paredes claras ayudan a que la luz rinda más.',
    pasos: ['A la mañana, abrí cortinas y persianas.', 'Poné el escritorio o la silla de lectura cerca de una ventana.', 'Prendé luz recién cuando de verdad no alcance.'],
    ef: elec(0.1), fuente: 'gcba-energia', tags: ['luz'], hereda: ['ener-aprovecha-la-luz-natural'],
  }),
  d('ene-lampara-donde-estas', 'Prendé sólo la luz que necesitás', {
    dom, e: 'easy', i: 'low', min: 1, ahorra: true,
    corto: 'Un velador consume mucho menos que todas las luces del techo.',
    desc: 'Para leer, cocinar o trabajar alcanza con iluminar donde estás. Un velador o la luz de la mesada gastan una fracción de lo que gastan todas las del techo juntas.',
    pasos: ['Para leer o estudiar, usá un velador.', 'En la cocina, prendé sólo la luz de la mesada.', 'Dejá las luces generales para cuando hay varias personas.'],
    ef: elec(0.08), tags: ['luz'],
  }),
  d('desenchufa-los-aparatos-que-no-estas-usando', 'Apagá del todo lo que queda en stand-by', {
    dom, e: 'easy', i: 'medium', min: 3, rut: true, ahorra: true,
    corto: 'El consumo "vampiro" de lo que queda en espera puede ser hasta el 15% de la luz del año.',
    desc: 'La tele, el decodificador, el equipo de música y el microondas siguen consumiendo con la lucecita prendida. Según la Guía de Ahorro de Energía de la Ciudad, ese consumo puede llegar al 15% del total anual. Apagarlos del botón o de la zapatilla lo corta.',
    pasos: ['Cuando termines de usar la tele o el equipo, apagalos del botón, no del control.', 'Si están en una zapatilla con interruptor, apagala.', 'Lo que casi no usás, desenchufalo.'],
    ef: elec(0.2), fuente: 'gcba-energia', tags: ['stand-by'], hereda: ['energia-apagar-standby-tv'],
  }),
  d('energia-desenchufar-cargadores', 'Desenchufá los cargadores que no están cargando', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Un cargador enchufado sin nada sigue tirando energía y se calienta.',
    desc: 'Los cargadores del celular, la notebook o los auriculares consumen aunque no haya nada conectado. Es poco por cargador, pero en una casa hay muchos y están enchufados todo el año.',
    pasos: ['Recorré la casa y mirá qué cargadores quedaron enchufados solos.', 'Desenchufalos.', 'Dejá los cargadores en una zapatilla que puedas apagar.'],
    ef: elec(0.05), fuente: 'gcba-energia', tags: ['stand-by', 'chicos'],
  }),
  d('energia-regleta-al-salir', 'Cortá la zapatilla antes de salir de casa', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true, ahorra: true,
    corto: 'Un solo botón apaga el consumo fantasma de todo el escritorio o el living.',
    desc: 'Si la compu, el monitor, la tele o el equipo están en una zapatilla con interruptor, apagarla al salir corta de una vez todo lo que queda en espera, hasta que vuelvas.',
    pasos: ['Antes de salir, apagá la zapatilla del escritorio o de la tele.', 'Dejá enchufado sólo lo que tiene que quedar prendido (heladera, alarma, router si hace falta).'],
    ef: elec(0.15), tags: ['stand-by'],
  }),
  d('ene-apagar-router-noche', 'Apagá el wifi a la noche', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'El router está prendido las 24 horas aunque nadie lo use mientras dormís.',
    desc: 'Si en tu casa nadie usa internet de noche, apagar el router al irse a dormir ahorra ocho horas de consumo por día. Muchos routers traen un botón de encendido o se pueden poner en una zapatilla con timer.',
    pasos: ['Antes de dormir, apagá el router desde su botón o la zapatilla.', 'Prendelo a la mañana.', 'Si alguien lo necesita de noche, dejalo prendido: es un gesto, no una regla.'],
    ef: elec(0.08), tags: ['stand-by', 'digital'],
  }),
  d('energia-pc-suspender', 'Suspendé la compu si te vas más de una hora', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'Media jornada encendida sin nadie adelante es pura pérdida.',
    desc: 'Una compu de escritorio con su monitor consume como varias lámparas. Si vas a almorzar, a una reunión o terminás el día, suspenderla o apagarla (y el monitor también) corta ese gasto sin perder lo que estabas haciendo.',
    pasos: ['Antes de levantarte por más de una hora, suspendé la compu.', 'Apagá el monitor del botón.', 'Configurá que se suspenda sola a los 15 minutos sin uso.'],
    ef: elec(0.1), tags: ['compu'],
  }),
  d('ene-consola-apagada', 'Apagá del todo la consola cuando terminás de jugar', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'En "reposo" o "encendido rápido" una consola sigue gastando toda la noche.',
    desc: 'Muchas consolas y televisores quedan en un modo de espera que mantiene todo listo para arrancar al instante, y eso gasta luz las horas que nadie juega. Apagarla del todo (y la tele del botón, no sólo del control) corta ese gasto; en la configuración de energía se puede elegir que el reposo gaste lo mínimo.',
    pasos: ['Al terminar, apagá la consola desde el menú, no la dejes en reposo.', 'Apagá la tele del botón.', 'Si tiene "encendido rápido" o "modo instantáneo", desactivalo en la configuración de energía.'],
    ef: elec(0.1), tags: ['stand-by', 'chicos'],
  }),
  d('ener-apaga-la-tele-de-fondo', 'Apagá la tele si nadie la está mirando', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Una tele de fondo consume igual que una que alguien mira.',
    desc: 'Muchas casas tienen la tele prendida de compañía. Apagarla cuando nadie la mira (o cambiarla por la radio, que consume mucho menos) es luz que no se paga.',
    pasos: ['Si nadie está mirando, apagá la tele.', 'Si querés sonido de fondo, usá la radio o música.'],
    ef: elec(0.15), tags: ['tele', 'chicos'],
  }),
  d('subi-por-la-escalera-en-vez-del-ascensor', 'Subí por la escalera si son pocos pisos', {
    dom, e: 'easy', i: 'low', min: 2, lugar: 'calle',
    corto: 'Cada viaje de ascensor arranca un motor grande; dos o tres pisos se suben en un minuto.',
    desc: 'El ascensor consume sobre todo al arrancar y frenar. Para subir uno a tres pisos sin carga, la escalera es más rápida de lo que parece, no gasta nada y suma movimiento al día.',
    pasos: ['Si vas a menos de cuatro pisos y no llevás peso, usá la escalera.', 'Dejá el ascensor para quien lo necesita.'],
    ef: elec(0.05), tags: ['edificio'],
  }),

  // ── Cocina ─────────────────────────────────────────────────────────────────
  d('energia-heladera-cerrar-rapido', 'Decidí qué buscás antes de abrir la heladera', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Cada segundo con la puerta abierta, el motor tiene que recuperar el frío.',
    desc: 'La heladera es el único aparato que está prendido todo el año. Abrirla con la idea clara y cerrarla enseguida evita que entre aire caliente que después el motor tiene que enfriar.',
    pasos: ['Pensá qué vas a sacar antes de abrir.', 'Sacalo y cerrá enseguida.', 'Si vas a sacar varias cosas, sacalas todas juntas.'],
    ef: elec(0.05), fuente: 'gcba-energia', tags: ['heladera', 'chicos'],
  }),
  d('ene-no-guardes-caliente', 'Esperá a que la comida se enfríe antes de guardarla', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Una olla caliente en la heladera obliga al motor a trabajar horas.',
    desc: 'La guía de la Ciudad lo recomienda: no guardar alimentos calientes. Dejá que lleguen a temperatura ambiente (no más de dos horas, por seguridad) y recién ahí a la heladera, en recipientes tapados.',
    pasos: ['Pasá lo que sobró a un recipiente chato para que se enfríe rápido.', 'Cuando esté tibio, tapalo y guardalo.', 'No lo dejes afuera más de dos horas.'],
    ef: elec(0.1), fuente: 'gcba-energia', tags: ['heladera', 'cocina'],
  }),
  d('cocina-con-tapa-y-aprovecha-el-calor', 'Cociná con la olla tapada', {
    dom, e: 'easy', i: 'medium', min: 1, rut: true, ahorra: true,
    corto: 'Tapando la olla se ahorra hasta un 25% de gas.',
    desc: 'Sin tapa, buena parte del calor se va con el vapor. Con tapa, el agua hierve antes y la cocción necesita menos fuego. MetroGAS, con datos de ENARGAS, calcula hasta un 25% menos de gas en esa hornalla.',
    pasos: ['Poné la tapa apenas empieces a calentar.', 'Cuando hierva, bajá el fuego al mínimo que mantenga el hervor.'],
    ef: gasKwh(0.4), fuente: 'metrogas-consejos', tags: ['cocina', 'gas'], hereda: ['ene-tapar-ollas'],
  }),
  d('ener-elegi-la-hornalla-del-tamano-justo', 'Que la llama no se salga de la olla', {
    dom, e: 'easy', i: 'low', min: 1, rut: true, ahorra: true,
    corto: 'La llama que asoma por los costados calienta el aire de la cocina, no la comida.',
    desc: 'La olla chica va en la hornalla chica, y la llama tiene que quedar debajo del fondo. Lo que se sale por los costados es gas que se quema sin cocinar nada.',
    pasos: ['Poné cada olla en la hornalla de su tamaño.', 'Regulá la llama para que no se salga del fondo.'],
    ef: gasKwh(0.2), fuente: 'gcba-energia', tags: ['cocina', 'gas'], hereda: ['ene-hornalla-del-tamano'],
  }),
  d('ener-no-abras-el-horno', 'No abras el horno mientras cocina', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'Cada vez que lo abrís se va una buena parte del calor acumulado.',
    desc: 'Abrir el horno para espiar baja la temperatura de golpe y alarga la cocción. Mirá por el vidrio con la luz del horno, y revisá que el burlete de la puerta cierre bien.',
    pasos: ['Mirá por el vidrio en lugar de abrir.', 'Abrí sólo para dar vuelta o sacar.'],
    ef: gasKwh(0.3), fuente: 'gcba-energia', tags: ['cocina', 'horno'], hereda: ['ene-horno-no-abrir'],
  }),
  d('energia-microondas-vs-horno', 'Para calentar una porción, usá la hornalla o el microondas', {
    dom, e: 'easy', i: 'medium', min: 1, edad: 'ta', ahorra: true,
    corto: 'El horno consume tanto como tres hornallas juntas.',
    desc: 'Prender el horno entero para recalentar un plato es calentar una caja enorme para nada. Según ENARGAS, el horno consume como tres hornallas: para porciones chicas, la sartén, una hornalla o el microondas alcanzan.',
    pasos: ['Para recalentar, usá una sartén tapada o el microondas.', 'Dejá el horno para cocinar varias cosas a la vez.'],
    ef: gasKwh(0.8), fuente: 'metrogas-consejos', tags: ['cocina', 'horno'],
  }),
  d('ene-aprovechar-horno-caliente', 'Si prendés el horno, cociná dos cosas', {
    dom, e: 'easy', i: 'medium', min: 5, edad: 'ta', ahorra: true,
    corto: 'Lo más caro del horno es calentarlo: aprovechalo de una vez.',
    desc: 'Si vas a hacer una tarta, aprovechá el mismo horno para unas verduras, unas galletitas o la comida de mañana. Calentarlo una vez para dos cosas gasta mucho menos que dos veces.',
    pasos: ['Planeá qué más podés hornear junto.', 'Metelo en la misma tanda o apenas sale lo primero.', 'Apagá el horno unos minutos antes: el calor que queda termina la cocción.'],
    ef: gasKwh(1), tags: ['cocina', 'horno'],
  }),
  d('ener-cocina-con-olla-a-presion', 'Usá la olla a presión para legumbres y guisos', {
    dom, e: 'easy', i: 'medium', min: 2, edad: 'ta', ahorra: true,
    corto: 'Corta los tiempos de cocción a la mitad.',
    desc: 'Lentejas, garbanzos, porotos, guisos o carnes duras se hacen en la mitad de tiempo en la olla a presión, con mucho menos gas. Si tenés una guardada, hoy es el día de sacarla.',
    pasos: ['Remojá las legumbres desde la noche anterior.', 'Cocinalas en la olla a presión siguiendo los tiempos del fabricante.', 'Apagá apenas termina el tiempo: no hace falta más.'],
    ef: gasKwh(0.6), fuente: 'metrogas-consejos', tags: ['cocina', 'legumbres'],
  }),
  d('ene-apagar-antes', 'Apagá la hornalla unos minutos antes de terminar', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'Los fideos, el arroz y los guisos terminan de cocinarse con el calor que queda.',
    desc: 'Una olla tapada mantiene el calor varios minutos. Apagar el fuego un poco antes del final deja que la comida termine sola, sin gastar más gas.',
    pasos: ['Cuando falten 3 o 4 minutos, apagá el fuego.', 'Dejá la olla tapada hasta servir.'],
    ef: gasKwh(0.15), tags: ['cocina', 'gas'],
  }),
  d('energia-pava-justa', 'Calentá en la pava sólo el agua que vas a usar', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Llenar la pava hasta arriba para un té es calentar agua de más.',
    desc: 'Cada litro que calentás de más es energía que se va cuando el agua se enfría y se tira. Medí con la taza o el termo y calentá sólo eso.',
    pasos: ['Medí el agua con la taza o el termo que vas a usar.', 'Calentá sólo esa cantidad.'],
    ef: elec(0.05), tags: ['mate', 'cocina'],
  }),
  d('ene-mate-sin-hervir', 'No hiervas el agua del mate', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'Para el mate alcanza con 75 u 80 grados: hervirla gasta de más y quema la yerba.',
    desc: 'El agua que hierve no mejora el mate: lo vuelve amargo y gasta energía que después se pierde esperando que baje la temperatura. Cortá la pava cuando empieza a hacer ruido, antes del hervor, o usá la posición "mate" de la pava eléctrica.',
    pasos: ['Cortá la pava cuando aparecen las primeras burbujas chicas, antes de que hierva.', 'Si tu pava eléctrica tiene temperatura, ponela en 80 °C.'],
    ef: elec(0.03), tags: ['mate'],
  }),
  d('ene-termo-no-recalentar', 'Guardá el agua caliente en el termo en vez de recalentar', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Recalentar la pava cinco veces en la tarde gasta más que calentarla una vez.',
    desc: 'Si vas a tomar mate o té durante un rato largo, calentá el agua una vez y pasala al termo. Mantiene la temperatura horas sin gastar nada más.',
    pasos: ['Calentá el agua una sola vez.', 'Pasala al termo y cerralo bien.', 'Serví del termo toda la tarde.'],
    ef: elec(0.1), tags: ['mate'],
  }),

  // ── Ropa ───────────────────────────────────────────────────────────────────
  d('lava-la-ropa-con-agua-fria', 'Lavá la ropa con agua fría', {
    dom, e: 'easy', i: 'medium', min: 1, ahorra: true,
    corto: 'Casi toda la energía de un lavado se va en calentar el agua.',
    desc: 'Los jabones actuales lavan bien en frío. La Guía de Ahorro de la Ciudad recomienda agua fría y programas cortos: dejá el agua caliente para toallas, sábanas o manchas de grasa.',
    pasos: ['Elegí el programa en frío.', 'Si hay manchas difíciles, tratalas a mano antes.'],
    ef: elec(0.5), fuente: 'gcba-energia', tags: ['lavarropas'], hereda: ['agua-lavarropas-carga-agua-fria'],
  }),
  d('colga-la-ropa-al-aire-en-vez-de-usar-secadora', 'Secá la ropa al aire, no en el secarropas', {
    dom, e: 'easy', i: 'medium', min: 5, ahorra: true,
    corto: 'El secarropas es de lo que más gasta en una casa; el sol y el viento son gratis.',
    desc: 'Un ciclo de secarropas a calor consume como dejar varias lámparas prendidas todo el día. Colgar al sol o en un tender cerca de la ventana seca igual, desinfecta y cuida las telas. Nunca uses la estufa para secar ropa.',
    pasos: ['Colgá la ropa afuera o en un tender junto a una ventana.', 'Sacudí bien cada prenda antes de colgarla, así se arruga menos.', 'Dejá el secarropas para un apuro.'],
    ef: elec(1), fuente: 'gcba-energia', tags: ['ropa', 'sol'], hereda: ['ene-secar-al-sol'],
    req: ['secarropas'],
  }),
  d('ene-planchar-todo-junto', 'Planchá todo junto y sólo lo necesario', {
    dom, e: 'easy', i: 'low', min: 15, edad: 'ta',
    corto: 'La plancha gasta mucho en calentarse: mejor una tanda que cinco.',
    desc: 'Cada vez que prendés la plancha, la mayor parte de la energía se va en llegar a temperatura. Juntá lo que hay que planchar y hacelo de una vez, empezando por lo que pide menos calor. Mucha ropa, colgada bien estirada, no necesita plancha.',
    pasos: ['Juntá lo que hay que planchar.', 'Empezá por las telas delicadas y terminá con el algodón.', 'Apagá un poco antes: lo último se plancha con el calor que queda.'],
    ef: elec(0.3), tags: ['ropa'],
  }),

  // ── Calor del verano ───────────────────────────────────────────────────────
  d('energia-ventilador-antes-aire', 'Probá el ventilador antes que el aire', {
    dom, e: 'easy', i: 'medium', min: 1, est: calor, ahorra: true,
    corto: 'Un ventilador consume hasta un 90% menos que un aire acondicionado.',
    desc: 'Con calor moderado, un ventilador de techo o de pie alcanza para estar cómodo. La Guía de Ahorro de Energía de la Ciudad calcula que consume hasta un 90% menos que el aire. Dejá el aire para los días en que de verdad no alcanza.',
    pasos: ['Cuando sientas calor, arrancá con el ventilador.', 'Cerrá cortinas del lado del sol.', 'Prendé el aire sólo si con eso no alcanza.'],
    ef: elec(1), fuente: 'gcba-energia', tags: ['verano', 'calor'],
    req: ['aire'],
  }),
  d('ene-aire-24', 'Poné el aire acondicionado en 24 °C', {
    dom, e: 'easy', i: 'high', min: 1, req: ['aire'], est: calor, rut: true, ahorra: true,
    corto: 'Cada grado menos sube el consumo cerca de un 8%: 24 °C es la recomendación oficial.',
    desc: 'La Secretaría de Energía y la Ciudad recomiendan 24 °C en verano. Ponerlo en 18 no enfría más rápido: sólo hace trabajar al equipo de más. Con la temperatura justa, puertas cerradas y el filtro limpio, el ambiente queda fresco y la factura no se dispara.',
    pasos: ['Fijá el aire en 24 °C.', 'Cerrá puertas y ventanas del ambiente.', 'Usá el modo "sleep" o el timer a la noche.'],
    ef: elec(1), fuente: 'gcba-energia', tags: ['verano', 'calor', 'aire'],
  }),
  d('energia-cerrar-puertas-clima', 'Cerrá puertas y ventanas del ambiente que climatizás', {
    dom, e: 'easy', i: 'medium', min: 1, rut: true, ahorra: true,
    corto: 'Enfriar o calentar toda la casa para una sola pieza no tiene sentido.',
    desc: 'Si prendiste el aire o la estufa, el calor (o el frío) se escapa por la puerta abierta al resto de la casa o al pasillo. Cerrar el ambiente hace que el equipo llegue antes a la temperatura y trabaje menos. Ventilá 5 a 10 minutos por día, no más.',
    pasos: ['Al prender el aire o la estufa, cerrá puertas y ventanas de ese ambiente.', 'Ventilá unos minutos a la mañana, con el equipo apagado.'],
    ef: elec(0.5), fuente: 'gcba-energia', tags: ['calor', 'frio'],
  }),
  d('ener-cortinas-segun-la-estacion', 'Usá las cortinas a favor del clima', {
    dom, e: 'easy', i: 'medium', min: 2, rut: true, ahorra: true,
    corto: 'Bien usadas, las cortinas ahorran más que subir o bajar un grado el aire o la estufa.',
    desc: 'En verano, cerrá cortinas y persianas del lado donde pega el sol de la tarde. En invierno, al revés: abrilas de día para que el sol caliente y cerralas al anochecer para guardar el calor. En el hemisferio sur la fachada que más sol recibe es la norte.',
    pasos: ['En verano: bajá persianas del lado del sol en las horas de más calor.', 'En invierno: abrí de día y cerrá apenas baja el sol.'],
    ef: elec(0.2), fuente: 'gcba-energia', tags: ['sol', 'calor', 'frio'], hereda: ['ene-cortina-al-sol'],
  }),
  d('ene-ventilar-noche-verano', 'Abrí las ventanas a la noche para refrescar la casa', {
    dom, e: 'easy', i: 'medium', min: 2, est: ['verano'], ahorra: true,
    corto: 'El aire fresco de la noche enfría paredes y pisos gratis.',
    desc: 'En verano, la casa guarda el calor del día. Abrir ventanas enfrentadas a la noche hace una corriente que la refresca, y a la mañana cerrar todo antes de que caliente el sol guarda ese fresco por horas.',
    pasos: ['A la noche, abrí ventanas de lados opuestos de la casa.', 'A la mañana temprano, cerrá ventanas y cortinas del lado del sol.'],
    fuente: 'gcba-energia', tags: ['verano', 'calor'],
  }),
  d('ene-apagar-antes-de-irte', 'Apagá el aire o la estufa un rato antes de irte', {
    dom, e: 'easy', i: 'low', min: 1, ahorra: true,
    corto: 'El ambiente mantiene la temperatura un buen rato: no hace falta que el equipo siga hasta la puerta.',
    desc: 'Si vas a salir o a cambiar de ambiente, apagá el equipo 15 o 30 minutos antes. La temperatura se sostiene sola ese tiempo y el equipo no trabaja para una pieza que va a quedar vacía.',
    pasos: ['Media hora antes de salir, apagá el aire o la estufa.', 'Si te vas por horas, verificá que quede apagado.'],
    ef: elec(0.4), tags: ['calor', 'frio'],
  }),

  // ── Frío del invierno ──────────────────────────────────────────────────────
  d('baja-un-poco-la-calefaccion-o-el-aire', 'Calefaccioná a 20 °C, no más', {
    dom, e: 'easy', i: 'high', min: 1, est: frio, rut: true, ahorra: true,
    corto: 'Cada grado menos de calefacción ahorra hasta un 10% de gas.',
    desc: 'La Ciudad recomienda 20 °C en invierno y ENARGAS, 18 °C de día y 15 °C de noche. Según MetroGAS, con datos de ENARGAS, bajar un solo grado ahorra hasta un 10%. Si la estufa no tiene termostato, bajá la llama apenas el ambiente esté templado.',
    pasos: ['Si tu estufa o calefactor tiene termostato, ponelo en 20 °C.', 'Si no tiene, bajá la llama cuando el ambiente ya está templado.', 'A la noche, bajalo más o apagalo.'],
    ef: gasKwh(2), fuente: 'metrogas-consejos', tags: ['invierno', 'frio', 'gas'],
  }),
  d('ene-abrigate-antes', 'Abrigate antes de subir la calefacción', {
    dom, e: 'easy', i: 'medium', min: 1, est: frio, rut: true, ahorra: true,
    corto: 'Un buzo y medias gruesas valen dos grados de estufa.',
    desc: 'En casa mucha gente anda en remera en pleno invierno con la estufa a fondo. ENARGAS recomienda lo obvio que se nos olvida: frazadas, camperas, medias. El cuerpo abrigado necesita menos grados en el ambiente.',
    pasos: ['Antes de tocar la estufa, ponete un buzo, medias y pantuflas.', 'Para el sillón, una manta.', 'Recién si seguís con frío, subí la calefacción.'],
    ef: gasKwh(1), tags: ['invierno', 'frio'],
  }),
  d('ene-bolsa-agua-caliente', 'Calentá la cama con una bolsa de agua caliente', {
    dom, e: 'easy', i: 'medium', min: 3, est: ['invierno'], adulto: true, ahorra: true,
    corto: 'Una bolsa de agua caliente reemplaza horas de estufa prendida a la noche.',
    desc: 'Dormir con la estufa prendida gasta gas toda la noche y no es seguro. Una bolsa de agua caliente (o una botella bien cerrada envuelta en una toalla) calienta la cama un buen rato, y con frazadas el resto de la noche se pasa bien.',
    pasos: ['Llená la bolsa con agua caliente, no hirviendo, hasta dos tercios.', 'Sacale el aire, cerrala bien y envolvela en una funda o toalla.', 'Ponela en la cama un rato antes de acostarte.'],
    ef: gasKwh(1), tags: ['invierno', 'frio'],
  }),
  d('ene-apagar-estufa-dormir', 'Apagá la estufa antes de dormir', {
    dom, e: 'easy', i: 'high', min: 1, est: ['invierno'], edad: 'ta', rut: true, ahorra: true,
    corto: 'Ocho horas menos de gas, y la forma más segura de dormir.',
    desc: 'ENARGAS recomienda 15 °C a la noche o apagar la calefacción. Además de ahorrar, es seguridad: una estufa mal ventilada en una pieza cerrada puede producir monóxido de carbono. Con la cama abrigada no hace falta.',
    pasos: ['Antes de acostarte, apagá la estufa o el calefactor de la pieza.', 'Si la vas a dejar, que sea de tiro balanceado y con una ventana apenas abierta.', 'Abrigá la cama con frazadas o una bolsa de agua caliente.'],
    ef: gasKwh(3), fuente: 'metrogas-seguridad', tags: ['invierno', 'gas', 'seguridad'],
  }),
  d('ene-no-calefaccionar-vacios', 'Calefaccioná sólo donde hay gente', {
    dom, e: 'easy', i: 'medium', min: 1, est: frio, ahorra: true,
    corto: 'Una estufa en una pieza vacía calienta paredes que nadie usa.',
    desc: 'MetroGAS lo pone entre sus primeros consejos: calefaccionar sólo los ambientes ocupados. Apagá o bajá al mínimo la estufa de las piezas donde no hay nadie y cerrá sus puertas.',
    pasos: ['Recorré la casa y apagá las estufas de los ambientes vacíos.', 'Cerrá esas puertas para que no se escape el calor.'],
    ef: gasKwh(2), fuente: 'metrogas-consejos', tags: ['invierno', 'gas'],
  }),

  // ── Afuera de casa ─────────────────────────────────────────────────────────
  d('ene-aprovecha-las-brasas', 'Aprovechá las brasas del asado para cocinar algo más', {
    dom, e: 'easy', i: 'low', min: 10, req: ['parrilla'], dias: 'finde', ahorra: true,
    corto: 'Las brasas que sobran alcanzan para unas verduras, unas papas o la comida de mañana.',
    desc: 'Después del asado quedan brasas que se apagan solas. Aprovecharlas para unas verduras al rescoldo, morrones, cebollas o zapallos para la semana es cocinar sin prender otra vez la hornalla.',
    pasos: ['Cuando sacás la carne, poné verduras enteras sobre la parrilla o envueltas al rescoldo.', 'Guardalas en la heladera para usar en la semana.'],
    ef: gasKwh(1), tags: ['asado', 'cocina'],
  }),
  d('ene-oficina-apagar-puesto', 'Apagá el monitor y la luz de tu puesto al irte', {
    dom, e: 'easy', i: 'low', min: 1, req: ['trabajo'], lugar: 'trabajo', dias: 'habil', edad: 'a', rut: true,
    corto: 'En una oficina, lo que queda prendido toda la noche se multiplica por cada escritorio.',
    desc: 'Monitores, impresoras, luces y aires de oficina muchas veces quedan prendidos hasta el otro día. Apagar lo tuyo al irte (y avisar si ves algo más prendido) es luz que tu trabajo no paga y que no se genera.',
    pasos: ['Antes de irte, apagá el monitor y la compu.', 'Si sos de los últimos, apagá las luces y el aire de tu sector.'],
    ef: elec(0.3), tags: ['trabajo'],
  }),
  d('ene-aula-luces-recreo', 'Apagá las luces del aula en el recreo', {
    dom, e: 'easy', i: 'low', min: 1, req: ['estudio'], lugar: 'escuela', dias: 'habil', edad: 'kt',
    corto: 'Si todos salen, nadie necesita las luces prendidas.',
    desc: 'Proponé ser quien apaga las luces y el ventilador cuando el curso sale al recreo o se va a otra clase. En una escuela con muchas aulas, la suma es grande, y el gesto contagia.',
    pasos: ['Cuando salgan del aula, fijate si queda alguien.', 'Si no, apagá luces y ventiladores.', 'Proponelo como una tarea del curso.'],
    ef: elec(0.2), tags: ['escuela', 'chicos'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('ene-apagar-piloto-estufa', 'Apagá el piloto de la estufa cuando termina el frío', {
    dom, e: 'easy', i: 'high', min: 5, req: ['gas'], est: calor, edad: 'a', ahorra: true, cool: 2160,
    corto: 'Un piloto prendido todo el año gasta como para hacer cientos de bizcochuelos.',
    desc: 'Los pilotos de las estufas a gas encendidos sin uso son, según ENARGAS, cerca del 5% de todo el gas que consumen los hogares. Apenas pasa el frío, apagarlos es de lo que más ahorra con menos esfuerzo. En otoño, se prenden de nuevo.',
    pasos: ['Girá la perilla de la estufa a "apagado" (no a "piloto").', 'Verificá que la llamita se haya apagado.', 'Si tenés dudas de cómo volver a prenderla, anotá el modelo y buscá el manual.'],
    ef: gasKwh(60), fuente: 'metrogas-consejos', tags: ['gas', 'piloto', 'verano'],
  }),
  c('ene-piloto-calefon-viaje', 'Apagá el piloto del calefón o termotanque si te vas unos días', {
    dom, e: 'easy', i: 'medium', min: 5, req: ['gas'], edad: 'a', ahorra: true, cool: 168,
    corto: 'Si nadie va a usar agua caliente, no hace falta mantenerla caliente.',
    desc: 'Un termotanque mantiene 80 o 100 litros calientes todo el día, y el piloto del calefón quema gas aunque nadie abra la canilla. Si te vas de viaje o un fin de semana largo, ponelo en "piloto" o apagalo.',
    pasos: ['Antes de viajar, poné el termotanque en posición "piloto" o apagalo.', 'Si es calefón, apagá el piloto siguiendo su instructivo.', 'Al volver, prendelo con cuidado o pedí ayuda.'],
    ef: gasKwh(15), fuente: 'metrogas-consejos', tags: ['gas', 'piloto', 'viaje'],
  }),
  c('ajusta-el-termotanque-a-una-temperatura-eficient', 'Bajá la temperatura del termotanque o calefón', {
    dom, e: 'easy', i: 'high', min: 5, edad: 'a', ahorra: true, cool: 4320,
    corto: 'Regularlo a unos 42 °C puede ahorrar hasta un 35% de la energía del agua caliente.',
    desc: 'Si el agua sale tan caliente que tenés que mezclarla con fría, estás pagando por calentar de más. La Guía de Ahorro de la Ciudad recomienda regular el termotanque o calefón a 42 °C: alcanza para bañarse y ahorra hasta un 35%.',
    pasos: ['Buscá la perilla de temperatura del termotanque o calefón.', 'Bajala a la posición media o "mínimo confort".', 'Probá en la ducha: si sale cómoda sin mezclar mucho, quedó bien.'],
    ef: gasKwh(30), fuente: 'gcba-energia', tags: ['gas', 'agua caliente'], hereda: ['ener-poné-timer-al-termotanque'],
  }),
  c('ene-heladera-lejos-del-calor', 'Dejale aire atrás a la heladera', {
    dom, e: 'easy', i: 'medium', min: 10, edad: 'ta', frec: 'one_time', ahorra: true,
    corto: 'Pegada a la pared o al lado del horno, la heladera trabaja de más todo el día.',
    desc: 'La heladera saca el calor por la rejilla de atrás. La guía de la Ciudad recomienda dejarle 15 cm de la pared y alejarla de fuentes de calor como el horno o el sol directo de una ventana.',
    pasos: ['Separá la heladera unos 15 cm de la pared.', 'Si está al lado del horno o al sol, buscale otro lugar si podés.', 'No la uses de estante: arriba también tiene que respirar.'],
    ef: elec(1.5), fuente: 'gcba-energia', tags: ['heladera'],
  }),
  c('ener-limpia-la-parrilla-de-la-heladera', 'Limpiá la rejilla de atrás de la heladera', {
    dom, e: 'easy', i: 'medium', min: 15, edad: 'ta', ahorra: true, cool: 4320,
    corto: 'Con polvo acumulado, el motor tarda más en sacar el calor.',
    desc: 'La rejilla negra de atrás (el condensador) junta polvo y pelusa. Limpiarla dos veces por año ayuda a que la heladera enfríe con menos esfuerzo y dure más.',
    pasos: ['Desenchufá la heladera.', 'Separala de la pared y pasá un cepillo suave o la aspiradora por la rejilla.', 'Volvé a enchufarla.'],
    ef: elec(1.5), tags: ['heladera'],
  }),
  c('ene-descongelar-freezer', 'Descongelá el freezer cuando tenga escarcha', {
    dom, e: 'medium', i: 'medium', min: 60, edad: 'ta', ahorra: true, cool: 2160,
    corto: 'Una capa gruesa de hielo funciona como aislante y obliga al motor a trabajar más.',
    desc: 'Si tu freezer no es "no frost", la escarcha se acumula y le resta eficiencia. La guía de la Ciudad recomienda descongelarlo regularmente: cuando la capa pasa el medio centímetro, es momento.',
    pasos: ['Pasá lo congelado a una conservadora o envolvelo en diarios.', 'Desenchufá y dejá la puerta abierta con trapos abajo.', 'Secá todo, enchufá y esperá que enfríe antes de volver a cargarlo.'],
    ef: elec(4), fuente: 'gcba-energia', tags: ['heladera'], hereda: ['ener-descongela-el-freezer'],
  }),
  c('ene-burlete-heladera', 'Probá el burlete de la heladera con una hoja', {
    dom, e: 'easy', i: 'medium', min: 5, formato: 'aprender', edad: 'kta', adulto: true, cool: 4320,
    corto: 'Si la hoja sale sin resistencia, la heladera pierde frío por la puerta.',
    desc: 'Un experimento rápido: cerrá la puerta sobre una hoja de papel y tirá. Si sale fácil, el burlete no ajusta y la heladera pierde frío todo el día. Muchas veces se arregla limpiándolo con agua y jabón.',
    pasos: ['Poné una hoja entre la puerta y la heladera y cerrá.', 'Tirá de la hoja: tiene que costar sacarla.', 'Probá en varios puntos. Si sale suelta, limpiá el burlete o cambialo.'],
    tags: ['heladera', 'experimento', 'chicos'],
  }),
  c('ene-limpiar-filtro-aire', 'Limpiá el filtro del aire acondicionado', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['aire'], est: calor, edad: 'ta', ahorra: true, cool: 720,
    corto: 'Un filtro sucio obliga al equipo a trabajar de más y tira aire peor.',
    desc: 'La guía de la Ciudad recomienda limpiar los filtros regularmente: el equipo consume menos y dura más. En los splits se sacan sin herramientas y se lavan con agua.',
    pasos: ['Apagá y desenchufá el equipo.', 'Abrí la tapa frontal y sacá los filtros.', 'Lavalos con agua tibia, dejalos secar a la sombra y volvé a ponerlos.'],
    ef: elec(5), fuente: 'gcba-energia', tags: ['aire', 'verano'],
  }),
  c('ene-burletes-caseros', 'Tapá una rendija por donde entra frío', {
    dom, e: 'easy', i: 'high', min: 20, est: frio, costo: 'bajo', ahorra: true, cool: 720,
    corto: 'Una rendija debajo de la puerta tira abajo toda la calefacción.',
    desc: 'Una casa bien cerrada puede gastar mucho menos en calefacción. No hace falta obra: un burlete autoadhesivo, una toalla enrollada al pie de la puerta o masilla en una ventana cortan la corriente de aire.',
    pasos: ['Pasá la mano por puertas y ventanas: donde sentís aire frío, hay rendija.', 'Poné burlete autoadhesivo en el marco, o un "chorizo" de tela al pie de la puerta.', 'Para las ventanas, masilla o cinta.'],
    ef: gasKwh(10), fuente: 'gcba-energia', tags: ['invierno', 'frio', 'arreglo'], hereda: ['mejora-la-aislacion-y-burletes-de-tu-casa'],
  }),
  c('ene-mantenimiento-gas', 'Hacé revisar los artefactos a gas antes del invierno', {
    dom, e: 'medium', i: 'medium', min: 60, req: ['gas'], est: ['otono'], edad: 'a', cool: 8760,
    corto: 'Un artefacto en buen estado gasta menos y no produce monóxido de carbono.',
    desc: 'La guía de la Ciudad y las distribuidoras recomiendan un mantenimiento anual antes del invierno, hecho por un gasista matriculado. Revisa las llamas, la ventilación y los conductos: es eficiencia y, sobre todo, seguridad.',
    pasos: ['Llamá a un gasista matriculado antes de que empiece el frío.', 'Pedile que revise estufas, calefón o termotanque y las ventilaciones.', 'Nunca tapes las rejillas de ventilación.'],
    ef: nada(), fuente: 'metrogas-seguridad', tags: ['gas', 'seguridad', 'invierno'],
  }),
  c('ene-llama-azul', 'Fijate que la llama de la cocina sea azul', {
    dom, e: 'easy', i: 'medium', min: 3, formato: 'aprender', edad: 'kta', adulto: true, cool: 2160,
    corto: 'Una llama amarilla o anaranjada quema mal el gas: gasta más y puede producir monóxido.',
    desc: 'Una buena combustión se ve: llama estable, azul en el centro y más clara afuera. Si es amarilla, alta o tiznada, el quemador está sucio o mal regulado. Limpiarlo mejora el rendimiento; si sigue igual, hay que llamar a un gasista.',
    pasos: ['Prendé cada hornalla y mirá el color de la llama.', 'Si alguna está amarilla, limpiá el quemador con un cepillo y dejalo secar.', 'Si sigue así, pedí que la revise un gasista matriculado.'],
    ef: nada(), fuente: 'gcba-energia', tags: ['gas', 'seguridad', 'cocina', 'experimento'],
  }),
  c('cambia-todas-las-lamparas-a-led', 'Cambiá por LED las lámparas que te quedan', {
    dom, e: 'easy', i: 'high', min: 15, edad: 'ta', costo: 'bajo', ahorra: true, cool: 4320,
    corto: 'Una LED consume una fracción de una incandescente o halógena y dura años.',
    desc: 'Si todavía quedan lámparas viejas (incandescentes, halógenas o de bajo consumo), empezá por las que más horas están prendidas: cocina, living, la de la vereda. La guía de la Ciudad la pone entre las primeras medidas de eficiencia.',
    pasos: ['Identificá las lámparas que no son LED.', 'Cambiá primero las que más horas están prendidas.', 'Llevá las de bajo consumo viejas a un punto de residuos especiales: tienen mercurio.'],
    ef: elec(3), fuente: 'gcba-energia', tags: ['luz'],
    mercado: ['hogar-y-deco', 'iluminacion', 'Lámparas LED que duran años. Estos negocios están en el programa de Brote.'],
  }),
  c('hace-una-auditoria-energetica-de-tu-casa', 'Mirá tus facturas y buscá el mes más caro', {
    dom, e: 'easy', i: 'medium', min: 20, formato: 'aprender', edad: 'a', cool: 2160,
    corto: 'Saber cuándo y en qué gastás más es el primer paso para gastar menos.',
    desc: 'Las facturas de luz y gas muestran el consumo de los últimos meses. Compararlas te dice si el pico es en verano (aire), en invierno (estufa) o parejo todo el año (heladera, stand-by, agua caliente), y dónde conviene empezar.',
    pasos: ['Buscá las últimas facturas de luz y gas (en la app o el mail de la distribuidora).', 'Mirá el gráfico de consumo del año.', 'Elegí el mes más alto y una acción de Brote para ese uso.'],
    ef: nada(), tags: ['factura'], hereda: ['ene-revisar-consumo'],
  }),
  c('ene-detective-stand-by', 'Cazá las lucecitas de stand-by de tu casa', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'aprender', edad: 'k', adulto: true, frec: 'recurring', cool: 720,
    corto: 'Una misión: contá cuántas luces rojas quedan prendidas cuando nadie usa nada.',
    desc: 'Con la casa a oscuras, buscá todas las lucecitas que quedan prendidas: tele, decodificador, microondas, cargadores, equipo de música. Cada una es un aparato consumiendo. Con un adulto, decidan cuáles se pueden apagar del todo.',
    pasos: ['A la noche, apagá las luces y recorré la casa.', 'Anotá cada lucecita que veas y de qué aparato es.', 'Con un adulto, elijan cuáles apagar del botón o de la zapatilla.'],
    tags: ['stand-by', 'chicos', 'mision'],
  }),
  c('ener-usa-el-ventilador-de-techo-al-reves', 'Invertí el ventilador de techo en invierno', {
    dom, e: 'easy', i: 'medium', min: 5, est: frio, edad: 'ta', cool: 4320,
    corto: 'Girando al revés y despacio, baja el aire caliente que se junta en el techo.',
    desc: 'El aire caliente sube y se queda arriba. Muchos ventiladores de techo tienen una llave para invertir el giro: en velocidad baja empujan ese calor hacia abajo sin hacer corriente, y la estufa rinde más.',
    pasos: ['Con el ventilador apagado, buscá la llavecita en el cuerpo del motor.', 'Cambiá el sentido de giro.', 'Usalo en la velocidad más baja mientras está prendida la estufa.'],
    ef: gasKwh(1), tags: ['invierno', 'frio'],
  }),
  c('agua-aislar-canos-agua-caliente', 'Forrá los caños de agua caliente que están a la vista', {
    dom, e: 'medium', i: 'medium', min: 40, edad: 'a', costo: 'bajo', ahorra: true, frec: 'one_time',
    corto: 'Sin aislación, el agua se enfría en el camino y tirás litros esperando que salga caliente.',
    desc: 'Los caños de agua caliente que pasan por afuera, por el lavadero o el techo pierden calor todo el tiempo. Un forro de espuma aislante, que se corta a medida, hace que el agua llegue caliente antes y con menos gas.',
    pasos: ['Medí el diámetro y el largo de los caños de agua caliente que estén a la vista.', 'Comprá cobertor de espuma para caños en la ferretería.', 'Cortalo a medida, abrazá el caño y cerralo con cinta.'],
    ef: gasKwh(10), tags: ['agua caliente', 'gas', 'arreglo'],
  }),
];
