// Movilidad — caminar, la bici, el colectivo, el tren, y manejar mejor cuando hace falta el auto.
import { d, c, km, nada, medida, por } from '../dsl.mjs';

const dom = 'movilidad';

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('camina-un-trayecto-en-vez-de-ir-en-auto', 'Caminá un trayecto que ibas a hacer en auto o colectivo', {
    dom, e: 'easy', i: 'high', min: 15, lugar: 'calle', rut: true,
    corto: 'Los viajes cortos en auto son los que más contaminan por kilómetro.',
    desc: 'Un viaje de diez cuadras en auto arranca con el motor frío, que es cuando más consume y más contamina. Caminando llegás casi en el mismo tiempo, sumás los minutos de actividad que recomienda la OMS y no emitís nada.',
    pasos: ['Elegí un trayecto de hasta 20 cuadras que hoy harías en auto, taxi o colectivo.', 'Hacelo caminando.', 'Contá cuántas cuadras fueron.'],
    medida: medida('¿Cuántas cuadras caminaste?', 'cuadra', 'cuadras', { min: 1, max: 60, def: 10, por: por(km(0.07)) }),
    fuente: 'oms-actividad-fisica', tags: ['caminar'],
  }),
  d('anda-en-bici-a-algun-lado-hoy', 'Andá en bici a algún lado hoy', {
    dom, e: 'medium', i: 'high', min: 20, req: ['bici'], lugar: 'calle', rut: true,
    corto: 'En la ciudad, la bici tarda lo mismo que el auto en trayectos de hasta 5 km, y no emite nada.',
    desc: 'Ir en bici al trabajo, a la escuela, a hacer un trámite o a ver a alguien reemplaza un viaje en auto, moto o colectivo. Cada kilómetro en bici en vez de auto son unos 170 gramos de CO₂ que no salen del caño de escape.',
    pasos: ['Elegí un trayecto que hoy harías en otro medio.', 'Hacelo en bici, por bicisenda o calles tranquilas.', 'Contá los kilómetros (ida y vuelta).'],
    medida: medida('¿Cuántos kilómetros hiciste en bici?', 'km', 'km', { min: 1, max: 40, def: 4, por: por(km(0.7)) }),
    fuente: 'owid-transporte', tags: ['bici'],
  }),
  d('usa-transporte-publico-hoy', 'Viajá en colectivo, tren o subte en vez de auto o remis', {
    dom, e: 'easy', i: 'high', min: 5, edad: 'kta', lugar: 'calle', rut: true, ahorra: true,
    corto: 'Un colectivo lleno reemplaza decenas de autos en la calle.',
    desc: 'Por pasajero, el colectivo y el tren emiten una fracción de lo que emite un auto o un remis con una sola persona. Resolver hoy un viaje con la SUBE en lugar del auto, un taxi o una app es una de las acciones de más impacto que se pueden hacer en un día.',
    pasos: ['Elegí un viaje de hoy que harías en auto, taxi o app.', 'Buscá cómo hacerlo en transporte público.', 'Contá los kilómetros del viaje.'],
    medida: medida('¿De cuántos kilómetros fue el viaje?', 'km', 'km', { min: 1, max: 60, def: 6, por: por(km(0.75)) }),
    fuente: 'owid-transporte', tags: ['colectivo', 'tren', 'sube'],
  }),
  d('mov-bajar-una-parada-antes', 'Bajate una parada antes y caminá', {
    dom, e: 'easy', i: 'low', min: 5, lugar: 'calle', rut: true,
    corto: 'Cinco minutos de caminata extra, todos los días, son media hora de movimiento por semana.',
    desc: 'No cambia el viaje, cambia tu día: bajarte antes suma movimiento, te hace conocer el barrio y es el primer paso para animarte a hacer a pie trayectos enteros.',
    pasos: ['Bajate del colectivo o el subte una parada antes de la tuya.', 'Caminá el resto.'],
    ef: nada(), fuente: 'oms-actividad-fisica', tags: ['caminar', 'colectivo'],
  }),
  d('mov-caminar-a-comprar', 'Hacé las compras del barrio caminando', {
    dom, e: 'easy', i: 'medium', min: 20, lugar: 'compras', rut: true,
    corto: 'Lo que está cerca no necesita auto.',
    desc: 'Ir caminando al almacén, la verdulería o la farmacia del barrio en vez de manejar hasta un súper lejano ahorra combustible, estacionamiento y le da trabajo al comercio de cercanía. Con un changuito o una mochila, se lleva bastante.',
    pasos: ['Llevá un changuito o una mochila grande.', 'Hacé las compras en los negocios cercanos, a pie.'],
    ef: km(1), tags: ['caminar', 'compras', 'barrio'], hereda: ['com-comprar-en-el-barrio'],
  }),
  d('mov-combinar-mandados', 'Juntá todos los mandados en una sola salida', {
    dom, e: 'easy', i: 'medium', min: 5, req: ['auto'], edad: 'ta', rut: true, ahorra: true,
    corto: 'Cuatro salidas cortas con el motor frío contaminan más que una vuelta larga.',
    desc: 'El auto consume y contamina mucho más en los primeros kilómetros con el motor frío. Anotar los trámites y hacerlos todos en un mismo recorrido (en el orden que menos vueltas da) ahorra combustible y tiempo.',
    pasos: ['Anotá todo lo que tenés que hacer.', 'Armá un recorrido en orden, sin volver sobre tus pasos.', 'Hacelo todo en una salida.'],
    ef: km(3), tags: ['auto'], hereda: ['mov-junta-los-mandados-en-un-viaje'],
  }),
  d('mov-maneja-suave', 'Manejá sin acelerones ni frenadas bruscas', {
    dom, e: 'easy', i: 'medium', min: 1, req: ['auto'], edad: 'a', rut: true, ahorra: true,
    corto: 'Manejar parejo puede bajar bastante el consumo en el mismo recorrido.',
    desc: 'Acelerar fuerte y frenar de golpe tira combustible. Anticipar los semáforos, soltar el acelerador antes y mantener una velocidad constante consume menos, gasta menos los frenos y es más seguro.',
    pasos: ['Mirá lejos para anticipar semáforos y frenadas.', 'Acelerá de forma gradual y pasá los cambios temprano.', 'Soltá el acelerador antes de llegar en vez de frenar a último momento.'],
    ef: { c: 0.5 }, tags: ['auto', 'manejo'], hereda: ['mov-manejar-suave'],
  }),
  d('aire-no-dejar-el-motor-en-ralenti', 'Apagá el motor si vas a esperar más de un minuto', {
    dom, e: 'easy', i: 'low', min: 1, req: ['auto'], edad: 'a', rut: true,
    corto: 'El motor prendido sin moverse contamina el aire de la cuadra sin llevar a nadie a ningún lado.',
    desc: 'Esperando a alguien en la puerta de la escuela, en una carga o estacionado, el motor en marcha quema combustible y llena de humo la vereda. Los autos actuales no gastan más al volver a arrancar.',
    pasos: ['Si vas a estar parado más de un minuto, apagá el motor.', 'En la puerta de la escuela, nunca lo dejes en marcha.'],
    ef: { c: 0.1 }, fuente: 'oms-aire-exterior', tags: ['auto', 'aire'], hereda: ['aire-no-ralenti'],
  }),
  d('mov-compartir-auto', 'Compartí el viaje con alguien que va para el mismo lado', {
    dom, e: 'medium', i: 'high', min: 5, req: ['auto'], edad: 'ta',
    corto: 'Dos personas en un auto es media huella para cada una.',
    desc: 'Si vas al trabajo, a la facu, al club o a un cumpleaños en auto, ofrecé lugar a alguien que va al mismo lado (o pedíselo vos). Es un auto menos en la calle y un viaje más barato para los dos.',
    pasos: ['Pensá quién hace un trayecto parecido al tuyo hoy.', 'Ofrecé llevar o pedí que te lleven.', 'Repartan la nafta y el estacionamiento.'],
    ef: km(5), tags: ['auto', 'compartir'],
  }),
  d('mov-videollamada', 'Resolvé por videollamada algo que te obligaba a viajar', {
    dom, e: 'easy', i: 'high', min: 2, edad: 'ta',
    corto: 'La reunión que no necesita presencia no necesita traslado.',
    desc: 'Una reunión, una consulta o un trámite que se puede hacer por videollamada o por internet ahorra el viaje completo de ida y vuelta, y el tiempo. Guardá la presencia para lo que la necesita de verdad.',
    pasos: ['Revisá tu agenda de hoy.', 'Proponé hacer por videollamada o en línea algo que ibas a resolver viajando.'],
    ef: km(10), tags: ['trabajo', 'digital'],
  }),
  d('mov-lleva-a-los-chicos-caminando', 'Llevá a los chicos a la escuela caminando o en bici', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['chicos'], dias: 'habil', edad: 'a', lugar: 'calle',
    corto: 'La puerta de las escuelas es donde más autos se juntan sin necesidad.',
    desc: 'Si la escuela está a menos de quince cuadras, ir caminando o en bici es un rato juntos, un auto menos en la puerta y chicos que llegan despiertos. Se puede armar una "ronda" con otras familias del barrio.',
    pasos: ['Calculá el tiempo y salí unos minutos antes.', 'Elegí el camino más tranquilo.', 'Si se puede, sumá a otros chicos del barrio.'],
    ef: km(1.5), tags: ['escuela', 'caminar', 'chicos'],
  }),
  d('mov-escuela-a-pie', 'Andá a la escuela caminando o en bici', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['estudio'], dias: 'habil', edad: 'kt', adulto: true, lugar: 'calle',
    corto: 'Si es cerca, llegás despierto y con los amigos del camino.',
    desc: 'Ir a la escuela o al colegio caminando o en bici (con un adulto o en grupo, si sos chico) evita un viaje en auto y te suma movimiento antes de clase. Si vivís lejos, una parte del camino también cuenta.',
    pasos: ['Pedí permiso y armá el recorrido con un adulto.', 'Andá caminando o en bici, mejor en grupo.'],
    ef: km(1), tags: ['escuela', 'caminar', 'chicos'],
  }),
  d('mov-mochila-en-vez-de-delivery', 'Buscá el pedido caminando en vez de pedir delivery', {
    dom, e: 'easy', i: 'low', min: 15, edad: 'ta', lugar: 'calle',
    corto: 'Un viaje de moto menos por cada pedido, y te ahorrás el envío.',
    desc: 'Si el local está cerca, ir a buscar la comida o el pedido caminando o en bici evita un viaje de moto ida y vuelta (y muchas veces sale más barato y llega más caliente).',
    pasos: ['Hacé el pedido "para retirar".', 'Andá a buscarlo caminando o en bici.'],
    ef: { c: 0.1 }, tags: ['delivery', 'caminar'],
  }),
  d('mov-ruta-sin-embotellamiento', 'Salí fuera del horario pico si podés', {
    dom, e: 'easy', i: 'low', min: 1, req: ['auto'], edad: 'a',
    corto: 'Parado en el tránsito, el motor gasta sin avanzar.',
    desc: 'Mover la salida media hora para esquivar el embotellamiento ahorra combustible, tiempo y bronca. Si tu trabajo lo permite, entrar y salir un poco antes o después del pico cambia mucho.',
    pasos: ['Mirá a qué hora se traba tu recorrido.', 'Si podés, salí media hora antes o después.'],
    ef: { c: 0.3 }, tags: ['auto'],
  }),
  d('mov-dia-sin-auto', 'Dejá el auto en casa todo el día', {
    dom, e: 'medium', i: 'high', min: 5, req: ['auto'], edad: 'a', lugar: 'calle',
    corto: 'Un día entero sin auto muestra cuántos viajes no lo necesitaban.',
    desc: 'Hoy resolvé todo a pie, en bici o en transporte público. Además de lo que no se emite, el día sirve para descubrir qué viajes se pueden hacer siempre sin auto. El 22 de septiembre es el Día Mundial sin Auto.',
    pasos: ['A la mañana, dejá las llaves del auto guardadas.', 'Planificá tus viajes del día en transporte público, bici o a pie.', 'A la noche, pensá cuáles podrías repetir.'],
    ef: km(12), tags: ['auto', 'sin-auto'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('pasa-una-semana-sin-auto', 'Pasá una semana sin auto', {
    dom, e: 'hard', i: 'high', min: 60, formato: 'reto', frec: 'weekly', req: ['auto'], edad: 'a', rango: 'plantula',
    corto: 'Una semana alcanza para descubrir qué viajes no lo necesitaban.',
    desc: 'Siete días resolviendo todo a pie, en bici, en colectivo, tren o compartiendo. Es exigente, pero cambia la forma de mirar la ciudad y casi siempre deja al menos un viaje que ya no volvés a hacer en auto.',
    pasos: ['Planificá la semana: rutas en colectivo, bici o a pie para cada viaje fijo.', 'Dejá el auto guardado los siete días (salvo una emergencia).', 'Al final, anotá qué viajes vas a seguir haciendo sin auto.'],
    ef: km(50), tags: ['auto', 'reto'],
  }),
  c('mov-tren-en-vez-de-avion', 'Para tu próximo viaje largo, elegí micro o tren', {
    dom, e: 'medium', i: 'high', min: 30, formato: 'salida', edad: 'ta', cool: 720,
    corto: 'Por pasajero, el avión emite varias veces más que un micro de larga distancia.',
    desc: 'La Argentina tiene una de las mejores redes de micros de larga distancia de la región, y trenes en varios corredores. Para distancias de hasta 800 km, el micro o el tren emiten una fracción de lo que emite el avión por pasajero, y muchos viajes se hacen de noche.',
    pasos: ['Para tu próximo viaje, compará micro, tren y avión.', 'Si la diferencia de tiempo es razonable, elegí micro o tren.', 'Contá los kilómetros del viaje.'],
    medida: medida('¿De cuántos kilómetros es el viaje? (hasta 300 cuentan)', 'km', 'km', { min: 50, max: 300, def: 200, por: { co2_kg: 0.1 } }),
    fuente: 'owid-aviacion', tags: ['viaje', 'micro', 'tren'], hereda: ['evita-un-vuelo-de-corta-distancia', 'mov-elegi-tren-o-micro', 'hace-el-compromiso-de-un-ano-sin-volar'],
  }),
  c('mov-presion-neumaticos', 'Revisá la presión de los neumáticos', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['auto'], edad: 'a', ahorra: true, cool: 720,
    corto: 'Con las gomas bajas el auto gasta más en cada viaje, y frena peor.',
    desc: 'Los neumáticos con poca presión aumentan el consumo y el desgaste. Revisarlos una vez por mes, en frío, en la estación de servicio o con un medidor propio, lleva cinco minutos.',
    pasos: ['Buscá en la puerta del conductor o el manual la presión recomendada.', 'Medí y cargá aire en frío, en la estación de servicio.', 'Revisá también la rueda de auxilio.'],
    ef: { c: 1 }, tags: ['auto'], hereda: ['mantene-la-presion-de-los-neumaticos'],
  }),
  c('mov-saca-el-peso-de-mas-del-baul', 'Vaciá el baúl de lo que no usás', {
    dom, e: 'easy', i: 'low', min: 10, req: ['auto'], edad: 'a', ahorra: true, cool: 720,
    corto: 'Cada kilo de más se paga en combustible en cada viaje.',
    desc: 'Herramientas, cajas, la silla de playa del verano pasado: todo lo que viaja en el baúl sin necesidad hace que el auto consuma un poco más en cada arranque.',
    pasos: ['Sacá del baúl todo lo que no necesitás llevar siempre.', 'Dejá sólo lo de seguridad: auxilio, criquet, matafuego y balizas.'],
    ef: { c: 0.5 }, tags: ['auto'], hereda: ['mov-sacar-peso-baul'],
  }),
  c('mov-saca-el-portaequipaje', 'Sacá el portaequipaje cuando no lo usás', {
    dom, e: 'easy', i: 'medium', min: 15, req: ['auto'], edad: 'a', ahorra: true, cool: 2160,
    corto: 'Un portaequipaje vacío frena el auto contra el viento en cada viaje.',
    desc: 'Las barras, el portaequipaje o el portabicis del techo aumentan la resistencia al aire, sobre todo en ruta. Si no los vas a usar en un tiempo, sacarlos baja el consumo.',
    pasos: ['Si no vas a usar el portaequipaje en las próximas semanas, desmontalo.', 'Guardalo con sus tornillos en una bolsa.'],
    ef: { c: 1 }, tags: ['auto'],
  }),
  c('mov-mantene-la-bici', 'Poné a punto la bici', {
    dom, e: 'easy', i: 'medium', min: 30, req: ['bici'], edad: 'kta', adulto: true, cool: 720,
    corto: 'Una bici desinflada en el fondo del garaje no reemplaza ningún viaje.',
    desc: 'Las gomas bien infladas, la cadena aceitada y los frenos firmes hacen que andar sea fácil y seguro. Una bici lista es una bici que se usa en vez del auto o el colectivo.',
    pasos: ['Inflá las cubiertas a la presión que dice el costado.', 'Limpiá y aceitá la cadena.', 'Probá los frenos y ajustalos si hace falta.'],
    ef: nada(), tags: ['bici'], hereda: ['mov-mantener-bici'],
  }),
  c('mov-taller-de-bici', 'Aprendé a parchar una cámara', {
    dom, e: 'medium', i: 'medium', min: 40, formato: 'aprender', frec: 'one_time', req: ['bici'], edad: 'kta', adulto: true,
    corto: 'La pinchadura es la excusa número uno para dejar la bici.',
    desc: 'Con un kit de parches, dos palancas y un inflador, cualquiera arregla una pinchadura en quince minutos. Saber hacerlo te da la confianza de usar la bici para todo.',
    pasos: ['Mirá un tutorial de cómo parchar una cámara.', 'Practicá en casa con una cámara vieja o la de tu bici.', 'Armá un kit chico para llevar siempre.'],
    ef: nada(), tags: ['bici', 'arreglo'],
  }),
  c('mov-ensenar-ruta-segura', 'Armá tu ruta segura en bici', {
    dom, e: 'easy', i: 'medium', min: 20, formato: 'aprender', frec: 'one_time', req: ['bici'], edad: 'ta',
    corto: 'Mucha gente no usa la bici porque no sabe por dónde ir tranquila.',
    desc: 'Buscá el mapa de bicisendas y ciclovías de tu ciudad (o calles de poco tránsito) y armá el recorrido de un viaje que hacés seguido. Probarlo un fin de semana, sin apuro, da confianza para hacerlo un día de semana.',
    pasos: ['Buscá el mapa de ciclovías de tu ciudad o usá un mapa con la opción bici.', 'Armá el recorrido a un lugar al que vas seguido.', 'Probalo un fin de semana.'],
    ef: nada(), tags: ['bici'],
  }),
  c('mov-ensenar-a-andar-en-bici', 'Enseñale a alguien a andar en bici', {
    dom, e: 'medium', i: 'high', min: 60, formato: 'social', edad: 'ta', cool: 720,
    corto: 'Una persona más que puede elegir la bici.',
    desc: 'Mucha gente adulta no sabe andar en bici o le tiene miedo a la calle. Acompañar a alguien en una plaza o una calle tranquila hasta que se anime es abrirle una forma de moverse para siempre.',
    pasos: ['Elegí un lugar plano y sin autos.', 'Bajá el asiento para que apoye los pies y empiecen sin pedales, empujando.', 'Cuando se equilibre, sumen los pedales.'],
    ef: nada(), tags: ['bici', 'compartir'],
  }),
  c('sumate-a-un-esquema-de-bicis-compartidas', 'Probá la bici pública de tu ciudad', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'salida', frec: 'one_time', edad: 'ta', lugar: 'calle',
    corto: 'Si tu ciudad tiene bicis públicas, resolvés viajes sin tener que guardar una bici.',
    desc: 'Buenos Aires, Rosario, Córdoba, Mendoza y otras ciudades tienen sistemas de bicis públicas. Registrarte y hacer un primer viaje corto es la forma de sumarla a tus opciones para los trayectos de todos los días.',
    pasos: ['Averiguá si tu ciudad tiene bicis públicas y cómo registrarte.', 'Hacé un viaje corto para probar.', 'Fijate qué estaciones te quedan cerca de casa y del trabajo o la escuela.'],
    ef: km(2), tags: ['bici'],
  }),
  c('organiza-un-grupo-de-auto-compartido', 'Armá un grupo para compartir el auto', {
    dom, e: 'medium', i: 'high', min: 30, formato: 'social', req: ['auto'], edad: 'a', cool: 720,
    corto: 'Cuatro autos con una persona cada uno pueden ser uno solo.',
    desc: 'Con compañeros de trabajo, padres de la escuela o vecinos que hacen el mismo recorrido, un grupo de auto compartido con turnos fijos baja a la mitad (o menos) los viajes, el gasto y el estacionamiento.',
    pasos: ['Buscá dos o tres personas con un recorrido parecido.', 'Armen los turnos y los puntos de encuentro.', 'Hagan un grupo de mensajes para avisar cambios.'],
    ef: km(20), tags: ['auto', 'compartir'], hereda: ['coordina-auto-compartido-en-el-trabajo-o-escuela'],
  }),
  c('trabaja-desde-casa-y-reduci-dias-de-viaje', 'Proponé un día de trabajo desde casa', {
    dom, e: 'medium', i: 'high', min: 30, formato: 'social', frec: 'one_time', req: ['trabajo'], edad: 'a',
    corto: 'Un día menos de viaje por semana es un 20% menos de traslados.',
    desc: 'Si tu trabajo se puede hacer a distancia aunque sea en parte, proponer un día fijo desde casa ahorra el viaje de ida y vuelta cada semana, y tiempo de vida.',
    pasos: ['Pensá qué tareas se pueden hacer bien desde casa.', 'Proponé un día fijo por semana, con un plan concreto.'],
    ef: km(20), tags: ['trabajo'],
  }),
  c('mov-aprende-la-ruta-en-colectivo', 'Averiguá cómo hacer en colectivo un viaje que hacés en auto', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'aprender', frec: 'one_time', req: ['auto'], edad: 'a',
    corto: 'Muchas veces no se usa el colectivo sólo porque no se sabe cuál tomar.',
    desc: 'Elegí un viaje fijo (al trabajo, a lo de tu familia, al centro) y averiguá cómo se hace en transporte público: qué línea, dónde se toma, cuánto tarda. Con la información a mano, es mucho más fácil dejar el auto un día.',
    pasos: ['Elegí un viaje que hacés seguido en auto.', 'Buscá el recorrido en transporte público con un mapa o una app.', 'Guardalo para probarlo esta semana.'],
    ef: nada(), fuente: 'red-sube', tags: ['colectivo', 'auto'],
  }),
  c('mov-semana-a-pie-o-bici', 'Una semana yendo a pie o en bici a todo lo cercano', {
    dom, e: 'medium', i: 'high', min: 60, formato: 'reto', frec: 'weekly', edad: 'kta',
    corto: 'Todo lo que está a menos de 15 cuadras, durante siete días, sin motor.',
    desc: 'Un reto de una semana: cada viaje corto (almacén, escuela, plaza, amigos, trámites cercanos) se hace caminando o en bici. Al final, la mayoría descubre que no necesitaba el auto ni el colectivo para eso.',
    pasos: ['Definí tu radio: todo lo que está a menos de 15 cuadras.', 'Durante siete días, esos viajes se hacen a pie o en bici.', 'Contá cuántos fueron.'],
    ef: km(10), tags: ['caminar', 'bici', 'reto'],
  }),
];
