// Plantas y verde urbano — macetas, huerta, árboles nativos, semillas.
import { d, c, agua, organico, nada } from '../dsl.mjs';

const dom = 'plantas';
const plantar = ['otono', 'invierno', 'primavera'];

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('pla-regar-segun-dedo', 'Tocá la tierra antes de regar', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'El exceso de agua mata más plantas que la falta.',
    desc: 'Regar "porque toca" pudre raíces y tira agua. Meté un dedo en la tierra: si a dos centímetros está húmeda, esa planta no necesita agua hoy.',
    pasos: ['Meté el dedo en la tierra de cada maceta.', 'Si está seca a dos centímetros, regá al pie.', 'Si está húmeda, esperá.'],
    ef: agua(2), tags: ['riego', 'chicos'],
  }),
  d('pla-no-pisar-cantero', 'Cuidá los canteros y el pasto nuevo de la plaza', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'naturaleza',
    corto: 'El suelo pisado se compacta y no deja crecer nada.',
    desc: 'Cortar camino por un cantero o el pasto recién sembrado de una plaza compacta la tierra y mata los brotes. Ir por el camino (y avisar con buena onda a otros chicos) ayuda a que el verde del barrio crezca.',
    pasos: ['En la plaza, caminá por los senderos.', 'No pises canteros ni pasto recién sembrado.'],
    ef: nada(), tags: ['plaza', 'chicos'],
  }),
  d('pla-huerta-cosecha', 'Cosechá algo de tu huerta para comer hoy', {
    dom, e: 'easy', i: 'low', min: 5, req: ['huerta'], rut: true,
    corto: 'Lo que crece en casa no viaja, no viene envasado y está en su punto.',
    desc: 'Unas hojas de lechuga, perejil, albahaca o un tomate de tu huerta son comida sin kilómetros ni envases. Cosechar seguido, además, hace que muchas plantas produzcan más.',
    pasos: ['Mirá qué está listo en la huerta.', 'Cortá sólo lo que vas a comer hoy, sin arrancar la planta.', 'Sumalo a una comida.'],
    tags: ['huerta', 'cocina'],
  }),
  d('plant-rega-el-arbol-de-la-vereda', 'Regá el árbol de tu vereda', {
    dom, e: 'easy', i: 'medium', min: 5, est: ['primavera', 'verano'], lugar: 'calle', adulto: true, rut: true,
    corto: 'Los primeros veranos definen si un árbol joven sobrevive.',
    desc: 'Los árboles de la vereda dan sombra a toda la cuadra y casi nadie los riega. En verano, un balde (mejor con el agua fría de la ducha o la de lluvia) al atardecer, sobre todo en los recién plantados, puede salvarlos.',
    pasos: ['Al atardecer, llevá un balde de agua al árbol de tu vereda.', 'Volcalo despacio al pie, para que la tierra lo absorba.', 'Si la tierra está dura, aflojala un poco con una pala de mano.'],
    ef: nada(), tags: ['arbol', 'verano', 'barrio'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('planta-un-arbol-nativo', 'Plantá un árbol nativo', {
    dom, e: 'medium', i: 'high', min: 60, req: ['jardin'], est: plantar, edad: 'kta', adulto: true, cool: 4320,
    corto: 'Un árbol nativo sostiene mucha más vida que uno exótico, y está hecho para tu clima.',
    desc: 'Lapacho, jacarandá, tipa, ceibo, algarrobo, chañar, molle, timbó: cada región tiene sus árboles. Uno nativo da sombra, refugio y alimento a aves e insectos que evolucionaron con él, y pide menos riego. El mejor momento para plantar es de otoño a principios de primavera.',
    pasos: ['Averiguá qué árboles nativos son de tu ecorregión (y cuánto crecen).', 'Hacé un pozo del doble del pan de tierra y plantalo con compost.', 'Regalo seguido el primer año, sobre todo en verano.'],
    fuente: 'plantas-nativas', tags: ['arbol', 'nativas'],
    mercado: ['jardin-y-huerta', 'semillas-y-plantines', 'Viveros con árboles nativos de tu zona. Estos negocios están en el programa de Brote.'],
  }),
  c('sumate-a-una-jornada-de-plantacion-de-arboles', 'Sumate a una plantación de árboles', {
    dom, e: 'medium', i: 'high', min: 120, formato: 'salida', est: plantar, edad: 'kta', adulto: true, lugar: 'naturaleza', cool: 720,
    corto: 'Plantar en grupo cubre en un día lo que en soledad llevaría meses.',
    desc: 'Municipios, escuelas, ONG y grupos de vecinos organizan plantaciones en plazas, costas y reservas, sobre todo alrededor del Día del Árbol (29 de agosto). Sumarte es plantar y además conocer a quienes cuidan el verde de tu zona.',
    pasos: ['Buscá plantaciones en tu municipio, escuela u organizaciones ambientales.', 'Anotate y llevá guantes, agua y gorra.', 'Volvé en unos meses a ver cómo crecen.'],
    tags: ['arbol', 'grupo'],
  }),
  c('pla-adopta-arbol-vereda', 'Adoptá el árbol de tu vereda', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'tarea', edad: 'kta', adulto: true, lugar: 'calle', cool: 2160,
    corto: 'Un árbol con alguien a cargo vive más y mejor.',
    desc: 'Adoptar el árbol de tu vereda es hacerte cargo de lo básico: que tenga su cuadrado de tierra libre (sin cemento ni basura), un poco de mantillo, riego en verano y avisar al municipio si está enfermo o mal podado.',
    pasos: ['Limpiá la casilla del árbol: sacá basura y aflojá la tierra.', 'Poné hojas secas encima para guardar humedad.', 'Si ves ramas secas o heridas, avisá al municipio.'],
    ef: nada(), tags: ['arbol', 'barrio', 'chicos'],
  }),
  c('empeza-una-huerta-en-el-balcon-o-ventana', 'Armá una huerta en macetas', {
    dom, e: 'easy', i: 'medium', min: 45, frec: 'one_time', edad: 'kta', adulto: true, otorga: 'huerta',
    corto: 'No hace falta jardín: un cajón al sol ya produce comida.',
    desc: 'Lechuga, rúcula, acelga, perejil o tomates cherry crecen en macetas o cajones en un balcón o una ventana con sol. El ProHuerta del INTA recomienda empezar con pocas especies de la estación y sumar de a poco.',
    pasos: ['Conseguí macetas o cajones con agujeros abajo y tierra con compost.', 'Elegí dos o tres especies de la estación y sembralas o plantá plantines.', 'Ponelas donde les dé al menos 5 horas de sol.'],
    ef: nada(), fuente: 'prohuerta', tags: ['huerta'],
    mercado: ['jardin-y-huerta', 'semillas-y-plantines', 'Semillas, tierra y macetas para empezar. Estos negocios están en el programa de Brote.'],
  }),
  c('pla-semillas-prohuerta', 'Conseguí semillas del ProHuerta en tu municipio', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'salida', est: ['otono', 'primavera'], edad: 'ta', cool: 2160,
    corto: 'El INTA reparte kits de semillas por temporada para huertas familiares.',
    desc: 'El ProHuerta del INTA distribuye semillas en dos campañas: otoño-invierno y primavera-verano, a través de municipios, escuelas y organizaciones. Hay kits para macetas, para patios y para quintas más grandes.',
    pasos: ['Preguntá en tu municipio, la agencia del INTA más cercana o una escuela si reparten semillas del ProHuerta.', 'Pedí el kit que corresponde a tu espacio.', 'Sembrá siguiendo el calendario de la temporada.'],
    ef: nada(), fuente: 'prohuerta', tags: ['huerta', 'semillas'],
  }),
  c('cultiva-tus-propias-verduras-o-hierbas', 'Sembrá algo de estación en tu huerta', {
    dom, e: 'easy', i: 'medium', min: 30, req: ['huerta'], edad: 'kta', cool: 336,
    corto: 'En otoño, hojas y habas; en primavera, tomates y zapallos.',
    desc: 'Cada estación tiene lo suyo: en otoño-invierno, acelga, lechuga, espinaca, arvejas y habas; en primavera-verano, tomate, zapallo, choclo, albahaca. Sembrar de a poco cada dos o tres semanas te da cosecha continua.',
    pasos: ['Fijate qué se siembra este mes en tu región.', 'Sembrá una tanda chica.', 'Anotá la fecha para sembrar la siguiente en dos o tres semanas.'],
    fuente: 'prohuerta', tags: ['huerta', 'estacion', 'semillas'],
    mercado: ['jardin-y-huerta', 'semillas-y-plantines', 'Semillas y plantines de estación. Estos negocios están en el programa de Brote.'],
  }),
  c('ali-huerta-aromaticas', 'Plantá aromáticas en una maceta', {
    dom, e: 'easy', i: 'low', min: 20, frec: 'one_time', edad: 'kta', otorga: 'huerta',
    corto: 'Perejil, albahaca y orégano a mano: sabor sin envase ni atado que se pudre.',
    desc: 'Las hierbas compradas vienen en atados o en plástico y se echan a perder en días. En una maceta junto a la ventana de la cocina, cortás lo que necesitás y la planta sigue creciendo.',
    pasos: ['Conseguí una maceta con agujeros y tierra buena.', 'Plantá perejil, albahaca, orégano, menta o romero (mejor de plantín).', 'Ponela al sol y cortá desde arriba para que se ramifique.'],
    ef: nada(), tags: ['huerta', 'cocina', 'chicos'], hereda: ['cultiva-hierbas-para-reemplazar-las-envasadas'],
    mercado: ['jardin-y-huerta', 'semillas-y-plantines', 'Plantines de aromáticas y macetas. Estos negocios están en el programa de Brote.'],
  }),
  c('pla-germinar-poroto', 'Germiná un poroto en un algodón', {
    dom, e: 'easy', i: 'low', min: 10, formato: 'observar', edad: 'k', cool: 720,
    corto: 'El experimento de la escuela de siempre: en una semana ves nacer una planta.',
    desc: 'Un poroto, un frasco y un algodón húmedo alcanzan para ver cómo sale la raíz, después el tallo y las primeras hojas. Anotá o dibujá cada día lo que cambia. Cuando tenga hojas, pasalo a una maceta.',
    pasos: ['Poné algodón húmedo en un frasco y un poroto contra el vidrio.', 'Dejalo cerca de la luz y mantené el algodón húmedo.', 'Dibujá cada día lo que ves y, cuando tenga hojas, plantalo en tierra.'],
    ef: nada(), tags: ['semillas', 'experimento', 'chicos', 'escuela'],
  }),
  c('pla-semillas-de-lo-que-comes', 'Hacé brotar la semilla de algo que comiste', {
    dom, e: 'easy', i: 'low', min: 10, formato: 'observar', edad: 'kta', cool: 720,
    corto: 'Un carozo de palta, una semilla de zapallo o de tomate traen una planta adentro.',
    desc: 'Las semillas de lo que comés pueden germinar: la palta con escarbadientes en un vaso de agua, las de zapallo o tomate en tierra húmeda. Es una forma gratis y entretenida de empezar a cultivar.',
    pasos: ['Lavá y secá las semillas de una fruta o verdura.', 'Ponelas en tierra húmeda (o la palta con escarbadientes en un vaso de agua).', 'Esperá y mirá cuál brota primero.'],
    ef: nada(), tags: ['semillas', 'experimento', 'chicos'],
  }),
  c('plant-multiplica-por-esqueje', 'Hacé un esqueje y regalá una planta', {
    dom, e: 'easy', i: 'medium', min: 15, edad: 'kta', cool: 336,
    corto: 'Un gajo es una planta nueva sin comprar nada.',
    desc: 'Muchas plantas (potus, malvón, romero, suculentas, sauce) se multiplican cortando un gajo y poniéndolo en agua o en tierra húmeda. En pocas semanas tiene raíces y es un regalo vivo.',
    pasos: ['Cortá un gajo de 10 a 15 cm debajo de un nudo.', 'Sacale las hojas de abajo y ponelo en agua o en tierra húmeda.', 'Cuando tenga raíces, plantalo y regalalo.'],
    ef: nada(), tags: ['esqueje', 'regalos', 'chicos'], hereda: ['pla-esqueje'],
  }),
  c('plant-guarda-semillas', 'Guardá semillas de lo que cosechaste', {
    dom, e: 'easy', i: 'medium', min: 20, req: ['huerta'], edad: 'kta', cool: 2160,
    corto: 'Guardar semillas mantiene variedades que el mercado ya no vende.',
    desc: 'De un tomate bien maduro, un zapallo o una lechuga que espigó salen semillas para la próxima temporada. Secas y guardadas en sobres de papel con el nombre y la fecha, duran años.',
    pasos: ['Elegí la planta más sana y dejá madurar bien un fruto.', 'Sacá las semillas, lavalas si hace falta y secalas a la sombra.', 'Guardalas en un sobre de papel con el nombre y la fecha.'],
    ef: nada(), tags: ['semillas', 'huerta'],
  }),
  c('plant-intercambia-semillas-o-gajos', 'Intercambiá semillas o gajos', {
    dom, e: 'easy', i: 'medium', min: 30, formato: 'social', edad: 'kta', cool: 720,
    corto: 'Un intercambio multiplica variedades sin que nadie compre nada.',
    desc: 'Las casas de semillas, las ferias de intercambio y los grupos de huerteros del barrio intercambian semillas y gajos. Es la forma de conseguir variedades locales y de conocer a quienes cultivan cerca.',
    pasos: ['Juntá semillas o gajos que te sobren.', 'Buscá una feria de intercambio, una casa de semillas o un grupo de huerta.', 'Llevá lo tuyo y traé algo nuevo para probar.'],
    ef: nada(), fuente: 'prohuerta', tags: ['semillas', 'esqueje', 'barrio'],
  }),
  c('planta-flores-nativas-para-polinizadores', 'Plantá flores nativas para abejas y mariposas', {
    dom, e: 'easy', i: 'high', min: 30, req: ['balcon'], est: ['otono', 'primavera'], edad: 'kta', cool: 2160,
    corto: 'Los polinizadores nativos prefieren las flores con las que evolucionaron.',
    desc: 'Verbenas, salvias, pasionarias, margaritas y otras nativas atraen abejas, mariposas y picaflores. Según la IPBES, la pérdida de flores es una de las causas del declive de los polinizadores, de los que depende buena parte de lo que comemos.',
    pasos: ['Averiguá qué flores nativas crecen en tu región.', 'Plantá varias en macetas o canteros al sol.', 'No uses insecticidas cerca.'],
    ef: nada(), fuente: 'ipbes-polinizadores', tags: ['polinizadores', 'nativas', 'flores'], hereda: ['ani-plantas-para-polinizadores'],
    mercado: ['jardin-y-huerta', 'semillas-y-plantines', 'Plantines y semillas de nativas para abejas y mariposas. Estos negocios están en el programa de Brote.'],
  }),
  c('pla-nativa-en-vez-de-exotica', 'Elegí una planta nativa para tu próxima maceta', {
    dom, e: 'easy', i: 'medium', min: 20, formato: 'salida', edad: 'kta', cool: 720,
    corto: 'Las nativas necesitan menos agua y alimentan a la fauna de tu zona.',
    desc: 'En lugar de una ornamental importada, elegí una especie nativa de tu ecorregión: está adaptada al clima, pide menos riego y sostiene insectos y aves locales. Muchos viveros ya tienen sección de nativas.',
    pasos: ['Buscá qué plantas son nativas de tu región.', 'En el vivero, preguntá por esas.', 'Plantala en una maceta o cantero al sol.'],
    ef: agua(20), fuente: 'plantas-nativas', tags: ['nativas'], hereda: ['elegi-plantas-nativas-resistentes-a-la-sequia'],
    mercado: ['jardin-y-huerta', 'semillas-y-plantines', 'Viveros que crían nativas de tu región. Estos negocios están en el programa de Brote.'],
  }),
  c('cubri-los-canteros-con-mantillo', 'Cubrí la tierra con hojas secas', {
    dom, e: 'easy', i: 'medium', min: 15, edad: 'kta', cool: 720,
    corto: 'Una capa de hojas o pasto seco guarda la humedad y frena los yuyos.',
    desc: 'El mantillo es una capa de hojas secas, pasto cortado o corteza sobre la tierra de macetas y canteros. Evita que el sol seque la tierra, así regás menos, y al descomponerse la alimenta.',
    pasos: ['Juntá hojas secas o pasto cortado.', 'Poné una capa de unos 5 cm sobre la tierra, sin tocar los tallos.', 'Reponela cuando se deshaga.'],
    ef: agua(30), tags: ['suelo', 'riego', 'chicos'], hereda: ['agua-mulch-macetas'],
  }),
  c('pla-abono-casero', 'Abonate las plantas con lo de la cocina', {
    dom, e: 'easy', i: 'low', min: 10, edad: 'kta', cool: 336,
    corto: 'Cáscaras de huevo, yerba y borra de café: abono gratis.',
    desc: 'La yerba usada, la borra de café y la cáscara de huevo molida aportan nutrientes a las macetas. Mezcladas con la tierra de arriba, alimentan la planta sin comprar fertilizantes.',
    pasos: ['Secá y molé cáscaras de huevo.', 'Mezclalas con yerba usada o borra de café.', 'Esparcí un puñado sobre la tierra de cada maceta y mezclalo un poco.'],
    ef: organico(0.2), tags: ['suelo', 'mate', 'chicos'],
  }),
  c('plant-prepara-te-de-compost', 'Prepará té de compost para tus plantas', {
    dom, e: 'easy', i: 'low', min: 15, req: ['compost'], edad: 'ta', cool: 336,
    corto: 'Un puñado de compost en agua es un fertilizante líquido sin químicos.',
    desc: 'Poner compost maduro en un balde con agua durante uno o dos días da un líquido marrón lleno de nutrientes y vida. Diluido, se riega al pie de las plantas.',
    pasos: ['Poné dos puñados de compost maduro en un balde con agua.', 'Dejalo uno o dos días, revolviendo de vez en cuando.', 'Colalo, diluilo mitad y mitad con agua y regá al pie.'],
    ef: nada(), tags: ['compost', 'suelo'],
  }),
  c('pla-rescatar-planta', 'Rescatá una planta que está por morirse', {
    dom, e: 'medium', i: 'low', min: 30, edad: 'kta', cool: 720,
    corto: 'Casi siempre se recupera con agua justa, una maceta mejor y luz.',
    desc: 'Una planta mustia muchas veces está ahogada, sin drenaje o en el lugar equivocado. Cambiarla de maceta, cortar lo seco y moverla a la luz que necesita la salva más seguido de lo que parece.',
    pasos: ['Sacá la planta y mirá las raíces: si están negras y blandas, cortalas.', 'Pasala a una maceta con agujeros y tierra nueva.', 'Cortá hojas secas y ponela donde tenga la luz que le gusta.'],
    ef: nada(), tags: ['chicos'],
  }),
  c('plant-elegi-macetas-de-material-recuperado', 'Plantá en envases recuperados', {
    dom, e: 'easy', i: 'low', min: 20, edad: 'kta', cool: 720,
    corto: 'Una lata, un bidón cortado o un cajón de verdulería son macetas gratis.',
    desc: 'Latas grandes, bidones, cajones de fruta o botellas cortadas, con agujeros abajo, sirven de macetas. Es plástico y metal que tiene una segunda vida en lugar de ir a la basura.',
    pasos: ['Elegí un envase grande y limpio.', 'Hacele agujeros en la base para que drene.', 'Llenalo de tierra y plantá algo.'],
    ef: { r: 0.1 }, tags: ['reuso', 'chicos'],
  }),
  c('pla-sombra-para-la-casa', 'Plantá una enredadera o un árbol que dé sombra a la casa', {
    dom, e: 'medium', i: 'medium', min: 45, req: ['balcon'], est: ['otono', 'primavera'], edad: 'ta', cool: 4320,
    corto: 'Una pared o una ventana con sombra vegetal baja varios grados adentro en verano.',
    desc: 'Una enredadera de hoja caduca en la pared del oeste o un árbol frente a la ventana más asoleada dan sombra en verano y dejan pasar el sol en invierno. Menos aire acondicionado, más fresco y más pájaros.',
    pasos: ['Identificá la pared o ventana que más sol recibe en verano (norte u oeste).', 'Plantá una enredadera de hoja caduca o un árbol que no crezca demasiado.', 'Guiá las ramas y regá el primer verano.'],
    ef: nada(), fuente: 'epa-isla-calor', tags: ['sombra', 'calor'], hereda: ['planta-para-dar-sombra-y-enfriar-la-ciudad'],
  }),
  c('plant-poda-en-el-momento-correcto', 'Podá en invierno, no en primavera', {
    dom, e: 'medium', i: 'medium', min: 60, req: ['jardin'], est: ['invierno'], edad: 'a', cool: 4320,
    corto: 'Una poda a destiempo debilita el árbol y destruye nidos.',
    desc: 'Los árboles y arbustos que pierden las hojas se podan a fines del invierno, antes de brotar. En primavera y verano la poda los debilita y es justo cuando las aves anidan. Una poda liviana alcanza: nunca "desmoches" un árbol.',
    pasos: ['Planeá la poda para fines del invierno.', 'Sacá sólo ramas secas, enfermas o que estorben.', 'Usá tijeras afiladas y cortá limpio, cerca del tronco o de una yema.'],
    ef: nada(), tags: ['arbol', 'poda', 'invierno'],
  }),
  c('deja-un-sector-sin-cortar-para-la-biodiversidad', 'Dejá un rincón del jardín sin cortar', {
    dom, e: 'easy', i: 'medium', min: 10, req: ['jardin'], edad: 'kta', frec: 'one_time',
    corto: 'El pasto alto es refugio y alimento para insectos y aves.',
    desc: 'Un rincón donde no pasa la cortadora se llena de flores silvestres, insectos y semillas que comen las aves. Es biodiversidad en tu casa sin hacer nada, y menos trabajo de jardín.',
    pasos: ['Elegí un rincón de uno o dos metros.', 'Dejá de cortarlo esta temporada.', 'Mirá qué aparece: flores, mariposas, aves.'],
    ef: nada(), tags: ['biodiversidad', 'jardin'], hereda: ['ani-dejar-rincon-silvestre'],
  }),
  c('converti-parte-del-cesped-en-plantas-nativas', 'Convertí parte del césped en un cantero de nativas', {
    dom, e: 'hard', i: 'high', min: 180, req: ['jardin'], est: ['otono', 'primavera'], edad: 'a', rango: 'plantula', frec: 'one_time',
    corto: 'El césped pide agua y corte y casi no alimenta a la fauna.',
    desc: 'Reemplazar unos metros de césped por un cantero de pastos, arbustos y flores nativas baja el riego, deja de necesitar cortadora y atrae polinizadores y aves. Es de las cosas con más impacto que se pueden hacer en un jardín.',
    pasos: ['Marcá el sector y sacá el césped (o tapalo con cartón unas semanas).', 'Agregá compost y plantá nativas de tu ecorregión.', 'Cubrí con mantillo y regá el primer año.'],
    ef: agua(200), fuente: 'plantas-nativas', tags: ['nativas', 'jardin', 'biodiversidad'],
  }),
  c('sumate-a-una-huerta-comunitaria', 'Sumate a una huerta comunitaria', {
    dom, e: 'medium', i: 'medium', min: 120, formato: 'social', edad: 'kta', adulto: true, lugar: 'naturaleza', cool: 336,
    corto: 'Una huerta comunitaria produce comida y vecinos a la vez.',
    desc: 'En muchas ciudades hay huertas en plazas, escuelas, centros comunitarios o terrenos recuperados. Sumarse una mañana es aprender a cultivar con otros y llevarte parte de la cosecha.',
    pasos: ['Buscá huertas comunitarias en tu municipio o en organizaciones del barrio.', 'Andá a una jornada de trabajo.', 'Llevá guantes y ganas de aprender.'],
    ef: nada(), fuente: 'prohuerta', tags: ['huerta', 'grupo', 'barrio'],
  }),
  c('hace-bombas-de-semillas-para-espacios-descuidado', 'Hacé bombas de semillas nativas', {
    dom, e: 'easy', i: 'medium', min: 30, est: ['otono', 'primavera'], edad: 'kta', adulto: true, cool: 720,
    corto: 'Bolitas de arcilla y semillas que florecen donde no había nada.',
    desc: 'Mezclando arcilla, compost y semillas de flores nativas se hacen bolitas que se tiran en baldíos, terraplenes o rincones descuidados. Con la lluvia germinan. Usá sólo semillas nativas y en lugares donde esté permitido.',
    pasos: ['Mezclá 5 partes de arcilla, 3 de compost y 1 de semillas nativas con un poco de agua.', 'Hacé bolitas del tamaño de una nuez y dejalas secar.', 'Tiralas en lugares descuidados antes de una lluvia.'],
    ef: nada(), tags: ['semillas', 'nativas', 'chicos'],
  }),
  c('air-plantas-de-interior', 'Sumá una planta de interior', {
    dom, e: 'easy', i: 'low', min: 15, edad: 'kta', cool: 2160,
    corto: 'Una planta adentro mejora el ánimo y te conecta con lo vivo todos los días.',
    desc: 'Potus, sansevierias, helechos o una suculenta en la ventana: una planta de interior es fácil de cuidar y es una forma de empezar si nunca tuviste plantas. Mejor de esqueje o regalada que comprada.',
    pasos: ['Pedí un gajo de potus o de alguna planta fácil, o elegí una en un vivero.', 'Ponela cerca de una ventana con luz indirecta.', 'Regala sólo cuando la tierra esté seca.'],
    ef: nada(), tags: ['interior', 'chicos'], hereda: ['aire-plantas-de-interior'],
  }),
  c('pla-planta-en-la-escuela', 'Plantá algo en la escuela con tu curso', {
    dom, e: 'medium', i: 'medium', min: 60, formato: 'social', req: ['estudio'], est: plantar, edad: 'kt', lugar: 'escuela', cool: 2160,
    corto: 'Un árbol o una huerta en el patio crece con todo el curso.',
    desc: 'Proponele a tu docente plantar un árbol nativo, armar una huerta en cajones o un cantero de flores para polinizadores en la escuela. Muchas escuelas reciben semillas y plantines del ProHuerta o del municipio.',
    pasos: ['Proponelo en clase con una idea concreta (árbol, huerta o cantero).', 'Pidan semillas o plantines al municipio o al ProHuerta.', 'Armen turnos para regar.'],
    ef: nada(), fuente: 'prohuerta', tags: ['escuela', 'huerta', 'arbol', 'chicos'],
  }),
];
