// Residuos — separar bien, generar menos y que lo que se puede usar vuelva al circuito.
import { d, c, plastico, reciclable, organico, suma, nada } from '../dsl.mjs';

const dom = 'residuos';

export default [
  // ── Del día ────────────────────────────────────────────────────────────────
  d('separa-bien-tus-residuos-hoy', 'Separá los reciclables de la basura', {
    dom, e: 'easy', i: 'medium', min: 3, rut: true,
    corto: 'Papel, cartón, plástico, vidrio y latas limpios y secos valen; mezclados con restos de comida, se pierden.',
    desc: 'Cerca de un tercio de lo que tira una casa argentina es papel, cartón, plástico, vidrio o metal. Separado limpio y seco, eso vuelve a la industria y le da trabajo a recuperadores y cooperativas; mezclado con restos de comida termina enterrado.',
    pasos: ['Tené dos bolsas o tachos: reciclables (secos) y el resto.', 'Poné en reciclables sólo lo limpio y seco.', 'Sacalos el día y el horario que corresponde en tu barrio, o entregalos a un recuperador.'],
    ef: reciclable(0.3), fuente: 'faccyr', tags: ['reciclaje', 'separar', 'chicos'],
  }),
  d('res-enjuagar-reciclables', 'Enjuagá los envases antes de separarlos', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Un envase con restos ensucia el papel y el cartón de toda la bolsa.',
    desc: 'Un yogur o una lata con restos pueden arruinar todo lo que va en la misma bolsa. No hace falta dejarlo impecable: un enjuague rápido con el agua de lavar los platos alcanza.',
    pasos: ['Pasale un chorrito de agua (mejor la que ya usaste para lavar).', 'Dejalo escurrir y ponelo con los reciclables.'],
    ef: reciclable(0.05), tags: ['reciclaje', 'separar'],
  }),
  d('res-aplastar-envases', 'Aplastá botellas y desarmá las cajas', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Un envase sin aplastar ocupa el lugar de cinco en la bolsa y en el camión.',
    desc: 'Botellas aplastadas y cajas desarmadas ocupan mucho menos: entra más en cada bolsa, el recuperador lleva más por viaje y el camión hace menos vueltas.',
    pasos: ['Sacale la tapa a la botella y aplastala.', 'Desarmá las cajas y doblalas planas.'],
    ef: nada(), tags: ['reciclaje', 'chicos'], hereda: ['res-aplasta-los-envases'],
  }),
  d('lleva-tu-botella-reutilizable', 'Salí con tu botella o termo lleno', {
    dom, e: 'easy', i: 'low', min: 1, rut: true, lugar: 'calle', ahorra: true,
    corto: 'Cada botella que no comprás es plástico que no se fabrica y plata que no gastás.',
    desc: 'El agua embotellada se usa un rato y su envase tarda siglos en desaparecer. Llenar tu botella o termo en casa (el agua de red es potable en casi todas las ciudades) te ahorra comprar y tirar.',
    pasos: ['A la noche, dejá la botella lista en la heladera.', 'Salí con ella en la mochila o la cartera.', 'Si se termina, pedí que te la rellenen en vez de comprar otra.'],
    ef: plastico(0.025), tags: ['plastico', 'botella'], hereda: ['agua-termo-en-vez-de-botella', 'ali-tomar-agua-de-canilla', 'toma-agua-de-la-canilla-en-vez-de-embotellada'],
  }),
  d('lleva-tus-bolsas-reutilizables-a-comprar', 'Llevá tu bolsa para las compras', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'compras', rut: true,
    corto: 'Las bolsas de un uso son de lo que más aparece en las limpiezas de ríos y costas.',
    desc: 'Una bolsa de tela o una mochila reemplaza cientos de bolsas plásticas a lo largo del año. El truco es que esté donde la necesitás: doblada en la cartera, en el auto o colgada al lado de la puerta.',
    pasos: ['Dejá una bolsa doblada en la mochila o la cartera.', 'Otra al lado de la puerta, para cuando salís a comprar.', 'En la verdulería y la panadería, pedí que te pongan las cosas ahí.'],
    ef: plastico(0.012), tags: ['plastico', 'bolsa'],
  }),
  d('usa-tu-vaso-o-termo-reutilizable', 'Pedí el café en taza o en tu vaso', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', lugar: 'calle',
    corto: 'Los vasos de café "de papel" tienen plástico adentro y casi nunca se reciclan.',
    desc: 'Si te quedás, pedilo en taza. Si es para llevar, en tu vaso térmico o en tu termo. Muchos cafés ya lo aceptan, y algunos hasta hacen descuento.',
    pasos: ['Si tomás el café ahí, pedilo en taza.', 'Si es para llevar, dales tu vaso o tu termo.'],
    ef: plastico(0.015), tags: ['plastico', 'cafe'], hereda: ['ali-tomar-sin-descartable'],
  }),
  d('res-sin-sorbete', 'Pedí tu bebida sin sorbete', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'calle',
    corto: 'Lo usás diez minutos; queda en el ambiente siglos.',
    desc: 'La mayoría de las bebidas se toman igual sin sorbete. Decirlo al pedir evita que te lo pongan de oficio. Si lo necesitás, uno de metal o de vidrio dura años.',
    pasos: ['Al pedir, decí "sin sorbete, por favor".', 'Si lo necesitás, llevá uno reutilizable.'],
    ef: plastico(0.001), tags: ['plastico', 'chicos'],
  }),
  d('res-sin-servilletas-de-mas', 'Agarrá sólo las servilletas que vas a usar', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'calle',
    corto: 'El puñado "por las dudas" termina en la basura sin usar.',
    desc: 'En los locales de comida se agarran servilletas de más que después se tiran limpias. Una o dos alcanzan casi siempre.',
    pasos: ['Agarrá una o dos.', 'Si te sobraron limpias, guardalas para la próxima.'],
    ef: { r: 0.005, c: 0.005 }, tags: ['papel'],
  }),
  d('res-decile-que-no-al-ticket', 'Rechazá el ticket que no necesitás', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', lugar: 'compras',
    corto: 'El papel térmico del ticket no se recicla.',
    desc: 'El ticket de la compra del súper o del cajero automático va casi siempre directo a la basura. Si no lo necesitás para un cambio o una garantía, pedí que no lo impriman o que te lo manden por mail.',
    pasos: ['Al pagar, decí que no necesitás el ticket.', 'Si lo necesitás, pedilo por mail o mirá el comprobante en la app.'],
    ef: { r: 0.002 }, tags: ['papel'], hereda: ['res-rechaza-ticket'],
  }),
  d('alim-pedi-sin-cubiertos-descartables', 'Pedí el delivery sin cubiertos ni servilletas', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', rut: true,
    corto: 'Si comés en casa, los cubiertos de plástico van directo a la basura sin abrir.',
    desc: 'Las apps de delivery tienen una opción para no recibir cubiertos ni servilletas. Marcarla una vez y dejarla así evita bolsitas de plástico que nadie usa.',
    pasos: ['Al pedir, marcá "sin cubiertos".', 'Si la app lo permite, dejalo guardado para siempre.'],
    ef: plastico(0.01), tags: ['plastico', 'delivery'],
  }),
  d('res-tupper-para-sobras', 'Llevá tu tupper si comés afuera', {
    dom, e: 'easy', i: 'low', min: 1, edad: 'ta', lugar: 'calle',
    corto: 'Lo que sobra del almuerzo vuelve a casa sin una bandeja de telgopor.',
    desc: 'Las porciones de afuera suelen sobrar. Si llevás tu recipiente, lo que no comiste vuelve a casa sin descartables, y no se tira comida.',
    pasos: ['Si vas a comer afuera, llevá un tupper chico.', 'Pedí que te pongan ahí lo que sobra.'],
    ef: plastico(0.03), tags: ['plastico', 'comida'],
  }),
  d('res-sin-monodosis', 'Evitá los sobrecitos de una sola dosis', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'compras',
    corto: 'Cada sobrecito de azúcar, kétchup o café es un envoltorio que no se recicla.',
    desc: 'Comprar el frasco o el paquete grande en vez de sobrecitos individuales genera mucho menos envase por cada uso, y suele salir más barato.',
    pasos: ['En casa, usá azucarera, frascos y paquetes grandes.', 'Afuera, agarrá sólo los sobrecitos que vas a usar.'],
    ef: plastico(0.005), tags: ['plastico'],
  }),
  d('res-trapo-en-vez-de-rollo', 'Limpiá con trapo, no con rollo de cocina', {
    dom, e: 'easy', i: 'low', min: 1, rut: true, ahorra: true,
    corto: 'Un trapo se lava y dura meses; el papel se usa una vez.',
    desc: 'El rollo de cocina es cómodo, pero se tira después de cada pasada. Un repasador o un trapo (hecho con una remera vieja) limpia igual y se lava con la ropa.',
    pasos: ['Dejá un trapo a mano en la mesada.', 'Usá el rollo sólo para grasa de verdad.'],
    ef: { r: 0.03, c: 0.03 }, tags: ['papel', 'cocina'],
  }),
  d('res-papel-de-los-dos-lados', 'Usá las hojas de los dos lados', {
    dom, e: 'easy', i: 'low', min: 1,
    corto: 'Casi la mitad del papel que se tira está escrito de un solo lado.',
    desc: 'Las hojas impresas o escritas de un lado sirven de borrador, para listas o para dibujar. En la escuela, en casa o en el trabajo, es papel que no hay que comprar.',
    pasos: ['Juntá las hojas usadas de un solo lado.', 'Cortalas al medio y usalas de anotador o borrador.'],
    ef: { r: 0.01, c: 0.01 }, tags: ['papel', 'escuela', 'chicos'],
  }),
  d('res-yerba-a-la-planta', 'Tirá la yerba usada a una maceta o al compost', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'La yerba del mate es de lo que más se tira en una casa argentina, y es abono.',
    desc: 'La yerba usada es materia orgánica que en el relleno sanitario produce metano. En la tierra de una maceta o en el compost, aporta nutrientes y ayuda a retener humedad.',
    pasos: ['Cuando termines el mate, volcá la yerba en una maceta o en el compost.', 'Si es mucha, mezclala con la tierra o esparcila en el jardín.'],
    ef: organico(0.1), tags: ['mate', 'compost'], hereda: ['alim-composta-la-yerba'],
  }),
  d('composta-tus-restos-de-comida', 'Llevá los restos de fruta y verdura al compost', {
    dom, e: 'easy', i: 'medium', min: 2, req: ['compost'], rut: true,
    corto: 'Casi la mitad de la basura de una casa es orgánica: en el compost se vuelve tierra.',
    desc: 'Cáscaras, restos de verdura, yerba, café y cáscaras de huevo van al compost en vez de a la bolsa. Así no generan metano en el relleno y la bolsa de basura pesa la mitad y no huele.',
    pasos: ['Juntá los restos crudos del día en un recipiente con tapa.', 'Llevalos al compost y tapalos con hojas secas o tierra.', 'No pongas carne, lácteos ni grasas.'],
    ef: organico(0.5), tags: ['compost'],
  }),
  d('reutiliza-un-frasco-o-envase', 'Reusá un frasco o envase antes de tirarlo', {
    dom, e: 'easy', i: 'low', min: 2,
    corto: 'Un frasco de vidrio es un tupper gratis que dura años.',
    desc: 'Los frascos de mermelada, de salsa o de dulce de leche sirven para guardar legumbres, especias, semillas o sobras. Cada envase que se reusa es uno menos que fabricar.',
    pasos: ['Lavá el frasco y sacale la etiqueta con agua tibia.', 'Usalo para guardar comida, semillas o lo que necesites.'],
    ef: { r: 0.2, c: 0.1 }, tags: ['reuso', 'chicos'], hereda: ['res-frasco-organizador'],
  }),
  d('res-reutiliza-las-bolsas-de-pan', 'Reusá una bolsa antes de tirarla', {
    dom, e: 'easy', i: 'low', min: 1, rut: true,
    corto: 'Casi toda bolsa aguanta muchos más usos de los que le damos.',
    desc: 'La bolsa del pan, la de la verdulería o la del súper pueden volver a salir con vos para la próxima compra o para juntar la basura. Doblá y guardá las que están sanas.',
    pasos: ['Doblá las bolsas que estén sanas.', 'Guardalas cerca de la puerta o en la bolsa de las compras.', 'Usalas de nuevo antes de pedir otra.'],
    ef: plastico(0.006), tags: ['plastico', 'bolsa', 'chicos'],
  }),
  d('evita-un-plastico-de-un-solo-uso-hoy', 'Decile que no a un descartable hoy', {
    dom, e: 'easy', i: 'low', min: 1,
    corto: 'Un plástico que usás un minuto queda cientos de años.',
    desc: 'Elegí uno solo para hoy: el vaso de plástico, la bolsita de la verdura, la cucharita del helado o el film. El PNUMA calcula que la mitad del plástico que se fabrica en el mundo es de un solo uso.',
    pasos: ['Pensá qué descartable usás por costumbre.', 'Hoy reemplazalo por algo que tengas (tu vaso, tu bolsa, un tupper).'],
    ef: plastico(0.01), fuente: 'unep-plasticos', tags: ['plastico', 'chicos'],
  }),
  d('res-envase-grande', 'Elegí el envase grande en vez de varios chicos', {
    dom, e: 'easy', i: 'low', min: 1, lugar: 'compras', edad: 'ta', ahorra: true,
    corto: 'Un kilo en un envase genera menos residuo que cuatro de 250 gramos.',
    desc: 'Lo que vas a terminar seguro (detergente, arroz, aceite, galletitas) conviene en el formato más grande: menos envase por cada uso y casi siempre más barato por kilo.',
    pasos: ['Compará el precio por kilo o por litro.', 'Si lo vas a terminar antes de que venza, llevá el grande.'],
    ef: plastico(0.02), tags: ['plastico', 'compras'],
  }),

  // ── Catálogo ───────────────────────────────────────────────────────────────
  c('res-recuperador-urbano', 'Entregale los reciclables a un recuperador urbano', {
    dom, e: 'easy', i: 'high', min: 10, formato: 'salida', edad: 'ta', lugar: 'calle', cool: 72,
    corto: 'En la Argentina, buena parte de lo que se recicla lo recuperan cartoneros y cooperativas.',
    desc: 'Los recuperadores urbanos y sus cooperativas son el corazón del reciclaje en el país. Separar en tu casa y entregarles el material limpio, seco y aplastado (o dejarlo donde pasan, en su horario) les hace el trabajo más digno y hace que más material vuelva a la industria.',
    pasos: ['Averiguá qué día y a qué hora pasa el recuperador de tu cuadra, o si hay una cooperativa cerca.', 'Juntá cartón, papel, plásticos y latas limpios y secos.', 'Entregáselos en mano o dejalos en su horario.'],
    ef: reciclable(1), fuente: 'faccyr', tags: ['reciclaje', 'cartoneros', 'barrio'],
  }),
  c('compra-a-granel-o-en-estaciones-de-recarga', 'Comprá algo suelto, con tu frasco o tu bolsa', {
    dom, e: 'easy', i: 'medium', min: 20, formato: 'salida', edad: 'ta', lugar: 'compras', cool: 168,
    corto: 'Comprando suelto pagás el producto, no el envase.',
    desc: 'Dietéticas, almacenes y ferias venden legumbres, arroz, yerba, frutos secos, harinas o productos de limpieza sueltos. Llevando tus frascos o bolsas de tela te llevás lo justo y nada de envase.',
    pasos: ['Llevá frascos o bolsas de tela limpios.', 'Comprá sueltas las cosas que más usás (arroz, legumbres, avena, detergente).', 'Pedí que pesen el recipiente vacío antes de llenarlo.'],
    ef: plastico(0.03), tags: ['plastico', 'granel', 'compras'], hereda: ['res-comprar-a-granel'],
  }),
  c('res-devolve-los-envases-retornables', 'Comprá bebidas en envase retornable', {
    dom, e: 'easy', i: 'medium', min: 5, formato: 'salida', edad: 'ta', lugar: 'compras', ahorra: true, cool: 72,
    corto: 'Una botella retornable vuelve a llenarse decenas de veces, y sale más barata.',
    desc: 'La cerveza de litro, varias gaseosas y el agua en bidón vienen en retornable: devolvés el envase y pagás sólo la bebida. Es el sistema más limpio que existe, y en la Argentina está en casi cualquier almacén.',
    pasos: ['Fijate qué bebidas que tomás vienen en retornable.', 'Comprá esas y guardá el envase.', 'Devolvelo en la próxima compra.'],
    ef: { r: 0.4, c: 0.3 }, tags: ['retornable', 'vidrio', 'compras'], hereda: ['res-comprar-a-quien-recibe-envase'],
  }),
  c('res-soderia', 'Pedí la soda o el agua en sifones y bidones retornables', {
    dom, e: 'easy', i: 'high', min: 10, edad: 'a', frec: 'one_time', ahorra: true,
    corto: 'El sodero es un sistema retornable de toda la vida: cero botellas al tacho.',
    desc: 'Si en tu casa se toma soda o agua embotellada, el sodero las trae en sifones y bidones que se lleva vacíos y vuelve a llenar. En un mes son decenas de botellas de plástico que no se fabrican ni se tiran.',
    pasos: ['Preguntá en el barrio o en el almacén por un sodero que reparta en tu zona.', 'Arreglá la entrega semanal de sifones o bidones.', 'Devolvé los vacíos en cada entrega.'],
    ef: plastico(0.6), tags: ['retornable', 'plastico', 'soda'],
  }),
  c('res-ecobotella', 'Armá una ecobotella con los plásticos chicos', {
    dom, e: 'easy', i: 'medium', min: 20, edad: 'kta', adulto: true, cool: 336,
    corto: 'Envoltorios y paquetitos que no se reciclan, compactados en una botella, se vuelven material de construcción.',
    desc: 'Los plásticos chicos y blandos (envoltorios de golosinas, paquetes de fideos, film) casi nunca se reciclan sueltos. Muchos municipios, escuelas y organizaciones reciben botellas rellenas y compactadas de esos plásticos para hacer ladrillos o bancos.',
    pasos: ['Juntá plásticos chicos limpios y secos.', 'Metelos en una botella de plástico apretándolos con un palo hasta que quede dura.', 'Averiguá en tu municipio o escuela dónde reciben ecobotellas.'],
    ef: reciclable(0.3), tags: ['plastico', 'reciclaje', 'chicos'],
  }),
  c('res-tapitas-garrahan', 'Juntá tapitas para una campaña solidaria', {
    dom, e: 'easy', i: 'medium', min: 10, formato: 'salida', edad: 'kta', adulto: true, cool: 336,
    corto: 'Las tapitas plásticas se reciclan y la plata va a un hospital o una escuela.',
    desc: 'La Fundación Garrahan recicla tapitas desde 2006, y muchas escuelas, clubes y municipios tienen sus propias campañas. Juntarlas en un frasco es un hábito fácil para hacer en familia, y el plástico vuelve a la industria.',
    pasos: ['Dejá un frasco o una bolsa para las tapitas en la cocina.', 'Cuando esté lleno, llevalo a una escuela, un comercio o un punto que las reciba.'],
    ef: reciclable(0.2), fuente: 'garrahan-reciclado', tags: ['plastico', 'garrahan', 'solidario', 'chicos'], hereda: ['res-separar-tapitas'],
  }),
  c('res-papel-garrahan', 'Llevá papel y cartón a una campaña de reciclado', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'salida', edad: 'kta', adulto: true, cool: 336,
    corto: 'El papel de diarios, cuadernos y cajas se recicla y financia causas solidarias.',
    desc: 'El Programa de Reciclado de la Fundación Garrahan empezó en 1999 con papel. Muchas escuelas y empresas tienen contenedores para juntar diarios, revistas, cuadernos viejos y cartón: llevarlos ahí asegura que se reciclen.',
    pasos: ['Juntá papel y cartón limpio y seco.', 'Sacale ganchos, espirales y cintas.', 'Llevalo a un contenedor de la campaña o a una escuela que lo reciba.'],
    ef: reciclable(2), fuente: 'garrahan-reciclado', tags: ['papel', 'garrahan', 'solidario', 'escuela'],
  }),
  c('lleva-pilas-y-baterias-a-un-punto-de-recoleccion', 'Llevá las pilas usadas a un punto de recolección', {
    dom, e: 'easy', i: 'medium', min: 15, formato: 'salida', edad: 'ta', lugar: 'calle', cool: 720,
    corto: 'Las pilas tienen metales que no deberían terminar en la tierra ni en el agua.',
    desc: 'Muchos municipios, supermercados y puntos verdes tienen contenedores para pilas y baterías. Juntarlas en un frasco cerrado y llevarlas todas juntas evita que vayan a la basura común.',
    pasos: ['Juntá las pilas usadas en un frasco cerrado.', 'Averiguá el punto de recolección más cercano (municipio, punto verde, súper).', 'Llevalas cuando el frasco esté lleno.'],
    ef: { r: 0.1 }, tags: ['pilas', 'especiales'], hereda: ['res-pilas-a-punto-limpio'],
  }),
  c('lleva-tus-residuos-electronicos-a-un-punto-certi', 'Llevá aparatos viejos a reciclaje de electrónicos', {
    dom, e: 'medium', i: 'high', min: 30, formato: 'salida', edad: 'ta', lugar: 'calle', cool: 720,
    corto: 'Un celular o un cargador en un cajón tienen metales que hay que volver a sacar de una mina.',
    desc: 'Celulares, cargadores, cables, mouses o aparatos rotos tienen cobre, oro y metales escasos, y también sustancias tóxicas. El Global E-waste Monitor calcula que menos de un cuarto de la basura electrónica del mundo se recicla bien.',
    pasos: ['Revisá cajones y juntá aparatos, cables y cargadores que no uses.', 'Borrá tus datos de celulares y compus.', 'Llevalos a un punto de residuos electrónicos de tu municipio o a una campaña.'],
    ef: reciclable(2), fuente: 'ewaste-monitor', tags: ['electronicos', 'especiales'], hereda: ['recicla-tus-dispositivos-viejos-responsablemente'],
  }),
  c('recicla-correctamente-el-aceite-de-cocina-usado', 'Juntá el aceite usado y llevalo a reciclar', {
    dom, e: 'easy', i: 'medium', min: 10, edad: 'ta', cool: 720,
    corto: 'Por la pileta tapa cañerías y contamina el agua; reciclado se vuelve biodiésel.',
    desc: 'El aceite de freír no va a la pileta ni al inodoro: se pega en los caños y llega a ríos y arroyos. Frío y en una botella cerrada, muchos municipios, estaciones de servicio y empresas lo reciben para hacer biodiésel.',
    pasos: ['Dejalo enfriar y colalo en una botella de plástico con tapa.', 'Guardala hasta llenarla.', 'Llevala a un punto de recolección de aceite de tu ciudad.'],
    ef: { r: 0.9 }, tags: ['aceite', 'especiales', 'cocina'], hereda: ['res-aceite-usado'],
  }),
  c('res-no-tires-pintura-ni-solventes', 'Llevá restos de pintura y solventes a residuos especiales', {
    dom, e: 'easy', i: 'medium', min: 20, edad: 'a', formato: 'salida', cool: 2160,
    corto: 'Un resto de solvente en la basura contamina la tierra y el agua alrededor del relleno.',
    desc: 'Restos de pintura, aguarrás, thinner, venenos y aerosoles son residuos peligrosos. No van a la basura común ni a la pileta: muchos municipios tienen días o puntos para recibirlos.',
    pasos: ['Juntá los restos en sus envases originales, bien cerrados.', 'Averiguá el punto o el día de residuos especiales de tu municipio.', 'Llevalos ahí.'],
    ef: { r: 1 }, tags: ['especiales'],
  }),
  c('res-saca-las-pilas-de-lo-que-tiras', 'Sacá las pilas antes de tirar un juguete o aparato', {
    dom, e: 'easy', i: 'medium', min: 5, edad: 'kta', adulto: true, cool: 720,
    corto: 'Una batería aplastada en el camión de basura puede prender fuego todo.',
    desc: 'Juguetes, controles, linternas o tarjetas musicales tienen pilas o baterías adentro. Antes de descartarlos, sacalas y llevalas aparte: es seguridad para quienes recolectan y menos metales en la basura.',
    pasos: ['Antes de tirar algo con pilas, abrí la tapa y sacalas.', 'Ponelas en el frasco de pilas usadas.'],
    ef: { r: 0.05 }, tags: ['pilas', 'especiales', 'chicos'],
  }),
  c('arma-una-estacion-de-separacion-de-residuos-en-c', 'Armá un rincón para separar en la cocina', {
    dom, e: 'easy', i: 'medium', min: 20, edad: 'kta', adulto: true, frec: 'one_time',
    corto: 'Si separar es incómodo, no se sostiene: con dos tachos al lado, sale solo.',
    desc: 'La razón número uno para no separar es que no hay dónde. Dos recipientes rotulados (reciclables y resto), y si podés uno chico para orgánicos, al lado de donde cocinás, hacen que separar sea tan fácil como tirar.',
    pasos: ['Conseguí dos tachos, cajas o bolsas grandes.', 'Rotulalos: "Reciclables (limpio y seco)" y "Resto".', 'Ponelos donde tirás la basura, no en otra pieza.'],
    ef: nada(), tags: ['separar', 'reciclaje', 'chicos'],
  }),
  c('res-averigua-dia-reciclables', 'Averiguá qué día se llevan los reciclables en tu barrio', {
    dom, e: 'easy', i: 'medium', min: 10, formato: 'aprender', edad: 'kta', frec: 'one_time',
    corto: 'Sacar los reciclables el día equivocado es como no separarlos.',
    desc: 'Cada ciudad tiene su sistema: contenedores, puntos verdes, días de recolección diferenciada o recuperadores. Saber cuál es el tuyo es lo que hace que separar sirva de verdad.',
    pasos: ['Buscá en la web de tu municipio "recolección diferenciada" o "puntos verdes".', 'Anotá el día y horario, o el punto más cercano.', 'Pegalo en la heladera.'],
    ef: nada(), tags: ['reciclaje', 'barrio'],
  }),
  c('empeza-a-compostar-en-casa', 'Empezá una compostera', {
    dom, e: 'medium', i: 'high', min: 45, req: ['balcon'], edad: 'ta', frec: 'one_time', otorga: 'compost',
    corto: 'Casi la mitad de la basura de una casa son restos que pueden volver a ser tierra.',
    desc: 'Una compostera se arma con un balde grande o un tacho con tapa y agujeros. Alternás restos húmedos (cáscaras, yerba, café) con secos (hojas, cartón sin tinta) y en unos meses tenés tierra negra para tus plantas. Tu bolsa de basura pesa la mitad y deja de oler.',
    pasos: ['Conseguí un tacho con tapa y hacele agujeros en la base y los costados.', 'Poné una capa de hojas secas o cartón y empezá a sumar restos crudos, tapando cada vez con algo seco.', 'Mezclá una vez por semana y mantenelo húmedo como una esponja escurrida.'],
    ef: organico(1), tags: ['compost'], hereda: ['res-compost-balcon', 'evita-compost-a-base-de-turba'],
  }),
  c('arma-una-compostera-con-lombrices-vermicompost', 'Armá una lombricompuesta', {
    dom, e: 'medium', i: 'high', min: 60, req: ['balcon'], edad: 'ta', frec: 'one_time', otorga: 'compost',
    corto: 'Las lombrices procesan los restos más rápido, sin olor y en poco espacio.',
    desc: 'Con dos cajones apilados y lombrices californianas (se consiguen en viveros o con alguien que ya tenga) se arma un compost que entra en un balcón. Las lombrices comen restos de verdura y dejan humus, uno de los mejores abonos.',
    pasos: ['Apilá dos cajones con agujeros en el fondo del de arriba.', 'Poné tierra húmeda, cartón y las lombrices.', 'Alimentalas con restos crudos picados, sin cítricos ni cebolla en exceso.'],
    ef: organico(1), tags: ['compost', 'lombrices'],
  }),
  c('res-compost-cosecha', 'Cosechá tu compost y usalo', {
    dom, e: 'easy', i: 'high', min: 30, req: ['compost'], edad: 'kta', adulto: true, cool: 2160,
    corto: 'La tierra negra del fondo es lo que dejaste de tirar estos meses.',
    desc: 'Cuando la capa de abajo está oscura, suelta y huele a tierra de bosque, está lista. Usarla en macetas, la huerta o al pie de un árbol cierra el círculo: lo que era basura ahora alimenta plantas.',
    pasos: ['Sacá la capa de abajo, la más oscura.', 'Tamizala con una rejilla y volvé a poner lo que no se deshizo.', 'Mezclala con la tierra de tus macetas o tu huerta.'],
    ef: organico(6), tags: ['compost', 'plantas', 'chicos'],
  }),
  c('hace-una-auditoria-de-tu-basura', 'Mirá qué tirás durante una semana', {
    dom, e: 'medium', i: 'medium', min: 15, formato: 'reto', frec: 'one_time', edad: 'kta', adulto: true,
    corto: 'Mirar la propia basura muestra exactamente qué cambiar.',
    desc: 'Durante siete días, antes de cerrar la bolsa, mirá qué hay: ¿muchas botellas? ¿comida que se venció? ¿envoltorios de lo mismo? Lo que más se repite es tu próximo cambio. En la Argentina cada persona genera más de un kilo de basura por día.',
    pasos: ['Durante una semana, anotá lo que más aparece en tu basura.', 'Al final, elegí lo que más se repite.', 'Buscá en Brote una acción para eso y sumala.'],
    ef: nada(), tags: ['experimento'],
  }),
  c('pasa-una-semana-de-residuo-cero', 'Hacé una semana basura cero', {
    dom, e: 'hard', i: 'high', min: 30, formato: 'reto', frec: 'weekly', edad: 'ta', rango: 'brote',
    corto: 'Siete días tratando de que no salga nada de tu casa que no se pueda reciclar o compostar.',
    desc: 'Un reto para cuando ya separás y compostás: durante una semana, evitá todo lo que termina en la bolsa de "resto". Al final, lo que no pudiste evitar te dice dónde está el próximo paso.',
    pasos: ['Planificá las compras: suelto, retornable, sin envoltorios.', 'Separá y compostá todo.', 'Guardá lo que no pudiste evitar y miralo al final de la semana.'],
    ef: suma(plastico(0.3), reciclable(1), organico(2)), tags: ['reto', 'plastico'],
  }),
  c('cambia-a-jabon-o-champu-en-barra', 'Pasate al jabón o al champú en barra', {
    dom, e: 'easy', i: 'medium', min: 10, edad: 'ta', frec: 'one_time', lugar: 'compras',
    corto: 'Una barra reemplaza varias botellas de plástico y dura más.',
    desc: 'El jabón de tocador de siempre, el jabón blanco y los champús sólidos vienen sin botella. Una barra dura lo que dos o tres envases líquidos, y si la guardás en una jabonera que drene, no se deshace.',
    pasos: ['La próxima vez, comprá jabón o champú en barra.', 'Usá una jabonera con agujeros para que se seque entre usos.'],
    ef: plastico(0.04), tags: ['plastico', 'baño'], hereda: ['res-jabon-en-barra'],
  }),
  c('res-ropa-a-trapos', 'Convertí una remera vieja en trapos', {
    dom, e: 'easy', i: 'low', min: 10, edad: 'kta', adulto: true, cool: 336,
    corto: 'Lo que ya no se puede usar ni donar todavía sirve para limpiar.',
    desc: 'Una remera o una toalla gastadas, cortadas en cuadrados, son trapos que absorben mejor que muchos comprados. Es tela que no va a la basura y rollo de cocina que no se compra.',
    pasos: ['Elegí una prenda de algodón que ya no se pueda donar.', 'Cortala en cuadrados.', 'Usalos en la cocina o para limpiar.'],
    ef: { r: 0.2, c: 0.2 }, tags: ['ropa', 'reuso', 'chicos'],
  }),
  c('res-lleva-los-textiles-a-un-punto', 'Llevá la ropa rota a reciclaje textil', {
    dom, e: 'easy', i: 'medium', min: 20, formato: 'salida', edad: 'ta', cool: 720,
    corto: 'La ropa que no sirve para donar se recicla como relleno, fieltro o hilo.',
    desc: 'La Fundación Ellen MacArthur calcula que menos del 1% de la ropa se recicla en ropa nueva. Lo que está muy gastado para donar, separado y entregado a un punto de reciclaje textil, se vuelve aislante, relleno o trapos industriales.',
    pasos: ['Separá la ropa demasiado gastada para donar.', 'Averiguá si tu municipio, una cooperativa o una tienda reciben textiles.', 'Llevala limpia y seca.'],
    ef: { r: 1, c: 1 }, fuente: 'emf-textiles', tags: ['ropa', 'reciclaje'],
  }),
  c('res-usa-servilletas-de-tela', 'Pasate a servilletas de tela', {
    dom, e: 'easy', i: 'medium', min: 10, frec: 'one_time', ahorra: true,
    corto: 'Un juego de servilletas de tela reemplaza cientos de rollos de papel al año.',
    desc: 'Las servilletas de tela se lavan con la ropa y duran años. Si en tu casa cada uno tiene la suya (con un servilletero o un color), se usan varios días antes de lavar.',
    pasos: ['Conseguí o cosé un juego de servilletas (sirven retazos de tela).', 'Que cada uno tenga la suya para usar varios días.', 'Lavalas con la ropa.'],
    ef: { r: 0.5, c: 0.5 }, tags: ['papel', 'cocina'],
  }),
  c('res-helado-en-tu-pote', 'Pedí el helado o la comida en tu propio recipiente', {
    dom, e: 'easy', i: 'low', min: 10, formato: 'salida', lugar: 'compras', edad: 'kta', cool: 48,
    corto: 'El pote de telgopor de la heladería se usa una tarde y dura siglos.',
    desc: 'Muchas heladerías, rotiserías y casas de comida aceptan que lleves tu recipiente. El telgopor casi nunca se recicla y vuela con el viento hasta el agua: tu tupper lo reemplaza.',
    pasos: ['Llevá un recipiente limpio con tapa.', 'Preguntá si te lo llenan ahí.', 'Si no aceptan, decilo con buena onda: muchos lo cambian cuando se lo piden.'],
    ef: plastico(0.03), tags: ['telgopor', 'plastico', 'helado', 'chicos'],
  }),
  c('res-campo-envases-agroquimicos', 'Hacé el triple lavado de los envases de agroquímicos', {
    dom, e: 'medium', i: 'high', min: 30, req: ['campo'], edad: 'a', cool: 720,
    corto: 'Un bidón de agroquímico mal descartado contamina el suelo y el agua por años.',
    desc: 'La ley de envases de fitosanitarios obliga a hacer el triple lavado y entregarlos en un centro de acopio. Lavados tres veces y perforados, se reciclan; quemados o enterrados en el campo, contaminan el agua de pozo.',
    pasos: ['Enjuagá cada envase tres veces y volcá el agua en el tanque de la pulverizadora.', 'Perforá el fondo para que no se reuse.', 'Llevalos a un centro de acopio de tu zona.'],
    ef: { r: 1 }, fuente: 'ley-27279-fitosanitarios', tags: ['campo', 'agroquimicos'],
  }),
];
