import type { DomainSlug } from '@/lib/domains';
import type {
  Ambicion,
  Confianza,
  Dossier,
  Horizonte,
  Inversion,
  MetodoTipo,
  MetricaTipo,
} from './tipos';

/**
 * El catálogo de palancas (`referencia/CATALOGO_PALANCAS.md`).
 *
 * Cumple tres funciones: es el camino sin IA (hoy no hay `GEMINI_API_KEY`),
 * es el ancla que se le pasa a Gemini para que no invente, y es el reemplazo
 * cuando el validador de realismo descarta una propuesta.
 *
 * Las palancas que el documento trae con texto completo están transcritas
 * **literales** — ya están escritas en voz de producto. Las que el documento
 * deja en una línea (métrica, esfuerzo, inversión) están completadas siguiendo
 * sus seis reglas: medible con algo que ya tienen, ≤ 6 h/mes, dentro de su
 * control, rango de efecto honesto, con escalón siguiente, y sin motivación ni
 * signos de exclamación.
 *
 * Ninguna promete un número: prometen un rango típico y un método para medirlo.
 */

/** Condiciones del dossier que una palanca necesita para tener sentido. */
export type Requisito =
  | 'linea_base_energia'
  | 'presupuesto'
  | 'puede_cambiar_proveedores'
  | 'agua_relevante'
  | 'flota'
  | 'equipo_5'
  | 'local_propio'
  | 'espacio_fisico';

export interface Palanca {
  slug: string;
  /** Con `{{variables}}` que rellena `rellenarPlantilla`. */
  titulo_plantilla: string;
  dominio: DomainSlug;
  /** `'*'` = cualquier rubro. */
  rubros: string[];
  metrica: string;
  unidad: string;
  metrica_tipo: MetricaTipo;
  metodo_tipo: MetodoTipo;
  alcance: 1 | 2 | 3;
  /** Fracción, orientativa. 0 en las palancas de medición. */
  efecto_min: number;
  efecto_max: number;
  horizonte: Horizonte;
  ambicion: Ambicion;
  esfuerzo_horas_mes: number;
  inversion: Inversion;
  requiere: Requisito[];
  /** Frases que, si aparecen en "ya hecho", significan que esto ya está hecho. */
  claves: string[];
  porque: string;
  pasos: string[];
  como_medir: string;
  evidencia_requerida: string;
  si_no_llegas: string;
  confianza: Confianza;
  es_evento_unico?: boolean;
  escalon_siguiente?: string;
}

// ── Transversales ────────────────────────────────────────────────────────────

const TRANSVERSALES: Palanca[] = [
  {
    slug: 'medir-energia',
    titulo_plantilla: 'Medir el consumo eléctrico mensual para tener una línea de base',
    dominio: 'energia',
    rubros: ['*'],
    metrica: 'consumo eléctrico',
    unidad: 'kWh/mes',
    metrica_tipo: 'medicion',
    metodo_tipo: 'factura',
    alcance: 2,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 1,
    inversion: 'ninguna',
    requiere: [],
    claves: ['medir el consumo', 'linea de base de energia', 'registro de facturas de luz'],
    porque:
      'No se puede mejorar lo que no se mide. Tres meses de facturas alcanzan para saber cuánto gastás de verdad y en qué momentos, y a partir de ahí cualquier cambio se puede evaluar.',
    pasos: [
      'Juntar las últimas 3 facturas',
      'Anotar kWh y período en una planilla',
      'Registrar cada factura nueva',
      'Marcar el mes más alto y anotar qué pasó ese mes',
    ],
    como_medir: 'Los kWh que figuran en la factura de la distribuidora',
    evidencia_requerida: 'Foto o PDF de las 3 facturas',
    si_no_llegas: 'Con dos meses registrados ya tenés con qué empezar. Cerralo con lo que juntaste.',
    confianza: 'alta',
    escalon_siguiente: 'iluminacion-led',
  },
  {
    slug: 'iluminacion-led',
    titulo_plantilla: 'Cambiar la iluminación de {{espacio}} a LED',
    dominio: 'energia',
    rubros: ['*'],
    metrica: 'consumo eléctrico',
    unidad: 'kWh/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'factura',
    alcance: 2,
    efecto_min: 0.05,
    efecto_max: 0.15,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'baja',
    requiere: ['linea_base_energia', 'presupuesto'],
    claves: ['led', 'cambiamos las luces', 'iluminacion led'],
    porque:
      'La iluminación suele ser una porción grande del consumo en locales comerciales, y es de los pocos cambios que se pagan solos en meses. Además dura mucho más, así que dejás de reponer.',
    pasos: [
      'Contar las luminarias y anotar su potencia',
      'Pedir dos presupuestos',
      'Empezar por el área de más horas encendida',
      'Cambiar el resto en 2 tandas',
      'Comparar la factura 2 meses después',
    ],
    como_medir: 'Comparar kWh de la factura contra el mismo mes del año anterior',
    evidencia_requerida: 'Factura de compra + foto del antes y el después',
    si_no_llegas: 'Cambiar solo el sector de más horas encendidas ya cuenta. Cerralo con eso y seguí después.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'apagado-programado',
  },
  {
    slug: 'apagado-programado',
    titulo_plantilla: 'Reducir el consumo fuera del horario de atención',
    dominio: 'energia',
    rubros: ['*'],
    metrica: 'consumo eléctrico',
    unidad: 'kWh/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'factura',
    alcance: 2,
    efecto_min: 0.03,
    efecto_max: 0.08,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: ['linea_base_energia'],
    claves: ['rutina de cierre', 'apagamos todo al cerrar', 'apagado programado'],
    porque:
      'Los equipos en espera consumen todo el tiempo que el local está cerrado, que suele ser más de la mitad del mes. Una rutina de cierre es gratis y el efecto se sostiene solo.',
    pasos: [
      'Recorrer el local después de cerrar y anotar qué quedó prendido',
      'Definir qué se puede apagar sin riesgo',
      'Escribir una lista de cierre de 5 puntos y pegarla en la puerta',
      'Revisar a las 4 semanas',
    ],
    como_medir: 'Comparar la factura del bimestre siguiente',
    evidencia_requerida: 'Foto de la lista de cierre + facturas del antes y el después',
    si_no_llegas: 'Si la factura no bajó lo esperado, la lista de cierre funcionando ya es la mitad del trabajo.',
    confianza: 'media',
  },
  {
    slug: 'separacion-residuos',
    titulo_plantilla: 'Separar {{materiales}} del residuo mixto',
    dominio: 'residuos',
    rubros: ['*'],
    metrica: 'residuo mixto',
    unidad: 'bolsas/semana',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.15,
    efecto_max: 0.35,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['separamos', 'separacion de residuos', 'reciclamos carton', 'cooperativa'],
    porque:
      'Separar cartón y vidrio saca de la bolsa negra lo que más volumen ocupa. En muchos casos hay cooperativas de recuperadores que lo pasan a buscar sin costo, y en algunos incluso lo pagan.',
    pasos: [
      'Contar cuántas bolsas de mixto se sacan por semana durante 2 semanas',
      'Poner recipientes separados donde se genera el residuo, no en el fondo',
      'Buscar una cooperativa o punto verde cercano',
      'Definir quién lo saca y cuándo',
      'Volver a contar',
    ],
    como_medir: 'Conteo de bolsas los viernes, en una planilla',
    evidencia_requerida: 'Planilla del antes y el después + foto de los recipientes',
    si_no_llegas: 'Separar un material en lugar de dos también baja el mixto. Cerralo con lo que sostuviste.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'residuo-organico',
  },
  {
    slug: 'residuo-organico',
    titulo_plantilla: 'Desviar el residuo orgánico del contenedor',
    dominio: 'residuos',
    rubros: ['*'],
    metrica: 'residuo orgánico',
    unidad: 'kg/semana',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.4,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['compost', 'organico', 'compostamos'],
    porque:
      'El orgánico es lo más pesado y lo que más problema genera en el contenedor. Compostarlo o entregarlo a alguien que lo composte saca peso y olor de un saque.',
    pasos: [
      'Pesar el orgánico de una semana típica',
      'Buscar quién lo reciba (huerta comunitaria, vecino con compost, servicio local)',
      'Definir el recipiente y la frecuencia',
      'Probar un mes',
      'Pesar de nuevo',
    ],
    como_medir: 'Balanza común, una vez por semana',
    evidencia_requerida: 'Registro de pesajes + acuerdo con quien lo recibe',
    si_no_llegas: 'Desviar dos días por semana en lugar de todos ya saca peso del contenedor. Cuenta igual.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'proveedores-locales',
    titulo_plantilla: 'Pasar {{porcentaje}}% de tus compras a proveedores de menos de {{km}} km',
    dominio: 'consumo',
    rubros: ['*'],
    metrica: 'compras a proveedores cercanos',
    unidad: '% de compras',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: ['puede_cambiar_proveedores'],
    claves: ['proveedores locales', 'compramos cerca', 'proveedores de la zona'],
    porque:
      'Comprar cerca baja el transporte, acorta los plazos de reposición y te da un proveedor con el que podés hablar. Además es lo que te habilita a afirmar origen local en tus productos del Mercado.',
    pasos: [
      'Listar los 10 insumos que más comprás y de dónde vienen',
      'Marcar cuáles tienen alternativa a menos de {{km}} km',
      'Pedir precio a dos de ellos',
      'Cambiar uno y evaluar a los 2 meses',
      'Repetir con el siguiente',
    ],
    como_medir: 'Porcentaje sobre el gasto mensual de compras, con los remitos',
    evidencia_requerida: 'Planilla de proveedores del antes y el después',
    si_no_llegas: 'Un proveedor cambiado y sostenido vale más que cinco consultados. Cerralo con ese.',
    confianza: 'media',
    escalon_siguiente: 'origen-declarado',
  },
  {
    slug: 'medir-agua',
    titulo_plantilla: 'Establecer la línea de base de consumo de agua',
    dominio: 'agua',
    rubros: ['*'],
    metrica: 'consumo de agua',
    unidad: 'litros/mes',
    metrica_tipo: 'medicion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 1,
    inversion: 'ninguna',
    requiere: [],
    claves: ['medimos el agua', 'linea de base de agua', 'lectura del medidor'],
    porque:
      'En muchos servicios el agua no se mide y se paga por canilla libre, así que no hay factura de la que aprender. Un registro propio de 3 meses te dice si hay una pérdida o un uso desproporcionado.',
    pasos: [
      'Ver si hay medidor',
      'Si hay, anotar la lectura el mismo día de cada mes',
      'Si no hay, estimar por uso principal y registrarlo',
      'Marcar el mes más alto',
    ],
    como_medir: 'Lectura del medidor o registro estimado',
    evidencia_requerida: 'Foto de las lecturas o la planilla',
    si_no_llegas: 'Dos lecturas ya muestran una tendencia. Cerralo con lo que tengas anotado.',
    confianza: 'alta',
  },
];

// ── Gastronomía ──────────────────────────────────────────────────────────────

const GASTRONOMIA: Palanca[] = [
  {
    slug: 'merma-cocina',
    titulo_plantilla: 'Bajar la merma de {{producto}} un {{pct}}%',
    dominio: 'alimentacion',
    rubros: ['gastronomia'],
    metrica: 'descarte de cocina',
    unidad: 'kg/semana',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.15,
    efecto_max: 0.3,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: [],
    claves: ['merma', 'desperdicio de cocina', 'pesamos lo que se tira'],
    porque:
      'La merma es comida que pagaste, preparaste y tirás. Bajarla es, al mismo tiempo, el cambio ambiental más grande de una cocina y el que más se nota en el margen.',
    pasos: [
      'Pesar lo que se descarta durante 2 semanas, separando preparación de sobrante',
      'Identificar los 3 productos que más se descartan',
      'Ajustar la producción de esos 3',
      'Definir qué hacer con el excedente del día',
      'Volver a pesar',
    ],
    como_medir: 'Balanza al cierre, planilla diaria',
    evidencia_requerida: 'Planilla de 4 semanas del antes y el después',
    si_no_llegas: 'Bajar la merma de un solo producto ya es plata y residuo que no se van. Cerralo con ese.',
    confianza: 'alta',
    escalon_siguiente: 'excedente-fin-de-dia',
  },
  {
    slug: 'excedente-fin-de-dia',
    titulo_plantilla: 'Dar salida al excedente del día en lugar de descartarlo',
    dominio: 'alimentacion',
    rubros: ['gastronomia'],
    metrica: 'excedente recuperado',
    unidad: 'kg/semana',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['excedente', 'ultima hora', 'donamos lo que sobra', 'app de rescate'],
    porque:
      'Lo que sobra al cierre todavía está bueno. Venderlo con descuento en la última hora, o coordinarlo con una organización del barrio, lo saca del contenedor y suma clientes nuevos.',
    pasos: [
      'Pesar el excedente de una semana',
      'Elegir el canal: descuento de última hora, app de rescate o donación',
      'Probar 3 semanas',
      'Medir cuánto se recuperó',
    ],
    como_medir: 'Pesaje semanal del excedente recuperado vs descartado',
    evidencia_requerida: 'Registro de pesajes + fotos o comprobantes del canal',
    si_no_llegas: 'Un canal que funciona dos días por semana ya cambia el número. Cerralo con lo que sostuviste.',
    confianza: 'media',
  },
  {
    slug: 'envases-para-llevar',
    titulo_plantilla: 'Reemplazar los envases de {{producto}} por una alternativa mejor',
    dominio: 'residuos',
    rubros: ['gastronomia'],
    metrica: 'envases de un solo uso',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.3,
    efecto_max: 0.7,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['cambiamos los envases', 'envases compostables', 'packaging para llevar'],
    porque:
      'Los envases de un solo uso son lo más visible que entrega tu negocio y lo primero que el cliente asocia con cómo trabajás. Cambiarlos es un cambio real y además se ve.',
    pasos: [
      'Contar cuántos envases usás por mes y cuánto te cuestan',
      'Pedir muestras a 2 proveedores de alternativas',
      'Probar con un producto durante un mes',
      'Evaluar costo y respuesta de la gente',
      'Extender al resto',
    ],
    como_medir: 'Conteo de compras de envases en los remitos',
    evidencia_requerida: 'Remitos del antes y el después + foto del envase nuevo',
    si_no_llegas: 'Cambiar el envase de un producto y sostenerlo cuenta como avance real.',
    confianza: 'media',
    es_evento_unico: true,
    escalon_siguiente: 'envase-propio',
  },
  {
    slug: 'envase-propio',
    titulo_plantilla: 'Que el {{pct}}% de las ventas de mostrador use envase del cliente',
    dominio: 'residuos',
    rubros: ['gastronomia'],
    metrica: 'ventas con envase del cliente',
    unidad: '% de ventas',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.2,
    horizonte: 'semestral',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['envase propio', 'traer su taza', 'descuento por traer envase'],
    porque:
      'Es el paso que más cuesta porque depende de que la gente cambie un hábito, y por eso necesita un incentivo concreto y un cartel bien visible. Cuando prende, el efecto es permanente y no te cuesta nada.',
    pasos: [
      'Definir el incentivo (descuento fijo o un extra)',
      'Cartel visible en el mostrador, no en la puerta',
      'Que el personal lo ofrezca en cada venta durante el primer mes',
      'Registrar cuántas ventas lo usan',
      'Ajustar el incentivo si no llega',
    ],
    como_medir: 'Conteo diario en la caja',
    evidencia_requerida: 'Registro mensual + foto del cartel',
    si_no_llegas: 'Los hábitos de mostrador tardan. La mitad del porcentaje, sostenida, ya es un cambio.',
    confianza: 'baja',
  },
];

// ── Comercio minorista ───────────────────────────────────────────────────────

const COMERCIO: Palanca[] = [
  {
    slug: 'bolsas-reutilizables',
    titulo_plantilla: 'Bajar las bolsas de un solo uso que entregás',
    dominio: 'residuos',
    rubros: ['comercio-minorista'],
    metrica: 'bolsas de un solo uso',
    unidad: 'unidades/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'remito',
    alcance: 1,
    efecto_min: 0.4,
    efecto_max: 0.8,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['bolsas reutilizables', 'no damos bolsas', 'bolsa de tela'],
    porque:
      'La bolsa es lo último que el cliente se lleva y lo primero que tira. Preguntar antes de darla, y tener una reutilizable a la venta, baja el número sin que nadie se enoje.',
    pasos: [
      'Anotar cuántas bolsas comprás por mes, con los remitos',
      'Que el personal pregunte "¿necesitás bolsa?" antes de darla',
      'Tener una opción reutilizable a precio de costo en la caja',
      'Volver a mirar los remitos a los 2 meses',
    ],
    como_medir: 'Compras de bolsas en los remitos del proveedor',
    evidencia_requerida: 'Remitos del antes y el después',
    si_no_llegas: 'Si bajaste menos de lo previsto pero el hábito de preguntar quedó, cerralo con ese número.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'granel-basico',
  },
  {
    slug: 'granel-basico',
    titulo_plantilla: 'Sumar {{porcentaje}}% del surtido en venta a granel',
    dominio: 'consumo',
    rubros: ['comercio-minorista'],
    metrica: 'surtido disponible a granel',
    unidad: '% del surtido',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.2,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 5,
    inversion: 'media',
    requiere: ['presupuesto', 'espacio_fisico'],
    claves: ['granel', 'vendemos suelto', 'dispensers'],
    porque:
      'El granel saca el envase de la ecuación y deja que cada cliente lleve la cantidad que necesita. Es el cambio de más impacto del rubro, pero tiene trámite: el primer paso es averiguar qué te habilitan.',
    pasos: [
      'Averiguar qué exige bromatología en tu municipio para los productos que te interesan',
      'Elegir 3 productos de rotación alta para empezar',
      'Conseguir los dispensers y definir cómo se pesa y se etiqueta',
      'Probar 2 meses y medir qué porcentaje del surtido quedó a granel',
    ],
    como_medir: 'Conteo de SKU a granel sobre el total del surtido',
    evidencia_requerida: 'Foto de la zona de granel + planilla de productos',
    si_no_llegas: 'Con un producto a granel andando ya tenés el circuito probado. Cerralo con eso.',
    confianza: 'media',
  },
  {
    slug: 'origen-declarado',
    titulo_plantilla: 'Declarar el origen de {{porcentaje}}% de los productos',
    dominio: 'consumo',
    rubros: ['comercio-minorista'],
    metrica: 'productos con origen declarado',
    unidad: '% de productos',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['origen declarado', 'cartel de origen', 'de donde viene cada producto'],
    porque:
      'Decir de dónde viene cada cosa no cuesta plata y cambia la conversación con el cliente. Además es lo que te habilita a afirmar origen local en el Mercado de Brote, con evidencia.',
    pasos: [
      'Listar los productos que más vendés y pedirle el origen a cada proveedor',
      'Anotarlo en una planilla, con el dato de dónde sale',
      'Poner el origen en el cartel o la etiqueta de góndola',
      'Revisar el porcentaje cubierto a los 2 meses',
    ],
    como_medir: 'Porcentaje de productos con origen anotado, sobre la planilla',
    evidencia_requerida: 'Planilla de origen + foto de los carteles',
    si_no_llegas: 'Los productos que más vendés son los que importan. Con esos declarados, cerralo.',
    confianza: 'alta',
  },
  {
    slug: 'reparacion-y-repuestos',
    titulo_plantilla: 'Ofrecer reparación o repuestos de lo que vendés',
    dominio: 'consumo',
    rubros: ['comercio-minorista'],
    metrica: 'reparaciones y repuestos',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.2,
    horizonte: 'semestral',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 5,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['reparacion', 'repuestos', 'arreglamos lo que vendemos'],
    porque:
      'Lo que se puede arreglar no se reemplaza, y el que vuelve a arreglar vuelve a comprar. En rubros donde el producto se rompe, es la palanca de más impacto y la que más fideliza.',
    pasos: [
      'Elegir los 3 productos que más se rompen o más repuestos necesitan',
      'Definir si reparás vos o derivás a un taller de confianza',
      'Publicar el servicio en el local y en tus redes',
      'Registrar cada reparación o repuesto vendido',
    ],
    como_medir: 'Conteo mensual en una planilla propia',
    evidencia_requerida: 'Planilla de reparaciones + foto del cartel o publicación',
    si_no_llegas: 'Aunque sea derivando a un taller, el producto no termina en la basura. Cuenta.',
    confianza: 'media',
  },
];

// ── Producción de alimentos ──────────────────────────────────────────────────

const PRODUCCION_ALIMENTOS: Palanca[] = [
  {
    slug: 'medir-agua-proceso',
    titulo_plantilla: 'Medir el agua que usa el proceso de {{producto}}',
    dominio: 'agua',
    rubros: ['produccion-alimentos'],
    metrica: 'agua de proceso',
    unidad: 'litros/mes',
    metrica_tipo: 'medicion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['medimos el agua del proceso', 'litros por lote'],
    porque:
      'En producción de alimentos el agua se va en lavados y enjuagues que nadie cronometra. Medir por lote, aunque sea con un balde y un reloj, te dice dónde está el grueso antes de tocar nada.',
    pasos: [
      'Elegir el lavado o enjuague más frecuente del proceso',
      'Medir cuántos litros lleva una vez, con balde o caudalímetro',
      'Anotar cuántas veces se repite por día y por lote',
      'Registrar 3 meses y marcar el pico',
    ],
    como_medir: 'Planilla de litros por lote, con la medición de una vez por etapa',
    evidencia_requerida: 'Planilla de mediciones de 3 meses',
    si_no_llegas: 'Con la etapa principal medida ya se puede dimensionar el resto. Cerralo con esa.',
    confianza: 'alta',
    escalon_siguiente: 'recirculacion-lavado',
  },
  {
    slug: 'recirculacion-lavado',
    titulo_plantilla: 'Recircular o reutilizar el agua del lavado',
    dominio: 'agua',
    rubros: ['produccion-alimentos'],
    metrica: 'agua de proceso',
    unidad: 'litros/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.15,
    efecto_max: 0.4,
    horizonte: 'anual',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 5,
    inversion: 'media',
    requiere: ['presupuesto', 'agua_relevante'],
    claves: ['recirculamos el agua', 'reuso de agua de lavado'],
    porque:
      'El agua del último enjuague suele estar más limpia que la del primero. Reusarla aguas arriba, con el filtrado que corresponda, baja el consumo sin tocar la calidad del producto.',
    pasos: [
      'Marcar qué enjuagues terminan con agua todavía limpia',
      'Consultar con bromatología qué reúso está permitido para tu producto',
      'Pedir presupuesto de tanque y filtro para el circuito más simple',
      'Probar un mes midiendo litros y controlando calidad',
    ],
    como_medir: 'Litros por lote en la planilla, contra la línea de base',
    evidencia_requerida: 'Planilla del antes y el después + foto de la instalación',
    si_no_llegas: 'Si el reúso quedó en una sola etapa, cerralo con esa: es agua que ya no entra.',
    confianza: 'baja',
    es_evento_unico: true,
  },
  {
    slug: 'subproductos',
    titulo_plantilla: 'Encontrarle destino a {{producto}} en lugar de descartarlo',
    dominio: 'residuos',
    rubros: ['produccion-alimentos'],
    metrica: 'subproducto desviado',
    unidad: 'kg/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.5,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: [],
    claves: ['subproducto', 'destino a las cascaras', 'alimentacion animal'],
    porque:
      'Cáscaras, sueros y recortes suelen tener destino: alimentación animal, compostaje, o incluso otro producto. Encontrarle uso al subproducto baja el residuo y a veces abre una línea nueva.',
    pasos: [
      'Pesar los subproductos de un mes, separados por tipo',
      'Buscar quién los usa: productores de la zona, compostaje, otra industria',
      'Acordar frecuencia de retiro y condiciones',
      'Registrar los kilos que salen por ese camino',
    ],
    como_medir: 'Pesaje mensual de lo que se desvía',
    evidencia_requerida: 'Registro de pesajes + acuerdo o remito con quien lo recibe',
    si_no_llegas: 'Un subproducto con destino fijo ya es residuo que no generás. Cerralo con ese.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'packaging-secundario',
    titulo_plantilla: 'Bajar el cartón y el film del embalaje secundario',
    dominio: 'residuos',
    rubros: ['produccion-alimentos'],
    metrica: 'cartón y film de embalaje',
    unidad: 'kg/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['embalaje secundario', 'menos film', 'cajas retornables'],
    porque:
      'El embalaje secundario lo paga el que produce y lo tira el que recibe. Ajustar la medida de la caja, bajar vueltas de film o pasar a cajas retornables con tus clientes habituales se nota rápido en los remitos.',
    pasos: [
      'Anotar cuánto cartón y film comprás por mes',
      'Revisar si la caja está sobredimensionada para el producto',
      'Probar bajar vueltas de film en una ruta o cliente',
      'Proponer caja retornable a los clientes de entrega frecuente',
    ],
    como_medir: 'Compras de cartón y film en los remitos',
    evidencia_requerida: 'Remitos del antes y el después',
    si_no_llegas: 'Si solo funcionó con un cliente, cerralo con ese volumen: es real y es repetible.',
    confianza: 'media',
    es_evento_unico: true,
  },
];

// ── Indumentaria y textil ────────────────────────────────────────────────────

const INDUMENTARIA: Palanca[] = [
  {
    slug: 'retazos',
    titulo_plantilla: 'Desviar los retazos del residuo mixto',
    dominio: 'residuos',
    rubros: ['indumentaria-textil'],
    metrica: 'retazo desviado',
    unidad: 'kg/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.5,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['retazos', 'recortes de tela'],
    porque:
      'El retazo ocupa volumen y sale del taller como basura, pero hay quien lo usa: talleres de accesorios, escuelas de costura, relleno industrial. Separarlo cuesta una caja y un acuerdo.',
    pasos: [
      'Pesar los retazos de un mes',
      'Separar por tipo de tela, que es lo que define quién los usa',
      'Buscar taller, escuela o cooperativa que los reciba',
      'Registrar los kilos que salen por ese camino',
    ],
    como_medir: 'Pesaje mensual de lo que se entrega',
    evidencia_requerida: 'Registro de pesajes + acuerdo con quien lo recibe',
    si_no_llegas: 'Aunque sea un tipo de tela con destino fijo, cerralo: es residuo que ya no sale.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'arreglos',
  },
  {
    slug: 'fibra-y-origen',
    titulo_plantilla: 'Declarar fibra y origen en {{porcentaje}}% de las prendas',
    dominio: 'consumo',
    rubros: ['indumentaria-textil'],
    metrica: 'prendas con fibra y origen declarados',
    unidad: '% de prendas',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['composicion de la prenda', 'declaramos la fibra', 'origen de la tela'],
    porque:
      'Decir de qué está hecha una prenda y dónde se hizo es información que el cliente ya busca, y es lo que sostiene cualquier afirmación de material en el Mercado. Sin eso, "sustentable" es una palabra suelta.',
    pasos: [
      'Pedir a cada proveedor de tela la composición exacta y el origen',
      'Volcarlo en una planilla por modelo',
      'Sumarlo a la etiqueta y a la descripción de venta',
      'Medir qué porcentaje del catálogo quedó cubierto',
    ],
    como_medir: 'Porcentaje de modelos con ficha completa, sobre el total',
    evidencia_requerida: 'Planilla de composición + foto de una etiqueta nueva',
    si_no_llegas: 'La línea que más vendés es la que más se mira. Con esa declarada, cerralo.',
    confianza: 'alta',
  },
  {
    slug: 'stock-y-sobreproduccion',
    titulo_plantilla: 'Bajar el stock sin vender al cierre de temporada',
    dominio: 'consumo',
    rubros: ['indumentaria-textil'],
    metrica: 'prendas sin vender al cierre',
    unidad: 'unidades/temporada',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'anual',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: [],
    claves: ['sobreproduccion', 'series cortas', 'stock sin vender'],
    porque:
      'La prenda que no se vende es el mayor impacto ambiental del rubro, porque ya consumió agua, energía y trabajo. Producir series más chicas y reponer lo que se vende es mejor negocio y mejor huella.',
    pasos: [
      'Contar cuántas unidades quedaron sin vender la temporada pasada, por modelo',
      'Identificar los modelos que siempre sobran',
      'Cortar series más chicas de esos y dejar margen de reposición',
      'Volver a contar al cierre de la temporada siguiente',
    ],
    como_medir: 'Conteo de stock remanente al cierre, contra la temporada anterior',
    evidencia_requerida: 'Planilla de stock de las dos temporadas',
    si_no_llegas: 'Si el remanente bajó menos de lo previsto pero dejaste de cortar lo que sobraba, cuenta.',
    confianza: 'media',
  },
  {
    slug: 'arreglos',
    titulo_plantilla: 'Ofrecer arreglos de las prendas que vendés',
    dominio: 'consumo',
    rubros: ['indumentaria-textil'],
    metrica: 'prendas arregladas',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.2,
    horizonte: 'semestral',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 5,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['arreglos', 'taller de reparacion de prendas', 'servicio de costura'],
    porque:
      'Una prenda arreglada es una prenda que no se reemplaza, y el servicio trae de vuelta al cliente al local. Es el paso que convierte una marca de ropa en algo que dura.',
    pasos: [
      'Definir qué arreglos hacés y a qué precio',
      'Acordar con una costurera del barrio si no lo hacés adentro',
      'Ofrecerlo en cada venta y publicarlo en el local',
      'Registrar cada prenda que entra a arreglo',
    ],
    como_medir: 'Conteo mensual en la planilla de arreglos',
    evidencia_requerida: 'Planilla de arreglos + foto del cartel o publicación',
    si_no_llegas: 'Pocas prendas arregladas por mes, sostenidas, ya instalan el servicio. Cerralo con eso.',
    confianza: 'media',
  },
];

// ── Servicios profesionales y oficina ────────────────────────────────────────
// El rubro más difícil: el impacto directo es chico y no hay que inventar uno
// grande. Las palancas honestas son de consumo interno, digital y compras.

const SERVICIOS: Palanca[] = [
  {
    slug: 'papel-cero',
    titulo_plantilla: 'Bajar el consumo de papel de la oficina',
    dominio: 'consumo',
    rubros: ['servicios-profesionales'],
    metrica: 'papel',
    unidad: 'resmas/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'remito',
    alcance: 1,
    efecto_min: 0.3,
    efecto_max: 0.6,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['papel cero', 'firma digital', 'dejamos de imprimir'],
    porque:
      'En una oficina el papel es el consumo que se puede contar sin instrumentos: entra por remito. Doble faz por defecto y firma digital en lo que ya la admite bajan el número sin cambiar cómo trabajan.',
    pasos: [
      'Anotar cuántas resmas comprás por mes',
      'Poner doble faz como valor por defecto en las impresoras',
      'Listar qué documentos se pueden firmar digital y hacerlo',
      'Revisar los remitos a los 3 meses',
    ],
    como_medir: 'Compras de resmas en los remitos',
    evidencia_requerida: 'Remitos del antes y el después',
    si_no_llegas: 'Si bajaste menos pero el doble faz quedó puesto, el ahorro sigue el año que viene.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'compras-de-oficina',
  },
  {
    slug: 'higiene-digital',
    titulo_plantilla: 'Ordenar y bajar el almacenamiento en la nube',
    dominio: 'digital',
    rubros: ['servicios-profesionales'],
    metrica: 'almacenamiento en la nube',
    unidad: 'GB',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.3,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['higiene digital', 'limpiamos la nube', 'borramos archivos viejos'],
    porque:
      'El impacto de una oficina es chico y hay que ser honestos con eso. Pero el almacenamiento en la nube que nadie borra sí suma, y ordenarlo cuesta poco.',
    pasos: [
      'Anotar los GB usados hoy en cada servicio que pagás',
      'Borrar duplicados, versiones viejas y adjuntos que ya no se usan',
      'Definir qué se archiva y qué se borra, y cada cuánto',
      'Volver a anotar los GB a los 3 meses',
    ],
    como_medir: 'El panel de uso de cada servicio, anotado en una planilla',
    evidencia_requerida: 'Captura del uso del antes y el después',
    si_no_llegas: 'Con la regla de archivado escrita y aplicada una vez, el orden se sostiene solo.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'compras-de-oficina',
    titulo_plantilla: 'Poner criterio ambiental en {{porcentaje}}% de las compras de oficina',
    dominio: 'consumo',
    rubros: ['servicios-profesionales'],
    metrica: 'insumos con criterio ambiental',
    unidad: '% de compras',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['compras con criterio', 'proveedores de oficina', 'compra responsable'],
    porque:
      'Una oficina casi no produce impacto propio, pero sí decide el de lo que compra. Elegir papel reciclado, cartuchos recargados y limpieza a granel mueve la aguja donde realmente está.',
    pasos: [
      'Listar los 10 insumos que más comprás',
      'Marcar cuáles tienen alternativa con criterio ambiental verificable',
      'Pedir precio de esas alternativas a tu proveedor actual',
      'Cambiar los que no encarecen y medir el porcentaje cubierto',
    ],
    como_medir: 'Porcentaje sobre el gasto mensual de insumos, con los remitos',
    evidencia_requerida: 'Planilla de compras del antes y el después',
    si_no_llegas: 'Tres insumos cambiados y sostenidos valen más que una política escrita. Cerralo con esos.',
    confianza: 'media',
  },
  {
    slug: 'movilidad-equipo',
    titulo_plantilla: 'Subir los viajes del equipo en transporte público, bici o a pie',
    dominio: 'movilidad',
    rubros: ['servicios-profesionales'],
    metrica: 'viajes sin auto particular',
    unidad: '% de viajes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: ['equipo_5'],
    claves: ['movilidad del equipo', 'vienen en bici', 'transporte publico'],
    porque:
      'En una oficina el viaje diario del equipo suele ser el impacto más grande, y es el único que no aparece en ninguna factura. Medirlo una semana ya cambia la conversación.',
    pasos: [
      'Preguntar una semana cómo viene cada persona, sin nombres',
      'Anotar el porcentaje de viajes en auto particular',
      'Sacar la traba más común: estacionamiento de bici, horario flexible, un día remoto',
      'Volver a preguntar a los 3 meses',
    ],
    como_medir: 'Encuesta interna de una semana, dos veces al año',
    evidencia_requerida: 'Planilla con las dos mediciones',
    si_no_llegas: 'Un solo cambio de modo por persona por semana ya mueve el porcentaje. Cuenta igual.',
    confianza: 'baja',
  },
];

// ── Belleza y cuidado personal ───────────────────────────────────────────────

const BELLEZA: Palanca[] = [
  {
    slug: 'composicion-declarada',
    titulo_plantilla: 'Tener la composición completa a la vista en {{porcentaje}}% de los productos',
    dominio: 'consumo',
    rubros: ['belleza-cuidado-personal'],
    metrica: 'productos con composición a la vista',
    unidad: '% de productos',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['composicion declarada', 'ingredientes a la vista', 'inci'],
    porque:
      'En cosmética la composición es lo que el cliente quiere leer y casi nadie muestra completo. Tenerla a la vista es gratis y es lo que sostiene cualquier afirmación de "libre de" en el Mercado, con el sustituto declarado.',
    pasos: [
      'Pedir a cada proveedor la composición completa de lo que vendés o usás',
      'Volcarla a una planilla por producto',
      'Publicarla en la etiqueta, la vidriera o la ficha de venta',
      'Medir qué porcentaje del catálogo quedó cubierto',
    ],
    como_medir: 'Porcentaje de productos con composición publicada, sobre el total',
    evidencia_requerida: 'Planilla de composiciones + foto de una ficha publicada',
    si_no_llegas: 'Los productos estrella son los que más se preguntan. Con esos cubiertos, cerralo.',
    confianza: 'alta',
  },
  {
    slug: 'agua-en-lavado',
    titulo_plantilla: 'Bajar el agua por lavado de cabeza',
    dominio: 'agua',
    rubros: ['belleza-cuidado-personal'],
    metrica: 'agua por servicio',
    unidad: 'litros/servicio',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.15,
    efecto_max: 0.3,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['aireadores', 'agua en el lavado', 'cabezal de bajo caudal'],
    porque:
      'El lavado es donde se va casi toda el agua de un salón, y el caudal del cabezal casi nunca se eligió: vino con la bacha. Un cabezal de bajo caudal cambia el número sin que el cliente note nada.',
    pasos: [
      'Medir cuántos litros salen del cabezal en un minuto, con un balde',
      'Multiplicar por el tiempo promedio de un lavado',
      'Cambiar el cabezal o poner aireador y volver a medir',
      'Anotar litros por servicio durante un mes',
    ],
    como_medir: 'Medición de caudal con balde y reloj, por servicio típico',
    evidencia_requerida: 'Planilla de mediciones + factura del cabezal',
    si_no_llegas: 'Si el caudal bajó menos de lo previsto, cerralo con la medición real: el dato ya es tuyo.',
    confianza: 'media',
    es_evento_unico: true,
    escalon_siguiente: 'envases-retorno',
  },
  {
    slug: 'envases-retorno',
    titulo_plantilla: 'Que vuelvan {{porcentaje}}% de los envases que entregás',
    dominio: 'residuos',
    rubros: ['belleza-cuidado-personal'],
    metrica: 'envases retornados',
    unidad: '% de envases',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.3,
    horizonte: 'semestral',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 4,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['retorno de envases', 'recarga', 'devolucion de frascos'],
    porque:
      'El envase de cosmética es caro de producir y el cliente lo tira lleno de culpa. Un sistema de retorno con incentivo lo transforma en una razón para volver al local.',
    pasos: [
      'Definir qué envases aceptás de vuelta y cómo los higienizás',
      'Fijar el incentivo: descuento en la recarga o crédito',
      'Contar cuántos envases entregás por mes para tener la base',
      'Registrar los que vuelven y ajustar el incentivo a los 2 meses',
    ],
    como_medir: 'Conteo en el local: entregados contra devueltos',
    evidencia_requerida: 'Planilla mensual + foto del punto de retorno',
    si_no_llegas: 'El retorno arranca lento siempre. Con el circuito probado y gente usándolo, cerralo.',
    confianza: 'baja',
    es_evento_unico: true,
  },
  {
    slug: 'toallas-y-descartables',
    titulo_plantilla: 'Reemplazar los descartables del salón por reutilizables',
    dominio: 'residuos',
    rubros: ['belleza-cuidado-personal'],
    metrica: 'descartables usados',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.5,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['toallas reutilizables', 'dejamos los descartables', 'capas de tela'],
    porque:
      'Toallas de papel, capas y guantes descartables salen todos los días por la puerta como residuo. Pasar a tela lavable se paga en pocos meses y baja el volumen de un saque.',
    pasos: [
      'Anotar cuántos descartables comprás por mes, con los remitos',
      'Elegir cuál reemplazar primero según volumen y costo de lavado',
      'Comprar el juego de reutilizables y definir la rutina de lavado',
      'Revisar los remitos a los 2 meses',
    ],
    como_medir: 'Compras de descartables en los remitos',
    evidencia_requerida: 'Remitos del antes y el después + foto de los reutilizables',
    si_no_llegas: 'Con un descartable reemplazado y la rutina de lavado andando, cerralo.',
    confianza: 'alta',
    es_evento_unico: true,
  },
];

// ── Logística y transporte ───────────────────────────────────────────────────

const LOGISTICA: Palanca[] = [
  {
    slug: 'medir-combustible',
    titulo_plantilla: 'Medir el consumo de combustible de la flota',
    dominio: 'movilidad',
    rubros: ['logistica-transporte'],
    metrica: 'combustible',
    unidad: 'litros/100 km',
    metrica_tipo: 'medicion',
    metodo_tipo: 'factura',
    alcance: 1,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: ['flota'],
    claves: ['medimos el combustible', 'litros cada 100', 'planilla de cargas'],
    porque:
      'Sin litros por cada 100 km no hay forma de saber si una ruta nueva, un vehículo o un chofer mejoran algo. Se arma con los tickets de carga y el odómetro, que ya tenés.',
    pasos: [
      'Anotar kilómetros y litros en cada carga, por vehículo',
      'Calcular litros cada 100 km al cierre de cada mes',
      'Registrar 3 meses',
      'Marcar el vehículo o la ruta con peor número',
    ],
    como_medir: 'Tickets de carga y odómetro, en una planilla por vehículo',
    evidencia_requerida: 'Planilla de 3 meses + tickets de carga',
    si_no_llegas: 'Con el vehículo que más rueda medido ya tenés la referencia. Cerralo con ese.',
    confianza: 'alta',
    escalon_siguiente: 'optimizacion-rutas',
  },
  {
    slug: 'optimizacion-rutas',
    titulo_plantilla: 'Bajar los kilómetros por entrega ordenando las rutas',
    dominio: 'movilidad',
    rubros: ['logistica-transporte'],
    metrica: 'kilómetros por entrega',
    unidad: 'km/entrega',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.05,
    efecto_max: 0.15,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: ['flota'],
    claves: ['optimizacion de rutas', 'agrupamos entregas por zona'],
    porque:
      'La mayoría de las rutas se arman por orden de pedido, no por geografía. Agrupar por zona y fijar días por área baja kilómetros, combustible y horas de chofer al mismo tiempo.',
    pasos: [
      'Registrar kilómetros y entregas por viaje durante un mes',
      'Agrupar los destinos por zona y asignarles día fijo',
      'Probar el esquema nuevo un mes completo',
      'Comparar kilómetros por entrega',
    ],
    como_medir: 'Kilómetros del odómetro divididos por entregas hechas, en planilla',
    evidencia_requerida: 'Planilla de rutas del antes y el después',
    si_no_llegas: 'Una zona ordenada ya baja el promedio. Cerralo con el número que te dio.',
    confianza: 'media',
    es_evento_unico: true,
    escalon_siguiente: 'carga-consolidada',
  },
  {
    slug: 'carga-consolidada',
    titulo_plantilla: 'Subir las entregas por viaje consolidando la carga',
    dominio: 'movilidad',
    rubros: ['logistica-transporte'],
    metrica: 'entregas por viaje',
    unidad: 'entregas/viaje',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.2,
    horizonte: 'anual',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 5,
    inversion: 'ninguna',
    requiere: ['flota'],
    claves: ['carga consolidada', 'viajes completos', 'consolidamos'],
    porque:
      'Un camión a media carga gasta casi lo mismo que uno lleno. Consolidar pedidos chicos, aunque sea esperando un día, es la palanca de más impacto del rubro y no requiere invertir nada.',
    pasos: [
      'Medir el porcentaje de ocupación promedio de los viajes de un mes',
      'Definir qué pedidos pueden esperar 24 o 48 horas sin afectar al cliente',
      'Fijar cortes de salida por zona y avisarlos',
      'Comparar entregas por viaje al mes siguiente',
    ],
    como_medir: 'Entregas y viajes de la planilla mensual',
    evidencia_requerida: 'Planilla de viajes del antes y el después',
    si_no_llegas: 'Consolidar solo los pedidos de una zona ya sube el promedio. Cuenta como avance.',
    confianza: 'media',
  },
  {
    slug: 'mantenimiento-preventivo',
    titulo_plantilla: 'Poner al día el mantenimiento de la flota',
    dominio: 'movilidad',
    rubros: ['logistica-transporte'],
    metrica: 'combustible',
    unidad: 'litros/100 km',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'factura',
    alcance: 1,
    efecto_min: 0.03,
    efecto_max: 0.08,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'baja',
    requiere: ['flota', 'presupuesto'],
    claves: ['mantenimiento preventivo', 'presion de neumaticos', 'service al dia'],
    porque:
      'Presión de neumáticos, filtros y puesta a punto no son una campaña ambiental: es mantenimiento común que casi nadie hace a tiempo y que se paga solo en combustible.',
    pasos: [
      'Armar la ficha de cada vehículo con su último service',
      'Fijar control de presión cada 15 días, con planilla en el taller',
      'Poner al día filtros y bujías de los que están atrasados',
      'Comparar litros cada 100 km a los 2 meses',
    ],
    como_medir: 'Litros cada 100 km de la planilla de cargas',
    evidencia_requerida: 'Fichas de service + planilla de consumo del antes y el después',
    si_no_llegas: 'El control de presión sostenido ya evita consumo de más. Cerralo con eso.',
    confianza: 'media',
  },
];

// ── Hotelería y turismo ──────────────────────────────────────────────────────

const HOTELERIA: Palanca[] = [
  {
    slug: 'medir-consumos-por-huesped',
    titulo_plantilla: 'Medir energía y agua por noche ocupada',
    dominio: 'energia',
    rubros: ['hoteleria-turismo'],
    metrica: 'consumo por noche ocupada',
    unidad: 'kWh/noche',
    metrica_tipo: 'medicion',
    metodo_tipo: 'factura',
    alcance: 2,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['consumo por noche', 'por huesped', 'medimos por ocupacion'],
    porque:
      'Medir por noche ocupada y no por mes es lo que te deja comparar temporada alta con baja. Sin eso, cualquier número engaña.',
    pasos: [
      'Anotar kWh y litros de cada factura',
      'Anotar las noches ocupadas del mismo período',
      'Dividir y registrar el valor por noche',
      'Registrar 3 meses y comparar alta contra baja',
    ],
    como_medir: 'Facturas de luz y agua divididas por noches ocupadas del período',
    evidencia_requerida: 'Planilla de 3 meses + facturas',
    si_no_llegas: 'Con dos períodos calculados ya podés comparar. Cerralo con esos.',
    confianza: 'alta',
    escalon_siguiente: 'cambio-de-blanco',
  },
  {
    slug: 'cambio-de-blanco',
    titulo_plantilla: 'Cambiar la frecuencia de lavado de blancos',
    dominio: 'agua',
    rubros: ['hoteleria-turismo'],
    metrica: 'agua y detergente de lavadero',
    unidad: 'litros/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.15,
    efecto_max: 0.3,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['cambio de sabanas', 'blancos', 'cartel de toallas'],
    porque:
      'Cambiar sábanas y toallas todos los días es una costumbre de hotelería, no un pedido del huésped. Ofrecer el cambio a demanda, bien explicado en la habitación, baja agua, detergente y horas de lavadero.',
    pasos: [
      'Contar cargas de lavado por semana durante un mes',
      'Poner un cartel claro en la habitación con la opción de no cambiar',
      'Capacitar a mucamas en el criterio nuevo',
      'Volver a contar cargas al mes siguiente',
    ],
    como_medir: 'Conteo de cargas de lavado, en planilla del lavadero',
    evidencia_requerida: 'Planilla de cargas del antes y el después + foto del cartel',
    si_no_llegas: 'Si solo prendió en estadías largas, cerralo con ese número: es el que más pesa.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'amenities-a-granel',
    titulo_plantilla: 'Pasar los amenities a dispensers recargables',
    dominio: 'residuos',
    rubros: ['hoteleria-turismo'],
    metrica: 'envases chicos de amenities',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 1,
    efecto_min: 0.6,
    efecto_max: 0.9,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['amenities a granel', 'dispensers', 'sacamos los pomitos'],
    porque:
      'Los pomitos chicos son el residuo más visible de una habitación y el que más caro sale por mililitro. Los dispensers fijos se amortizan en meses y el huésped no los extraña.',
    pasos: [
      'Contar cuántos envases chicos comprás por mes',
      'Elegir dispensers con cierre y definir quién los recarga',
      'Probar en una planta o tipo de habitación',
      'Extender y revisar los remitos a los 3 meses',
    ],
    como_medir: 'Compras de amenities en los remitos',
    evidencia_requerida: 'Remitos del antes y el después + foto del dispenser instalado',
    si_no_llegas: 'Si quedó en una parte de las habitaciones, cerralo con ese alcance y seguí después.',
    confianza: 'alta',
    es_evento_unico: true,
  },
  {
    slug: 'desayuno-local',
    titulo_plantilla: 'Subir el porcentaje de desayuno de origen local',
    dominio: 'alimentacion',
    rubros: ['hoteleria-turismo'],
    metrica: 'productos de desayuno de origen local',
    unidad: '% del desayuno',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: ['puede_cambiar_proveedores'],
    claves: ['desayuno local', 'productores de la zona', 'producto regional'],
    porque:
      'El desayuno es lo que el huésped recuerda y lo único que consume todos los días. Comprarlo cerca baja transporte, mejora el producto y te da algo concreto para contar de la zona.',
    pasos: [
      'Listar los productos del desayuno y su origen actual',
      'Buscar productores de la zona para los 3 de más volumen',
      'Probar uno por mes y medir costo y respuesta del huésped',
      'Calcular el porcentaje local sobre el gasto de desayuno',
    ],
    como_medir: 'Porcentaje del gasto mensual de desayuno, con los remitos',
    evidencia_requerida: 'Planilla de proveedores del antes y el después',
    si_no_llegas: 'Dos productos locales sostenidos ya cambian el desayuno. Cerralo con esos.',
    confianza: 'media',
  },
];

// ── Agro, vivero y huerta ────────────────────────────────────────────────────

const AGRO: Palanca[] = [
  {
    slug: 'riego-medido',
    titulo_plantilla: 'Medir y ajustar el riego',
    dominio: 'agua',
    rubros: ['agro-vivero-huerta'],
    metrica: 'agua de riego',
    unidad: 'litros/mes',
    metrica_tipo: 'medicion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['medimos el riego', 'litros de riego', 'horario de riego'],
    porque:
      'El riego se define por costumbre y por clima, casi nunca por medición. Anotar cuántos litros y a qué hora regás durante una temporada es lo que después permite bajar sin arriesgar plantas.',
    pasos: [
      'Medir el caudal de la manguera o el gotero en un minuto',
      'Anotar minutos de riego por sector y por día',
      'Registrar una temporada completa',
      'Marcar los sectores de mayor consumo',
    ],
    como_medir: 'Caudal medido con balde, por minutos de riego anotados',
    evidencia_requerida: 'Planilla de riego de la temporada',
    si_no_llegas: 'Con el sector más grande medido ya tenés la referencia. Cerralo con ese.',
    confianza: 'alta',
    escalon_siguiente: 'riego-eficiente',
  },
  {
    slug: 'riego-eficiente',
    titulo_plantilla: 'Bajar el agua de riego sin perder producción',
    dominio: 'agua',
    rubros: ['agro-vivero-huerta'],
    metrica: 'agua de riego',
    unidad: 'litros/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['riego por goteo', 'mulching', 'regamos temprano'],
    porque:
      'Regar de noche o temprano, con goteo y con cobertura sobre la tierra, evita que el agua se evapore antes de llegar a la raíz. Es el mismo riego con menos pérdida, no menos planta.',
    pasos: [
      'Pasar el riego al horario de menor evaporación',
      'Poner cobertura vegetal sobre la tierra en los sectores de más sol',
      'Cambiar a goteo el sector de más consumo',
      'Comparar litros contra la temporada anterior',
    ],
    como_medir: 'Planilla de riego, contra la línea de base de la temporada previa',
    evidencia_requerida: 'Planilla del antes y el después + foto de la instalación',
    si_no_llegas: 'Cambiar el horario y sostenerlo ya baja el consumo. Cerralo con lo medido.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'compost-propio',
    titulo_plantilla: 'Hacer compost con el resto vegetal propio',
    dominio: 'aire_suelo',
    rubros: ['agro-vivero-huerta'],
    metrica: 'resto vegetal compostado',
    unidad: 'kg/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.3,
    efecto_max: 0.7,
    horizonte: 'semestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['compostamos', 'compost propio', 'pila de compost'],
    porque:
      'El resto de poda y de plantas descartadas es materia orgánica que ya tenés y que después comprás en bolsa como sustrato. Compostarlo cierra el círculo adentro del vivero.',
    pasos: [
      'Pesar el resto vegetal de un mes',
      'Armar la pila o cajón en un sector con sombra y acceso de agua',
      'Definir quién voltea y cada cuánto',
      'Pesar lo que entra a la pila cada mes',
    ],
    como_medir: 'Pesaje mensual de lo que entra al compost',
    evidencia_requerida: 'Registro de pesajes + foto de la compostera',
    si_no_llegas: 'Con la compostera andando y cargándose, el ciclo ya está armado. Cerralo.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'sustrato-propio',
  },
  {
    slug: 'sustrato-propio',
    titulo_plantilla: 'Reemplazar parte del sustrato comprado por compost propio',
    dominio: 'aire_suelo',
    rubros: ['agro-vivero-huerta'],
    metrica: 'sustrato comprado',
    unidad: '% de sustrato',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'anual',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 4,
    inversion: 'ninguna',
    requiere: [],
    claves: ['sustrato propio', 'dejamos de comprar tierra', 'turba'],
    porque:
      'El sustrato comprado suele traer turba, que se extrae de humedales que tardan siglos en formarse. Reemplazar aunque sea una parte con compost propio baja costo y saca turba del circuito.',
    pasos: [
      'Anotar cuántas bolsas de sustrato comprás por mes',
      'Probar mezclas con compost propio en un lote de plantas',
      'Comparar crecimiento y sanidad a los 2 meses',
      'Extender la mezcla y revisar los remitos',
    ],
    como_medir: 'Compras de sustrato en los remitos, contra la línea de base',
    evidencia_requerida: 'Remitos del antes y el después + registro de la prueba',
    si_no_llegas: 'Si la mezcla funcionó en una línea de plantas, cerralo con esa: ya está probada.',
    confianza: 'media',
  },
];

// ── Limpieza e higiene ───────────────────────────────────────────────────────

const LIMPIEZA: Palanca[] = [
  {
    slug: 'dosificacion-limpieza',
    titulo_plantilla: 'Dosificar los productos de limpieza con medida',
    dominio: 'agua_azul',
    rubros: ['limpieza-higiene'],
    metrica: 'producto de limpieza',
    unidad: 'litros/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'remito',
    alcance: 1,
    efecto_min: 0.15,
    efecto_max: 0.35,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['dosificacion', 'dosificamos', 'medida de producto'],
    porque:
      'Casi todo el producto de limpieza se usa de más porque se sirve a ojo. Un dosificador y una tabla de diluciones pegada en el carro bajan el consumo y el vertido, sin cambiar el resultado.',
    pasos: [
      'Anotar cuántos litros de cada producto comprás por mes',
      'Poner dosificador o medida en cada bidón',
      'Pegar la tabla de diluciones donde se prepara',
      'Revisar los remitos a los 2 meses',
    ],
    como_medir: 'Compras de producto en los remitos',
    evidencia_requerida: 'Remitos del antes y el después + foto de la tabla de diluciones',
    si_no_llegas: 'Con la dosificación instalada en el equipo, el ahorro sigue apareciendo solo.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'concentrados-recarga',
  },
  {
    slug: 'concentrados-recarga',
    titulo_plantilla: 'Pasar a concentrados y recarga de envases',
    dominio: 'residuos',
    rubros: ['limpieza-higiene'],
    metrica: 'envases plásticos comprados',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.3,
    efecto_max: 0.7,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['concentrados', 'recarga de envases', 'compramos a granel'],
    porque:
      'Comprar producto ya diluido es pagar y transportar agua en botellas nuevas. Los concentrados con envase que se recarga bajan plástico, flete y costo por uso al mismo tiempo.',
    pasos: [
      'Pedir a tu proveedor la versión concentrada de lo que más usás',
      'Definir estación de recarga y rotulado',
      'Capacitar al equipo en la dilución correcta',
      'Contar envases comprados a los 3 meses',
    ],
    como_medir: 'Conteo de envases comprados en los remitos',
    evidencia_requerida: 'Remitos del antes y el después + foto de la estación de recarga',
    si_no_llegas: 'Con un producto pasado a concentrado ya bajan los envases. Cerralo con ese.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'fichas-de-seguridad',
    titulo_plantilla: 'Tener a la vista la composición y la ficha de cada producto',
    dominio: 'consumo',
    rubros: ['limpieza-higiene'],
    metrica: 'productos con ficha completa',
    unidad: '% de productos',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 2,
    inversion: 'ninguna',
    requiere: [],
    claves: ['ficha tecnica', 'hoja de seguridad', 'composicion de los productos'],
    porque:
      'La ficha técnica y la hoja de seguridad ya existen: te las tiene que dar el proveedor. Tenerlas ordenadas protege al equipo y es lo único que sostiene una afirmación de "libre de" con el sustituto declarado.',
    pasos: [
      'Pedir ficha técnica y hoja de seguridad de cada producto que usás o vendés',
      'Archivarlas juntas, en papel o digital',
      'Anotar en una planilla qué tiene cada una y qué falta',
      'Reclamar las que falten y medir el porcentaje cubierto',
    ],
    como_medir: 'Porcentaje de productos con ficha archivada, sobre el total',
    evidencia_requerida: 'Planilla de fichas + una ficha de ejemplo',
    si_no_llegas: 'Los productos de uso diario son los que importan. Con esos cubiertos, cerralo.',
    confianza: 'alta',
  },
  {
    slug: 'microfibra-y-agua',
    titulo_plantilla: 'Bajar el agua de la limpieza con método de doble balde',
    dominio: 'agua',
    rubros: ['limpieza-higiene'],
    metrica: 'agua de limpieza',
    unidad: 'litros/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'planilla',
    alcance: 1,
    efecto_min: 0.1,
    efecto_max: 0.3,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['doble balde', 'microfibra', 'menos agua en limpieza'],
    porque:
      'El doble balde y los paños de microfibra limpian igual con menos agua y menos producto, y además se cambia menos seguido el agua sucia. Es método, no tecnología.',
    pasos: [
      'Medir cuántos baldes de agua se usan por jornada',
      'Comprar el juego de microfibra y los baldes',
      'Capacitar al equipo en el método',
      'Volver a contar baldes al mes siguiente',
    ],
    como_medir: 'Conteo de baldes por jornada, en planilla',
    evidencia_requerida: 'Planilla del antes y el después + factura de los materiales',
    si_no_llegas: 'Si el método quedó en una parte del equipo, cerralo con esa: ya está probado.',
    confianza: 'media',
    es_evento_unico: true,
  },
];

// ── Hogar, muebles y construcción ────────────────────────────────────────────

const HOGAR: Palanca[] = [
  {
    slug: 'separacion-obra',
    titulo_plantilla: 'Separar los escombros y restos de obra',
    dominio: 'residuos',
    rubros: ['hogar-construccion'],
    metrica: 'residuo de obra mezclado',
    unidad: 'm3/mes',
    metrica_tipo: 'reduccion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.5,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['separacion de obra', 'escombro separado', 'volquete'],
    porque:
      'El volquete mezclado va entero a disposición final y se paga por volumen. Separar escombro limpio, metal y madera baja lo que pagás y manda a reúso lo que sirve.',
    pasos: [
      'Contar volquetes o metros cúbicos que sacás por mes',
      'Definir sectores de acopio para escombro, metal y madera',
      'Acordar con quien retira cada material',
      'Volver a contar al mes siguiente',
    ],
    como_medir: 'Conteo de volquetes retirados, en planilla',
    evidencia_requerida: 'Planilla de retiros + fotos de los sectores de acopio',
    si_no_llegas: 'Separar el metal solo ya baja volumen y a veces se cobra. Cerralo con eso.',
    confianza: 'alta',
    es_evento_unico: true,
    escalon_siguiente: 'madera-certificada',
  },
  {
    slug: 'madera-certificada',
    titulo_plantilla: 'Pasar {{porcentaje}}% de la madera a origen declarado o certificado',
    dominio: 'aire_suelo',
    rubros: ['hogar-construccion'],
    metrica: 'madera con origen declarado',
    unidad: '% de compras',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: ['puede_cambiar_proveedores'],
    claves: ['madera certificada', 'origen de la madera', 'fsc'],
    porque:
      'La madera es el insumo del rubro donde el origen cambia todo, y el dato lo tiene el proveedor: hay que pedirlo. Con el certificado en mano podés afirmarlo en el Mercado; sin él, no.',
    pasos: [
      'Pedir a cada proveedor de madera el origen y el certificado si lo tiene',
      'Anotarlo por compra en una planilla',
      'Priorizar proveedores con documentación para lo que más usás',
      'Calcular el porcentaje sobre el gasto en madera',
    ],
    como_medir: 'Porcentaje del gasto en madera con documentación, en los remitos',
    evidencia_requerida: 'Planilla de compras + un certificado de ejemplo',
    si_no_llegas: 'Con el proveedor principal documentado, cerralo: es la mayor parte del volumen.',
    confianza: 'media',
  },
  {
    slug: 'recortes-taller',
    titulo_plantilla: 'Aprovechar los recortes del taller',
    dominio: 'residuos',
    rubros: ['hogar-construccion'],
    metrica: 'recorte descartado',
    unidad: 'kg/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.4,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['recortes', 'retazos de madera', 'aprovechamiento de placa'],
    porque:
      'El recorte es material que ya pagaste y que se va como basura. Optimizar el despiece y guardar los recortes útiles baja compra y residuo, y a veces se convierte en una línea chica de productos.',
    pasos: [
      'Pesar el recorte descartado de un mes',
      'Revisar el despiece de los trabajos más frecuentes',
      'Armar un sector de recortes útiles, ordenado por medida',
      'Volver a pesar a los 2 meses',
    ],
    como_medir: 'Pesaje mensual del recorte que se descarta',
    evidencia_requerida: 'Registro de pesajes + foto del sector de recortes',
    si_no_llegas: 'Si el despiece mejoró en un tipo de trabajo, cerralo con ese: se repite solo.',
    confianza: 'media',
    es_evento_unico: true,
  },
  {
    slug: 'pinturas-y-solventes',
    titulo_plantilla: 'Cambiar pinturas y solventes por opciones de base agua',
    dominio: 'aire_suelo',
    rubros: ['hogar-construccion'],
    metrica: 'productos con solvente',
    unidad: '% de compras',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'remito',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.5,
    horizonte: 'semestral',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 3,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['base agua', 'sin solventes', 'pintura al agua'],
    porque:
      'Los solventes se evaporan adentro del taller y los respira tu equipo antes que nadie. Las opciones de base agua avanzaron mucho en terminación, y el cambio se nota primero en el aire del lugar.',
    pasos: [
      'Listar qué pinturas y solventes comprás y en qué volumen',
      'Pedir muestras de base agua para los usos más frecuentes',
      'Probar en un trabajo y comparar terminación y tiempos',
      'Calcular el porcentaje cambiado sobre las compras',
    ],
    como_medir: 'Porcentaje de compras sin solvente, en los remitos',
    evidencia_requerida: 'Remitos del antes y el después + registro de la prueba',
    si_no_llegas: 'Si la base agua funcionó para un uso, cerralo con ese: el resto llega después.',
    confianza: 'baja',
    es_evento_unico: true,
  },
];

// ── Reparación, reuso y reciclaje ────────────────────────────────────────────

const REPARACION: Palanca[] = [
  {
    slug: 'medir-reparaciones',
    titulo_plantilla: 'Registrar cuántas unidades vuelven a funcionar',
    dominio: 'consumo',
    rubros: ['reparacion-reuso'],
    metrica: 'unidades reparadas',
    unidad: 'unidades/mes',
    metrica_tipo: 'medicion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0,
    efecto_max: 0,
    horizonte: 'trimestral',
    ambicion: 'basico',
    esfuerzo_horas_mes: 1,
    inversion: 'ninguna',
    requiere: [],
    claves: ['registramos las reparaciones', 'planilla de reparaciones'],
    porque:
      'Tu impacto es cada cosa que no se tiró, pero si no lo contás no lo podés mostrar ni mejorarlo. Una planilla de entradas y salidas es toda la medición que necesita el rubro.',
    pasos: [
      'Anotar cada equipo que entra, qué se le hizo y si salió funcionando',
      'Separar reparado de irreparable',
      'Registrar 3 meses',
      'Calcular el porcentaje que vuelve a funcionar',
    ],
    como_medir: 'Planilla de ingresos y egresos del taller',
    evidencia_requerida: 'Planilla de 3 meses',
    si_no_llegas: 'Con dos meses registrados ya tenés el número. Cerralo con eso.',
    confianza: 'alta',
    escalon_siguiente: 'tasa-de-reparacion',
  },
  {
    slug: 'tasa-de-reparacion',
    titulo_plantilla: 'Subir el porcentaje de equipos que se reparan',
    dominio: 'consumo',
    rubros: ['reparacion-reuso'],
    metrica: 'equipos reparados sobre ingresados',
    unidad: '% de equipos',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'planilla',
    alcance: 3,
    efecto_min: 0.1,
    efecto_max: 0.25,
    horizonte: 'semestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 4,
    inversion: 'baja',
    requiere: ['presupuesto'],
    claves: ['tasa de reparacion', 'mas equipos reparados'],
    porque:
      'Lo que hoy se declara irreparable suele serlo por falta de un repuesto puntual o de tiempo de diagnóstico. Atacar las dos o tres fallas más comunes sube la tasa sin cambiar el taller.',
    pasos: [
      'Mirar la planilla y listar por qué se declara irreparable',
      'Elegir las 3 causas más frecuentes',
      'Conseguir stock mínimo de esos repuestos o un proveedor rápido',
      'Comparar la tasa a los 3 meses',
    ],
    como_medir: 'Porcentaje reparados sobre ingresados, en la planilla',
    evidencia_requerida: 'Planilla del antes y el después',
    si_no_llegas: 'Resolver una sola causa frecuente ya mueve la tasa. Cerralo con ese avance.',
    confianza: 'media',
  },
  {
    slug: 'repuestos-recuperados',
    titulo_plantilla: 'Recuperar repuestos de lo que no tiene arreglo',
    dominio: 'residuos',
    rubros: ['reparacion-reuso'],
    metrica: 'repuestos recuperados',
    unidad: 'unidades/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'conteo',
    alcance: 1,
    efecto_min: 0.2,
    efecto_max: 0.5,
    horizonte: 'trimestral',
    ambicion: 'intermedio',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['recuperamos repuestos', 'canibalizamos', 'stock de usados'],
    porque:
      'El equipo que no tiene arreglo sigue teniendo partes buenas. Desarmarlo y ordenar esas partes te da repuestos sin comprar y saca del residuo lo que todavía sirve.',
    pasos: [
      'Definir qué partes vale la pena recuperar de cada tipo de equipo',
      'Armar un sector de repuestos usados, etiquetado',
      'Anotar cada parte que entra y cada una que se usa',
      'Contar cuántas reparaciones se resolvieron con repuestos recuperados',
    ],
    como_medir: 'Conteo mensual en la planilla de repuestos',
    evidencia_requerida: 'Planilla de repuestos + foto del sector ordenado',
    si_no_llegas: 'Aunque sea un tipo de repuesto recuperado y usado, cerralo: el circuito quedó.',
    confianza: 'alta',
    es_evento_unico: true,
  },
  {
    slug: 'disposicion-responsable',
    titulo_plantilla: 'Dar destino responsable a lo que no se puede reparar',
    dominio: 'residuos',
    rubros: ['reparacion-reuso'],
    metrica: 'material entregado a gestor',
    unidad: 'kg/mes',
    metrica_tipo: 'sustitucion',
    metodo_tipo: 'pesaje',
    alcance: 1,
    efecto_min: 0.3,
    efecto_max: 0.8,
    horizonte: 'semestral',
    ambicion: 'avanzado',
    esfuerzo_horas_mes: 3,
    inversion: 'ninguna',
    requiere: [],
    claves: ['gestor de residuos', 'raee', 'disposicion responsable'],
    porque:
      'Placas, pilas y baterías son lo más contaminante que pasa por el taller y lo que más se tira mal. Un gestor habilitado te da constancia de entrega, que además es evidencia que después podés mostrar.',
    pasos: [
      'Pesar por tipo lo que hoy se descarta',
      'Buscar gestor habilitado o punto de recepción de tu municipio',
      'Definir frecuencia de entrega y dónde se acopia mientras tanto',
      'Registrar cada entrega con su constancia',
    ],
    como_medir: 'Pesaje de lo entregado, con las constancias del gestor',
    evidencia_requerida: 'Constancias de entrega + registro de pesajes',
    si_no_llegas: 'Una corriente bien gestionada, la más riesgosa, ya es el grueso del problema. Cerralo.',
    confianza: 'alta',
    es_evento_unico: true,
  },
];

export const PALANCAS: Palanca[] = [
  ...TRANSVERSALES,
  ...GASTRONOMIA,
  ...COMERCIO,
  ...PRODUCCION_ALIMENTOS,
  ...INDUMENTARIA,
  ...SERVICIOS,
  ...BELLEZA,
  ...LOGISTICA,
  ...HOTELERIA,
  ...AGRO,
  ...LIMPIEZA,
  ...HOGAR,
  ...REPARACION,
];

export function palanca(slug: string | null | undefined): Palanca | undefined {
  return slug ? PALANCAS.find((p) => p.slug === slug) : undefined;
}

/** Las palancas de un rubro: las suyas y las transversales. */
export function palancasPara(rubro: string, tamano?: string): Palanca[] {
  return PALANCAS.filter((p) => p.rubros.includes('*') || p.rubros.includes(rubro)).filter((p) => {
    // `movilidad-equipo` no tiene sentido con dos personas.
    if (p.requiere.includes('equipo_5') && tamano === '1') return false;
    return true;
  });
}

/** Si el dossier cumple lo que la palanca necesita para tener sentido. */
export function cumpleRequisitos(p: Palanca, d: Dossier): boolean {
  for (const r of p.requiere) {
    if (r === 'presupuesto' && d.restricciones.presupuesto === 'ninguno') return false;
    if (r === 'linea_base_energia' && !(typeof d.energia.consumo_mensual === 'number' || d.energia.tiene_factura === true))
      return false;
    if (r === 'puede_cambiar_proveedores' && d.insumos.puede_cambiar_proveedores === false) return false;
    if (r === 'agua_relevante' && d.agua.es_relevante === false) return false;
    if (r === 'flota' && (d.logistica.flota === 'no_aplica' || d.logistica.flota === 'retiran')) return false;
    if (r === 'local_propio' && d.restricciones.local === 'alquilado') return false;
  }
  if (p.esfuerzo_horas_mes > d.restricciones.horas_mes_disponibles) return false;
  return true;
}

export const ORDEN_INVERSION: Record<Inversion, number> = { ninguna: 0, baja: 1, media: 2 };
