// ─────────────────────────────────────────────────────────────────────────────
// Las fuentes del Árbol.
//
// Son las 56 del currículum anterior (scripts/academia/fuentes.mjs, que sigue
// siendo la fuente de verdad de esas filas) más las que el currículum nuevo
// necesita. Cada unidad nombra las suyas por slug y `construir.mjs` falla si
// una unidad cita un slug que no está acá.
//
// DÓNDE SE VEN. Ya no en la lección: desde esta versión las fuentes viven en
// una página propia (`/legal/fuentes`), a la que se llega desde Ajustes o
// desde el pie. Esa página se genera desde este archivo.
//
// CÓMO SE ELIGIERON. Las seleccionó un modelo de IA al escribir el
// currículum, priorizando organismos públicos, agencias de Naciones Unidas,
// normas argentinas y literatura revisada por pares. Cada URL se comprueba con
// `node scripts/academia-arbol/verificar-fuentes.mjs` antes de publicar.
// ─────────────────────────────────────────────────────────────────────────────

import { FUENTES as ANTERIORES } from '../academia/fuentes.mjs';

/** @type {import('../academia/fuentes.mjs').Fuente[]} */
const NUEVAS = [
  // ── Clima y carbono ─────────────────────────────────────────────────────────
  {
    slug: 'ipcc-ar6-syr',
    titulo: 'AR6 Synthesis Report: Climate Change 2023',
    organizacion: 'IPCC',
    url: 'https://www.ipcc.ch/report/ar6/syr/',
    publicado: '2023',
  },
  {
    slug: 'noaa-co2',
    titulo: 'Trends in Atmospheric Carbon Dioxide (Mauna Loa)',
    organizacion: 'NOAA Global Monitoring Laboratory',
    url: 'https://gml.noaa.gov/ccgg/trends/',
    publicado: '2025',
  },
  {
    slug: 'nasa-evidencia',
    titulo: 'Evidence: How Do We Know Climate Change Is Real?',
    organizacion: 'NASA',
    url: 'https://science.nasa.gov/climate-change/evidence/',
    publicado: '2024',
  },
  {
    slug: 'nasa-ciclo-carbono',
    titulo: 'The Carbon Cycle',
    organizacion: 'NASA Earth Observatory',
    url: 'https://earthobservatory.nasa.gov/features/CarbonCycle',
    publicado: '2011',
  },
  {
    slug: 'global-carbon-budget',
    titulo: 'Global Carbon Budget',
    organizacion: 'Global Carbon Project',
    url: 'https://globalcarbonbudget.org/',
    publicado: '2024',
  },
  {
    slug: 'owid-co2',
    titulo: 'CO₂ and Greenhouse Gas Emissions',
    organizacion: 'Our World in Data',
    url: 'https://ourworldindata.org/co2-and-greenhouse-gas-emissions',
    publicado: '2024',
  },
  {
    slug: 'owid-energia',
    titulo: 'Energy',
    organizacion: 'Our World in Data',
    url: 'https://ourworldindata.org/energy',
    publicado: '2024',
  },
  {
    slug: 'consenso-cook-2016',
    titulo: 'Consensus on consensus: a synthesis of consensus estimates on human-caused global warming',
    organizacion: 'Environmental Research Letters (Cook et al.)',
    url: 'https://iopscience.iop.org/article/10.1088/1748-9326/11/4/048002',
    publicado: '2016',
  },
  {
    slug: 'wynes-nicholas-2017',
    titulo: 'The climate mitigation gap: education and government recommendations miss the most effective individual actions',
    organizacion: 'Environmental Research Letters (Wynes y Nicholas)',
    url: 'https://iopscience.iop.org/article/10.1088/1748-9326/aa7541',
    publicado: '2017',
  },
  {
    slug: 'inventario-gei-ar',
    titulo: 'Inventario Nacional de Gases de Efecto Invernadero',
    organizacion: 'Ministerio de Ambiente de la Nación (Argentina)',
    url: 'https://inventariogei.ambiente.gob.ar/',
    publicado: '2023',
  },
  // ── Agua ────────────────────────────────────────────────────────────────────
  {
    slug: 'usgs-ciclo-agua',
    titulo: 'The Water Cycle',
    organizacion: 'U.S. Geological Survey',
    url: 'https://www.usgs.gov/special-topics/water-science-school/science/water-cycle',
    publicado: '2019',
  },
  {
    slug: 'oms-agua-potable',
    titulo: 'Drinking-water (fact sheet)',
    organizacion: 'Organización Mundial de la Salud',
    url: 'https://www.who.int/news-room/fact-sheets/detail/drinking-water',
    publicado: '2023',
  },
  {
    slug: 'un-water',
    titulo: 'UN-Water: Water facts',
    organizacion: 'Naciones Unidas',
    url: 'https://www.unwater.org/water-facts',
    publicado: '2024',
  },
  {
    slug: 'aysa',
    titulo: 'Agua y Saneamientos Argentinos',
    organizacion: 'AySA',
    url: 'https://www.aysa.com.ar/',
    publicado: '2025',
  },
  {
    slug: 'water-footprint-network',
    titulo: 'Product gallery: the water footprint of products',
    organizacion: 'Water Footprint Network',
    url: 'https://www.waterfootprint.org/resources/interactive-tools/product-gallery/',
    publicado: '2017',
  },
  {
    slug: 'ley-26639-glaciares',
    titulo: 'Ley 26.639 — Régimen de Presupuestos Mínimos para la Preservación de los Glaciares y del Ambiente Periglacial',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-26639-174117',
    publicado: '2010',
  },
  // ── Energía ─────────────────────────────────────────────────────────────────
  {
    slug: 'cammesa',
    titulo: 'Compañía Administradora del Mercado Mayorista Eléctrico',
    organizacion: 'CAMMESA',
    url: 'https://www.cammesa.com/',
    publicado: '2025',
  },
  {
    slug: 'ley-27424-generacion',
    titulo: 'Ley 27.424 — Régimen de Fomento a la Generación Distribuida de Energía Renovable',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27424-305179',
    publicado: '2017',
  },
  {
    slug: 'iea-eficiencia',
    titulo: 'Energy Efficiency',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/energy-system/energy-efficiency-and-demand/energy-efficiency',
    publicado: '2024',
  },
  {
    slug: 'irena',
    titulo: 'International Renewable Energy Agency',
    organizacion: 'IRENA',
    url: 'https://www.irena.org/',
    publicado: '2025',
  },
  {
    slug: 'iea-datacenters',
    titulo: 'Data centres and data transmission networks',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/energy-system/buildings/data-centres-and-data-transmission-networks',
    publicado: '2024',
  },
  // ── Residuos, plásticos y consumo ───────────────────────────────────────────
  {
    slug: 'unep-plasticos',
    titulo: 'Plastic pollution',
    organizacion: 'Programa de las Naciones Unidas para el Medio Ambiente',
    url: 'https://www.unep.org/plastic-pollution',
    publicado: '2024',
  },
  {
    slug: 'ewaste-monitor',
    titulo: 'The Global E-waste Monitor 2024',
    organizacion: 'UIT y UNITAR',
    url: 'https://ewastemonitor.info/',
    publicado: '2024',
  },
  {
    slug: 'ceamse',
    titulo: 'Coordinación Ecológica Área Metropolitana Sociedad del Estado',
    organizacion: 'CEAMSE',
    url: 'https://www.ceamse.gov.ar/',
    publicado: '2025',
  },
  {
    slug: 'ley-25916-residuos',
    titulo: 'Ley 25.916 — Gestión de Residuos Domiciliarios',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-25916-98327',
    publicado: '2004',
  },
  {
    slug: 'unep-food-waste-2024',
    titulo: 'Food Waste Index Report 2024',
    organizacion: 'Programa de las Naciones Unidas para el Medio Ambiente',
    url: 'https://www.unep.org/resources/publication/food-waste-index-report-2024',
    publicado: '2024',
  },
  // ── Alimentación y suelo ────────────────────────────────────────────────────
  {
    slug: 'poore-nemecek-2018',
    titulo: 'Reducing food’s environmental impacts through producers and consumers',
    organizacion: 'Science (Poore y Nemecek)',
    url: 'https://www.science.org/doi/10.1126/science.aaq0216',
    publicado: '2018',
  },
  {
    slug: 'ley-27642-etiquetado',
    titulo: 'Ley 27.642 — Promoción de la Alimentación Saludable',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27642-356607',
    publicado: '2021',
  },
  {
    slug: 'guias-alimentarias-ar',
    titulo: 'Guías Alimentarias para la Población Argentina — manual de aplicación',
    organizacion: 'Ministerio de Salud de la Nación',
    url: 'https://www.argentina.gob.ar/sites/default/files/bancos/2020-08/guias-alimentarias-para-la-poblacion-argentina_manual-de-aplicacion_0.pdf',
    publicado: '2016',
  },
  {
    slug: 'fao-suelos',
    titulo: 'Portal de Suelos de la FAO',
    organizacion: 'FAO',
    url: 'https://www.fao.org/soils-portal/es/',
    publicado: '2024',
  },
  {
    slug: 'fao-pesca-sofia',
    titulo: 'El estado mundial de la pesca y la acuicultura',
    organizacion: 'FAO',
    url: 'https://www.fao.org/publications/home/fao-flagship-publications/the-state-of-world-fisheries-and-aquaculture/es',
    publicado: '2024',
  },
  // ── Aire, salud y movilidad ─────────────────────────────────────────────────
  {
    slug: 'oms-calidad-aire',
    titulo: 'Directrices mundiales de la OMS sobre la calidad del aire',
    organizacion: 'Organización Mundial de la Salud',
    url: 'https://www.who.int/publications/i/item/9789240034228',
    publicado: '2021',
  },
  {
    slug: 'oms-actividad-fisica',
    titulo: 'Actividad física (nota descriptiva)',
    organizacion: 'Organización Mundial de la Salud',
    url: 'https://www.who.int/es/news-room/fact-sheets/detail/physical-activity',
    publicado: '2024',
  },
  {
    slug: 'noaa-acidificacion',
    titulo: 'Ocean acidification',
    organizacion: 'NOAA',
    url: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification',
    publicado: '2023',
  },
  // ── Biodiversidad ───────────────────────────────────────────────────────────
  {
    slug: 'ipbes-polinizadores',
    titulo: 'Assessment Report on Pollinators, Pollination and Food Production',
    organizacion: 'IPBES',
    url: 'https://www.ipbes.net/assessment-reports/pollinators',
    publicado: '2016',
  },
  {
    slug: 'parques-nacionales',
    titulo: 'Administración de Parques Nacionales',
    organizacion: 'Parques Nacionales (Argentina)',
    url: 'https://www.argentina.gob.ar/parquesnacionales',
    publicado: '2025',
  },
  {
    slug: 'vida-silvestre',
    titulo: 'Fundación Vida Silvestre Argentina',
    organizacion: 'Fundación Vida Silvestre Argentina',
    url: 'https://www.vidasilvestre.org.ar/',
    publicado: '2025',
  },
  // ── Hábitos y acción ────────────────────────────────────────────────────────
  {
    slug: 'lally-2010-habitos',
    titulo: 'How are habits formed: Modelling habit formation in the real world',
    organizacion: 'European Journal of Social Psychology (Lally et al.)',
    url: 'https://onlinelibrary.wiley.com/doi/10.1002/ejsp.674',
    publicado: '2010',
  },
  {
    slug: 'bit-east',
    titulo: 'EAST: Four simple ways to apply behavioural insights',
    organizacion: 'The Behavioural Insights Team',
    url: 'https://www.bi.team/publications/east-four-simple-ways-to-apply-behavioural-insights/',
    publicado: '2014',
  },
  {
    slug: 'inventario-glaciares',
    titulo: 'Inventario Nacional de Glaciares',
    organizacion: 'IANIGLA-CONICET y Ministerio de Ambiente',
    url: 'https://www.glaciaresargentinos.gob.ar/',
    publicado: '2018',
  },
  // ── Plantas ─────────────────────────────────────────────────────────────────
  {
    slug: 'bar-on-biomasa-2018',
    titulo: 'The biomass distribution on Earth',
    organizacion: 'PNAS (Bar-On, Phillips y Milo)',
    url: 'https://www.pnas.org/doi/10.1073/pnas.1711842115',
    publicado: '2018',
  },
  // ── Animales ────────────────────────────────────────────────────────────────
  {
    slug: 'loss-2013-gatos',
    titulo: 'The impact of free-ranging domestic cats on wildlife of the United States',
    organizacion: 'Nature Communications (Loss, Will y Marra)',
    url: 'https://www.nature.com/articles/ncomms2380',
    publicado: '2013',
  },
  {
    slug: 'loss-2014-vidrios',
    titulo: 'Bird–window collisions in the United States',
    organizacion: 'The Condor (Loss, Will, Loss y Marra)',
    url: 'https://academic.oup.com/condor/article/116/1/8/5153098',
    publicado: '2014',
  },
  // ── Aire y suelo ────────────────────────────────────────────────────────────
  {
    slug: 'oms-aire-exterior',
    titulo: 'Calidad del aire ambiente (exterior) y salud (nota descriptiva)',
    organizacion: 'Organización Mundial de la Salud',
    url: 'https://www.who.int/es/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health',
    publicado: '2024',
  },
  {
    slug: 'oms-aire-hogar',
    titulo: 'Contaminación del aire doméstico y salud (nota descriptiva)',
    organizacion: 'Organización Mundial de la Salud',
    url: 'https://www.who.int/es/news-room/fact-sheets/detail/household-air-pollution-and-health',
    publicado: '2024',
  },
  {
    slug: 'anthony-2023-suelo',
    titulo: 'Enumerating soil biodiversity',
    organizacion: 'PNAS (Anthony, Bender y van der Heijden)',
    url: 'https://www.pnas.org/doi/10.1073/pnas.2304663120',
    publicado: '2023',
  },
  {
    slug: 'fao-suelos-degradacion',
    titulo: 'Estado mundial del recurso suelo (resumen técnico)',
    organizacion: 'FAO y Grupo Técnico Intergubernamental de Suelos',
    url: 'https://www.fao.org/3/i5126s/i5126s.pdf',
    publicado: '2015',
  },
  // ── Movilidad ───────────────────────────────────────────────────────────────
  {
    slug: 'owid-transporte',
    titulo: 'Which form of transport has the smallest carbon footprint?',
    organizacion: 'Our World in Data',
    url: 'https://ourworldindata.org/travel-carbon-footprint',
    publicado: '2023',
  },
  {
    slug: 'oms-seguridad-vial',
    titulo: 'Traumatismos causados por el tránsito (nota descriptiva)',
    organizacion: 'Organización Mundial de la Salud',
    url: 'https://www.who.int/es/news-room/fact-sheets/detail/road-traffic-injuries',
    publicado: '2023',
  },
  // ── Consumo ─────────────────────────────────────────────────────────────────
  {
    slug: 'emf-textiles',
    titulo: 'A new textiles economy: Redesigning fashion’s future',
    organizacion: 'Ellen MacArthur Foundation',
    url: 'https://www.ellenmacarthurfoundation.org/a-new-textiles-economy',
    publicado: '2017',
  },
  {
    slug: 'unep-moda',
    titulo: 'Putting the brakes on fast fashion',
    organizacion: 'Programa de las Naciones Unidas para el Medio Ambiente',
    url: 'https://www.unep.org/news-and-stories/story/putting-brakes-fast-fashion',
    publicado: '2018',
  },
  {
    slug: 'ce-green-claims',
    titulo: 'Green claims',
    organizacion: 'Comisión Europea',
    url: 'https://environment.ec.europa.eu/topics/circular-economy/green-claims_en',
    publicado: '2023',
  },
  {
    slug: 'senasa-organicos',
    titulo: 'Producción orgánica',
    organizacion: 'SENASA',
    url: 'https://www.argentina.gob.ar/senasa/programas-sanitarios/produccion-organica',
    publicado: '2024',
  },
  // ── Digital ─────────────────────────────────────────────────────────────────
  {
    slug: 'iea-streaming',
    titulo: 'The carbon footprint of streaming video: fact-checking the headlines',
    organizacion: 'Agencia Internacional de Energía (IEA)',
    url: 'https://www.iea.org/commentaries/the-carbon-footprint-of-streaming-video-fact-checking-the-headlines',
    publicado: '2020',
  },
  {
    slug: 'global-forest-watch',
    titulo: 'Global Forest Watch',
    organizacion: 'World Resources Institute',
    url: 'https://www.globalforestwatch.org/',
    publicado: '2024',
  },
  {
    slug: 'nasa-firms',
    titulo: 'FIRMS — Fire Information for Resource Management System',
    organizacion: 'NASA',
    url: 'https://firms.modaps.eosdis.nasa.gov/',
    publicado: '2024',
  },
  {
    slug: 'conae',
    titulo: 'Comisión Nacional de Actividades Espaciales (CONAE)',
    organizacion: 'Gobierno de Argentina',
    url: 'https://www.argentina.gob.ar/ciencia/conae',
    publicado: '2024',
  },
  // ── Océanos y ríos ──────────────────────────────────────────────────────────
  {
    slug: 'pampa-azul',
    titulo: 'Iniciativa Pampa Azul',
    organizacion: 'Gobierno de Argentina',
    url: 'https://www.pampazul.gob.ar/',
    publicado: '2024',
  },
  {
    slug: 'inidep',
    titulo: 'Instituto Nacional de Investigación y Desarrollo Pesquero (INIDEP)',
    organizacion: 'INIDEP',
    url: 'https://www.inidep.edu.ar/',
    publicado: '2024',
  },
  // ── Alimentación ────────────────────────────────────────────────────────────
  {
    slug: 'fao-agroecologia',
    titulo: 'Centro de conocimientos sobre agroecología',
    organizacion: 'FAO',
    url: 'https://www.fao.org/agroecology/overview/es/',
    publicado: '2024',
  },
  {
    slug: 'red-bancos-alimentos',
    titulo: 'Red Argentina de Bancos de Alimentos',
    organizacion: 'Red Argentina de Bancos de Alimentos',
    url: 'https://www.redbda.org.ar/',
    publicado: '2024',
  },
  // ── Verde urbano ────────────────────────────────────────────────────────────
  {
    slug: 'epa-isla-calor',
    titulo: 'Using Trees and Vegetation to Reduce Heat Islands',
    organizacion: 'US EPA',
    url: 'https://www.epa.gov/heatislands/using-trees-and-vegetation-reduce-heat-islands',
    publicado: '2024',
  },
  {
    slug: 'oms-espacios-verdes',
    titulo: 'Urban green spaces: a brief for action',
    organizacion: 'Organización Mundial de la Salud (Europa)',
    url: 'https://www.who.int/europe/publications/i/item/9789289052498',
    publicado: '2017',
  },
  // ── El clima que cambia ─────────────────────────────────────────────────────
  {
    slug: 'noaa-co2-historia',
    titulo: 'Climate Change: Atmospheric Carbon Dioxide',
    organizacion: 'NOAA Climate.gov',
    url: 'https://www.climate.gov/news-features/understanding-climate/climate-change-atmospheric-carbon-dioxide',
    publicado: '2025',
  },
  {
    slug: 'nasa-gistemp',
    titulo: 'GISS Surface Temperature Analysis (GISTEMP v4)',
    organizacion: 'NASA Goddard Institute for Space Studies',
    url: 'https://data.giss.nasa.gov/gistemp/',
    publicado: '2025',
  },
  {
    slug: 'copernicus-clima-2024',
    titulo: 'Global Climate Highlights 2024',
    organizacion: 'Copernicus Climate Change Service',
    url: 'https://climate.copernicus.eu/global-climate-highlights-2024',
    publicado: '2025',
  },
  {
    slug: 'wmo-clima-2024',
    titulo: 'State of the Global Climate 2024',
    organizacion: 'Organización Meteorológica Mundial',
    url: 'https://wmo.int/publication-series/state-of-global-climate/state-of-global-climate-2024',
    publicado: '2025',
  },
  {
    slug: 'noaa-nivel-mar',
    titulo: 'Climate Change: Global Sea Level',
    organizacion: 'NOAA Climate.gov',
    url: 'https://www.climate.gov/news-features/understanding-climate/climate-change-global-sea-level',
    publicado: '2024',
  },
  {
    slug: 'wwa-atribucion',
    titulo: 'World Weather Attribution',
    organizacion: 'World Weather Attribution',
    url: 'https://www.worldweatherattribution.org/',
    publicado: '2025',
  },
  {
    slug: 'ipcc-sr15',
    titulo: 'Global Warming of 1.5 °C',
    organizacion: 'IPCC',
    url: 'https://www.ipcc.ch/sr15/',
    publicado: '2018',
  },
  {
    slug: 'acuerdo-paris',
    titulo: 'The Paris Agreement',
    organizacion: 'Convención Marco de las Naciones Unidas sobre el Cambio Climático',
    url: 'https://unfccc.int/process-and-meetings/the-paris-agreement',
    publicado: '2015',
  },
  // ── Pensamiento científico ──────────────────────────────────────────────────
  {
    slug: 'vosoughi-2018',
    titulo: 'The spread of true and false news online',
    organizacion: 'Science (Vosoughi, Roy y Aral)',
    url: 'https://www.science.org/doi/10.1126/science.aap9559',
    publicado: '2018',
  },
  {
    slug: 'flicc-cook',
    titulo: 'The history of FLICC: the 5 techniques of science denial',
    organizacion: 'Skeptical Science (John Cook)',
    url: 'https://skepticalscience.com/history-FLICC-5-techniques-science-denial.html',
    publicado: '2020',
  },
  {
    slug: 'first-draft-tipos',
    titulo: 'Fake news. It’s complicated.',
    organizacion: 'First Draft (Claire Wardle)',
    url: 'https://firstdraftnews.org/articles/fake-news-complicated/',
    publicado: '2017',
  },
  {
    slug: 'inoculacion',
    titulo: 'Inoculation Science',
    organizacion: 'Cambridge Social Decision-Making Lab',
    url: 'https://inoculation.science/',
    publicado: '2025',
  },
  {
    slug: 'lectura-lateral',
    titulo: 'Civic Online Reasoning',
    organizacion: 'Digital Inquiry Group (ex Stanford History Education Group)',
    url: 'https://cor.inquirygroup.org/',
    publicado: '2025',
  },
  {
    slug: 'cochrane',
    titulo: 'About Cochrane',
    organizacion: 'Cochrane',
    url: 'https://www.cochrane.org/about-us',
    publicado: '2025',
  },
  {
    slug: 'ecsa-principios',
    titulo: 'Ten Principles of Citizen Science',
    organizacion: 'European Citizen Science Association',
    url: 'https://www.ecsa.ngo/10-principles/',
    publicado: '2015',
  },
  {
    slug: 'inaturalist-calidad',
    titulo: 'What is the Data Quality Assessment and how do observations qualify to become Research Grade?',
    organizacion: 'iNaturalist',
    url: 'https://help.inaturalist.org/en/support/solutions/articles/151000169936-what-is-the-data-quality-assessment-and-how-do-observations-qualify-to-become-research-grade-',
    publicado: '2025',
  },
  {
    slug: 'geovin',
    titulo: 'GeoVin: el proyecto de ciencia ciudadana sobre vinchucas',
    organizacion: 'Proyecto GeoVin (investigadores del CONICET)',
    url: 'https://geovin.com.ar/',
    publicado: '2025',
  },
  // ── Transporte público y autos ──────────────────────────────────────────────
  {
    slug: 'red-sube',
    titulo: 'Red SUBE',
    organizacion: 'Gobierno de la República Argentina',
    url: 'https://www.argentina.gob.ar/redsube',
    publicado: '2025',
  },
  {
    slug: 'metrobus-gcba',
    titulo: 'Metrobus',
    organizacion: 'Gobierno de la Ciudad de Buenos Aires',
    url: 'https://buenosaires.gob.ar/gcaba_historico/metrobus',
    publicado: '2024',
  },
  {
    slug: 'itdp-brt',
    titulo: 'The Bus Rapid Transit Standard',
    organizacion: 'Institute for Transportation and Development Policy',
    url: 'https://itdp.org/library/standards-and-guides/the-bus-rapid-transit-standard/',
    publicado: '2024',
  },
  {
    slug: 'human-transit',
    titulo: 'Explainer: The Transit Ridership Recipe',
    organizacion: 'Human Transit (Jarrett Walker)',
    url: 'https://humantransit.org/2015/07/mega-explainer-the-ridership-recipe.html',
    publicado: '2015',
  },
  {
    slug: 'epa-auto-tipico',
    titulo: 'Greenhouse Gas Emissions from a Typical Passenger Vehicle',
    organizacion: 'Agencia de Protección Ambiental de EE. UU. (EPA)',
    url: 'https://www.epa.gov/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle',
    publicado: '2024',
  },
  {
    slug: 'icct-ev-global',
    titulo: 'A global comparison of the life-cycle greenhouse gas emissions of combustion engine and electric passenger cars',
    organizacion: 'ICCT — International Council on Clean Transportation',
    url: 'https://theicct.org/publication/a-global-comparison-of-the-life-cycle-greenhouse-gas-emissions-of-combustion-engine-and-electric-passenger-cars/',
    publicado: '2021',
  },
  {
    slug: 'iea-ev-outlook',
    titulo: 'Global EV Outlook 2025',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/reports/global-ev-outlook-2025',
    publicado: '2025',
  },
  {
    slug: 'oecd-no-escape',
    titulo: 'Non-exhaust Particulate Emissions from Road Transport',
    organizacion: 'OCDE',
    url: 'https://www.oecd.org/en/publications/non-exhaust-particulate-emissions-from-road-transport_4a4dc6ca-en.html',
    publicado: '2020',
  },
  {
    slug: 'doe-eficiencia-ev',
    titulo: 'All-Electric Vehicles',
    organizacion: 'Departamento de Energía de EE. UU. (fueleconomy.gov)',
    url: 'https://www.fueleconomy.gov/feg/evtech.shtml',
    publicado: '2025',
  },
  {
    slug: 'ley-27640-biocombustibles',
    titulo: 'Ley 27.640 — Marco regulatorio de biocombustibles',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27640-352587',
    publicado: '2021',
  },
  // ── Economía circular y precios ─────────────────────────────────────────────
  {
    slug: 'circularity-gap-2025',
    titulo: 'Circularity Gap Report 2025',
    organizacion: 'Circle Economy y Deloitte',
    url: 'https://circularity-gap.world/2025',
    publicado: '2025',
  },
  {
    slug: 'emf-mariposa',
    titulo: 'The butterfly diagram: visualising the circular economy',
    organizacion: 'Ellen MacArthur Foundation',
    url: 'https://www.ellenmacarthurfoundation.org/circular-economy-diagram',
    publicado: '2024',
  },
  {
    slug: 'ue-ecodiseno',
    titulo: 'Ecodesign for Sustainable Products Regulation',
    organizacion: 'Comisión Europea',
    url: 'https://environment.ec.europa.eu/strategy/circular-economy/ecodesign-sustainable-products-regulation_en',
    publicado: '2024',
  },
  {
    slug: 'ue-derecho-reparar',
    titulo: 'Right to repair: making repair easier and more appealing to consumers',
    organizacion: 'Parlamento Europeo',
    url: 'https://www.europarl.europa.eu/news/en/press-room/20240419IPR20590/right-to-repair-making-repair-easier-and-more-appealing-to-consumers',
    publicado: '2024',
  },
  {
    slug: 'bm-precio-carbono',
    titulo: 'State and Trends of Carbon Pricing',
    organizacion: 'Banco Mundial',
    url: 'https://www.worldbank.org/en/publication/state-and-trends-of-carbon-pricing',
    publicado: '2026',
  },
  {
    slug: 'fmi-subsidios',
    titulo: 'IMF Fossil Fuel Subsidies Data: 2023 Update',
    organizacion: 'Fondo Monetario Internacional',
    url: 'https://www.imf.org/en/Publications/WP/Issues/2023/08/22/IMF-Fossil-Fuel-Subsidies-Data-2023-Update-537281',
    publicado: '2023',
  },
  {
    slug: 'fao-sofa-2023',
    titulo: 'El estado mundial de la agricultura y la alimentación 2023: los costos ocultos de los sistemas agroalimentarios',
    organizacion: 'FAO',
    url: 'https://www.fao.org/publications/fao-flagship-publications/the-state-of-food-and-agriculture/2023/en',
    publicado: '2023',
  },
  {
    slug: 'ley-27430-impuesto-co2',
    titulo: 'Ley 27.430 — Impuesto al dióxido de carbono sobre los combustibles',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27430-305262',
    publicado: '2017',
  },
  // ── Centros de datos, IA y minerales ────────────────────────────────────────
  {
    slug: 'iea-energia-ia',
    titulo: 'Energy and AI',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/reports/energy-and-ai/energy-demand-from-ai',
    publicado: '2025',
  },
  {
    slug: 'uptime-2024',
    titulo: 'Uptime Institute Global Data Center Survey Results 2024',
    organizacion: 'Uptime Institute',
    url: 'https://uptimeinstitute.com/resources/research-and-reports/uptime-institute-global-data-center-survey-results-2024',
    publicado: '2024',
  },
  {
    slug: 'google-ia-2025',
    titulo: 'Measuring the environmental impact of delivering AI at Google Scale',
    organizacion: 'Google (Elsworth y otros), arXiv',
    url: 'https://arxiv.org/abs/2508.15734',
    publicado: '2025',
  },
  {
    slug: 'usgs-litio-2025',
    titulo: 'Mineral Commodity Summaries 2025: Lithium',
    organizacion: 'Servicio Geológico de EE. UU. (USGS)',
    url: 'https://pubs.usgs.gov/periodicals/mcs2025/mcs2025-lithium.pdf',
    publicado: '2025',
  },
  {
    slug: 'usgs-cobalto-2025',
    titulo: 'Mineral Commodity Summaries 2025: Cobalt',
    organizacion: 'Servicio Geológico de EE. UU. (USGS)',
    url: 'https://pubs.usgs.gov/periodicals/mcs2025/mcs2025-cobalt.pdf',
    publicado: '2025',
  },
  {
    slug: 'iea-minerales-2025',
    titulo: 'Global Critical Minerals Outlook 2025',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/reports/global-critical-minerals-outlook-2025',
    publicado: '2025',
  },
  {
    slug: 'amnistia-cobalto',
    titulo: '"This is what we die for": human rights abuses in the Democratic Republic of the Congo power the global trade in cobalt',
    organizacion: 'Amnistía Internacional',
    url: 'https://www.amnesty.org/en/documents/afr62/3183/2016/en/',
    publicado: '2016',
  },
  {
    slug: 'ley-24196-mineria',
    titulo: 'Ley 24.196 — Inversiones mineras (tope de regalías provinciales)',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-24196-594',
    publicado: '1993',
  },
  {
    slug: 'ue-minerales-conflicto',
    titulo: 'Conflict Minerals Regulation',
    organizacion: 'Comisión Europea',
    url: 'https://policy.trade.ec.europa.eu/development-and-sustainability/conflict-minerals-regulation_en',
    publicado: '2021',
  },
  {
    slug: 'ocde-diligencia-minerales',
    titulo: 'OECD Due Diligence Guidance for Responsible Supply Chains of Minerals from Conflict-Affected and High-Risk Areas',
    organizacion: 'OCDE',
    url: 'https://www.oecd.org/en/publications/oecd-due-diligence-guidance-for-responsible-supply-chains-of-minerals-from-conflict-affected-and-high-risk-areas_9789264252479-en.html',
    publicado: '2016',
  },
  {
    slug: 'ley-24071-oit-169',
    titulo: 'Ley 24.071 — Aprueba el Convenio 169 de la OIT sobre pueblos indígenas y tribales',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-24071-470',
    publicado: '1992',
  },
  // ── Justicia y conflictos ambientales ───────────────────────────────────────
  {
    slug: 'oxfam-clima-2023',
    titulo: 'Climate Equality: A planet for the 99%',
    organizacion: 'Oxfam y Stockholm Environment Institute',
    url: 'https://www.oxfam.org/en/research/climate-equality-planet-99',
    publicado: '2023',
  },
  {
    slug: 'cij-clima-2025',
    titulo: 'Obligations of States in respect of Climate Change (opinión consultiva)',
    organizacion: 'Corte Internacional de Justicia',
    url: 'https://www.icj-cij.org/case/187',
    publicado: '2025',
  },
  {
    slug: 'acumar-causa-mendoza',
    titulo: 'Causa Mendoza',
    organizacion: 'ACUMAR',
    url: 'https://www.acumar.gob.ar/institucional/causa-mendoza/',
    publicado: '2024',
  },
  {
    slug: 'ejatlas',
    titulo: 'Environmental Justice Atlas',
    organizacion: 'EJAtlas (Universitat Autònoma de Barcelona)',
    url: 'https://ejatlas.org/',
    publicado: '2025',
  },
  {
    slug: 'ejatlas-esquel',
    titulo: 'Meridian Gold Mine in Esquel, Argentina',
    organizacion: 'EJAtlas',
    url: 'https://ejatlas.org/conflict/esquel-meridian-gold-mine-argentina',
    publicado: '2024',
  },
  {
    slug: 'global-witness-defensores',
    titulo: 'Land and Environmental Defenders',
    organizacion: 'Global Witness',
    url: 'https://globalwitness.org/en/campaigns/land-and-environmental-defenders/',
    publicado: '2026',
  },
  {
    slug: 'cij-papeleras-2010',
    titulo: 'Pulp Mills on the River Uruguay (Argentina v. Uruguay)',
    organizacion: 'Corte Internacional de Justicia',
    url: 'https://www.icj-cij.org/case/135',
    publicado: '2010',
  },
  // ── Mares contaminados y áreas marinas protegidas ───────────────────────────
  {
    slug: 'diaz-rosenberg-2008',
    titulo: 'Spreading dead zones and consequences for marine ecosystems',
    organizacion: 'Science (Diaz y Rosenberg)',
    url: 'https://www.science.org/doi/10.1126/science.1156401',
    publicado: '2008',
  },
  {
    slug: 'un-water-aguas-residuales',
    titulo: 'Progress on wastewater treatment – 2024 update',
    organizacion: 'ONU-Agua (UN-Water)',
    url: 'https://www.unwater.org/publications/progress-wastewater-treatment-2024-update',
    publicado: '2024',
  },
  {
    slug: 'minamata',
    titulo: 'Convenio de Minamata sobre el Mercurio',
    organizacion: 'Programa de las Naciones Unidas para el Medio Ambiente',
    url: 'https://minamataconvention.org/es',
    publicado: '2013',
  },
  {
    slug: 'ley-27490-amp',
    titulo: 'Ley 27.490 — Áreas marinas protegidas Yaganes y Namuncurá-Banco Burdwood II',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27490-317651',
    publicado: '2018',
  },
  {
    slug: 'cdb-meta-3',
    titulo: 'Marco Mundial de Biodiversidad Kunming-Montreal: Meta 3',
    organizacion: 'Convenio sobre la Diversidad Biológica',
    url: 'https://www.cbd.int/gbf/targets/3',
    publicado: '2022',
  },
  {
    slug: 'mpatlas',
    titulo: 'Marine Protection Atlas',
    organizacion: 'Marine Conservation Institute',
    url: 'https://mpatlas.org/',
    publicado: '2026',
  },
  {
    slug: 'mci-10-3',
    titulo: '10% Protected. 3% Effective. The Widening Gap We Can’t Ignore',
    organizacion: 'Marine Conservation Institute',
    url: 'https://marine-conservation.org/on-the-tide/ten-percent-protected-three-percent-effective/',
    publicado: '2026',
  },
  {
    slug: 'edgar-2014-neoli',
    titulo: 'Global conservation outcomes depend on marine protected areas with five key features',
    organizacion: 'Nature (Edgar y otros)',
    url: 'https://www.nature.com/articles/nature13022',
    publicado: '2014',
  },
  // ── Red eléctrica y almacenamiento ──────────────────────────────────────────
  {
    slug: 'iea-baterias-2024',
    titulo: 'Batteries and Secure Energy Transitions',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/reports/batteries-and-secure-energy-transitions',
    publicado: '2024',
  },
  {
    slug: 'bnef-baterias-2024',
    titulo: 'Lithium-Ion Battery Pack Prices See Largest Drop Since 2017, Falling to $115 per Kilowatt-Hour',
    organizacion: 'BloombergNEF',
    url: 'https://about.bnef.com/insights/commodities/lithium-ion-battery-pack-prices-see-largest-drop-since-2017-falling-to-115-per-kilowatt-hour-bloombergnef/',
    publicado: '2024',
  },
  {
    slug: 'eia-curva-pato',
    titulo: 'As solar capacity grows, duck curves are getting deeper in California',
    organizacion: 'Administración de Información Energética de EE. UU.',
    url: 'https://www.eia.gov/todayinenergy/detail.php?id=56880',
    publicado: '2023',
  },
  {
    slug: 'almagba-2025',
    titulo: 'Se abrió la licitación de AlmaGBA: se recibieron 27 proyectos por más de 1347 MW de almacenamiento',
    organizacion: 'Gobierno de la República Argentina',
    url: 'https://www.argentina.gob.ar/noticias/se-abrio-la-licitacion-de-almagba-se-recibieron-27-proyectos-por-mas-de-1347-mw-de',
    publicado: '2025',
  },
  {
    slug: 'iea-renovables-2024',
    titulo: 'Renewables 2024',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/reports/renewables-2024',
    publicado: '2024',
  },
  // ── Transición energética en Argentina ──────────────────────────────────────
  {
    slug: 'ley-27191-renovables',
    titulo: 'Ley 27.191 — Régimen de fomento de las energías renovables',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27191-253626',
    publicado: '2015',
  },
  {
    slug: 'argendata-transicion',
    titulo: 'Transición energética',
    organizacion: 'Argendata (Fundar)',
    url: 'https://argendata.fund.ar/topico/transicion-energetica/',
    publicado: '2024',
  },
  {
    slug: 'renovables-2025-ar',
    titulo: 'Las energías renovables sumaron más de 1000 MW en 2025 y ya cubren casi un quinto de la demanda',
    organizacion: 'EconoJournal (con datos de CAMMESA)',
    url: 'https://econojournal.com.ar/renovables-te/las-energias-renovables-sumaron-mas-de-1-000-mw-en-2025-y-ya-cubren-casi-un-quinto-de-la-demanda/',
    publicado: '2026',
  },
  {
    slug: 'censo-gas-2022',
    titulo: 'Censo 2022: cuántos argentinos tienen acceso a gas natural, cloacas y vivienda propia',
    organizacion: 'Infobae (con datos del INDEC)',
    url: 'https://www.infobae.com/economia/2023/11/22/censo-2022-cuantos-argentinos-tienen-acceso-a-gas-natural-cloacas-y-vivienda-propia/',
    publicado: '2023',
  },
  {
    slug: 'balanza-energetica-2024',
    titulo: 'La balanza comercial energética del 2024 arrojó el superávit más alto en 18 años',
    organizacion: 'Ámbito (con datos de la Secretaría de Energía)',
    url: 'https://www.ambito.com/energia/la-balanza-comercial-energetica-del-2024-arrojo-el-superavit-mas-alto-18-anos-n6105371',
    publicado: '2025',
  },
  {
    slug: 'iea-metano-2025',
    titulo: 'Global Methane Tracker 2025',
    organizacion: 'Agencia Internacional de Energía',
    url: 'https://www.iea.org/reports/global-methane-tracker-2025',
    publicado: '2025',
  },
  // ── Gestión de residuos y residuos peligrosos ───────────────────────────────
  {
    slug: 'basurales-ar',
    titulo: 'Basurales a cielo abierto: situación socioambiental y propuestas de solución integral',
    organizacion: 'Gobierno de la República Argentina',
    url: 'https://www.argentina.gob.ar/jefatura/ambiente/accion-ambiental/basurales',
    publicado: '2024',
  },
  {
    slug: 'chequeado-basurales',
    titulo: 'Qué datos existen sobre los basurales a cielo abierto en la Argentina',
    organizacion: 'Chequeado',
    url: 'https://chequeado.com/el-explicador/que-datos-existen-sobre-los-basurales-a-cielo-abierto-en-la-argentina/',
    publicado: '2023',
  },
  {
    slug: 'bm-what-a-waste',
    titulo: 'What a Waste',
    organizacion: 'Banco Mundial',
    url: 'https://www.worldbank.org/en/publication/what-a-waste',
    publicado: '2025',
  },
  {
    slug: 'ley-24051-peligrosos',
    titulo: 'Ley 24.051 — Residuos peligrosos',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-24051-450',
    publicado: '1991',
  },
  {
    slug: 'basilea',
    titulo: 'Convenio de Basilea sobre el control de los movimientos transfronterizos de los desechos peligrosos',
    organizacion: 'Programa de las Naciones Unidas para el Medio Ambiente',
    url: 'https://www.basel.int/TheConvention/Overview/tabid/1271/Default.aspx',
    publicado: '1989',
  },
  {
    slug: 'ley-27279-fitosanitarios',
    titulo: 'Ley 27.279 — Gestión de los envases vacíos de fitosanitarios',
    organizacion: 'Congreso de la Nación Argentina',
    url: 'https://www.argentina.gob.ar/normativa/nacional/ley-27279-266332',
    publicado: '2016',
  },
  // ── Residuos y materiales ───────────────────────────────────────────────────
  {
    slug: 'mst-bolsas-2018',
    titulo: 'Life Cycle Assessment of grocery carrier bags',
    organizacion: 'Danish Environmental Protection Agency',
    url: 'https://www2.mst.dk/Udgiv/publications/2018/02/978-87-93614-73-4.pdf',
    publicado: '2018',
  },
  {
    slug: 'iai-reciclaje-aluminio',
    titulo: 'Aluminium recycling',
    organizacion: 'European Aluminium',
    url: 'https://european-aluminium.eu/about-aluminium/aluminium-recycling/',
    publicado: '2024',
  },
  {
    slug: 'oecd-plasticos',
    titulo: 'Global Plastics Outlook: Economic Drivers, Environmental Impacts and Policy Options',
    organizacion: 'OCDE',
    url: 'https://www.oecd.org/en/publications/global-plastics-outlook_de747aef-en.html',
    publicado: '2022',
  },
  {
    slug: 'onu-ods',
    titulo: 'Objetivos de Desarrollo Sostenible',
    organizacion: 'Naciones Unidas',
    url: 'https://sdgs.un.org/goals',
    publicado: '2015',
  },
];

// Links de la lista anterior que ya no responden (verificado con
// verificar-fuentes.mjs el 2026-09-22). Se corrigen acá y no en el archivo
// viejo, que describe lo que se cargó en su momento.
const CORRECCIONES = {
  'rewilding-argentina': { url: 'https://rewildingargentina.org/' },
  'ley-1854-basura-cero': {
    titulo: 'Ley 1.854 «Basura Cero» y su decreto reglamentario',
    url: 'https://www.cedom.gob.ar/legislacion/normas/leyes/RepoLeyes/anexos/drl1854.html',
  },
};

// El orden de las anteriores se respeta; las nuevas van detrás.
export const FUENTES = [...ANTERIORES.map((f) => ({ ...f, ...(CORRECCIONES[f.slug] ?? {}) })), ...NUEVAS];
