-- Generado por scripts/academia-arbol/construir.mjs — fuentes y ramas.
-- No se edita a mano: se edita el contenido y se vuelve a construir.
-- Idempotente: cargar dos veces deja lo mismo.

select ac_cargar_fuente($ac${"slug":"ipbes-global","titulo":"IPBES Global Assessment on Biodiversity and Ecosystem Services","organizacion":"IPBES","url":"https://www.ipbes.net/global-assessment","publicado":"2019","licencia":"Uso con atribución","contenido":"Alrededor de un millón de especies animales y vegetales están amenazadas de extinción. Los cinco impulsores directos del cambio en la naturaleza, ordenados por impacto: cambio de uso de la tierra y el mar, explotación directa de organismos, cambio climático, contaminación e invasión de especies exóticas."}$ac$::jsonb);
select ac_cargar_fuente($ac${"slug":"invasoras-mayds","titulo":"Lista de especies exóticas invasoras de Argentina","organizacion":"Ministerio de Ambiente y Desarrollo Sostenible","url":"https://www.argentina.gob.ar/ambiente/biodiversidad/exoticas-invasoras/lista","publicado":"2024","licencia":"Datos públicos","contenido":"Especies exóticas invasoras registradas en Argentina: castor canadiense, visón americano, ciervo colorado, jabalí europeo, ardilla de vientre rojo, estornino pinto, paloma doméstica, mejillón dorado, caracol gigante africano, mosquito tigre. Entre las plantas: ligustro, mora, acacia negra, rosa mosqueta, gleditsia y tamarisco."}$ac$::jsonb);
select ac_cargar_fuente($ac${"slug":"global-footprint","titulo":"Ecological Footprint y Earth Overshoot Day","organizacion":"Global Footprint Network","url":"https://www.footprintnetwork.org/","publicado":"2025","licencia":"Uso con atribución","contenido":"El Día de Sobregiro de la Tierra marca la fecha en la que la humanidad consumió todos los recursos que los ecosistemas pueden regenerar en un año. A partir de esa fecha el consumo del año se sostiene sobre stock, no sobre renovación."}$ac$::jsonb);
select ac_cargar_fuente($ac${"slug":"unep","titulo":"UNEP — Programa de las Naciones Unidas para el Medio Ambiente","organizacion":"UNEP","url":"https://www.unep.org/","publicado":"2025","licencia":"Uso con atribución","contenido":"La gran mayoría de la basura marina se origina en tierra y llega al mar a través de ríos, desagües y viento. Los cinco impulsores de la crisis de la naturaleza son el cambio de uso de la tierra y el mar, la explotación directa, el cambio climático, la contaminación y las especies invasoras."}$ac$::jsonb);
select ac_cargar_fuente($ac${"slug":"unesco-ods","titulo":"Education for Sustainable Development Goals: Learning Objectives","organizacion":"UNESCO","url":"https://unesdoc.unesco.org/ark:/48223/pf0000247444","publicado":"2017","licencia":"CC BY-SA","contenido":"UNESCO define, para cada Objetivo de Desarrollo Sostenible, objetivos de aprendizaje cognitivos, socioemocionales y conductuales, y ocho competencias transversales: pensamiento sistémico, anticipatorio, normativo, estratégico, colaboración, pensamiento crítico, autoconciencia y resolución integrada de problemas."}$ac$::jsonb);
select ac_cargar_fuente($ac${"slug":"nasa-ciclo-carbono","titulo":"The Carbon Cycle","organizacion":"NASA Earth Observatory","url":"https://earthobservatory.nasa.gov/features/CarbonCycle","publicado":"2011","licencia":null,"contenido":null}$ac$::jsonb);
select ac_cargar_fuente($ac${"slug":"usgs-ciclo-agua","titulo":"The Water Cycle","organizacion":"U.S. Geological Survey","url":"https://www.usgs.gov/special-topics/water-science-school/science/water-cycle","publicado":"2019","licencia":null,"contenido":null}$ac$::jsonb);

select ac_cargar_rama($ac${"slug":"tronco","es_tronco":true,"nombre_es":"Tronco","bajada_es":"La base de todo: cómo funciona el ambiente, cómo se mide y cómo se pasa de saber a hacer.","sort_order":0}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"agua_azul","es_tronco":false,"nombre_es":"Océanos y Ríos","bajada_es":"Ríos, humedales y mar: cómo funcionan, qué los amenaza y qué los protege.","sort_order":1}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"agua","es_tronco":false,"nombre_es":"Agua","bajada_es":"De dónde sale el agua de tu canilla, adónde va la que usás y cómo cuidarla.","sort_order":2}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"alimentacion","es_tronco":false,"nombre_es":"Alimentación","bajada_es":"Qué hay detrás de lo que comés: huella, desperdicio, estaciones y etiquetas.","sort_order":3}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"plantas","es_tronco":false,"nombre_es":"Plantas y Verde Urbano","bajada_es":"Cómo vive una planta, qué es una nativa y cómo hacer crecer verde donde estás.","sort_order":4}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"animales","es_tronco":false,"nombre_es":"Animales y Vida Silvestre","bajada_es":"Fauna, cadenas de vida y conservación: de los bichos de tu barrio al yaguareté.","sort_order":5}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"aire_suelo","es_tronco":false,"nombre_es":"Aire y Suelo","bajada_es":"El aire que respirás, el suelo que te alimenta y el clima que los une.","sort_order":6}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"ciencia","es_tronco":false,"nombre_es":"Ciencia Ciudadana","bajada_es":"Cómo sabemos lo que sabemos: datos, gráficos, fuentes y pensamiento crítico.","sort_order":7}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"energia","es_tronco":false,"nombre_es":"Energía y CO₂","bajada_es":"Qué es la energía, cuánto usás en casa y de dónde sale la electricidad.","sort_order":8}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"movilidad","es_tronco":false,"nombre_es":"Movilidad","bajada_es":"Cómo nos movemos, cuánto pesa cada forma de viajar y cómo se diseña una ciudad.","sort_order":9}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"residuos","es_tronco":false,"nombre_es":"Residuos y Reciclaje","bajada_es":"Qué pasa con lo que tirás, cómo separar bien y por qué reducir le gana a reciclar.","sort_order":10}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"consumo","es_tronco":false,"nombre_es":"Consumo Responsable","bajada_es":"Lo que cuesta de verdad lo que comprás, cómo detectar el greenwashing y cómo durar más.","sort_order":11}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"digital","es_tronco":false,"nombre_es":"Digital y Tecnología","bajada_es":"La huella de tus dispositivos y de la nube, y cómo usar la tecnología a favor.","sort_order":12}$ac$::jsonb);
select ac_cargar_rama($ac${"slug":"comunidad","es_tronco":false,"nombre_es":"Comunidad","bajada_es":"Actuar con otros: organizarse, participar, comunicar y buscar justicia ambiental.","sort_order":13}$ac$::jsonb);
